import assert from 'node:assert/strict';
import test from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile,access,cp} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {_electron as electron} from 'playwright-core';
import {createTemporaryDesktopProject} from '../../fixtures/xanthil-desktop/desktop-fixtures.ts';
import {completedCase} from '../../fixtures/case-assistant/completed-case.ts';
import {config} from '../../fixtures/case-assistant/fixtures.ts';
import {closeOwnedNativeProcess} from '../../fixtures/case-assistant/owned-native-cleanup.ts';
import {createCaseAssistantApplication} from '../../../packages/application/case-assistant.ts';
import {createLocalCaseAssistantStore} from '../../../adapters/storage-local/case-assistant.ts';

test('AC-FS-01/UI-FS-04 production Main opens one secure independent Fork window',{timeout:120000},async t=>{
 const evidence=process.env.JUANERAI_COLLABORATION_GUI_EVIDENCE,packageRoot=process.env.JUANERAI_GUI_PACKAGE_ROOT;
 assert.ok(evidence&&packageRoot,'current engineering package and fresh persistent evidence required');
 await mkdir(evidence,{recursive:true});
 // Historical smoke packages still require physical helper absence. Decision004
 // host verification may bind one exact helper, but never configured credentials.
 const helper=join(packageRoot,'Contents/MacOS/xanthil-keychain'),helperSha=process.env.JUANERAI_KEYCHAIN_VERIFICATION_HELPER_SHA256;
 if(helperSha===undefined){
  await assert.rejects(access(helper),'engineering package must have no production credential helper');
  await writeFile(join(evidence,'credential-precondition.json'),JSON.stringify({mode:'historical-helper-absent',helper,helper_executed:false}));
 }else{
  assert.match(helperSha,/^[a-f0-9]{64}$/,'explicit host helper identity required');
  const {createHash}=await import('node:crypto'),{spawnSync}=await import('node:child_process');
  assert.equal(createHash('sha256').update(await readFile(helper)).digest('hex'),helperSha,'only the host-bound production helper may be inspected');
  const probe=spawnSync(helper,[],{input:JSON.stringify({operation:'inspect',interactive:false}),env:{PATH:'/usr/bin:/bin',LANG:'en_US.UTF-8'},encoding:'utf8',timeout:30000,killSignal:'SIGKILL',maxBuffer:8192});
  let status='protocol_error';try{const value=JSON.parse(probe.stdout);if(value&&typeof value==='object'&&Object.keys(value).every(k=>['status','synchronizable','os_status'].includes(k))&&typeof value.status==='string')status=value.status;}catch{/* fail closed without logging unexpected output */}
  await writeFile(join(evidence,'credential-precondition.json'),JSON.stringify({mode:'decision004-presence-only',helper,sha256:helperSha,pid:probe.pid,operation:'inspect',interactive:false,exit:probe.status,signal:probe.signal,error:probe.error?.message??null,status,credential_read:false,item_mutation:false},null,2));
  assert.equal(probe.error,undefined);assert.equal(probe.status,0);assert.equal(probe.signal,null);
  assert.equal(status,'absent','refuse before launching Main if any credential is present or absence is unknown');
 }
 const project=await createTemporaryDesktopProject();
 let native:Awaited<ReturnType<typeof electron.launch>>|undefined,ownedProcess:ReturnType<Awaited<ReturnType<typeof electron.launch>>['process']>|undefined,connectionClosed=false;
 t.after(async()=>{try{if(native&&ownedProcess)await closeOwnedNativeProcess(ownedProcess,async()=>{if(!connectionClosed)await native!.close();},async value=>{await writeFile(join(evidence,'cleanup-result.json'),JSON.stringify({...(value as object),connection_closed:connectionClosed},null,2));});}finally{await cp(project.projectRoot,join(evidence,'fixture-project-final'),{recursive:true,errorOnExist:true,force:false});await project.dispose();}});
 const baseline=await completedCase(project.projectRoot),store=createLocalCaseAssistantStore({projectRoot:project.projectRoot});
 let calls=0;
 const application=createCaseAssistantApplication({store,config,clock:()=>new Date(),runtime:{async turn(){calls++;return {provider:config.provider,model:config.model,cost_microunits:0,output:{kind:'advice',text:'已保存父模型讨论；依据不足。'}};}}});
 const parent=await application.link(baseline.owner,'原生合成 Fork 来源',randomUUID());
 const authorization=await application.prepare(parent.session.id,'检查依据边界');await application.start(parent.session.id,authorization.id,true);
 let history=await application.read(parent.session.id);
 for(let i=0;i<100&&history.attempts.at(-1)?.status!=='Succeeded';i++){await new Promise(r=>setTimeout(r,5));history=await application.read(parent.session.id);}
 assert.equal(history.attempts.at(-1)?.status,'Succeeded');assert.equal(calls,1);await application.close();
 const cutoff=history.events.find(e=>e.kind==='advice')!,selected=history.events.find(e=>e.kind==='user')!;
 const original=await readFile(join(project.projectRoot,'.xanthil/desktop/state.sqlite'));
 await writeFile(join(evidence,'fixture-parent.json'),JSON.stringify(history,null,2));
 await cp(project.projectRoot,join(evidence,'fixture-project-before-native'),{recursive:true,errorOnExist:true,force:false});
 native=await electron.launch({executablePath:resolve(packageRoot,'Contents/MacOS/Xanthil'),args:['--user-data-dir='+join(evidence,'user-data')],env:{PATH:'/usr/bin:/bin',LANG:'en_US.UTF-8'},cwd:resolve('.')});
 ownedProcess=native.process();native.on('close',()=>{connectionClosed=true;});
 await writeFile(join(evidence,'owned-process.json'),JSON.stringify({pid:ownedProcess.pid,executable:resolve(packageRoot,'Contents/MacOS/Xanthil')},null,2));
 const page=await native.firstWindow();page.setDefaultTimeout(10000);
 const settingsBefore=await page.evaluate(()=>window.xanthilProviderSettingsApi!.request({operation:'read'}));
 await writeFile(join(evidence,'unconfigured-before.json'),JSON.stringify(settingsBefore,null,2));
 assert.equal(settingsBefore.ok,true);assert.equal(settingsBefore.value.configured,false);assert.equal(settingsBefore.value.busy,false);assert.equal(settingsBefore.value.last_test,'none');
 if(helperSha!==undefined)assert.equal(settingsBefore.value.state,'unconfigured');
 await native.evaluate(({dialog},root)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[root]});},project.projectRoot);
 await page.getByRole('button',{name:'选择项目',exact:true}).click();
 // Invoke the unchanged production Main handler through its real isolated preload.
 const result=await page.evaluate(async input=>{
  const api=window.xanthilCaseAssistantApi;
  const prepared=await api.request<any>(input.prepare as any);if(!prepared.ok)return {phase:'prepare',prepared};
  const created=await api.request<any>({version:'1.1',operation:'create_child',session_id:input.parent,preview_id:prepared.value.id,command_id:input.command,confirmed:true} as any);if(!created.ok)return {phase:'create',prepared,created};
  const opened=await api.request<any>({version:'1.1',operation:'open_child_window',session_id:created.value.session.id} as any);return {phase:'open',prepared,created,opened};
 },{parent:parent.session.id,command:randomUUID(),prepare:{version:'1.1',operation:'prepare_child',session_id:parent.session.id,kind:'fork',task:'独立检查已保存讨论',cutoff_id:cutoff.id,history_ids:[selected.id],report_ids:[],include_aggregate:false}});
 await writeFile(join(evidence,'open-result.json'),JSON.stringify(result,null,2));assert.equal(result.phase,'open',JSON.stringify(result));assert.ok('opened' in result&&result.opened);assert.equal(result.opened.ok,true,JSON.stringify(result));
 const child=await native.waitForEvent('window',{predicate:w=>w!==page,timeout:10000}).catch(()=>native.windows().find(w=>w!==page));assert.ok(child,'a real independent native window exists');
 assert.equal(native.windows().length,2);
 const preferences=await native.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().map(w=>{const p=(w.webContents as unknown as {getLastWebPreferences():{sandbox:boolean;contextIsolation:boolean;nodeIntegration:boolean;webSecurity:boolean}}).getLastWebPreferences();return {sandbox:p.sandbox,contextIsolation:p.contextIsolation,nodeIntegration:p.nodeIntegration,webSecurity:p.webSecurity};}));
 for(const p of preferences)assert.deepEqual(p,{sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true});
 assert.ok('created' in result&&result.created?.ok);const childId=result.created.value.session.id;
 const sibling=await page.evaluate(async input=>window.xanthilCaseAssistantApi.request<any>({version:'1.1',operation:'create_child',session_id:input.parent,preview_id:input.preview,command_id:input.command,confirmed:true}),{parent:parent.session.id,preview:result.prepared.value.id,command:randomUUID()});assert.equal(sibling.ok,true);assert.ok(sibling.ok);
 const authority=await child.evaluate(async({parent,childId,siblingId})=>({
  own:await window.xanthilCaseAssistantApi.request({version:'1.1',operation:'read_collaboration',session_id:childId}),
  root:await window.xanthilCaseAssistantApi.request({version:'1.0',operation:'read',session_id:parent}),
  parent:await window.xanthilCaseAssistantApi.request({version:'1.1',operation:'read_parent',session_id:parent}),
  sibling:await window.xanthilCaseAssistantApi.request({version:'1.1',operation:'read_collaboration',session_id:siblingId}),
  settings:await window.xanthilProviderSettingsApi!.request({operation:'read'}),
  descendant:await window.xanthilCaseAssistantApi.request({version:'1.1',operation:'prepare_child',session_id:childId,kind:'fork',task:'禁止递归',cutoff_id:null,history_ids:[],report_ids:[],include_aggregate:false})
 }),{parent:parent.session.id,childId,siblingId:sibling.value.session.id});
 await writeFile(join(evidence,'authority-result.json'),JSON.stringify(authority,null,2));assert.equal(authority.own.ok,true);for(const value of [authority.root,authority.parent,authority.sibling,authority.descendant]){assert.equal(value.ok,false);assert.ok(!value.ok);assert.equal(value.error.code,'FORBIDDEN');}assert.equal(authority.settings.ok,false);assert.equal(authority.settings.code,'FORBIDDEN');
 await child.getByRole('heading',{name:'自己的历史',exact:true}).waitFor();
 await child.getByRole('button',{name:'返回父对话',exact:true}).click();
 await page.getByRole('heading',{name:'原生合成 Fork 来源',exact:false}).waitFor();
 assert.equal(native.windows().length,2,'navigation leaves child alive');
 const beforeSubagent=(await store.readParentCollaboration(parent.session.id)).children.length;
 await page.getByRole('button',{name:'Subagent',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('本次有界任务').fill('有界证据复核');assert.equal(await dialog.getByLabel('选择父对话历史位置').count(),0);await dialog.getByRole('button',{name:'取消',exact:true}).click();assert.equal((await store.readParentCollaboration(parent.session.id)).children.length,beforeSubagent,'cancel creates no Subagent');
 await page.getByRole('button',{name:'Subagent',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('本次有界任务').fill('有界证据复核');await dialog.getByRole('button',{name:'创建独立子窗口',exact:true}).click();
 for(let i=0;i<100&&native.windows().length!==3;i++)await new Promise(r=>setTimeout(r,20));assert.equal(native.windows().length,3);
 const subagent=native.windows().find(w=>w!==page&&w!==child)!;await subagent.getByRole('heading',{name:'有界证据复核',exact:true}).waitFor();const relation=(await store.readParentCollaboration(parent.session.id)).children.find(c=>c.kind==='subagent')!;assert.ok(relation);assert.equal(relation.cutoff_id,null);assert.deepEqual(relation.selected_history,[]);
 await subagent.getByLabel('子任务文本').fill('只使用明确授权材料');await subagent.getByRole('button',{name:'查看任务授权',exact:true}).click();const authorizationDialog=subagent.getByRole('dialog');await authorizationDialog.waitFor();assert.equal(await authorizationDialog.getByRole('button',{name:'确认并开始',exact:true}).isEnabled(),false,'unconfigured native package cannot acquire model authority');await subagent.keyboard.press('Shift+Tab');assert.equal(await subagent.evaluate(()=>!!document.activeElement?.closest('dialog')),true);await subagent.keyboard.press('Escape');assert.equal(await authorizationDialog.count(),0);assert.equal((await store.readSession(relation.child_session_id)).attempts.length,0);
 await writeFile(join(evidence,'subagent-ui-result.json'),JSON.stringify({cancel_no_effects:true,created:relation,attempts:0,authorization_blocked:true},null,2));
 for(const [width,height] of [[1440,900],[1280,720]]){
  await (await native.browserWindow(child)).evaluate((w,size)=>w.setContentSize(size[0],size[1]),[width,height]);
  await child.screenshot({path:join(evidence,`fork-${width}x${height}.png`)});
  assert.equal(await child.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'child viewport has no horizontal overflow');
  const composer=await child.getByLabel('子任务文本').boundingBox(),center=await child.locator('.ca-conversation').boundingBox();assert.ok(composer&&center&&composer.width>center.width*0.7,'accepted composer uses the available column width');
  await (await native.browserWindow(subagent)).evaluate((w,size)=>w.setContentSize(size[0],size[1]),[width,height]);await subagent.screenshot({path:join(evidence,`subagent-${width}x${height}.png`)});assert.equal(await subagent.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 }
 await Promise.all([subagent.waitForEvent('close',{timeout:10000}),(await native.browserWindow(subagent)).evaluate(w=>w.close())]);assert.equal((await store.readLifecycle(relation.child_session_id)).open,false);
 await Promise.all([child.waitForEvent('close',{timeout:10000}),(await native.browserWindow(child)).evaluate(w=>w.close())]);
 const closed=await store.readLifecycle(childId);assert.equal(closed.open,false);assert.equal((await store.readSession(childId)).attempts.length,0,'no implicit model work');
 const reopened=await page.evaluate(id=>window.xanthilCaseAssistantApi.request({version:'1.1',operation:'open_child_window',session_id:id}),childId);assert.equal(reopened.ok,true);
 for(let i=0;i<100&&native.windows().length!==2;i++)await new Promise(r=>setTimeout(r,20));assert.equal(native.windows().length,2);
 assert.equal((await store.readLifecycle(childId)).open,true);assert.equal((await store.readLifecycle(childId)).epoch,closed.epoch+1);
 const duplicate=await page.evaluate(id=>window.xanthilCaseAssistantApi.request({version:'1.1',operation:'open_child_window',session_id:id}),childId);assert.equal(duplicate.ok,true);assert.equal(native.windows().length,2);
 const settingsAfter=await page.evaluate(()=>window.xanthilProviderSettingsApi!.request({operation:'read'}));
 await writeFile(join(evidence,'unconfigured-after.json'),JSON.stringify(settingsAfter,null,2));
 assert.equal(settingsAfter.ok,true);assert.equal(settingsAfter.value.configured,false);assert.equal(settingsAfter.value.busy,false);assert.equal(settingsAfter.value.last_test,'none','window creation/navigation/reopen must not test or configure a model');
 assert.equal(calls,1,'only the explicit prelaunch synthetic parent fixture invoked its runtime');
 await writeFile(join(evidence,'root-close-before.json'),JSON.stringify({windows:native.windows().length,parent:await store.readLifecycle(parent.session.id),child:await store.readLifecycle(childId)}));
 await (await native.browserWindow(page)).evaluate(w=>w.close());
 for(let i=0;i<100&&native.windows().length;i++)await new Promise(r=>setTimeout(r,20));await writeFile(join(evidence,'root-close-after.json'),JSON.stringify({windows:native.windows().length,parent:await store.readLifecycle(parent.session.id),child:await store.readLifecycle(childId)}));assert.equal(native.windows().length,0,'actual root close also closes owned child windows');
 assert.equal((await store.readLifecycle(childId)).open,false);assert.equal((await store.readLifecycle(parent.session.id)).open,false);
 await cp(project.projectRoot,join(evidence,'fixture-project-after-native'),{recursive:true,errorOnExist:true,force:false});
 await writeFile(join(evidence,'lifecycle-result.json'),JSON.stringify({closed,reopened:true,root_closed:true,model_calls:calls},null,2));
 assert.deepEqual(await readFile(join(project.projectRoot,'.xanthil/desktop/state.sqlite')),original);
});

// Existing offline OS/SDK seams; exact packaged Main, sender registry and UI are unchanged.
test('AC-FS-01–09/UI-FS-01–14 native packaged Main and installed Pi: Fork R1/R2, review/material and Subagent auto-return',{timeout:180000},async t=>{
 const evidence=join(process.env.JUANERAI_COLLABORATION_GUI_EVIDENCE!,'integrated'),packageRoot=process.env.JUANERAI_GUI_PACKAGE_ROOT!;await mkdir(evidence,{recursive:true});
 const {createRequire}=await import('node:module'),{createHash}=await import('node:crypto');const require=createRequire(import.meta.url),asar=join(packageRoot,'Contents/Resources/app.asar'),asarHash=createHash('sha256').update(await readFile(asar)).digest('hex'),main=require('@electron/asar').extractFile(asar,'.vite/build/main.cjs'),mainHash=createHash('sha256').update(main).digest('hex');
 const project=await createTemporaryDesktopProject();let native:Awaited<ReturnType<typeof electron.launch>>|undefined,owned:ReturnType<Awaited<ReturnType<typeof electron.launch>>['process']>|undefined;
 t.after(async()=>{try{if(native&&owned)await closeOwnedNativeProcess(owned,()=>native!.close(),async value=>{await writeFile(join(evidence,'cleanup-result.json'),JSON.stringify(value,null,2));});}finally{await cp(project.projectRoot,join(evidence,'fixture-project-final'),{recursive:true,errorOnExist:true,force:false});await project.dispose();}});
 const baseline=await completedCase(project.projectRoot,true),store=createLocalCaseAssistantStore({projectRoot:project.projectRoot}),seed=createCaseAssistantApplication({store,config,clock:()=>new Date(),runtime:{async turn(){return {provider:config.provider,model:config.model,cost_microunits:0,output:{kind:'advice',text:'已保存的父讨论，不自动继承。'}};}}});
 const parent=await seed.link(baseline.owner,'原生协作完整路径',randomUUID()),grant=await seed.prepare(parent.session.id,'保存父问题');await seed.start(parent.session.id,grant.id,true);let p=await seed.read(parent.session.id);for(let i=0;i<100&&p.attempts.at(-1)?.status!=='Succeeded';i++){await new Promise(r=>setTimeout(r,10));p=await seed.read(parent.session.id);}assert.equal(p.attempts[0].status,'Succeeded');const cutoff=p.events.find(e=>e.kind==='advice')!.id,selectedParent=p.events.find(e=>e.kind==='user')!,candidate=p.source.candidates[0];assert.equal(p.source.candidates.length,2);await seed.close();const original=await readFile(join(project.projectRoot,'.xanthil/desktop/state.sqlite'));
 const fixture=resolve('tests/fixtures/case-assistant/provider-lifecycle-main.cjs');await writeFile(join(evidence,'native-fixture.cjs'),await readFile(fixture));
 assert.equal(process.env.ELECTRON_OVERRIDE_DIST_PATH,undefined);const installedExecutable=resolve('node_modules/electron/dist',(await readFile('node_modules/electron/path.txt','utf8')).trim());await access(installedExecutable);await writeFile(join(evidence,'installed-runtime.json'),JSON.stringify({executable:installedExecutable,sha256:createHash('sha256').update(await readFile(installedExecutable)).digest('hex')},null,2));
 native=await electron.launch({args:[fixture,'--user-data-dir='+join(evidence,'user-data')],env:{PATH:'/usr/bin:/bin',LANG:'en_US.UTF-8',JUANERAI_LIFECYCLE_ASAR:asar,JUANERAI_LIFECYCLE_ASAR_SHA256:asarHash,JUANERAI_LIFECYCLE_MAIN_SHA256:mainHash},cwd:resolve('.')});owned=native.process();await writeFile(join(evidence,'owned-process.json'),JSON.stringify({pid:owned.pid,asarHash,mainHash},null,2));
 async function control<T=any>(method:string,arg?:unknown):Promise<T>{return native!.evaluate((_,input)=>Reflect.get(globalThis,'lifecycle')[input.method](input.arg),{method,arg});}
 const health=await control('health');assert.equal(health.mainSha,mainHash);assert.equal(health.mainLoaded,true);await writeFile(join(evidence,'main-health.json'),JSON.stringify(health,null,2));await control('project',project.projectRoot);
 const root=await native.firstWindow();root.setDefaultTimeout(10000);await root.getByRole('button',{name:'选择项目',exact:true}).click();await root.locator('.ca-rail li button').filter({hasText:'原生协作完整路径'}).click();
 async function createChild(kind:'Fork'|'Subagent',task:string,selectMaterials=false){const before=new Set(native!.windows());await root.getByRole('button',{name:kind,exact:true}).click();const modal=root.getByRole('dialog');await modal.getByLabel(kind==='Fork'?'本次讨论目的':'本次有界任务').fill(task);if(kind==='Fork')await modal.getByLabel('选择父对话历史位置').selectOption(cutoff);assert.equal(await modal.locator('input[type=checkbox]:checked').count(),0);if(selectMaterials){await modal.getByRole('checkbox',{name:/保存父问题/}).check();await modal.getByRole('checkbox',{name:/已验证聚合与 Evidence/}).check();await modal.getByRole('checkbox',{name:/原 final report 摘要/}).check();}await modal.getByRole('button',{name:'创建独立子窗口',exact:true}).click();for(let i=0;i<100&&!native!.windows().some(w=>!before.has(w));i++)await new Promise(r=>setTimeout(r,20));const page=native!.windows().find(w=>!before.has(w));assert.ok(page);page.setDefaultTimeout(10000);await page.getByRole('heading',{name:task,exact:true}).waitFor();const relation=(await store.readParentCollaboration(parent.session.id)).children.find(c=>c.task===task)!;assert.ok(relation);return {page,id:relation.child_session_id};}
 async function begin(page:typeof root,text:string,stage?:string){await page.getByLabel('子任务文本').fill(text);await page.getByRole('button',{name:'查看任务授权',exact:true}).click();const modal=page.getByRole('dialog');await modal.getByText('精确外发内容、来源与选择范围',{exact:true}).waitFor();await modal.getByRole('checkbox').check();if(stage){await writeFile(join(evidence,stage+'-authorization.json'),JSON.stringify({dialog:await modal.innerText(),stats:await control('stats'),fault:await control('deliveryFaultRead')},null,2));assert.equal(await modal.getByRole('button',{name:'确认并开始',exact:true}).isEnabled(),true,'healthy prepared authorization before delivery fault');}await modal.getByRole('button',{name:'确认并开始',exact:true}).click();}
 async function waitStatus(id:string,status:string){for(let i=0;i<200;i++){const saved=await store.readSession(id);if(saved.attempts.at(-1)?.status===status)return saved;await new Promise(r=>setTimeout(r,20));}assert.equal((await store.readSession(id)).attempts.at(-1)?.status,status);return store.readSession(id);}
 async function capture(page:typeof root,name:string){for(const [width,height]of [[1440,900],[1280,720]]){
  await (await native!.browserWindow(page)).evaluate((w,size)=>w.setContentSize(size[0],size[1]),[width,height]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  if(await page.locator('.ca-history-selection').count()){
   const geometry=await page.locator('.ca-child-inspector').evaluate(panel=>{const bounds=panel.getBoundingClientRect();return [...panel.querySelectorAll<HTMLElement>('.ca-history-selection, .ca-history-selection *')].map(el=>{const b=el.getBoundingClientRect(),range=document.createRange();range.selectNodeContents(el);return {tag:el.tagName,className:el.className,client:el.clientWidth,scroll:el.scrollWidth,left:b.left,right:b.right,panelLeft:bounds.left,panelRight:bounds.right,textRects:['STRONG','SMALL'].includes(el.tagName)?[...range.getClientRects()].map(r=>({left:r.left,right:r.right})):[]};});});
   await writeFile(join(evidence,`${name}-inspector-${width}.json`),JSON.stringify(geometry,null,2));for(const el of geometry){assert.ok(!el.client||el.scroll<=el.client+1,`inspector content fits ${el.tag}.${el.className}`);assert.ok(el.left>=el.panelLeft-1&&el.right<=el.panelRight+1,'inspector descendants remain inside panel');for(const rect of el.textRects)assert.ok(rect.left>=el.panelLeft-1&&rect.right<=el.panelRight+1,'wrapped metadata is not clipped');}
   const boxes=page.locator('.ca-history-selection input[type=checkbox]');if(await boxes.count()&&await boxes.first().isEnabled()){
    await boxes.first().focus();for(let i=0;i<await boxes.count();i++){const box=boxes.nth(i);assert.equal(await box.evaluate(el=>document.activeElement===el),true,'Tab reaches each choice');const visible=await box.evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&['.ca-selection-list','.ca-history-selection','.ca-child-inspector'].every(selector=>{const bounds=el.closest(selector)!.getBoundingClientRect();return r.top>=bounds.top-1&&r.bottom<=bounds.bottom+1;});});assert.equal(visible,true,'focused checkbox scrolls into view');const before=await box.isChecked();await page.keyboard.press('Space');assert.equal(await box.isChecked(),!before);await page.keyboard.press('Space');assert.equal(await box.isChecked(),before);if(i+1<await boxes.count())await page.keyboard.press('Tab');}
    await page.screenshot({path:join(evidence,`${name}-keyboard-last-${width}x${height}.png`)});await boxes.first().focus();
   }
   for(const control of [page.getByRole('button',{name:'停止',exact:true}),page.getByRole('heading',{name:'固定来源',exact:true})]){const b=await control.boundingBox();assert.ok(b&&b.y>=0&&b.y+b.height<=height,'Stop and fixed source remain reachable');}
  }
  await page.screenshot({path:join(evidence,`${name}-${width}x${height}.png`)});
 }}
 const fork=await createChild('Fork',`比较候选 ${candidate.candidate_id} 与 no_action / defer`,true);await control('childOutput','question');await begin(fork.page,'检查 R1');await fork.page.getByText('是否只检查所选证据边界？',{exact:true}).first().waitFor();await waitStatus(fork.id,'Waiting');await capture(fork.page,'fork-waiting');
 const blocked=await root.evaluate(async id=>{const a=await window.xanthilCaseAssistantApi.request<any>({version:'1.0',operation:'prepare',session_id:id,text:'不能并行',history_ids:[],report_ids:[],rebase:false});if(!a.ok)return a;return window.xanthilCaseAssistantApi.request({version:'1.0',operation:'start',session_id:id,authorization_id:a.value.id,free_text_confirmed:true});},parent.session.id);assert.equal(blocked.ok,false,'Waiting child excludes parent model admission');
 await native.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:0,checkboxChecked:false});});await (await native.browserWindow(root)).evaluate(w=>w.close());await new Promise(r=>setTimeout(r,100));assert.equal(root.isClosed(),false);assert.equal((await store.readSession(fork.id)).attempts[0].status,'Waiting','cancel native close preserves work');
 await control('childOutput','result');await fork.page.getByLabel('子任务文本').fill('是，只检查已选范围');await fork.page.getByRole('button',{name:'确认并发送当前文本',exact:true}).click();await waitStatus(fork.id,'Succeeded');await fork.page.getByRole('heading',{name:'MODEL · 结果 v1',exact:true}).waitFor();const r1=(await store.childResults(fork.id))[0];assert.equal((await store.readParentCollaboration(parent.session.id)).deliveries.find(d=>d.result_id===r1.id)?.status,'unreturned');
 const verifyCandidatePayload=(payload:any)=>{const c=payload.authorized_context;assert.deepEqual(c.inherited_history,[selectedParent]);assert.deepEqual(c.selected_history,[]);assert.deepEqual(c.selected_results,[]);assert.deepEqual(c.business_projection.candidates,p.source.candidates);assert.deepEqual(c.aggregate,p.source.aggregate);assert.equal(c.selected_reports.length,1);assert.deepEqual(c.allowed_references.find((r:any)=>r.kind==='report'),{kind:'report',id:p.source.report.report_id,version:p.source.report.version,sha256:p.source.report.sha256,revision_id:baseline.owner.revision_id});assert.equal(c.allowed_references.find((r:any)=>r.kind==='aggregate').sha256,p.source.aggregate.sha256);assert.ok(!JSON.stringify(c.inherited_history).includes('已保存的父讨论'));};verifyCandidatePayload((await control('childPayloads')).at(-1));assert.ok(r1.value.references.some(v=>v.kind==='candidate'&&v.id===candidate.candidate_id));
 await fork.page.getByRole('checkbox',{name:/结果 v1/}).check();await begin(fork.page,'仅选择 R1 继续复核');await waitStatus(fork.id,'Succeeded');await fork.page.getByRole('heading',{name:'MODEL · 结果 v2',exact:true}).waitFor();const results=await store.childResults(fork.id);assert.equal(results.length,2);assert.deepEqual(results[0],r1);assert.equal(results[1].value.references[0].sha256,r1.sha256);await capture(fork.page,'fork-r1-r2');
 const payloads=await control('childPayloads');assert.deepEqual(payloads.at(-1).authorized_context.selected_results.map((r:any)=>r.id),[r1.id]);assert.deepEqual(payloads.at(-1).authorized_context.selected_history,[]);
 await fork.page.getByRole('button',{name:'回流到来源对话',exact:true}).first().click();await root.getByRole('button',{name:'采纳为材料',exact:true}).waitFor();await root.getByRole('button',{name:'采纳为材料',exact:true}).click();await root.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();assert.equal((await store.readParentCollaboration(parent.session.id)).materials.length,0);
 await root.getByRole('button',{name:'采纳为材料',exact:true}).click();await root.getByRole('dialog').getByRole('button',{name:'确认采纳为材料',exact:true}).click();const material=root.getByRole('checkbox',{name:/MODEL · 结果 v1/});await material.waitFor();assert.equal(await material.isChecked(),false);await material.check();await root.getByLabel('Case Assistant 任务文本').fill('明确使用已采纳材料');await root.getByRole('button',{name:'发送',exact:true}).click();assert.match(await root.getByRole('dialog').innerText(),/R1 检查完成/);const disclosure=root.getByRole('region',{name:'本次授权的 MODEL 材料'});for(const text of [r1.value.summary,r1.sha256,r1.attempt_id,r1.child_session_id,r1.source.owner.revision_id])assert.ok((await disclosure.innerText()).includes(text));assert.equal(await disclosure.locator('details, pre').count(),0);await disclosure.getByRole('heading',{name:'本次选择的 MODEL 材料',exact:true}).scrollIntoViewIfNeeded();await capture(root,'parent-authorization');await root.keyboard.press('Escape');await capture(root,'parent-material');assert.equal((await store.readSession(parent.session.id)).attempts.length,1);
 const sub=await createChild('Subagent',`反驳同一候选 ${candidate.candidate_id}`,true);await control('childOutput','question');await begin(sub.page,'只检查所选边界');await waitStatus(sub.id,'Waiting');await sub.page.getByText('是否只检查所选证据边界？',{exact:true}).first().waitFor();await control('childOutput','result');await sub.page.getByLabel('子任务文本').fill('是');await sub.page.getByRole('button',{name:'确认并发送当前文本',exact:true}).click();await waitStatus(sub.id,'Succeeded');
 for(let i=0;i<100;i++){const result=(await store.childResults(sub.id))[0];if((await store.readParentCollaboration(parent.session.id)).deliveries.some(d=>d.result_id===result.id&&d.status==='returned'))break;await new Promise(r=>setTimeout(r,20));}
 const subResult=(await store.childResults(sub.id))[0];verifyCandidatePayload((await control('childPayloads')).at(-1));assert.ok(subResult.value.references.some(v=>v.kind==='candidate'&&v.id===candidate.candidate_id));assert.equal((await store.readParentCollaboration(parent.session.id)).deliveries.find(d=>d.result_id===subResult.id)?.status,'returned');await capture(sub.page,'subagent-returned');await root.getByRole('button',{name:'不采纳',exact:true}).click();await root.getByRole('dialog').getByRole('button',{name:'确认不采纳',exact:true}).click();
 await control('childOutput','advice');await begin(sub.page,'不完整输出必须失败');await waitStatus(sub.id,'Failed');assert.equal((await store.childResults(sub.id)).length,1,'failure never publishes a new result');
 // A synthetic disk fault rejects only delivery publication; the real Store still
 // saves a complete result and records the failed return. No Main handler replacement.
 const retry=await createChild('Subagent','原生本地回流恢复');
 const readSchema=()=>{const db=new DatabaseSync(join(project.projectRoot,'.xanthil/desktop/case-assistant.sqlite'));try{return db.prepare('SELECT type,name,tbl_name,sql FROM sqlite_schema ORDER BY type,name').all();}finally{db.close();}};
 const schemaBefore=readSchema();await control('deliveryFaultArm',retry.id);
 const healthySource=await store.readSource(baseline.owner),healthyHistory=await store.readSession(retry.id),healthySessions=await store.listSessions(baseline.owner.project_id);
 await writeFile(join(evidence,'retry-fixture-health.json'),JSON.stringify({source:healthySource,history:healthyHistory,session_count:healthySessions.length,schema:schemaBefore,fault:await control('deliveryFaultRead')},null,2));
 assert.equal(healthySource.eligible,true);assert.equal(healthyHistory.attempts.length,0);assert.equal((await control('deliveryFaultRead')).hits.length,0);assert.deepEqual(readSchema(),schemaBefore);
 await control('childOutput','result');await begin(retry.page,'形成独立完整意见','retry');const savedRetry=await waitStatus(retry.id,'Succeeded'),retryResults=await store.childResults(retry.id);
 await writeFile(join(evidence,'retry-result-committed.json'),JSON.stringify({history:savedRetry,results:retryResults,fault:await control('deliveryFaultRead')},null,2));assert.equal(retryResults.length,1);assert.equal(retryResults[0].attempt_id,savedRetry.attempts[0].id);
 await retry.page.getByRole('button',{name:'重试回流',exact:true}).waitFor();const failedFault=await control('deliveryFaultRead'),failedDelivery=(await store.readParentCollaboration(parent.session.id)).deliveries.find(d=>d.result_id===retryResults[0].id);
 await writeFile(join(evidence,'retry-delivery-failed.json'),JSON.stringify({fault:failedFault,delivery:failedDelivery,stats:await control('stats')},null,2));assert.equal(failedFault.armed,null);assert.equal(failedFault.hits.length,1);assert.equal(failedFault.hits[0].result_id,retryResults[0].id);assert.equal(failedFault.hits[0].attempt_status,'Succeeded');assert.equal(failedDelivery?.status,'failed');assert.deepEqual(readSchema(),schemaBefore);
 await capture(retry.page,'subagent-return-failed');const callsBeforeRetry=(await control('stats')).requests;
 await retry.page.getByRole('button',{name:'重试回流',exact:true}).click();await retry.page.getByText('已回流 · 待父对话处理',{exact:true}).waitFor();assert.equal((await control('stats')).requests,callsBeforeRetry,'local retry never runs the model');assert.equal((await store.readSession(retry.id)).attempts.length,1);assert.deepEqual(await store.childResults(retry.id),retryResults);assert.deepEqual(await control('deliveryFaultRead'),failedFault);assert.deepEqual(readSchema(),schemaBefore);await capture(retry.page,'subagent-local-retry');
 await writeFile(join(evidence,'retry-local-recovery.json'),JSON.stringify({delivery:(await store.readParentCollaboration(parent.session.id)).deliveries.find(d=>d.result_id===retryResults[0].id),requests_before:callsBeforeRetry,requests_after:(await control('stats')).requests,attempts:(await store.readSession(retry.id)).attempts.length,fault:await control('deliveryFaultRead')},null,2));
 // Real native Stop while installed Pi transport is pending must fence late output.
 const beforeLate=(await store.childResults(fork.id)).length;await control('arm','runtime');await begin(fork.page,'停止迟到结果');
 for(let i=0;i<100&&(await control('stats')).held!=='runtime';i++)await new Promise(r=>setTimeout(r,20));assert.equal((await control('stats')).held,'runtime');
 await fork.page.getByRole('button',{name:'停止',exact:true}).click();await waitStatus(fork.id,'Stopped');await control('release');await new Promise(r=>setTimeout(r,100));assert.equal((await store.childResults(fork.id)).length,beforeLate);await capture(fork.page,'fork-stopped-late');
 const callsBeforeReopen=(await control('stats')).requests;await Promise.all([fork.page.waitForEvent('close'),(await native.browserWindow(fork.page)).evaluate(w=>w.close())]);const closedEpoch=(await store.readLifecycle(fork.id)).epoch;
 const reopened=await root.evaluate(id=>window.xanthilCaseAssistantApi.request({version:'1.1',operation:'open_child_window',session_id:id}),fork.id);assert.equal(reopened.ok,true);
 for(let i=0;i<100&&!native.windows().some(w=>w!==root&&w!==sub.page&&w!==retry.page);i++)await new Promise(r=>setTimeout(r,20));const recovered=native.windows().find(w=>w!==root&&w!==sub.page&&w!==retry.page)!;assert.ok(recovered);await recovered.getByRole('heading',{name:'MODEL · 结果 v2',exact:true}).waitFor();assert.equal((await store.readLifecycle(fork.id)).epoch,closedEpoch+1);assert.equal((await control('stats')).requests,callsBeforeReopen);await capture(recovered,'fork-reopened-history');
 const final=await store.readParentCollaboration(parent.session.id),stats=await control('stats');assert.equal(final.materials.length,1);assert.equal(final.reviews.length,2);assert.equal(stats.fetches,0);assert.equal(stats.sockets,0);assert.equal(stats.saves,0);assert.deepEqual(await store.formalHistory(baseline.owner),{decisions:[],reports:[]});assert.deepEqual(await readFile(join(project.projectRoot,'.xanthil/desktop/state.sqlite')),original);
 await writeFile(join(evidence,'result.json'),JSON.stringify({final,stats,payloads:await control('childPayloads'),parentAttempts:(await store.readSession(parent.session.id)).attempts.length,network:false,realKeychain:false,productionMainUnchanged:true},null,2));
 // Deliberate mutation of this test-owned source after unchanged-formal assertions.
 // Preserve both identities and prove UI invalidation without a new model request.
 await writeFile(join(evidence,'source-before-stale.sqlite'),await readFile(join(project.projectRoot,'.xanthil/desktop/state.sqlite')));
 const stale=new DatabaseSync(join(project.projectRoot,'.xanthil/desktop/state.sqlite'));stale.prepare('UPDATE aggregate_artifacts SET sha256=? WHERE artifact_id=?').run('f'.repeat(64),r1.source.aggregate.artifact_id);stale.close();
 await recovered.getByText('来源或会话已失效，保留历史',{exact:true}).waitFor();assert.equal(await recovered.getByLabel('子任务文本').isEnabled(),false);assert.equal(await recovered.getByRole('button',{name:'回流到来源对话',exact:true}).last().isEnabled(),false);assert.equal((await control('stats')).requests,stats.requests);await capture(recovered,'fork-source-stale');
 await writeFile(join(evidence,'source-stale-result.json'),JSON.stringify({intentionalSyntheticSourceMutation:true,artifact_id:r1.source.aggregate.artifact_id,previous_sha256:r1.source.aggregate.sha256,current_sha256:'f'.repeat(64),requests:stats.requests,results:(await store.childResults(fork.id)).length},null,2));
});

// Durable successors to validator-independent-001 F1/F2; real Main owns all events.
test('F1/F2 native selected-family close and child/root renderer loss fence pending Running Waiting and late return',{timeout:240000},async t=>{
 const evidence=join(process.env.JUANERAI_COLLABORATION_GUI_EVIDENCE!,'renderer-loss'),packageRoot=process.env.JUANERAI_GUI_PACKAGE_ROOT!;await mkdir(evidence,{recursive:true});
 const {createRequire}=await import('node:module'),{createHash}=await import('node:crypto'),require=createRequire(import.meta.url),sha=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
 const asar=join(packageRoot,'Contents/Resources/app.asar'),asarHash=sha(await readFile(asar)),mainHash=sha(require('@electron/asar').extractFile(asar,'.vite/build/main.cjs'));
 const project=await createTemporaryDesktopProject(),store=createLocalCaseAssistantStore({projectRoot:project.projectRoot}),baseline=await completedCase(project.projectRoot,true),seed=createCaseAssistantApplication({store,config,runtime:null,clock:()=>new Date()});
 const a=await seed.link(baseline.owner,'关闭测试父 A',randomUUID()),b=await seed.link(baseline.owner,'保留测试父 B',randomUUID());await seed.close();const formal=await readFile(join(project.projectRoot,'.xanthil/desktop/state.sqlite'));
 const native=await electron.launch({args:[resolve('tests/fixtures/case-assistant/provider-lifecycle-main.cjs'),'--user-data-dir='+join(evidence,'user-data')],env:{PATH:'/usr/bin:/bin',LANG:'en_US.UTF-8',JUANERAI_LIFECYCLE_ASAR:asar,JUANERAI_LIFECYCLE_ASAR_SHA256:asarHash,JUANERAI_LIFECYCLE_MAIN_SHA256:mainHash},cwd:resolve('.')});
 const owned=native.process(),exited=new Promise<void>(r=>owned.once('exit',()=>r()));await writeFile(join(evidence,'owned-process.json'),JSON.stringify({pid:owned.pid,args:owned.spawnargs,asarHash,mainHash}));
 t.after(async()=>{let error:unknown;const signals:string[]=[];try{if(owned.exitCode===null&&owned.signalCode===null){await Promise.race([(async()=>{await native.close();await exited;})(),new Promise<never>((_,reject)=>setTimeout(()=>reject(Error('owned close timeout')),5000))]);}assert.equal(owned.exitCode,0);assert.equal(owned.signalCode,null);}catch(e){error=e;for(const signal of ['SIGTERM','SIGKILL'] as const){if(owned.exitCode!==null||owned.signalCode!==null)break;signals.push(signal);owned.kill(signal);await Promise.race([exited,new Promise(r=>setTimeout(r,5000))]);}}finally{await writeFile(join(evidence,'owned-cleanup.json'),JSON.stringify({pid:owned.pid,exit:owned.exitCode,signal:owned.signalCode,signals,error:error?String(error):null}));await cp(project.projectRoot,join(evidence,'project-final'),{recursive:true});await project.dispose();}if(error)throw error;});
 async function control(method:string,arg?:unknown):Promise<any>{return native.evaluate((_,input)=>Reflect.get(globalThis,'lifecycle')[input.method](input.arg),{method,arg});}
 async function until(check:()=>Promise<boolean>,message:string){for(let i=0;i<200;i++){if(await check())return;await new Promise(r=>setTimeout(r,20));}assert.fail(message);}
 let root=await native.firstWindow();root.setDefaultTimeout(10000);await control('project',project.projectRoot);
 async function selectParent(title:string){await root.locator('.ca-rail li button').filter({hasText:title}).click();await root.getByRole('heading',{name:new RegExp(title)}).waitFor();}
 await root.getByRole('button',{name:'选择项目',exact:true}).click();await selectParent(a.session.title);
 const request=(page:typeof root,input:any)=>page.evaluate(q=>window.xanthilCaseAssistantApi.request<any>(q),input);
 async function child(parent:string,task:string){const pv=await request(root,{version:'1.1',operation:'prepare_child',session_id:parent,kind:'subagent',task,cutoff_id:null,history_ids:[],report_ids:[],include_aggregate:false});assert.equal(pv.ok,true,JSON.stringify(pv));assert.ok(pv.ok);const made=await request(root,{version:'1.1',operation:'create_child',session_id:parent,preview_id:pv.value.id,command_id:randomUUID(),confirmed:true});assert.ok(made.ok,JSON.stringify(made));const id=made.value.session.id,before=new Set(native.windows());const opened=await request(root,{version:'1.1',operation:'open_child_window',session_id:id});assert.equal(opened.ok,true);await until(async()=>native.windows().some(w=>!before.has(w)),'child exists');const page=native.windows().find(w=>!before.has(w))!;page.setDefaultTimeout(10000);await page.getByLabel('子任务文本').waitFor();return {id,page};}
 async function begin(c:{id:string;page:typeof root},boundary:'read'|'runtime'|'Waiting'){
  await control('childOutput',boundary==='Waiting'?'question':'result');await c.page.getByLabel('子任务文本').fill('renderer 消失后不得发布');await c.page.getByRole('button',{name:'查看任务授权',exact:true}).click();const modal=c.page.getByRole('dialog');await modal.getByRole('checkbox').check();
  if(boundary!=='Waiting')await control('arm',boundary);await modal.getByRole('button',{name:'确认并开始',exact:true}).click();
  if(boundary==='Waiting')await until(async()=>(await store.readSession(c.id)).attempts.at(-1)?.status==='Waiting','Waiting reached');else await until(async()=>(await control('stats')).held===boundary,'held '+boundary);
 }
 await selectParent(b.session.title);const keep=await child(b.session.id,'父 B 的保留子任务'),keepBefore=await store.readSession(keep.id),keepLife=await store.readLifecycle(keep.id);
 await selectParent(a.session.title);const ownedChild=await child(a.session.id,'父 A 的 Waiting 子任务');await begin(ownedChild,'Waiting');
 const stale=await request(root,{version:'1.0',operation:'prepare',session_id:a.session.id,text:'关闭后失效的父授权',history_ids:[],report_ids:[],rebase:false});assert.ok(stale.ok);
 await root.getByRole('button',{name:'关闭父会话',exact:true}).click();await root.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();assert.equal((await store.readSession(ownedChild.id)).attempts.at(-1)?.status,'Waiting');assert.equal((await store.readLifecycle(a.session.id)).open,true);
 await root.getByRole('button',{name:'关闭父会话',exact:true}).click();for(const [width,height]of [[1280,720],[1440,900]]){await(await native.browserWindow(root)).evaluate((w,s)=>w.setContentSize(s[0],s[1]),[width,height]);await root.screenshot({path:join(evidence,`parent-close-confirm-${width}.png`)});}await root.getByRole('dialog').getByRole('button',{name:'关闭并停止',exact:true}).click();await until(async()=>!(await store.readLifecycle(a.session.id)).open,'selected parent closes');
 assert.equal((await store.readSession(ownedChild.id)).attempts.at(-1)?.status,'Interrupted');assert.deepEqual(await store.readSession(keep.id),keepBefore);assert.deepEqual(await store.readLifecycle(keep.id),keepLife);assert.equal((await store.readLifecycle(b.session.id)).open,true);
 const beforeReopen=await control('stats');await selectParent(a.session.title);assert.equal((await store.readLifecycle(a.session.id)).open,true);const refused=await request(root,{version:'1.0',operation:'start',session_id:a.session.id,authorization_id:stale.value.id,free_text_confirmed:true});assert.equal(refused.ok,false);assert.equal((await control('stats')).requests,beforeReopen.requests);assert.equal((await store.readParentCollaboration(a.session.id)).deliveries.length,0);
 await writeFile(join(evidence,'family-close.json'),JSON.stringify({selected:await store.readParentCollaboration(a.session.id),other:await store.readParentCollaboration(b.session.id),stale:refused,stats:await control('stats')},null,2));
 // The independent failure was a real killed renderer while held Running. Also
 // cover pending admission, Waiting and root loss through actual Main events.
 for(const scope of ['child','root'] as const)for(const boundary of ['read','runtime','Waiting','destroy'] as const){
  const c=await child(a.session.id,`${scope}-${boundary}`),otherBefore=await store.readSession(keep.id),otherLife=await store.readLifecycle(keep.id);await begin(c,boundary==='destroy'?'runtime':boundary);
  const target=scope==='child'?c.page:root,targetWindow=await native.browserWindow(target),identity=await targetWindow.evaluate(w=>({id:w.id,webContentsId:w.webContents.id,rendererPid:w.webContents.getOSProcessId()}));
  await writeFile(join(evidence,`${scope}-${boundary}-before.json`),JSON.stringify({identity,p:await store.readSession(c.id),lifecycle:await store.readLifecycle(c.id),events:await control('windowState'),stats:await control('stats')},null,2));
  if(boundary==='destroy')await targetWindow.evaluate(w=>w.destroy());else await targetWindow.evaluate(w=>w.webContents.forcefullyCrashRenderer());
  try{await until(async()=>!(await store.readLifecycle(c.id)).open,scope+' crash persisted close');}finally{await writeFile(join(evidence,`${scope}-${boundary}-close-readback.json`),JSON.stringify({p:await store.readSession(c.id),lifecycle:await store.readLifecycle(c.id),events:await control('windowState'),stats:await control('stats')},null,2));}
  if(boundary!=='Waiting')await control('release');await new Promise(r=>setTimeout(r,150));
  const p=await store.readSession(c.id),results=await store.childResults(c.id),parent=await store.readParentCollaboration(a.session.id),events=await control('windowState');assert.ok(events.events.some((e:any)=>e.event===(boundary==='destroy'?'webContents-destroyed':'render-process-gone')&&e.webContentsId===identity.webContentsId),'real captured renderer event');assert.equal(results.length,0);assert.equal(parent.deliveries.length,0);assert.ok(p.attempts.every(v=>v.status==='Interrupted'));if(boundary==='read')assert.equal(p.attempts.length,0,'pending never becomes persisted Running');
  await writeFile(join(evidence,`${scope}-${boundary}.json`),JSON.stringify({identity,p,results,parent,events,stats:await control('stats')},null,2));
  if(scope==='child'){await until(async()=>c.page.isClosed(),'lost child window destroyed');assert.equal(root.isClosed(),false);assert.deepEqual(await store.readSession(keep.id),otherBefore);assert.deepEqual(await store.readLifecycle(keep.id),otherLife);}
  else{await until(async()=>native.windows().length===0,'root loss closes owned windows');await native.evaluate(({app})=>app.emit('activate'));await until(async()=>native.windows().length===1,'Dock creates fresh root');root=native.windows()[0];root.setDefaultTimeout(10000);await root.getByRole('button',{name:'选择项目',exact:true}).click();await selectParent(a.session.title);}
  const calls=(await control('stats')).requests,before=new Set(native.windows()),opened=await request(root,{version:'1.1',operation:'open_child_window',session_id:c.id});assert.equal(opened.ok,true);await until(async()=>native.windows().some(w=>!before.has(w)),'explicit history reopen');const history=native.windows().find(w=>!before.has(w))!;await history.getByLabel('子任务文本').waitFor();assert.equal((await control('stats')).requests,calls);assert.equal((await store.childResults(c.id)).length,0);await(await native.browserWindow(history)).evaluate(w=>w.close());await until(async()=>history.isClosed(),'normal reopened history close');
 }
 const stats=await control('stats');assert.equal(stats.fetches,0);assert.equal(stats.sockets,0);assert.equal(stats.saves,0);assert.deepEqual(await readFile(join(project.projectRoot,'.xanthil/desktop/state.sqlite')),formal);await writeFile(join(evidence,'result.json'),JSON.stringify({stats,formalUnchanged:true,network:false,realKeychain:false}));
});
