import assert from 'node:assert/strict';
import test from 'node:test';
import {EventEmitter} from 'node:events';
import {observeCompanion} from '../../../tools/harness/validation/browser-companion-process.mjs';
function fixture(){const child=new EventEmitter();Object.assign(child,{exitCode:null,signalCode:null,kill(signal){child.signalCode=signal;child.emit('exit',null,signal);}});let disposed=false;return {child,app:{process(){if(disposed)throw new TypeError('disposed wrapper');return child;},async close(){disposed=true;throw new TypeError('disposed wrapper');}},dispose(){disposed=true;}};}
test('E06 host receipt survives wrapper disposal and exit before waiter',async()=>{const f=fixture(),receipt=observeCompanion(f.app);f.child.exitCode=0;f.child.emit('exit',0,null);f.dispose();assert.deepEqual(await receipt.exited,{code:0,signal:null});await receipt.cleanup();});
test('E06 cleanup uses captured child when wrapper close fails',async()=>{const f=fixture(),receipt=observeCompanion(f.app);f.dispose();await receipt.cleanup();assert.deepEqual(await receipt.exited,{code:null,signal:'SIGTERM'});});
test('E06 receipt preserves nonzero exit, signal and process error without success coercion',async()=>{for(const event of ['nonzero','signal','error']){const f=fixture(),receipt=observeCompanion(f.app);if(event==='error'){f.child.emit('error',new Error('synthetic process error'));assert.deepEqual(await receipt.exited,{code:null,signal:null,error:'synthetic process error'});}else{f.child.exitCode=event==='nonzero'?7:null;f.child.signalCode=event==='signal'?'SIGKILL':null;f.child.emit('exit',f.child.exitCode,f.child.signalCode);assert.deepEqual(await receipt.exited,{code:f.child.exitCode,signal:f.child.signalCode});f.dispose();await receipt.cleanup();}}});

test('E06 snapshot equality preserves every SQLite data field across JSON evidence readback',async()=>{
 const {DatabaseSync}=await import('node:sqlite'),{snapshotSqliteRows}=await import('../../../tools/harness/validation/browser-companion-process.mjs'),db=new DatabaseSync(':memory:');try{db.exec("CREATE TABLE sample(id TEXT,sequence INTEGER,nullable TEXT,byte_string TEXT);INSERT INTO sample VALUES('original',2,NULL,'00ff000a');");const raw=db.prepare('SELECT * FROM sample').all();assert.equal(Object.getPrototypeOf(raw[0]),null);const plain=snapshotSqliteRows(raw);assert.equal(Object.getPrototypeOf(plain[0]),Object.prototype);assert.deepEqual(plain,JSON.parse(JSON.stringify(raw)));for(const [key,value] of Object.entries({id:'other',sequence:3,nullable:'not-null',byte_string:'00ff000b'}))assert.throws(()=>assert.deepEqual([{...plain[0],[key]:value}],plain));assert.deepEqual(snapshotSqliteRows([{unknown:7,bytes:new Uint8Array([0,255])}]),[{unknown:7,bytes:new Uint8Array([0,255])}]);}finally{db.close();}
});
