// Retained-task and material-policy integration cases; immutable seed state is process-local.
import { DatabaseSync } from "node:sqlite";
import assert from "node:assert/strict";
import test, { after } from "node:test";
import { createHash, randomUUID } from "node:crypto";
import { cpSync, mkdtempSync, readdirSync } from "node:fs";
import { join, relative } from "node:path";
import { tmpdir } from "node:os";
import { createMembershipTaskApplication } from "../../../packages/application/member-task.ts";
import { createLocalMembershipTaskStore } from "../../../adapters/storage-local/member-task.ts";
import { desktopTestIds } from "../../fixtures/xanthil-desktop/desktop-fixtures.ts";
import { createPiCaseAssistantRuntime } from "../../../adapters/agent-pi/case-assistant.ts";
import { createLocalModelAccess } from "../../../packages/application/provider-settings.ts";
import { createLocalDesktopDecisionCaseStore } from "../../../adapters/storage-local/xanthil-desktop-decision-case.ts";
import { writeFileSync, readFileSync } from "node:fs";
import { config as legacyConfig } from "../../fixtures/case-assistant/fixtures.ts";
import {blankTaskFixture,syntheticProfile,authorizedTaskFixture,until,reviewChoiceFixture} from '../../fixtures/xanthil-desktop/member-task-test-support.ts';
async function completedMembershipFixture(){
 const f=await reviewChoiceFixture(undefined,['M1','M2']),completed=await f.app.submitReview(f.id,f.command);
 return {root:f.root,id:f.id,desktop:f.desktop,store:f.store,shared:f.shared,app:f.app,completed};
}
async function retainedFixture(respond:(payload:string)=>Promise<unknown>,clock=()=>new Date(),prepared?:Awaited<ReturnType<typeof completedMembershipFixture>>){
 const f=prepared??await completedMembershipFixture(),completed=f.completed;const {createLocalCaseAssistantStore}=await import('../../../adapters/storage-local/case-assistant.ts'),{createCaseAssistantApplication}=await import('../../../packages/application/case-assistant.ts'),{config}=await import('../../fixtures/case-assistant/fixtures.ts');
 const assistantStore=createLocalCaseAssistantStore({projectRoot:f.root}),app=createCaseAssistantApplication({store:assistantStore,config,clock,modelAccess:f.shared,runtime:createPiCaseAssistantRuntime({provider:'synthetic',model:'offline',max_input_bytes:16000,max_output_tokens:1000},{respond}),membership:{store:f.store,desktop:f.desktop,sourceStore:createLocalDesktopDecisionCaseStore({projectRoot:f.root}),profile:syntheticProfile()}});
 const parent=await app.link(completed.owner,'合成后续任务',randomUUID());const wait=async()=>{for(let n=0;n<200;n++){const p=await app.read(parent.session.id);if(p.attempts.at(-1)?.status!=='Running')return p;await new Promise(r=>setTimeout(r,10));}assert.fail('retained task timeout');};return {...f,completed,retained:app,assistantStore,parent,wait};
}

function retainedFixtureFiles(root:string){
 return readdirSync(root,{recursive:true,withFileTypes:true}).filter(e=>e.isFile()).map(e=>{
  const path=join(e.parentPath,e.name),bytes=readFileSync(path);
  assert.equal(bytes.includes(Buffer.from(root)),false,'completed fixture must not bind its original absolute root');
  return {path:relative(root,path),bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};
 }).sort((a,b)=>a.path.localeCompare(b.path));
}
async function createRetainedMatrixSeed(){
 const {root,id,completed,shared}=await completedMembershipFixture();
 assert.equal(completed.status,'closed');assert.equal(completed.case.revision!.state,'Completed');
 assert.ok(completed.grants.every(g=>g.revoked_at));assert.equal(shared.occupant?.(),null);
 return {root,id,completed,files:retainedFixtureFiles(root)};
}
let retainedMatrixSeed:ReturnType<typeof createRetainedMatrixSeed>|undefined;
// Only the repeated material-policy matrices share immutable completed bytes.
// Every consumer gets its own project, applications, stores and model lease;
// current retained authorization is still issued by the real Application.
async function retainedMatrixFixture(respond:(payload:string)=>Promise<unknown>){
 const seed=await (retainedMatrixSeed??=createRetainedMatrixSeed()),root=mkdtempSync(join(process.env.JUANERAI_TEST_EVIDENCE_DIR??tmpdir(),'member-retained-'));
 cpSync(seed.root,root,{recursive:true});assert.deepEqual(retainedFixtureFiles(root),seed.files);
 const base=await blankTaskFixture(root),store=createLocalMembershipTaskStore(root),shared=createLocalModelAccess(true);
 const app=createMembershipTaskApplication({desktop:base.desktop,project_id:desktopTestIds.project,store,profile:syntheticProfile(),modelAccess:shared,sourceStore:createLocalDesktopDecisionCaseStore({projectRoot:root})});
 const completed=await app.read(seed.id);assert.deepEqual(completed,seed.completed,'copied completed source must retain the exact public projection');
 return retainedFixture(respond,()=>new Date(),{root,id:seed.id,desktop:base.desktop,store,shared,app,completed});
}
after(async()=>{if(retainedMatrixSeed){const seed=await retainedMatrixSeed;assert.deepEqual(retainedFixtureFiles(seed.root),seed.files,'all matrix consumers must preserve the closed seed bytes');}});

test('CI-PERF-005 completed fixture copies preserve independent state and source-tamper rejection',async()=>{
 const first=await retainedMatrixFixture(async()=>({kind:'advice',text:'unused'})),second=await retainedMatrixFixture(async()=>({kind:'advice',text:'unused'}));
 assert.notEqual(first.root,second.root);assert.notEqual(first.shared,second.shared);assert.notEqual(first.parent.session.id,second.parent.session.id);
 const secondBefore=await second.app.read(second.id),source=join(first.root,first.completed.owner.session_id,'010_draw',first.completed.case.snapshot!.snapshot_id,'orders.csv');
 writeFileSync(source,'synthetic clone-only source drift');
 await assert.rejects(()=>createLocalDesktopDecisionCaseStore({projectRoot:first.root}).readConfirmedSnapshot({...first.completed.owner,confirmation_id:first.completed.case.confirmation!.confirmation_id}),{code:'INTEGRITY_BLOCKED'});
 assert.deepEqual(await second.app.read(second.id),secondBefore,'one copy cannot change another source or resource ledger');
 const authorization=await second.retained.prepare(second.parent.session.id,'核对当前结果');assert.deepEqual(authorization.blockers,[]);
 await first.retained.close();await second.retained.close();
 const db=new DatabaseSync(join(second.root,'.xanthil/desktop/state.sqlite'));db.prepare('UPDATE membership_attempts SET body_sha256=?').run('f'.repeat(64));db.close();
 await assert.rejects(()=>second.store.read(second.id),{code:'INTEGRITY_BLOCKED'});
 const seed=await retainedMatrixSeed!;assert.deepEqual(retainedFixtureFiles(seed.root),seed.files,'source and database mutations in both copies must leave seed bytes unchanged');
});
for(const operation of ['stop','close'] as const)test(`P1-D004-02 ${operation} fences late result and retains unknown usage and physical ownership`,async()=>{
 let entered!:()=>void,release!:()=>void;const entry=new Promise<void>(r=>entered=r),pending=new Promise<void>(r=>release=r);const f=await retainedFixture(async()=>{entered();await pending;return {kind:'advice',text:'迟到合成意见'};}),id=f.parent.session.id,a=await f.retained.prepare(id,'核对当前结果');await f.retained.start(id,a.id,true);await entry;
 if(operation==='stop')await f.retained.stop(id);else await f.retained.closeSession(id,true);
 let state=await f.store.read(f.id);assert.ok(state.grants.find(g=>g.id===a.id)?.revoked_at,'logical stop must durably revoke retained grant');assert.ok(f.shared.occupant?.());assert.equal(state.status,'closed');assert.equal(state.usage.at(-1)?.calls,1);release();for(let n=0;n<100&&f.shared.occupant?.();n++)await new Promise(r=>setTimeout(r,10));assert.equal(f.shared.occupant?.(),null);
 assert.equal((await f.retained.read(id)).events.some(e=>e.kind==='advice'),false);state=await createLocalMembershipTaskStore(f.root).read(f.id);assert.equal(state.usage.at(-1)?.status,'unresolved');assert.equal(state.usage.reduce((n,u)=>n+u.calls,0),f.completed.totals.calls+1);await f.app.reopen();assert.equal((await f.app.read(f.id)).status,'closed');await f.retained.close();
});
for(const material of ['member_id','检查 1 /2026/private','请检查 exports/.env','请检查 exports%2F.env','/Volumes/Finance/exports/source.csv','/tmp/source.csv','Please check exports/source.csv.','请检查 exports/source.csv！'])test(`P1-D004-03 selected text history and child result cannot launder raw identity or group labels (${material})`,async()=>{
 let calls=0;const f=await retainedMatrixFixture(async()=>++calls===1?{kind:'advice',text:material}:{kind:'question',text:'合成问题'}),id=f.parent.session.id;
 await assert.rejects(()=>f.retained.prepare(id,material),{code:'OUTBOUND_FORBIDDEN'});
 const a=await f.retained.prepare(id,'核对结果');await f.retained.start(id,a.id,true);assert.equal((await f.wait()).attempts.at(-1)?.status,'Failed');assert.equal((await f.retained.read(id)).events.some(e=>e.kind==='advice'),false);
 const fresh=await f.retained.prepare(id,'再次核对');await f.retained.start(id,fresh.id,true);await f.wait();const attempt=(await f.retained.read(id)).attempts.at(-1)!;await f.assistantStore.appendEvent(id,{id:randomUUID(),attempt_id:attempt.id,at:new Date().toISOString(),kind:'advice',text:material,tool:null,status:'completed',source_revision:f.completed.owner.revision_id});const poisoned=(await f.retained.read(id)).events.at(-1)!;await f.retained.stop(id);await assert.rejects(()=>f.retained.prepare(id,'检查', [poisoned.id]),{code:'OUTBOUND_FORBIDDEN'});await f.retained.close();
});

test('P1-B-EXPRESSION-02 concise revision replaces the primary expression while immutable facts and older reports remain',async()=>{
 let calls=0;const f=await authorizedTaskFixture(async()=>++calls===1?{kind:'tool',tool:'execute_plan'}:calls===2?{kind:'report',text:'初始说明'}:{kind:'comment',intent:'expression',text:calls===3?'复购率持平，收入增加。':'复购率持平。',periods:null});await f.app.continue(f.id);let p=await f.app.wait(f.id);const original=p.case.reports[0];
 for(let i=0;i<2;i++){const r=p.case.reports.at(-1)!,id=randomUUID();await f.app.comment(f.id,{id,report_id:r.report_id,report_version:r.version_sequence,report_sha256:r.markdown_sha256,scope:'expression',author:'合成人员',text:'简短一点',text_consent:true});await f.app.processComment(f.id,id);p=await f.app.wait(f.id);}
 const latest=p.case.reports.at(-1)!.review_content!.markdown_text;assert.ok(latest.indexOf('复购率持平。')<latest.indexOf('## 两期指标'),'revised expression must be primary, not an appendix');assert.equal(latest.includes('复购率持平，收入增加。'),false,'new expression replaces earlier expression');assert.ok(latest.includes(original.review_content!.markdown_text),'exact facts and evidence remain accessible');assert.deepEqual(p.case.reports[0],original);assert.ok(p.case.reports[1].review_content!.markdown_text.includes('复购率持平，收入增加。'));assert.equal(p.case.runs.length,1);assert.equal(p.case.findings.length,1);
});

test('P1-D004-04 expiry and changed source persist fences and forbid late publication',async()=>{
 let time=Date.now(),entered!:()=>void,release!:()=>void;const entry=new Promise<void>(r=>entered=r),pending=new Promise<void>(r=>release=r);const f=await retainedFixture(async()=>{entered();await pending;return {kind:'advice',text:'迟到意见'};},()=>new Date(time));const id=f.parent.session.id,a=await f.retained.prepare(id,'检查');await f.retained.start(id,a.id,true);await entry;time=Date.parse(a.membership!.expires_at)+1;
 await f.retained.read(id);assert.ok((await f.store.read(f.id)).grants.find(g=>g.id===a.id)?.revoked_at);release();for(let n=0;n<100&&f.shared.occupant?.();n++)await new Promise(r=>setTimeout(r,10));assert.equal((await f.retained.read(id)).events.some(e=>e.kind==='advice'),false);assert.equal((await f.store.read(f.id)).usage.at(-1)?.status,'unresolved');await f.retained.close();
});
test('P1-D004-05 source drift refuses explicit stale preview before issue',async()=>{
 let calls=0;const f=await retainedFixture(async()=>{calls++;return {kind:'advice',text:'合成回答'};}),id=f.parent.session.id,a=await f.retained.prepare(id,'核对结果');
 const db=new DatabaseSync(join(f.root,'.xanthil/desktop/state.sqlite'));db.prepare('UPDATE case_revisions SET row_version=row_version+1 WHERE revision_id=?').run(f.completed.owner.revision_id);db.close();await assert.rejects(()=>f.retained.start(id,a.id,true));assert.equal(calls,0);const restore=new DatabaseSync(join(f.root,'.xanthil/desktop/state.sqlite'));restore.prepare('UPDATE case_revisions SET row_version=row_version-1 WHERE revision_id=?').run(f.completed.owner.revision_id);restore.close();assert.equal((await f.store.read(f.id)).usage.length,f.completed.usage.length);await f.retained.close();
});

test('P1-D004-06 original completed task cannot regain admission via ordinary authorize',async()=>{
 const f=await reviewChoiceFixture();const p=await f.app.submitReview(f.id,f.command);await assert.rejects(()=>f.app.authorize(f.id,{fingerprint:p.prepared!.fingerprint,source_files:f.input.source_files,authority_confirmed:true,text_consent:false}));assert.equal((await f.app.read(f.id)).status,'closed');
});

for(const material of ['member_id','检查 1 /2026/private','请检查 exports/.env','请检查 exports%2F.env','/Volumes/Finance/exports/source.csv','/tmp/source.csv','Please check exports/source.csv.','请检查 exports/source.csv！'])test(`P1-D004-07 manual child result refuses prohibited text before save or return (${material})`,async()=>{
 const f=await retainedMatrixFixture(async payload=>({kind:'result',summary:material,references:[JSON.parse(payload).authorized_context.allowed_references[0]],limitations:['合成限制'],unknowns:[]})),id=f.parent.session.id;
 const preview=await f.retained.prepareChild(id,'subagent','检查反证',null,[],[],true),child=await f.retained.createChild(id,preview.id,randomUUID(),true),a=await f.retained.prepareCollaboration(child.session.id,'检查反证',[],[]);await f.retained.start(child.session.id,a.id,true);for(let n=0;n<200&&(await f.retained.read(child.session.id)).attempts.at(-1)?.status==='Running';n++)await new Promise(r=>setTimeout(r,10));assert.equal((await f.retained.read(child.session.id)).attempts.at(-1)?.status,'Failed');assert.equal((await f.retained.readCollaboration(child.session.id)).results.length,0);assert.equal((await f.retained.readParent(id)).deliveries.length,0);assert.equal((await f.app.read(f.id)).totals.calls,f.completed.totals.calls+1);await f.retained.close();
});

for(const material of ['member_id','检查 1 /2026/private','请检查 exports/.env','请检查 exports%2F.env','/Volumes/Finance/exports/source.csv','/tmp/source.csv','Please check exports/source.csv.','请检查 exports/source.csv！'])test(`P1-D004-08 Waiting holds the shared slot and cumulative reservation; unsafe reply has no extra request (${material})`,async()=>{
 let calls=0;const f=await retainedMatrixFixture(async()=>{calls++;return {kind:'question',text:'需要补充哪项限制？'};}),id=f.parent.session.id,a=await f.retained.prepare(id,'检查限制');await f.retained.start(id,a.id,true);assert.equal((await f.wait()).attempts.at(-1)?.status,'Waiting');assert.ok(f.shared.occupant?.());let state=await f.store.read(f.id);assert.equal(state.usage.at(-1)?.kind,'waiting');assert.equal(state.usage.at(-1)?.status,'issued');await assert.rejects(()=>f.retained.send(id,material),{code:'OUTBOUND_FORBIDDEN'});assert.equal(calls,1);state=await f.store.read(f.id);assert.ok(state.grants.find(g=>g.id===a.id)?.revoked_at);assert.equal(state.usage.reduce((n,u)=>n+u.calls,0),f.completed.totals.calls+1);await f.retained.close();
});

test('P1-D004-09 reopened Application retains completed identity and cumulative usage without issuing',async()=>{
 let calls=0;const f=await retainedFixture(async()=>{calls++;return {kind:'advice',text:'合成回答'};}),id=f.parent.session.id,a=await f.retained.prepare(id,'核对');await f.retained.start(id,a.id,true);await f.wait();const before=await f.app.read(f.id);await f.retained.close();await f.app.reopen();const after=await f.app.read(f.id);assert.deepEqual(after.usage,before.usage);assert.equal(after.case.revision!.state,'Completed');assert.equal(after.status,'closed');assert.equal(calls,1);assert.ok(after.grants.every(g=>g.revoked_at));
});

test('P1-D004-10 late source-byte drift revokes retained grant without publishing',async()=>{
 let entered!:()=>void,release!:()=>void;const entry=new Promise<void>(r=>entered=r),pending=new Promise<void>(r=>release=r);const f=await retainedFixture(async()=>{entered();await pending;return {kind:'advice',text:'迟到意见'};}),id=f.parent.session.id,a=await f.retained.prepare(id,'检查');await f.retained.start(id,a.id,true);await entry;const path=join(f.root,f.completed.owner.session_id,'010_draw',f.completed.case.snapshot!.snapshot_id,'orders.csv'),bytes=readFileSync(path);writeFileSync(path,'synthetic source drift');release();for(let n=0;n<100&&f.shared.occupant?.();n++)await new Promise(r=>setTimeout(r,10));writeFileSync(path,bytes);assert.equal((await f.retained.read(id)).events.some(e=>e.kind==='advice'),false);assert.ok((await f.store.read(f.id)).grants.find(g=>g.id===a.id)?.revoked_at);assert.equal((await f.app.read(f.id)).totals.calls,f.completed.totals.calls+1);await f.retained.close();
});
test('P1-D004-11 changed finite profile cannot reset or expand originating allowance',async()=>{
 const f=await retainedFixture(async()=>({kind:'advice',text:'unused'})),{createCaseAssistantApplication}=await import('../../../packages/application/case-assistant.ts');let calls=0;const app=createCaseAssistantApplication({store:f.assistantStore,clock:()=>new Date(),config:legacyConfig,runtime:{async turn(){calls++;throw Error('forbidden');}},modelAccess:f.shared,membership:{store:f.store,desktop:f.desktop,sourceStore:createLocalDesktopDecisionCaseStore({projectRoot:f.root}),profile:{...syntheticProfile(),model_calls:11}}});await assert.rejects(()=>app.prepare(f.parent.session.id,'检查'),{code:'CONFIGURATION_CHANGED'});assert.equal(calls,0);assert.deepEqual((await f.store.read(f.id)).usage,f.completed.usage);await app.close();await f.retained.close();
});

test('P1-D004-12 retained origin activation rolls back atomically and actual frozen reader refuses 102',async()=>{
 const {withFork}=await import('../../fixtures/case-assistant/collaboration.ts');await withFork('retained-activation',async legacy=>{
 const {pathToFileURL}=await import('node:url');const historical=readFileSync('tests/fixtures/case-assistant/reader-c413bee3.ts.txt','utf8');assert.equal((await import('node:crypto')).createHash('sha256').update(historical).digest('hex'),'93e19f9c212520de5738eb0c1f68d7efdc5ae8ea4a4c85323fbd1c246c5d6b04');const oldPath=join(legacy.root,'frozen-reader.ts');writeFileSync(oldPath,historical.replace(/from ['"](\.[^'"]+)['"]/g,(_all,relative)=>`from ${JSON.stringify(new URL(relative,new URL('../../../adapters/storage-local/case-assistant.ts',import.meta.url)).href)}`));const frozen=await import(pathToFileURL(oldPath).href),old=frozen.createLocalCaseAssistantStore({projectRoot:legacy.root});const oldSessions=await old.listSessions(legacy.baseline.owner.project_id);
 const sidecar=join(legacy.root,'.xanthil/desktop/case-assistant.sqlite'),inspect=()=>{const db=new DatabaseSync(sidecar);try{return {version:db.prepare('PRAGMA user_version').get()!.user_version,rows:Object.fromEntries(['sessions','attempts','events','drafts','decisions','reports','heads','receipts','collaboration_children','collaboration_lifecycle','collaboration_results','collaboration_returns','collaboration_reviews'].map(t=>[t,db.prepare(`SELECT * FROM ${t} ORDER BY rowid`).all()]))};}finally{db.close();}};
 const f=await reviewChoiceFixture(legacy.root),completed=await f.app.submitReview(f.id,{...f.command,outcome:'analysis'});assert.equal(inspect().version,101);const before=inspect();const {createLocalCaseAssistantStore}=await import('../../../adapters/storage-local/case-assistant.ts'),store=createLocalCaseAssistantStore({projectRoot:f.root}),source=await store.readSource(completed.owner),session={id:randomUUID(),project_id:completed.owner.project_id,title:'合成后续',source:completed.owner,created_at:new Date().toISOString(),archived:false};
 const exec=DatabaseSync.prototype.exec;let injected=false;DatabaseSync.prototype.exec=function(sql:string){const result=exec.call(this,sql);if(!injected&&sql.includes('user_version=102')){injected=true;throw Error('synthetic activation interruption');}return result;};try{await assert.rejects(()=>store.createSession(randomUUID(),session,source));assert.equal(injected,true);}finally{DatabaseSync.prototype.exec=exec;}
 assert.deepEqual(inspect(),before);assert.deepEqual(await old.listSessions(completed.owner.project_id),oldSessions);await store.createSession(randomUUID(),session,source);assert.equal(inspect().version,102);const bytes=readFileSync(sidecar);await assert.rejects(()=>old.listSessions(completed.owner.project_id),{code:'SCHEMA_UNSUPPORTED'});assert.deepEqual(readFileSync(sidecar),bytes);const after=inspect();for(const [table,rows]of Object.entries(before.rows))assert.deepEqual(after.rows[table].slice(0,rows.length),rows,table);assert.equal((await createLocalCaseAssistantStore({projectRoot:f.root}).readSession(session.id)).session.id,session.id);
 });
});

test('UI-P1-D004-INTERACTION main authorization discloses original ledger before explicit consent and actual IPC start',async()=>{
 let calls=0;const f=await retainedFixture(async()=>{calls++;return {kind:'advice',text:'合成限定意见'};});const {createCaseAssistantHandler}=await import('../../../apps/desktop/case-assistant-main.ts'),{memberComponentProbe}=await import('../../fixtures/xanthil-desktop/member-component-probe.ts');const handler=createCaseAssistantHandler({senderPolicy:()=>true,getApplication:()=>f.retained,exportReport:async()=>assert.fail('no export')});let pending=Promise.resolve();const requests:any[]=[];const api={request(input:any){requests.push(input);const work=handler('main',input);pending=work.then(r=>{assert.equal(r.ok,true,JSON.stringify(r));});return work;}};const probe=await memberComponentProbe(f.root,'CaseAssistantWorkspace','case-assistant-workspace.tsx');const render=()=>probe.render({api,projectId:f.completed.owner.project_id,sources:[],initial:f.parent,onChange(){},onOpenSource(){},onChooseProject(){}});render();probe.input('Case Assistant 任务文本').onChange({target:{value:'检查当前结果'}});render();probe.button('查看任务授权').onClick();await pending;await new Promise(r=>setImmediate(r));render();assert.equal(calls,0);const disclosure=probe.component('MembershipResourceDisclosure').find(p=>p.authorization?.membership);assert.ok(disclosure,'the real confirmation dialog must disclose the original ledger before start');assert.equal(disclosure.authorization.membership.task_id,f.id);assert.deepEqual(disclosure.authorization.membership.usage,f.completed.totals);assert.equal(probe.field('我单独确认上述自由文本').checked,false);assert.equal(probe.button('确认并开始').disabled,true);probe.field('我单独确认上述自由文本').onChange({target:{checked:true}});render();probe.button('确认并开始').onClick();await pending;await f.wait();assert.equal(calls,1);assert.equal((await f.app.read(f.id)).totals.calls,f.completed.totals.calls+1);assert.deepEqual(requests.map(r=>r.operation),['prepare','start']);probe.dispose();await f.retained.close();
});

for(const material of ['/custom-root/private/source.csv','检查 1 /2026/private','请检查 exports/.env','请检查 exports%2F.env','exports/source.csv!','exports%2Fsource.csv。'])for(const kind of ['report','comment'] as const)test(`F1 returned ${kind} ${material} path cannot become published or reused material`,async()=>{
 let calls=0;const f=await authorizedTaskFixture(async()=>++calls===1?{kind:'tool',tool:'execute_plan'}:kind==='report'?{kind:'report',text:'资料在 '+material}:calls===2?{kind:'report',text:'已核对'}:{kind:'comment',intent:'expression',text:'资料在 '+material,periods:null});await f.app.continue(f.id);let p=await f.app.wait(f.id);const original=p.case.reports[0];
 if(kind==='comment'){const id=randomUUID();await f.app.comment(f.id,{id,report_id:original.report_id,report_version:original.version_sequence,report_sha256:original.markdown_sha256,scope:'expression',author:'合成人员',text:'简短一点',text_consent:true});await f.app.processComment(f.id,id);p=await f.app.wait(f.id);}
 assert.equal(p.attempts.at(-1)!.status,'failed');assert.equal(p.attempts.at(-1)!.error,'OUTBOUND_FORBIDDEN');assert.equal(p.events.some(e=>e.kind==='explanation'&&e.text.includes(material)),false);assert.equal(p.case.reports.length,1);assert.deepEqual(p.case.reports[0],original);assert.equal(p.comments.some(c=>c.resolution?.text.includes(material)),false);assert.equal(p.case.findings.length,1);
});

for(const material of ['/Volumes/Finance/exports/source.csv','检查 1 /2026/private','请检查 exports/.env','请检查 exports%2F.env','/tmp/source.csv','exports/source.csv.','exports%2Fsource.csv！'])test(`F1 Application new question supplement and comment deny ${material} before actual transport`,async()=>{
 let calls=0;const f=await authorizedTaskFixture(async()=>++calls===1?{kind:'question',text:'请核对'}:calls===2?{kind:'tool',tool:'execute_plan'}:{kind:'report',text:'已核对'});const other=await f.app.create('检查 '+material,randomUUID()),prepared=await f.app.prepare(other.task_id,f.input);await assert.rejects(()=>f.app.authorize(other.task_id,{fingerprint:prepared.prepared!.fingerprint,source_files:f.input.source_files,authority_confirmed:true,text_consent:true}),{code:'OUTBOUND_FORBIDDEN'});assert.equal(calls,0);assert.equal((await f.app.read(other.task_id)).usage.length,0);
 await f.app.continue(f.id);await until(async()=>(await f.app.read(f.id)).status==='waiting');await assert.rejects(()=>f.app.reply(f.id,'请检查 '+material,true),{code:'OUTBOUND_FORBIDDEN'});assert.equal(calls,1);await f.app.reply(f.id,'请继续核对两期比例',true);const p=await f.app.wait(f.id),report=p.case.reports[0],id=randomUUID();await f.app.comment(f.id,{id,report_id:report.report_id,report_version:report.version_sequence,report_sha256:report.markdown_sha256,scope:'expression',author:'合成人员',text:'请检查 '+material,text_consent:true});const before=(await f.app.read(f.id)).usage;await assert.rejects(()=>f.app.processComment(f.id,id),{code:'OUTBOUND_FORBIDDEN'});assert.equal(calls,3);assert.deepEqual((await f.app.read(f.id)).usage,before);
});

for(const forbidden of ['/tmp/source.csv','检查 1 /2026/private','请检查 exports/.env','请检查 exports%2F.env','exports/source.csv!'])for(const kind of ['fork','subagent'] as const)test(`F1 retained ${kind} ${forbidden} initial selected reports return adoption and late reuse enforce current material policy`,async()=>{
 let isChild=false;const payloads:string[]=[];const f=await retainedMatrixFixture(async payload=>{payloads.push(payload);return isChild?{kind:'result',summary:'合成未知事项',references:[JSON.parse(payload).authorized_context.allowed_references[0]],limitations:['因果未知'],unknowns:[]}:{kind:'advice',text:'合成限制'};}),id=f.parent.session.id;const a=await f.retained.prepare(id,'核对当前结果',[],[f.parent.source.report.report_id]);await f.retained.start(id,a.id,true);await f.wait();const cutoff=kind==='fork'?(await f.retained.read(id)).events.find(e=>e.kind==='advice')!.id:null;
 await f.retained.prepareChild(id,kind,'检查 '+forbidden,cutoff,[],[],true); // A local preview grants no model admission.
 assert.equal(payloads.length,1);const preview=await f.retained.prepareChild(id,kind,'检查未知事项',cutoff,[],[f.parent.source.report.report_id],true),child=await f.retained.createChild(id,preview.id,randomUUID(),true);await assert.rejects(()=>f.retained.prepareCollaboration(child.session.id,'检查 /Volumes/Finance/source.csv',[],[]),{code:'OUTBOUND_FORBIDDEN'});const ca=await f.retained.prepareCollaboration(child.session.id,'检查未知事项',[],[]);isChild=true;await f.retained.start(child.session.id,ca.id,true);await until(async()=>(await f.retained.read(child.session.id)).attempts.at(-1)?.status!=='Running');const result=(await f.retained.readCollaboration(child.session.id)).results[0],target={result_id:result.id,result_version:result.version,result_sha256:result.sha256};assert.ok(result);assert.equal(payloads.length,2);for(const payload of payloads){assert.equal(payload.includes(f.completed.case.reports.at(-1)!.review_content!.markdown_text),false);assert.doesNotMatch(payload,/\/tmp\/|\/Volumes\/|member_id|North|South/);assert.equal(JSON.parse(payload).authorized_context.selected_reports[0].material.result.m2,undefined);}
 // Simulate a readable pre-correction result. Both the inner immutable identity
 // and the SQLite envelope are rehashed, so refusal must be material policy.
 const {createHash}=await import('node:crypto');const encode=(v:unknown)=>JSON.stringify(v,(_k,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x),hash=(v:string)=>createHash('sha256').update(v).digest('hex');const poison=()=>{const {sha256,...body}=result;body.value={...body.value,summary:'检查 '+forbidden};const poisoned={...body,sha256:hash(encode(body))},text=encode(poisoned),db=new DatabaseSync(join(f.root,'.xanthil/desktop/case-assistant.sqlite'));db.prepare('UPDATE collaboration_results SET body=?,sha256=? WHERE id=?').run(text,hash(text),result.id);db.close();return {...target,result_sha256:poisoned.sha256};};
 const bad=poison();assert.equal((await f.assistantStore.childResults(child.session.id))[0].value.summary,'检查 '+forbidden);await assert.rejects(()=>f.retained.returnResult(child.session.id,bad,randomUUID()),{code:'OUTBOUND_FORBIDDEN'});await assert.rejects(()=>f.retained.reviewResult(id,bad,randomUUID(),'adopted','人工选择',true),{code:'OUTBOUND_FORBIDDEN'});assert.equal(payloads.length,2);assert.equal((await f.retained.readParent(id)).materials.length,0);
 const restore=new DatabaseSync(join(f.root,'.xanthil/desktop/case-assistant.sqlite')),original=encode(result);restore.prepare('UPDATE collaboration_results SET body=?,sha256=? WHERE id=?').run(original,hash(original),result.id);restore.close();if(kind==='fork')await f.retained.returnResult(child.session.id,target,randomUUID());await f.retained.reviewResult(id,target,randomUUID(),'adopted','合成历史采纳',true);const adopted=(await f.retained.readParent(id)).materials[0];const poisoned=poison(),db=new DatabaseSync(join(f.root,'.xanthil/desktop/case-assistant.sqlite'));const body=encode({...adopted.review,result_sha256:poisoned.result_sha256});db.prepare('UPDATE collaboration_reviews SET body=?,sha256=? WHERE id=?').run(body,hash(body),result.id);db.close();assert.equal((await f.retained.readParent(id)).materials.length,1);await assert.rejects(()=>f.retained.prepareParent(id,'检查旧意见',[],[],[adopted.id],false),{code:'OUTBOUND_FORBIDDEN'});assert.equal(payloads.length,2);await f.retained.close();
});

for(const text of ['占比 50 % / 100 %','复购会员数（人） / 活跃会员数（人）','金额 100元 / 20人'])test(`F1-V4 Application preserves unit ratio through question reply report and expression comment: ${text}`,async()=>{
 const payloads:any[]=[];const f=await authorizedTaskFixture(async payload=>{payloads.push(JSON.parse(payload));return payloads.length===1?{kind:'question',text}:payloads.length===2?{kind:'tool',tool:'execute_plan'}:payloads.length===3?{kind:'report',text}:{kind:'comment',intent:'expression',text,periods:null};});
 const created=await f.app.create(text,randomUUID()),prepared=await f.app.prepare(created.task_id,f.input);await f.app.authorize(created.task_id,{fingerprint:prepared.prepared!.fingerprint,source_files:f.input.source_files,authority_confirmed:true,text_consent:true});await f.app.continue(created.task_id);await until(async()=>(await f.app.read(created.task_id)).status==='waiting');assert.equal(payloads[0].selected_text,text);await f.app.reply(created.task_id,text,true);let p=await f.app.wait(created.task_id);assert.equal(payloads[1].selected_text,text);assert.equal(p.attempts.at(-1)!.status,'succeeded');assert.ok(p.events.some(e=>e.kind==='explanation'&&e.text===text));const report=p.case.reports[0],id=randomUUID();await f.app.comment(created.task_id,{id,report_id:report.report_id,report_version:report.version_sequence,report_sha256:report.markdown_sha256,scope:'expression',author:'合成人员',text,text_consent:true});await f.app.processComment(created.task_id,id);p=await f.app.wait(created.task_id);assert.equal(payloads.at(-1).selected_text,text);assert.equal(p.comments.at(-1)!.resolution!.text,text);assert.equal(p.case.reports.length,2);assert.deepEqual(p.case.reports[0],report);
});
for(const text of ['占比 50 % / 100 %','复购会员数（人） / 活跃会员数（人）','金额 100元 / 20人'])test(`F1-V4 retained Application preserves unit ratio in main return and selected history: ${text}`,async()=>{
 const payloads:any[]=[];const f=await retainedFixture(async p=>{payloads.push(JSON.parse(p));return {kind:'advice',text};}),id=f.parent.session.id;
 const a=await f.retained.prepare(id,text);await f.retained.start(id,a.id,true);const first=await f.wait();assert.equal(first.attempts.at(-1)!.status,'Succeeded');const advice=first.events.find(e=>e.kind==='advice'&&e.text===text)!;assert.ok(advice);assert.equal(payloads[0].visible_message,text);const b=await f.retained.prepare(id,text,[advice.id]);await f.retained.start(id,b.id,true);await f.wait();assert.equal(payloads[1].authorized_context.selected_history[0].text,text);assert.equal(payloads[1].visible_message,text);await f.retained.close();
});

for(const text of ['复购会员数 （人） / 活跃会员数 （人）','复购会员数（ 人 ） / 活跃会员数（ 人 ）'])test(`F1-V5 Application preserves unit ratio through question reply report and expression comment: ${text}`,async()=>{
 const payloads:any[]=[];const f=await authorizedTaskFixture(async payload=>{payloads.push(JSON.parse(payload));return payloads.length===1?{kind:'question',text}:payloads.length===2?{kind:'tool',tool:'execute_plan'}:payloads.length===3?{kind:'report',text}:{kind:'comment',intent:'expression',text,periods:null};});
 const created=await f.app.create(text,randomUUID()),prepared=await f.app.prepare(created.task_id,f.input);await f.app.authorize(created.task_id,{fingerprint:prepared.prepared!.fingerprint,source_files:f.input.source_files,authority_confirmed:true,text_consent:true});await f.app.continue(created.task_id);await until(async()=>(await f.app.read(created.task_id)).status==='waiting');assert.equal(payloads[0].selected_text,text);await f.app.reply(created.task_id,text,true);let p=await f.app.wait(created.task_id);assert.equal(payloads[1].selected_text,text);assert.equal(p.attempts.at(-1)!.status,'succeeded');assert.ok(p.events.some(e=>e.kind==='explanation'&&e.text===text));const report=p.case.reports[0],id=randomUUID();await f.app.comment(created.task_id,{id,report_id:report.report_id,report_version:report.version_sequence,report_sha256:report.markdown_sha256,scope:'expression',author:'合成人员',text,text_consent:true});await f.app.processComment(created.task_id,id);p=await f.app.wait(created.task_id);assert.equal(payloads.at(-1).selected_text,text);assert.equal(p.comments.at(-1)!.resolution!.text,text);assert.equal(p.case.reports.length,2);assert.deepEqual(p.case.reports[0],report);
});
for(const text of ['复购会员数 （人） / 活跃会员数 （人）','复购会员数（ 人 ） / 活跃会员数（ 人 ）'])test(`F1-V5 retained Application preserves unit ratio in main return and selected history: ${text}`,async()=>{
 const payloads:any[]=[];const f=await retainedFixture(async p=>{payloads.push(JSON.parse(p));return {kind:'advice',text};}),id=f.parent.session.id;
 const a=await f.retained.prepare(id,text);await f.retained.start(id,a.id,true);const first=await f.wait();assert.equal(first.attempts.at(-1)!.status,'Succeeded');const advice=first.events.find(e=>e.kind==='advice'&&e.text===text)!;assert.ok(advice);assert.equal(payloads[0].visible_message,text);const b=await f.retained.prepare(id,text,[advice.id]);await f.retained.start(id,b.id,true);await f.wait();assert.equal(payloads[1].authorized_context.selected_history[0].text,text);assert.equal(payloads[1].visible_message,text);await f.retained.close();
});
