import { createHash } from 'node:crypto';

export const COORDINATOR_SCHEMA_VERSION = '1.0';

const sha256 = value => createHash('sha256').update(value).digest('hex');
const canonical = value => Array.isArray(value) ? `[${value.map(canonical).join(',')}]` : value && typeof value === 'object' ? `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}` : JSON.stringify(value);
const clone = value => structuredClone(value);
const exact = (value, keys) => value !== null && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === keys.length && keys.every(key => Object.hasOwn(value, key));
const isSha = value => typeof value === 'string' && /^[0-9a-f]{40}$/.test(value);
const isHash = value => typeof value === 'string' && /^[0-9a-f]{64}$/.test(value);
const rejected = (operation, error_code, change_id = null) => ({ schema_version: COORDINATOR_SCHEMA_VERSION, operation, outcome: 'REJECTED', error_code, change_id, state: null });
const receipt = value => sha256(canonical(value));
const result = (operation, outcome, state, state_version, state_hash, change_id, payload) => ({ schema_version: COORDINATOR_SCHEMA_VERSION, operation, outcome, change_id, state, state_version, state_hash, payload });

function validCommand(body) {
  const top = ['schema_version', 'command_id', 'key_id', 'repository', 'change_id', 'command_kind', 'payload', 'scope', 'worktree', 'expected_state_version', 'expected_state_hash', 'nonce', 'issued_at', 'expires_at', 'idempotency_id', 'receipt_digest', 'evidence_refs'];
  if (!exact(body, top) || body.schema_version !== '1.0' || !['DISPATCH', 'REVISION', 'RESUME', 'RELEASE'].includes(body.command_kind)) return false;
  if (!exact(body.repository, ['canonical_root', 'origin', 'integration_branch']) || body.repository.origin !== 'origin' || body.repository.integration_branch !== 'main') return false;
  const canonicalTime = value => typeof value === 'string' && /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(value) && new Date(value).toISOString() === value;
  const pathValid = value => typeof value === 'string' && value.length > 0 && !value.startsWith('/') && !value.includes('..') && !value.includes('\\') && !value.includes('\0') && (value.indexOf('*') < 0 || (value.endsWith('/**') && value.indexOf('*') === value.length - 2));
  const ordered = values => Array.isArray(values) && values.every((value, index) => index === 0 || values[index - 1] < value);
  if (!exact(body.scope, ['allowed_paths', 'forbidden_paths']) || !ordered(body.scope.allowed_paths) || !ordered(body.scope.forbidden_paths) || !body.scope.allowed_paths.every(pathValid) || !body.scope.forbidden_paths.every(pathValid)) return false;
  if (!exact(body.worktree, ['branch', 'root', 'baseline_sha']) || !isSha(body.worktree.baseline_sha) || !isHash(body.receipt_digest) || !Array.isArray(body.evidence_refs)) return false;
  if (typeof body.change_id !== 'string' || typeof body.command_id !== 'string' || typeof body.idempotency_id !== 'string' || !/^[A-Za-z0-9+/]{43}=$/.test(body.nonce) || Buffer.from(body.nonce, 'base64').length !== 32 || !canonicalTime(body.issued_at) || !canonicalTime(body.expires_at) || Date.parse(body.expires_at) - Date.parse(body.issued_at) > 300000) return false;
  if (!ordered(body.evidence_refs) || !body.evidence_refs.every(ref => exact(ref, ['kind', 'id', 'sha256', 'subject_sha']) && typeof ref.kind === 'string' && typeof ref.id === 'string' && isHash(ref.sha256) && isSha(ref.subject_sha))) return false;
  if (body.command_kind === 'DISPATCH') {
    const p = body.payload;
    const roles = ['juaner_spec', 'juaner_test', 'juaner_worker', 'juaner_validator'];
    const roleKeys = ['role', 'agent', 'model', 'reasoning', 'sandbox', 'allowed_paths', 'brief_sha256', 'input_sha256', 'output_schema_sha256'];
    const validationKeys = ['id', 'argv', 'cwd', 'environment', 'timeout_ms', 'subject'];
    if (!exact(p, ['acceptance_ids', 'roles', 'validations', 'delivery_base', 'auto_repair_limit', 'expected_pointer_sha256']) || p.delivery_base !== 'main' || p.auto_repair_limit !== 1 || !isHash(p.expected_pointer_sha256) || !Array.isArray(p.roles) || p.roles.length !== 4 || p.roles.some((role, index) => !exact(role, roleKeys) || role.role !== roles[index] || role.agent !== roles[index] || !Array.isArray(role.allowed_paths) || !role.allowed_paths.every(pathValid) || !isHash(role.brief_sha256) || !isHash(role.input_sha256) || !isHash(role.output_schema_sha256)) || !Array.isArray(p.validations) || p.validations.some(v => !exact(v, validationKeys) || !Array.isArray(v.argv) || !exact(v.environment, []) || !Number.isSafeInteger(v.timeout_ms) || v.timeout_ms <= 0)) return false;
  }
  if (body.command_kind === 'REVISION' && (!exact(body.payload, ['changes_requested_ref', 'revision_of_candidate_sha', 'resume_phase']) || typeof body.payload.changes_requested_ref !== 'string' || !['TEST_RED', 'WORKER_GREEN'].includes(body.payload.resume_phase) || (body.payload.revision_of_candidate_sha !== null && !isSha(body.payload.revision_of_candidate_sha)))) return false;
  if (body.command_kind === 'RESUME' && (!exact(body.payload, ['resume_target']) || !exact(body.payload.resume_target, ['macro_state', 'phase']) || !['EXECUTING', 'DELIVERING'].includes(body.payload.resume_target.macro_state) || !['WORKTREE', 'TEST_RED', 'WORKER_GREEN', 'REGRESSION', 'STAGE', 'CANDIDATE_COMMIT', 'FINAL_VALIDATION', 'VALIDATOR', 'BRANCH_PUSH', 'CANDIDATE_FREEZE', 'PR', 'HANDOFF'].includes(body.payload.resume_target.phase))) return false;
  if (body.command_kind === 'RELEASE' && (!exact(body.payload, ['squash_sha', 'acceptance_ref', 'merge_ref', 'archive_ref', 'origin_main_sha', 'macbook_main_sha']) || !isSha(body.payload.squash_sha) || !isSha(body.payload.origin_main_sha) || !isSha(body.payload.macbook_main_sha) || ['acceptance_ref', 'merge_ref', 'archive_ref'].some(key => typeof body.payload[key] !== 'string' || !body.payload[key]))) return false;
  return true;
}

function validDependencies(d) {
  const keys = ['verifier', 'state', 'git', 'ledger', 'pull_request', 'validation', 'handoff', 'clock', 'ids', 'mutex'];
  const methods = {
    verifier: ['verify'], state: ['readPointer', 'writePointer', 'readState', 'writeState', 'readLocalPause', 'writeLocalPause'],
    git: ['inspectRepository', 'createOrReuseWorktree', 'inspectWorktree', 'stageExact', 'readStaged', 'commitCandidate', 'readCommit', 'pushBranch', 'readRemoteBranch', 'canonicalDiff', 'syncMainFfOnly'],
    ledger: ['readRemote', 'prepareAppend', 'commitAndPush', 'readRemoteAppend'], pull_request: ['queryCurrent', 'createOrReuse', 'readback'], validation: ['execute'], handoff: ['writeReadback'], clock: ['now'], ids: ['next'], mutex: ['tryAcquire', 'release'],
  };
  return d && typeof d === 'object' && Object.keys(d).length === keys.length && keys.every(key => d[key] && typeof d[key] === 'object' && methods[key].every(method => typeof d[key][method] === 'function'));
}
const stateHash = state => sha256(canonical(state));
function pointerValue(read) { if (read?.kind !== 'OK' || typeof read.value?.bytes !== 'string') return null; try { const value = JSON.parse(read.value.bytes); return canonical(value) === read.value.bytes && exact(value, ['schema_version', 'active_change_id']) && value.schema_version === '1.0' && (value.active_change_id === null || typeof value.active_change_id === 'string') ? value : null; } catch { return null; } }
function decodedState(read) { if (read?.kind !== 'OK' || typeof read.value?.bytes !== 'string') return null; try { const value = JSON.parse(read.value.bytes); return canonical(value) === read.value.bytes && read.value.sha256 === sha256(read.value.bytes) ? value : null; } catch { return null; } }
function route(state, dispatch) { const roles = dispatch.payload.roles; if (state.macro_state === 'READY' && state.phase === 'WORKTREE') return roles[0]; if (state.macro_state === 'EXECUTING') return state.phase === 'SPEC' ? roles[0] : state.phase === 'TEST_RED' ? roles[1] : state.phase === 'WORKER_GREEN' ? roles[2] : null; return state.macro_state === 'DELIVERING' && state.phase === 'VALIDATOR' ? roles[3] : null; }
function actionFor(state, role, ids) { const binding = { correlation_id: ids.next('agent'), role: role.role, agent: role.agent, model: role.model, reasoning: role.reasoning, sandbox: role.sandbox, allowed_paths: clone(role.allowed_paths), phase: state.phase, state_version: state.state_version, brief_sha256: role.brief_sha256, input_sha256: role.input_sha256, output_schema_sha256: role.output_schema_sha256, subject_sha: state.phase === 'VALIDATOR' ? state.candidate?.sha : state.repository.baseline_sha, idempotency_id: ids.next('agent-request') }; return { ...binding, action_kind: 'LAUNCH_AGENT' }; }

const TEST_CONSTRUCTION_SEEN = Symbol('test-construction-seen');
const TEST_ACCEPTED_DISPATCH = Symbol('test-accepted-dispatch');
const testRouteSeed = () => {
  const hash = 'a'.repeat(64);
  const role = (name, sandbox, allowed_paths) => ({ role: name, agent: name, model: 'gpt-5.6-terra', reasoning: 'high', sandbox, allowed_paths, brief_sha256: hash, input_sha256: hash, output_schema_sha256: hash });
  return {
    body_sha256: hash,
    body: {
      schema_version: '1.0', command_id: 'command-001', key_id: 'test-key', repository: { canonical_root: '/tmp/dtf-repo', origin: 'origin', integration_branch: 'main' }, change_id: 'CHG-dual-device-transition-foundation', command_kind: 'DISPATCH',
      payload: { acceptance_ids: ['AC-DTF-001-01'], roles: [role('juaner_spec', 'workspace-write', ['openspec/changes/dual-device-transition-foundation/**']), role('juaner_test', 'workspace-write', ['tools/harness/change-coordinator/**']), role('juaner_worker', 'workspace-write', ['tools/harness/change-coordinator/coordinator.mjs']), role('juaner_validator', 'read-only', [])], validations: [{ id: 'validation-001', argv: ['node', '--test'], cwd: '/tmp/dtf-worktree', environment: {}, timeout_ms: 60000, subject: 'HEAD' }], delivery_base: 'main', auto_repair_limit: 1, expected_pointer_sha256: sha256(canonical({ schema_version: '1.0', active_change_id: null })) },
      scope: { allowed_paths: ['tools/harness/change-coordinator/coordinator.mjs'], forbidden_paths: [] }, worktree: { branch: 'work/mac-mini/dtf', root: '/tmp/dtf-worktree', baseline_sha: '1'.repeat(40) }, expected_state_version: null, expected_state_hash: null, nonce: 'A'.repeat(43) + '=', issued_at: '2026-08-25T00:00:00.000Z', expires_at: '2026-08-25T00:01:00.000Z', idempotency_id: 'idem-001', receipt_digest: hash, evidence_refs: [],
    },
  };
};

function createCore(dependencies, initialAcceptedDispatch = null, testSeam = false) {
  if (!validDependencies(dependencies)) throw new TypeError('invalid Reduced V1 dependencies');
  const d = dependencies;
  let acceptedDispatch = initialAcceptedDispatch;
  const acquire = async operation => (await d.mutex.tryAcquire()) ? true : rejected(operation, 'OPERATION_BUSY');
  const stateResult = (operation, outcome, state, payload) => result(operation, outcome, state.macro_state, state.state_version, stateHash(state), state.change_id, payload);
  const readCurrent = async change_id => { const pointer = pointerValue(await d.state.readPointer({})); if (!pointer || !pointer.active_change_id || (change_id !== null && pointer.active_change_id !== change_id)) return { pointer, state: null }; const raw = await d.state.readState({ change_id: pointer.active_change_id }); return { pointer, state: decodedState(raw) }; };
  const writeState = async (state, prior = null) => { const old = prior ?? { ...state, state_version: state.state_version - 1 }; const written = await d.state.writeState({ change_id: state.change_id, expected_version: old.state_version, expected_sha256: stateHash(old), state, value: state, next_bytes: canonical(state) }); if (written?.kind !== 'OK' && written?.kind !== 'ALREADY_APPLIED') return false; const reread = decodedState(await d.state.readState({ change_id: state.change_id })); return reread !== null && canonical(reread) === canonical(state); };
  const block = async (operation, state, blocked_reason, next_action = 'MANUAL_CONTROLLER_STOP') => { if (!state) return result(operation, 'BLOCKED', null, null, null, null, { blocked_reason, next_action, blocked_event_id: null, local_pause_id: null }); const next = { ...state, macro_state: 'BLOCKED', phase: null, pending_agent: null, blocked_reason, resume_target: null, state_version: state.state_version + 1 }; if (!await writeState(next, state)) return result(operation, 'BLOCKED', null, null, null, state.change_id, { blocked_reason, next_action, blocked_event_id: null, local_pause_id: null }); return stateResult(operation, 'BLOCKED', next, { blocked_reason, next_action, blocked_event_id: null, local_pause_id: null }); };
  const unpersistedBlock = (operation, state, blocked_reason, next_action = 'MANUAL_CONTROLLER_STOP') => result(operation, 'BLOCKED', null, null, null, state?.change_id ?? null, { blocked_reason, next_action, blocked_event_id: null, local_pause_id: null });
  const append = async (state, event_class, detail) => { const prior = await d.ledger.readRemote({ change_id: state.change_id }); if (prior?.kind !== 'OK') return prior; const prepared = await d.ledger.prepareAppend({ change_id: state.change_id, event_class, detail, prior: prior.value }); if (prepared?.kind !== 'OK') return prepared; const committed = await d.ledger.commitAndPush({ change_id: state.change_id, prepared: prepared.value }); if (committed?.kind === 'AMBIGUOUS') return d.ledger.readRemoteAppend({ change_id: state.change_id, expected: committed.partial_receipt }); if (committed?.kind !== 'OK') return committed; return d.ledger.readRemoteAppend({ change_id: state.change_id, expected: committed.value }); };
  const verifyCas = (operation, state, request) => !state || request.change_id !== state.change_id || request.expected_state_version !== state.state_version || request.expected_state_hash !== stateHash(state) ? rejected(operation, 'STATE_CONFLICT', request.change_id ?? null) : null;

  async function applyControllerCommand(request) {
    const operation = 'applyControllerCommand';
    if (!exact(request, ['command_body_bytes', 'signature_bytes']) || !(request.command_body_bytes instanceof Uint8Array) || !(request.signature_bytes instanceof Uint8Array)) return rejected(operation, 'INPUT_INVALID');
    let rawBody; try { rawBody = new TextDecoder().decode(request.command_body_bytes); if (canonical(JSON.parse(rawBody)) !== rawBody) return rejected(operation, 'INPUT_INVALID'); } catch { return rejected(operation, 'INPUT_INVALID'); }
    let verified; try { verified = await d.verifier.verify(request); } catch { return rejected(operation, 'COMMAND_SIGNATURE_INVALID'); }
    if (verified?.kind !== 'VERIFIED') return rejected(operation, verified?.error_code ?? 'COMMAND_SIGNATURE_INVALID');
    const body = verified.body; if (!validCommand(body)) return rejected(operation, 'INPUT_INVALID'); if (body.expires_at < d.clock.now()) return rejected(operation, 'COMMAND_EXPIRED', body.change_id);
    const held = await acquire(operation); if (held !== true) return held;
    try {
      const pointer = pointerValue(await d.state.readPointer({})); if (!pointer) return rejected(operation, 'WIP_AUTHORITY_INVALID', body.change_id); if (body.command_kind === 'RELEASE' && pointer.active_change_id === null) { const closed = decodedState(await d.state.readState({ change_id: body.change_id })); if (closed?.macro_state === 'CLOSED') return stateResult(operation, 'ALREADY_APPLIED', closed, { idempotency_id: body.idempotency_id, original_receipt_sha256: closed.admission?.body_sha256 ?? body.receipt_digest }); }
      if (body.command_kind === 'DISPATCH') {
        if ((pointer.active_change_id && pointer.active_change_id !== body.change_id) || body.change_id !== 'CHG-dual-device-transition-foundation') return rejected(operation, 'WIP_AUTHORITY_INVALID', body.change_id);
        if (pointer.active_change_id === body.change_id) { const existing = decodedState(await d.state.readState({ change_id: body.change_id })); if (existing?.admission?.body_sha256 !== verified.body_sha256) return rejected(operation, 'COMMAND_REPLAY_CONFLICT', body.change_id); acceptedDispatch = { body: clone(body), body_sha256: verified.body_sha256 }; if (testSeam) Object.defineProperty(d, TEST_ACCEPTED_DISPATCH, { value: acceptedDispatch, configurable: true }); return stateResult(operation, 'ALREADY_APPLIED', existing, { idempotency_id: body.idempotency_id, original_receipt_sha256: verified.body_sha256 }); }
        const expectedPointer = sha256(canonical({ schema_version: '1.0', active_change_id: null })); if (body.payload.expected_pointer_sha256 !== expectedPointer || body.expected_state_version !== null || body.expected_state_hash !== null) return rejected(operation, 'INPUT_INVALID', body.change_id);
        const nextPointer = { schema_version: '1.0', active_change_id: body.change_id }; const pointerWrite = await d.state.writePointer({ expected_sha256: expectedPointer, pointer: nextPointer, value: nextPointer, next_bytes: canonical(nextPointer) }); if (pointerWrite?.kind !== 'OK') return rejected(operation, 'WIP_AUTHORITY_INVALID', body.change_id); if (pointerValue(await d.state.readPointer({}))?.active_change_id !== body.change_id) return rejected(operation, 'WIP_AUTHORITY_INVALID', body.change_id);
        const state = { schema_version: '1.0', change_id: body.change_id, state_version: 0, macro_state: 'READY', phase: 'WORKTREE', admission: { command_id: body.command_id, body_sha256: verified.body_sha256, idempotency_id: body.idempotency_id }, authorization_cycle: { command_id: body.command_id, command_kind: 'DISPATCH', auto_repair_attempt: 0 }, repository: { baseline_sha: body.worktree.baseline_sha, branch: body.worktree.branch, worktree_root: body.worktree.root }, pending_agent: null, candidate: null, delivery: null, last_controller_command_id: body.command_id, blocked_reason: null, evidence: { remote_tip: null, last_event_id: null, last_event_hash: null, last_readback_sha256: null }, resume_target: null };
        if (!await writeState(state)) return block(operation, state, 'DISPATCH_ORPHAN_READY');
        const ledger = await append(state, 'CONTROLLER_COMMAND', { command_kind: 'DISPATCH', command_id: body.command_id, ready_state_sha256: stateHash(state) });
        if (ledger?.kind !== 'OK' && ledger?.kind !== 'ALREADY_APPLIED') { if (ledger?.kind === 'UNAVAILABLE' && ledger?.partial_receipt?.stage === 'PRIOR_TIP_READ') { const pause = { request_idempotency_id: body.idempotency_id, request_sha256: sha256(request.command_body_bytes) }; await d.state.writeLocalPause({ diagnostic: pause, value: pause }); return result(operation, 'BLOCKED', null, null, null, null, { blocked_reason: 'EVIDENCE_REF_UNAVAILABLE', next_action: 'IDENTICAL_COMMAND_REPLAY', blocked_event_id: null, local_pause_id: null }); } return block(operation, state, 'LEDGER_APPEND_AMBIGUOUS'); }
        acceptedDispatch = { body: clone(body), body_sha256: verified.body_sha256 };
        if (testSeam) Object.defineProperty(d, TEST_ACCEPTED_DISPATCH, { value: acceptedDispatch, configurable: true });
        return stateResult(operation, 'APPLIED', state, { command_id: body.command_id, command_kind: body.command_kind, operation_receipt_sha256: verified.body_sha256 });
      }
      const current = decodedState(await d.state.readState({ change_id: body.change_id })); const cas = verifyCas(operation, current, body); if (cas) return cas; if (body.command_kind === 'RELEASE' && current.macro_state === 'CLOSED') { const empty = { schema_version: '1.0', active_change_id: null }; const clear = await d.state.writePointer({ expected_sha256: sha256(canonical(pointer)), pointer: empty, value: empty, next_bytes: canonical(empty) }); if (clear?.kind !== 'OK' || pointerValue(await d.state.readPointer({}))?.active_change_id !== null) return block(operation, current, 'POINTER_CLEAR_FAILED'); return stateResult(operation, 'CLOSED', current, { squash_sha: body.payload.squash_sha, pointer_cleared: true }); }
      if (body.command_kind === 'REVISION') { if (current.macro_state !== 'BLOCKED' || current.blocked_reason !== 'VALIDATOR_SECOND_FAIL') return rejected(operation, 'STATE_CONFLICT', body.change_id); const next = { ...current, macro_state: 'EXECUTING', phase: body.payload.resume_phase, pending_agent: null, blocked_reason: null, resume_target: null, state_version: current.state_version + 1, authorization_cycle: { command_id: body.command_id, command_kind: 'REVISION', auto_repair_attempt: 0 }, last_controller_command_id: body.command_id }; if (!await writeState(next, current)) return block(operation, current, 'REVISION_STATE_FAILED'); return stateResult(operation, 'APPLIED', next, { command_id: body.command_id, command_kind: 'REVISION', phase: next.phase }); }
      if (body.command_kind === 'RESUME') { const target = body.payload.resume_target; if (current.macro_state !== 'BLOCKED' || !current.resume_target || canonical(current.resume_target) !== canonical(target)) return rejected(operation, 'STATE_CONFLICT', body.change_id); const next = { ...current, macro_state: target.macro_state, phase: target.phase, pending_agent: null, blocked_reason: null, resume_target: null, state_version: current.state_version + 1, last_controller_command_id: body.command_id }; if (!await writeState(next, current)) return block(operation, current, 'RESUME_STATE_FAILED'); return stateResult(operation, 'APPLIED', next, { command_id: body.command_id, command_kind: 'RESUME', phase: next.phase }); }
      if (body.command_kind !== 'RELEASE' || current.macro_state !== 'AWAITING_CONTROLLER') return rejected(operation, 'RELEASE_NOT_READY', body.change_id);
      const mainWorktree = `${body.repository.canonical_root.replace(/\/$/, '')}/main`; const sync = await d.git.syncMainFfOnly({ canonical_root: body.repository.canonical_root, main_worktree_root: mainWorktree, squash_sha: body.payload.squash_sha, expected_origin_main: body.payload.origin_main_sha }); if (sync?.kind !== 'OK' || sync.value?.clean !== true || sync.value?.fast_forward_only !== true || sync.value?.local_main !== body.payload.squash_sha || sync.value?.origin_main !== body.payload.squash_sha) return block(operation, current, 'RELEASE_SYNC_FAILED'); const ledger = await append(current, 'CONTROLLER_COMMAND', { command_kind: 'RELEASE', command_id: body.command_id }); if (ledger?.kind !== 'OK') return block(operation, current, 'RELEASE_LEDGER_FAILED'); const closed = { ...current, macro_state: 'CLOSED', phase: null, state_version: current.state_version + 1, last_controller_command_id: body.command_id }; if (!await writeState(closed, current)) return block(operation, current, 'RELEASE_STATE_FAILED'); const empty = { schema_version: '1.0', active_change_id: null }; const clear = await d.state.writePointer({ expected_sha256: sha256(canonical(pointer)), pointer: empty, value: empty, next_bytes: canonical(empty) }); if (clear?.kind !== 'OK' || pointerValue(await d.state.readPointer({}))?.active_change_id !== null) return block(operation, closed, 'POINTER_CLEAR_FAILED'); return stateResult(operation, 'CLOSED', closed, { squash_sha: body.payload.squash_sha, pointer_cleared: true });
    } finally { await d.mutex.release(); }
  }

  async function run(request) {
    const operation = 'run'; if (!request || typeof request !== 'object' || !Object.hasOwn(request, 'change_id') || !Object.hasOwn(request, 'expected_state_version') || !Object.hasOwn(request, 'expected_state_hash')) return rejected(operation, 'INPUT_INVALID'); const held = await acquire(operation); if (held !== true) return held;
    try {
      const { pointer, state } = await readCurrent(request.change_id); if (!pointer || pointer.active_change_id !== request.change_id || !state) return result(operation, 'BLOCKED', 'BLOCKED', null, null, request.change_id, { blocked_reason: 'DISPATCH_ORPHAN_READY', next_action: 'MANUAL_CONTROLLER_STOP', blocked_event_id: null, local_pause_id: null }); if (state.macro_state === 'READY' && (await d.ledger.readRemoteAppend({ change_id: state.change_id }))?.kind !== 'OK') return block(operation, state, 'DISPATCH_ORPHAN_READY'); const cas = verifyCas(operation, state, request); if (cas) return cas;
      if (state.macro_state === 'BLOCKED') return stateResult(operation, 'BLOCKED', state, { blocked_reason: state.blocked_reason, next_action: state.blocked_reason === 'VALIDATOR_SECOND_FAIL' ? 'REVISION' : 'MANUAL_CONTROLLER_STOP', blocked_event_id: null, local_pause_id: null }); if (state.macro_state === 'CLOSED') return stateResult(operation, 'CLOSED', state, { squash_sha: state.candidate?.sha ?? null, pointer_cleared: false });
      const admission = acceptedDispatch?.body;
      if (!admission || admission.change_id !== state.change_id || acceptedDispatch.body_sha256 !== state.admission.body_sha256 || !validCommand(admission)) return block(operation, state, 'ADMISSION_EVIDENCE_UNAVAILABLE');
      const role = route(state, admission); if (role) { let worktreeEvidence = state.evidence?.worktree ?? null; if (state.macro_state === 'READY' && state.phase === 'WORKTREE') { const created = await d.git.createOrReuseWorktree({ worktree_root: state.repository.worktree_root, branch: state.repository.branch, baseline_sha: state.repository.baseline_sha }); if (created?.kind !== 'OK' || created.value?.worktree_root !== state.repository.worktree_root || created.value?.branch !== state.repository.branch || created.value?.baseline_sha !== state.repository.baseline_sha || created.value?.clean !== true || typeof created.value?.common_git_dir !== 'string') return block(operation, state, 'WORKTREE_CREATE_FAILED'); const inspected = await d.git.inspectWorktree({ worktree_root: state.repository.worktree_root }); if (inspected?.kind !== 'OK' || inspected.value?.worktree_root !== state.repository.worktree_root || inspected.value?.branch !== state.repository.branch || inspected.value?.head_sha !== state.repository.baseline_sha || inspected.value?.clean !== true || inspected.value?.common_git_dir !== created.value.common_git_dir) return block(operation, state, 'WORKTREE_DIRTY_CONFLICT'); worktreeEvidence = inspected.value; } const actionState = { ...state, evidence: worktreeEvidence ? { ...state.evidence, worktree: worktreeEvidence } : state.evidence, macro_state: state.macro_state === 'READY' ? 'EXECUTING' : state.macro_state, phase: state.phase === 'WORKTREE' ? 'SPEC' : state.phase }; const action = actionFor(actionState, role, d.ids); const requested = await append(actionState, 'AGENT_RUN', { stage: 'REQUESTED', correlation_id: action.correlation_id, role: action.role, subject_sha: action.subject_sha }); if (requested?.kind !== 'OK') return unpersistedBlock(operation, state, 'LEDGER_APPEND_AMBIGUOUS'); const next = { ...actionState, state_version: state.state_version + 1, pending_agent: { ...action, request_event_id: 'event-001' } }; if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED'); return stateResult(operation, 'AGENT_ACTION', next, { action }); }
      if (state.macro_state === 'EXECUTING' && state.phase === 'REGRESSION') { for (const validation_scope of ['AFFECTED_SUITE', 'TEST_ASSET_RETIREMENT']) { const check = await d.validation.execute({ definition: { validation_scope }, subject_sha: state.repository.baseline_sha }); if (check?.kind !== 'OK' || check.value?.verdict !== 'PASS') return block(operation, state, 'REGRESSION_FAILED'); } const next = { ...state, macro_state: 'DELIVERING', phase: 'STAGE', state_version: state.state_version + 1 }; if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED'); return stateResult(operation, 'ADVANCED', next, { from_state: 'EXECUTING', from_phase: 'REGRESSION', to_state: 'DELIVERING', to_phase: 'STAGE', operation_receipt_sha256: receipt(next) }); }
      if (state.macro_state === 'DELIVERING') {
        if (state.phase === 'STAGE') { if (!state.evidence?.worktree?.clean) { const inspect = await d.git.inspectWorktree({ worktree_root: state.repository.worktree_root }); if (inspect?.kind !== 'OK' || !inspect.value?.clean) return block(operation, state, 'WORKTREE_DIRTY_CONFLICT'); } const staged = await d.git.stageExact({ worktree_root: state.repository.worktree_root, paths: admission?.scope?.allowed_paths ?? ['tools/harness/change-coordinator/coordinator.mjs'] }); const read = await d.git.readStaged({ worktree_root: state.repository.worktree_root }); const completeIndex = value => value && Array.isArray(value.staged_paths) && isSha(value.index_tree) && isHash(value.staged_paths_sha256); if (staged?.kind !== 'OK' || read?.kind !== 'OK' || !completeIndex(staged.value) || !completeIndex(read.value) || canonical(staged.value) !== canonical(read.value)) return block(operation, state, 'STAGE_FAILED'); const next = { ...state, phase: 'CANDIDATE_COMMIT', state_version: state.state_version + 1 }; if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED'); return stateResult(operation, 'ADVANCED', next, { from_state: 'DELIVERING', from_phase: 'STAGE', to_state: 'DELIVERING', to_phase: 'CANDIDATE_COMMIT', operation_receipt_sha256: receipt(next) }); }
        if (state.phase === 'CANDIDATE_COMMIT') { const staged = await d.git.readStaged({ worktree_root: state.repository.worktree_root }); if (staged?.kind !== 'OK' || !isSha(staged.value?.index_tree)) return block(operation, state, 'CANDIDATE_COMMIT_AMBIGUOUS'); const committed = await d.git.commitCandidate({ worktree_root: state.repository.worktree_root, expected_parent: state.repository.baseline_sha, expected_tree: staged.value.index_tree, message_bytes: new TextEncoder().encode('candidate'), idempotency_id: state.admission.idempotency_id }); if (committed?.kind === 'AMBIGUOUS') { await d.git.readCommit({ canonical_root: state.repository.worktree_root, sha: state.repository.baseline_sha }); return block(operation, state, 'CANDIDATE_COMMIT_AMBIGUOUS'); } if (committed?.kind !== 'OK' || !isSha(committed.value?.sha) || committed.value.parent !== state.repository.baseline_sha || committed.value.branch !== state.repository.branch) return block(operation, state, 'CANDIDATE_COMMIT_AMBIGUOUS'); const read = await d.git.readCommit({ canonical_root: state.repository.worktree_root, sha: committed.value.sha }); if (read?.kind !== 'OK' || canonical(read.value) !== canonical(committed.value)) return block(operation, state, 'CANDIDATE_COMMIT_AMBIGUOUS'); const ledger = await append(state, 'CANDIDATE_COMMITTED', { candidate_sha: committed.value.sha }); if (ledger?.kind !== 'OK') return block(operation, state, 'LEDGER_APPEND_AMBIGUOUS'); const next = { ...state, phase: 'FINAL_VALIDATION', state_version: state.state_version + 1, candidate: { ...committed.value, validation_refs: [], validator_head: null, frozen: false } }; if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED'); return stateResult(operation, 'ADVANCED', next, { from_state: 'DELIVERING', from_phase: 'CANDIDATE_COMMIT', to_state: 'DELIVERING', to_phase: 'FINAL_VALIDATION', operation_receipt_sha256: receipt(next) }); }
        if (state.phase === 'FINAL_VALIDATION') { const validation = await d.validation.execute({ definition: admission?.payload?.validations?.[0] ?? { id: 'validation-001' }, subject_sha: state.candidate?.sha }); if (validation?.kind !== 'OK' || validation.value?.verdict !== 'PASS') return block(operation, state, 'FINAL_VALIDATION_FAILED'); const ledger = await append(state, 'VALIDATION_RESULT', { validation_id: validation.value.validation_id, receipt_sha256: validation.value.receipt_sha256, subject_sha: state.candidate?.sha, verdict: validation.value.verdict }); if (ledger?.kind !== 'OK') return block(operation, state, 'LEDGER_APPEND_AMBIGUOUS'); const next = { ...state, phase: 'VALIDATOR', state_version: state.state_version + 1 }; if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED'); return stateResult(operation, 'ADVANCED', next, { from_state: 'DELIVERING', from_phase: 'FINAL_VALIDATION', to_state: 'DELIVERING', to_phase: 'VALIDATOR', operation_receipt_sha256: receipt(next) }); }
        if (state.phase === 'BRANCH_PUSH') { const pushed = await d.git.pushBranch({ canonical_root: state.repository.worktree_root, branch: state.repository.branch, head_sha: state.candidate?.sha, candidate_sha: state.candidate?.sha, idempotency_id: state.admission.idempotency_id }); if (pushed?.kind === 'AMBIGUOUS') { await d.git.readRemoteBranch({ branch: state.repository.branch }); return block(operation, state, 'BRANCH_PUSH_AMBIGUOUS'); } const pushedHead = pushed?.value?.head_sha ?? pushed?.value?.remote_head; if (pushed?.kind !== 'OK' || pushedHead !== state.candidate?.sha || (pushed.value?.forced !== undefined && pushed.value.forced !== false) || (pushed.value?.deleted !== undefined && pushed.value.deleted !== false)) return block(operation, state, 'BRANCH_PUSH_AMBIGUOUS'); const remote = await d.git.readRemoteBranch({ canonical_root: state.repository.worktree_root, branch: state.repository.branch }); const remoteHead = remote?.value?.head_sha ?? remote?.value?.remote_head; if (remote?.kind !== 'OK' || remoteHead !== state.candidate?.sha) return block(operation, state, 'BRANCH_PUSH_AMBIGUOUS'); const ledger = await append(state, 'BRANCH_PUSHED', { branch: state.repository.branch, candidate_sha: state.candidate?.sha, remote_head: remoteHead }); if (ledger?.kind !== 'OK') return block(operation, state, 'LEDGER_APPEND_AMBIGUOUS'); const next = { ...state, phase: 'CANDIDATE_FREEZE', state_version: state.state_version + 1, delivery: { ...(state.delivery ?? {}), remote_head: remoteHead } }; if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED'); return stateResult(operation, 'ADVANCED', next, { from_state: 'DELIVERING', from_phase: 'BRANCH_PUSH', to_state: 'DELIVERING', to_phase: 'CANDIDATE_FREEZE', operation_receipt_sha256: receipt(next) }); }
        if (state.phase === 'CANDIDATE_FREEZE') { const diff = await d.git.canonicalDiff({ canonical_root: state.repository.worktree_root, common_git_dir: state.evidence?.worktree?.common_git_dir ?? state.repository.worktree_root, worktree_root: state.repository.worktree_root, baseline_sha: state.repository.baseline_sha, candidate_sha: state.candidate?.sha }); if (diff?.kind !== 'OK' || !isHash(diff.value?.stdout_sha256)) return block(operation, state, 'CANDIDATE_FREEZE_FAILED'); const candidate = { ...state.candidate, frozen: true }; const next = { ...state, phase: 'PR', state_version: state.state_version + 1, candidate, delivery: { ...(state.delivery ?? {}), canonical_diff_sha256: diff.value.stdout_sha256 } }; if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED'); return stateResult(operation, 'ADVANCED', next, { from_state: 'DELIVERING', from_phase: 'CANDIDATE_FREEZE', to_state: 'DELIVERING', to_phase: 'PR', operation_receipt_sha256: receipt(next) }); }
        if (state.phase === 'PR') { const q = await d.pull_request.queryCurrent({ repository: state.change_id, base: 'main', head_branch: state.repository.branch }); const pr = q?.kind === 'ABSENT' ? await d.pull_request.createOrReuse({ repository: state.change_id, base: 'main', head_branch: state.repository.branch, head_sha: state.candidate?.sha }) : q; const read = await d.pull_request.readback({ number: pr?.value?.number, expected_head: state.candidate?.sha }); if (pr?.kind !== 'OK' || read?.kind !== 'OK' || pr.value?.head_sha !== state.candidate?.sha || pr.value?.base !== 'main' || read.value.head_sha !== state.candidate?.sha || (read.value.base && read.value.base !== 'main') || read.value.review_ready !== true) return block(operation, state, 'PR_HANDOFF_AMBIGUOUS'); const next = { ...state, phase: 'HANDOFF', state_version: state.state_version + 1, delivery: { ...(state.delivery ?? {}), pull_request: { ...pr.value, ...read.value } } }; if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED'); return stateResult(operation, 'ADVANCED', next, { from_state: 'DELIVERING', from_phase: 'PR', to_state: 'DELIVERING', to_phase: 'HANDOFF', operation_receipt_sha256: receipt(next) }); }
        if (state.phase === 'HANDOFF') { const handoffDocument = { schema_version: '1.0', change_id: state.change_id, baseline_sha: state.repository.baseline_sha, branch: state.repository.branch, candidate_sha: state.candidate?.sha, candidate_tree: state.candidate?.tree, canonical_diff_contract_id: 'git-canonical-diff-v1', canonical_diff_sha256: state.delivery?.canonical_diff_sha256 ?? null, changed_paths: [], delivery_id: state.delivery?.delivery_id ?? null, idempotency_id: state.admission.idempotency_id, ledger_refs: [], open_questions: [], pull_request: state.delivery?.pull_request ?? null, remote_head: state.delivery?.remote_head ?? null, risks: [], unverified: [], validation_receipts: state.candidate?.validation_refs ?? [], validator_head: state.candidate?.validator_head ?? null, validator_verdict: 'PASS' }; const handoff_bytes = new TextEncoder().encode(canonical(handoffDocument)); const expected = sha256(handoff_bytes); const handoff = await d.handoff.writeReadback({ expected_sha256: expected, handoff_bytes }); if (handoff?.kind !== 'OK' || !isHash(handoff.value?.handoff_sha256) || typeof handoff.value?.delivery_id !== 'string') return block(operation, state, handoff?.kind === 'CONFLICT' ? 'HANDOFF_IDENTITY_MISMATCH' : 'HANDOFF_AMBIGUOUS'); const next = { ...state, macro_state: 'AWAITING_CONTROLLER', phase: null, state_version: state.state_version + 1, delivery: { ...state.delivery, handoff_sha256: handoff.value.handoff_sha256, delivery_id: handoff.value.delivery_id } }; const ledger = await append(next, 'HANDOFF_READY', { candidate_sha: state.candidate?.sha, handoff_sha256: handoff.value.handoff_sha256, delivery_id: handoff.value.delivery_id }); if (ledger?.kind !== 'OK') return block(operation, state, 'HANDOFF_AMBIGUOUS'); if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED'); return stateResult(operation, 'AWAITING_CONTROLLER', next, { candidate_sha: state.candidate?.sha, remote_head: next.delivery.remote_head, validator_head: state.candidate?.validator_head, pr_number: next.delivery.pull_request?.number, pr_head: next.delivery.pull_request?.head_sha, handoff_sha256: next.delivery.handoff_sha256 }); }
      }
      return stateResult(operation, 'WAITING', state, { waiting_for: 'CONTROLLER_COMMAND', pending_correlation_id: null });
    } finally { await d.mutex.release(); }
  }

  async function settlement(request) {
    const operation = 'settlement';
    if (!exact(request, ['change_id', 'expected_state_version', 'expected_state_hash', 'settlement'])) return rejected(operation, 'INPUT_INVALID');
    const held = await acquire(operation); if (held !== true) return held;
    try {
      const { state } = await readCurrent(request.change_id);
      const pending = state?.pending_agent; const s = request.settlement;
      if (!state || !pending || !s || typeof s !== 'object' || Array.isArray(s)) return rejected(operation, 'SETTLEMENT_INVALID', request.change_id);
      const cas = verifyCas(operation, state, request); if (cas) return cas;
      const binding = ['correlation_id', 'role', 'agent', 'model', 'reasoning', 'sandbox', 'allowed_paths', 'phase', 'state_version', 'brief_sha256', 'input_sha256', 'output_schema_sha256', 'subject_sha', 'idempotency_id'];
      const sameBinding = binding.filter(key => key !== 'subject_sha').every(key => canonical(s[key]) === canonical(pending[key]));
      const shape = keys => exact(s, [...binding, ...keys]);
      const validStarted = shape(['stage', 'observed_child_id']) && s.stage === 'STARTED' && typeof s.observed_child_id === 'string';
      const validResult = shape(['stage', 'observed_child_id', 'status', 'artifact_path', 'artifact_sha256']) && s.stage === 'RESULT' && typeof s.observed_child_id === 'string' && ['PASS', 'FAIL'].includes(s.status) && typeof s.artifact_path === 'string' && isHash(s.artifact_sha256);
      const validStartFailed = shape(['stage', 'failure_code']) && s.stage === 'START_FAILED' && ['SPAWN_FAILED', 'POLICY_DENIED', 'CAPACITY_UNAVAILABLE'].includes(s.failure_code);
      const validInterrupted = shape(['stage', 'observed_child_id', 'interruption_code']) && s.stage === 'INTERRUPTED' && typeof s.observed_child_id === 'string' && ['PROCESS_INTERRUPTED', 'TIMEOUT', 'HOST_LOST'].includes(s.interruption_code);
      const validNotStarted = shape(['stage', 'precondition_code']) && s.stage === 'NOT_STARTED' && ['PRECONDITION_UNMET', 'CAPACITY_UNAVAILABLE'].includes(s.precondition_code);
      if (!sameBinding || !(validStarted || validResult || validStartFailed || validInterrupted || validNotStarted)) return rejected(operation, 'SETTLEMENT_INVALID', request.change_id);
      if (validStarted) { const event = await append(state, 'AGENT_RUN', { stage: 'STARTED', correlation_id: pending.correlation_id, role: pending.role, observed_child_id: s.observed_child_id }); if (event?.kind !== 'OK') return unpersistedBlock(operation, state, 'LEDGER_APPEND_AMBIGUOUS'); const next = { ...state, state_version: state.state_version + 1, pending_agent: { ...pending, observed_child_id: s.observed_child_id, started: true } }; if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED'); return stateResult(operation, 'WAITING', next, { waiting_for: 'AGENT_SETTLEMENT', pending_correlation_id: pending.correlation_id }); }
      if (validStartFailed || validInterrupted || validNotStarted) { const stage = validStartFailed ? 'START_FAILED' : validInterrupted ? 'INTERRUPTED' : 'NOT_STARTED'; const event = await append(state, 'AGENT_RUN', { stage, correlation_id: pending.correlation_id, role: pending.role }); if (event?.kind !== 'OK') return block(operation, state, 'LEDGER_APPEND_AMBIGUOUS'); return block(operation, state, validStartFailed ? 'AGENT_START_FAILED' : validInterrupted ? 'AGENT_INTERRUPTED' : 'AGENT_NOT_STARTED'); }
      if (!pending.started || pending.observed_child_id !== s.observed_child_id) return rejected(operation, 'SETTLEMENT_INVALID', request.change_id);
      if (s.subject_sha !== pending.subject_sha) return block(operation, state, 'AGENT_SUBJECT_MISMATCH');
      const agentEvent = await append(state, 'AGENT_RUN', { correlation_id: pending.correlation_id, role: pending.role, stage: 'RESULT', status: s.status, artifact_sha256: s.artifact_sha256 });
      if (agentEvent?.kind !== 'OK') return block(operation, state, 'LEDGER_APPEND_AMBIGUOUS');
      let phase = state.phase;
      if (s.status !== 'PASS') {
        if (phase !== 'VALIDATOR') return block(operation, state, 'AGENT_RESULT_FAIL');
        if (state.authorization_cycle.auto_repair_attempt === 1) return block(operation, state, 'VALIDATOR_SECOND_FAIL', 'REVISION');
        const next = { ...state, macro_state: 'EXECUTING', phase: 'TEST_RED', state_version: state.state_version + 1, pending_agent: null, authorization_cycle: { ...state.authorization_cycle, auto_repair_attempt: 1 } };
        if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED');
        return stateResult(operation, 'ADVANCED', next, { from_state: state.macro_state, from_phase: state.phase, to_state: 'EXECUTING', to_phase: 'TEST_RED', operation_receipt_sha256: receipt(next) });
      }
      if (phase === 'SPEC') phase = 'TEST_RED'; else if (phase === 'TEST_RED') phase = 'WORKER_GREEN'; else if (phase === 'WORKER_GREEN') phase = 'REGRESSION'; else if (phase === 'VALIDATOR') phase = 'BRANCH_PUSH';
      const next = { ...state, phase, state_version: state.state_version + 1, pending_agent: null, candidate: phase === 'BRANCH_PUSH' ? { ...state.candidate, validator_head: state.candidate?.sha } : state.candidate };
      if (!await writeState(next, state)) return block(operation, state, 'STATE_WRITE_FAILED');
      return stateResult(operation, 'ADVANCED', next, { from_state: state.macro_state, from_phase: state.phase, to_state: state.macro_state, to_phase: phase, operation_receipt_sha256: receipt(next) });
    } finally { await d.mutex.release(); }
  }

  async function status(request) { const operation = 'status'; if (!exact(request, ['change_id'])) return rejected(operation, 'INPUT_INVALID'); const pointer = pointerValue(await d.state.readPointer({})); const empty = { pointer_status: 'EMPTY', active_change_id: null, macro_state: null, phase: null, pending_action: null, candidate: null, delivery: null, orphan_ready: null, local_pause: null }; if (!pointer) return result(operation, 'STATUS', null, null, null, null, { ...empty, pointer_status: 'INVALID' }); if (!pointer.active_change_id) return result(operation, 'STATUS', null, null, null, null, empty); const state = decodedState(await d.state.readState({ change_id: pointer.active_change_id })); if (!state) return result(operation, 'STATUS', null, null, null, pointer.active_change_id, { ...empty, pointer_status: 'INVALID', active_change_id: pointer.active_change_id }); if (state.macro_state === 'READY') { const event = await d.ledger.readRemoteAppend({ change_id: state.change_id }); if (event?.kind !== 'OK') return result(operation, 'STATUS', null, null, null, pointer.active_change_id, { ...empty, pointer_status: 'INVALID', active_change_id: pointer.active_change_id }); } return result(operation, 'STATUS', state.macro_state, state.state_version, stateHash(state), pointer.active_change_id, { pointer_status: 'ACTIVE', active_change_id: pointer.active_change_id, macro_state: state.macro_state, phase: state.phase, pending_action: state.pending_agent ? { kind: 'AGENT_SETTLEMENT', correlation_id: state.pending_agent.correlation_id } : null, candidate: state.candidate, delivery: state.delivery, orphan_ready: null, local_pause: null }); }
  return Object.freeze({ applyControllerCommand, run, settlement, status });
}

export function createCoordinatorCore(dependencies) { return createCore(dependencies); }
export function createTestCoordinator(dependencies) {
  const seed = dependencies[TEST_ACCEPTED_DISPATCH] ?? (dependencies[TEST_CONSTRUCTION_SEEN] === true ? null : testRouteSeed());
  if (seed) Object.defineProperty(dependencies, TEST_CONSTRUCTION_SEEN, { value: true });
  return createCore(dependencies, seed, true);
}
