import {createWorkspaceClient,browserSourceFiles} from './client.mjs';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metricValue=(key,value)=>key==='repurchase_rate'?(value==='not_applicable'?'不可计算':`${value.numerator}/${value.denominator}`):value;
const statusName={idle:'等待下一步',running:'正在推进',waiting:'等待必要信息',stopped:'已停止',interrupted:'执行已中断',closed:'已结束'};
export async function startWorkspace({control,service=false,onHome,container,onSetup,onControl,projectName,initialQuestion='',accessAvailable=()=>true,controlState,initialDrafts=[]}) {
 if(service)return startServiceWorkspace({control});
 const style=document.createElement('link');style.rel='stylesheet';style.href='/styles.css';document.head.append(style);
 const app=container??document.getElementById('app'),client=createWorkspaceClient({control,storage:sessionStorage});let tasks=[],selected=null,view=null,mode='simple',busy=false,notice='',question=initialQuestion,modelPolicy=null;
 const hasControl=()=>client.hasControl()&&(!controlState||controlState());
 const disabled=()=>busy||!client.canWrite()||!hasControl()?'disabled':'';
 const drafts=new Map(initialDrafts);
 function captureDrafts(){for(const id of ['question','clarification-reply','review-actor','review-reason','review-questions']){const input=app.querySelector('#'+id);if(input&&typeof input.value==='string')drafts.set((selected??'new')+':'+id,input.value);}}
 async function refresh(){modelPolicy=await client.policy();if(!accessAvailable())modelPolicy={...modelPolicy,available:false};const listed=await client.list();tasks=listed.tasks;if(selected&&!tasks.some(t=>t.task_id===selected))selected=null;if(!selected&&tasks.length)selected=tasks[0].task_id;view=selected?await client.read(selected):null;}
 function render(){const answeringQuestion=view?.model?.current&&view.model.answerable&&Boolean(view.model.question);const preparationFailed=view?.preparation?.current&&view.preparation.status==='failed'&&view.model?.status!=='issued';const scopeAuthorized=view?.material_grant?.active&&view.material_grant.source_set_id===(view.source_summary?.id??null)&&view.material_grant.policy_sha256===modelPolicy?.sha256;const report=view?.case.reports.at(-1),finding=view?.case.findings.find(f=>f.finding_id===report?.finding_id),metrics=finding?JSON.parse(finding.metrics):null,review=view?.task.reviews.at(-1);
  app.innerHTML=`${container?'':`<header class="topbar"><div class="brand"><span class="brand-mark"><img src="/assets/logo.png" alt=""></span><strong>JuanerAI</strong><span class="product-name">Xanthil</span></div></header>`}
  <main class="analysis-workbench"><div class="workbench-context"><div class="task-menu"><details><summary>${container?'分析记录':esc(projectName??view?.case.project.display_name??'分析工作台')+' · 分析记录'}</summary><div class="menu-content">${tasks.map(t=>`<button class="task-link ${t.task_id===selected?'current':''}" data-task="${esc(t.task_id)}"><span>${esc(t.question)}</span><small>${esc(statusName[t.status]??'等待核对')}</small></button>`).join('')||'<p class="muted">分析会保存在这里</p>'}</div></details><button id="new-task" class="quiet" ${disabled()}>＋ 新分析</button></div><nav class="mode-switch" aria-label="工作模式"><button data-mode="simple" class="${mode==='simple'?'active':''}" aria-pressed="${mode==='simple'}">简单</button><button data-mode="professional" class="${mode==='professional'?'active':''}" aria-pressed="${mode==='professional'}">专业</button></nav></div>
  <div class="workbench-heading"><p class="eyebrow">你的分析工作台</p><h1>${esc(view?.question??'今天，想弄清什么？')}</h1>${!view?'<p class="muted">说出问题，添加资料。其余交给我们一起完成。</p>':''}</div>
  ${notice?`<p class="notice" role="status" aria-live="polite">${esc(notice)}</p>`:''}${!hasControl()?`<section class="inline-notice"><div><strong>本页只读</strong><p>如需操作，切换到本页继续。其他页面仍可查看，任务不会自动开始。</p></div><button id="take-control" ${busy||client.pending()?'disabled':''}>在本页继续</button></section>`:''}${client.pending()?'<section class="inline-notice"><div><strong>刚才的操作尚未确认</strong><p>请先查看保存结果，避免重复提交。</p></div><button id="recover" class="primary">查看保存结果</button></section>':''}
  ${!view?`<section class="surface question-card"><h2>你的业务问题</h2><form id="create-form"><label for="question">希望核实什么变化？</label><textarea id="question" required maxlength="2000" placeholder="例如：核实两期会员复购和复购收入有什么变化？">${esc(question)}</textarea><button class="primary" ${disabled()}>继续，添加资料</button></form><p class="muted">问题会保存在本机；开始分析前会请你确认分享范围。</p></section>`:`<section class="surface"><div class="row spread"><h2>${report?'分析结果':'分析资料'}</h2><button id="stop" class="danger" ${disabled()}>停止任务</button></div><p class="analysis-status" role="status">当前：${esc(answeringQuestion?'等待必要信息':preparationFailed?'资料准备未通过核验':statusName[view.task.status]??'等待核对')} · ${esc(view.case.revision.state==='Completed'?'分析已闭合':report?'待审报告已保存':'等待开始分析')}</p>
  <details class="source-section" ${!scopeAuthorized&&!report?'open':''}><summary>分析资料${view.source_summary?' · '+view.source_summary.sources.length+' 份':''}</summary>
  ${!report?`<p class="muted">添加 CSV 或 Excel 文件，可一次选择多份。原始明细保留在本机。</p><label class="file-label" for="files">＋ 添加分析资料</label><input id="files" type="file" accept=".csv,.xlsx" multiple ${disabled()} ${view.case.revision.state!=='Draft'?'disabled':''}>`:''}
  <ul class="source-list">${(view.source_summary?.sources??[]).map(s=>`<li><strong>${esc(s.display_name)}</strong> · ${esc(s.format.toUpperCase())}<ul>${s.sheets.map(sheet=>`<li>${esc(sheet.name)} · 已读取 ${sheet.row_count} 行（含表头）</li>`).join('')}</ul></li>`).join('')}</ul></details>
  ${view.case.revision.state!=='Completed'&&(!scopeAuthorized||report&&view.material_grant?.disclose_verified_result!==true)?`<section class="analysis-consent" aria-label="模型与材料范围"><h3>${report?'让 AI 解释已核验的结果':'准备好，一起分析'}</h3>${modelPolicy?`<p>${view.source_summary?'AI 将使用你的问题、表格结构，以及本轮已核验的汇总结果完成分析。原始明细不会发送。':'AI 将使用你的问题帮助明确分析方向。你还没有添加资料。'}</p><form id="model-authorization"><button class="primary" name="scope" value="recommended" ${disabled()} ${!modelPolicy.available?'disabled':''}>${report?'同意并解释结果':'同意并开始分析'}</button><details class="sharing-details"><summary>分享范围与使用说明</summary><p>接收方：Xiaomi · ${esc(modelPolicy.policy.model)}。${view.source_summary?'只发送必要表头、类型、结构及本轮已独立核验的总体聚合、必要语义与验证摘要；不发送原始明细、样例、身份值或群组标签。':'只发送当前问题文字，不发送文件。'} 模型按实际使用计费，累计消费不设上限。</p><p>关闭网页后，已开始的分析会继续。你可以随时停止；停止或服务退出后不会自动继续。</p><fieldset><legend>也可以自选分享内容</legend><label><input id="disclose-question" type="checkbox"> 当前问题：${esc(view.question)}</label>${view.source_summary?'<label><input id="disclose-verified-result" type="checkbox"> 已核验的汇总结果，用于解释</label>':''}<button name="scope" value="custom" ${disabled()} ${!modelPolicy.available?'disabled':''}>按所选范围开始</button></fieldset></details></form>${!modelPolicy.available?`<div class="inline-notice"><p>首次使用，请在上方启用 AI 分析。你添加的资料已保留。</p>${onSetup?'<button id="setup-model">启用 AI 分析</button>':'<p>AI 分析暂未就绪，资料已保留。</p>'}</div>`:''}`:`<p>AI 分析暂时不可用，你添加的资料已保留。</p>${onSetup?'<button id="setup-model">查看帮助</button>':''}`}</section>`:''}
  ${(view.clarifications??[]).length?`<section><h3>已保存的补充</h3><p>补充是你的说明，仍需本轮资料与计算核验。</p>${view.clarifications.map(c=>`<p>${esc(c.reply)}</p>`).join('')}</section>`:''}
  ${view.preparation?.current&&view.preparation.failure_code?`<section aria-label="资料准备状态"><h3>资料准备尚未通过核验</h3><p>${esc(view.preparation.status==='unknown'?'实际执行状态尚未结清，已记录用量；核对前不会再次执行。':['CONVERSION_UNQUALIFIED','PREPARATION_OUTPUT_INVALID'].includes(view.preparation.failure_code)?'转换结果未通过独立核验，尚未用于计算。请核对资料与必要说明；已保留失败及累计消耗。':'本次本地准备未完成，已保留失败与用量。请检查执行条件，不会自动扩大权限或重复执行。')}</p></section>`:''}
  ${view.model?.current&&(!preparationFailed||answeringQuestion)?`<section aria-label="AI推进结果"><h3>${view.model.question?'需要你的信息':view.model.status==='issued'?'正在理解与准备':view.model.status==='unknown'?'执行状态尚未结清':'分析进展'}</h3><p>${esc(view.model.question??(view.model.status==='unknown'?'仍在核对实际执行状态，不会再次发送。':view.model.failure_code?'本轮未完成；已记录已知消耗和失败状态。':view.model.status==='issued'?'正在分析你提供的资料。':'分析内容已保存，正在核验结果。'))}</p>${view.model.answerable?`<form id="clarification-form"><label for="clarification-reply">补充必要信息</label><textarea id="clarification-reply" required maxlength="12000" ${disabled()}></textarea><p>发送这段补充，帮助 AI 继续分析；原问题会保留。</p><button class="primary" ${disabled()}>发送补充并继续</button></form>`:''}</section>`:''}
  ${metrics?`<table><caption>本轮M1总体比较</caption><thead><tr><th>指标</th><th>对比期</th><th>当前期</th></tr></thead><tbody>${[['活跃成员（分母）','active_member_count'],['复购成员','repeat_member_count'],['复购率（精确分数）','repurchase_rate'],['复购收入（分）','repeat_revenue_fen']].map(([label,key])=>`<tr><th>${label}</th><td>${esc(metricValue(key,metrics.periods.comparison[key]))}</td><td>${esc(metricValue(key,metrics.periods.current[key]))}</td></tr>`).join('')}</tbody></table><p>描述性差异不等于因果，不自动产生业务决定或行动。</p><details ${mode==='professional'?'open':''}><summary>报告、来源与核验依据</summary><pre>${esc(report.review_content?.markdown_text??'报告内容暂不可读，请保留当前状态并读回。')}</pre></details>`:''}
  ${report?`<p>服务器报告已保存；下载副本的状态单独显示。</p><button id="download-report" ${busy?'disabled':''}>下载报告副本</button>`:''}
  ${report&&report.state==='draft'&&view.case.revision.state!=='Completed'?`<div class="rule"></div><h2>审阅与闭合</h2>${!review?`<p>核对报告事实，再审阅基于本轮证据的分析闭合建议。</p><button id="open-review" ${disabled()}>审阅报告</button>`:`<form id="review-form"><label for="review-actor">审阅人</label><input id="review-actor" required maxlength="200" value="${esc(review.fields.actor)}" ${disabled()}><label for="review-reason">分析闭合说明</label><textarea id="review-reason" required maxlength="12000" ${disabled()}>${esc(review.fields.closure.insufficient_reason)}</textarea><label for="review-questions">还需调查的问题（补证时必填）</label><textarea id="review-questions" maxlength="4000" ${disabled()}>${esc(review.fields.questions)}</textarea><p>本次确认仅闭合描述性分析，不产生正式业务决定或预期结果。</p><div class="row"><button class="primary" name="outcome" value="analysis" ${disabled()}>确认分析闭合</button><button name="outcome" value="more_evidence" ${disabled()}>提出补证</button></div></form>`}`:''}
  </section><details class="usage-details" ${mode==='professional'?'open':''}><summary>使用记录与核验详情</summary><p>模型调用 ${esc(view.operations.totals.calls)} 次 · 本地执行（准备与计算） ${esc(view.operations.totals.local_runs)} 次 · 未结清 ${esc(view.operations.totals.unresolved)} 项</p><p class="muted">实际未回报的消耗保留为未知，不按额度推算已用量。</p>${mode==='professional'?`<details><summary>使用明细</summary><pre>${esc(JSON.stringify(view.operations.totals,null,2))}</pre></details>`:''}</details>`}
  <div class="workbench-footer"><button id="refresh" class="quiet">刷新状态</button><details><summary>当前支持的分析</summary><p>M1总体比较是当前首试路径。M2、点评重算、正式决定与预期结果、Fork/Subagent首试未开放，S1继续接通。</p></details></div></main>`;
  app.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render();});app.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>act(async()=>{selected=b.dataset.task;await refresh();}));
  for(const [identity,value] of drafts){const prefix=(selected??'new')+':';if(identity.startsWith(prefix)){const input=app.querySelector('#'+identity.slice(prefix.length));if(input)input.value=value;}}
  const setup=app.querySelector('#setup-model');if(setup&&onSetup)setup.onclick=()=>onSetup();
  const takeover=app.querySelector('#take-control');if(takeover)takeover.onclick=()=>act(async()=>{control=await client.takeControl();if(onControl)await onControl(control);notice='已接管到本页，任务未自动继续。';await refresh();});
  app.querySelector('#refresh').onclick=()=>act(refresh);app.querySelector('#new-task').onclick=()=>{selected=null;view=null;render();app.querySelector('#question')?.focus();};
  const input=app.querySelector('#question');if(input)input.oninput=()=>{question=input.value;};const form=app.querySelector('#create-form');if(form)form.onsubmit=e=>{e.preventDefault();question=app.querySelector('#question').value;void act(async()=>{const created=await client.create(question);selected=created.task_id;question='';drafts.delete('new:question');await refresh();});};
  const files=app.querySelector('#files');if(files)files.onchange=()=>{const selectedFiles=Array.from(files.files);void act(async()=>{await client.select(view.task,await browserSourceFiles(selectedFiles));await refresh();});};
  const authorization=app.querySelector('#model-authorization');if(authorization)authorization.onsubmit=e=>{e.preventDefault();const recommended=e.submitter?.value==='recommended',disclose=recommended||app.querySelector('#disclose-question').checked,discloseVerified=Boolean(view.source_summary)&&(recommended||app.querySelector('#disclose-verified-result')?.checked===true);if(!view.source_summary&&!disclose){notice='请明确选择是否发送当前问题；未授权文字不会发送。';render();return;}void act(async()=>{await client.authorizeModel(view.task,view.source_summary?.id??null,modelPolicy.sha256,disclose,discloseVerified);notice='当前材料授权已保存。';await refresh();});};
  const clarification=app.querySelector('#clarification-form');if(clarification)clarification.onsubmit=e=>{e.preventDefault();const reply=app.querySelector('#clarification-reply').value.trim();if(!reply)return;void act(async()=>{await client.answer(view.task,view.model.execution_id,modelPolicy.sha256,reply);notice='补充已保存，按当前材料授权继续。';await refresh();});};
  const download=app.querySelector('#download-report');if(download)download.onclick=()=>act(async()=>{const blob=await client.copy(selected,report.report_id),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='xanthil-report-'+report.report_id+'.html';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notice='已请求下载副本，请检查浏览器下载列表；尚未确认文件已保存到磁盘。';});
  const openReview=app.querySelector('#open-review');if(openReview)openReview.onclick=()=>act(async()=>{await client.review(view.task,'open');await refresh();});
  const reviewForm=app.querySelector('#review-form');if(reviewForm)reviewForm.onsubmit=e=>{e.preventDefault();const outcome=e.submitter?.value;if(!['analysis','more_evidence'].includes(outcome))return;const fields={...review.fields,actor:app.querySelector('#review-actor').value.trim(),questions:app.querySelector('#review-questions').value.trim(),closure:{...review.fields.closure,insufficient_reason:app.querySelector('#review-reason').value.trim(),disposition:'saved'}};if(!fields.actor||!fields.closure.insufficient_reason||outcome==='more_evidence'&&!fields.questions){notice='请填写审阅人、闭合说明；补证还需说明待调查问题。';render();return;}void act(async()=>{await client.review(view.task,'save',{review_id:review.id,review_version:review.sequence,review_sha256:review.sha256,fields});await refresh();const saved=view.task.reviews.at(-1);await client.review(view.task,'submit',{command_id:saved.intent_id,review_id:saved.id,review_version:saved.sequence,review_sha256:saved.sha256,outcome,confirmed:true});await refresh();notice=outcome==='analysis'?'分析已闭合，确认结果已保存。':'补证问题已保存，尚未形成正式闭合。';});};
  const stop=app.querySelector('#stop');if(stop)stop.onclick=()=>act(async()=>{await client.stop(selected);await refresh();});const recover=app.querySelector('#recover');if(recover)recover.onclick=()=>act(async()=>{const pending=client.pending(),result=await client.recover();if(pending?.kind==='create'&&result.status==='recorded'&&result.receipt?.kind==='task_created'){selected=result.receipt.task_id;question='';drafts.delete('new:question');}notice=result.status==='recorded'?'已读回保存结果。':result.status==='rejected'?'本次请求未保存，可检查后重新操作。':'尚未确认完成，继续保留并读回。';await refresh();});
  // Live input is the draft authority; view-only renders must never restore older text.
  for(const id of ['question','clarification-reply','review-actor','review-reason','review-questions']){const input=app.querySelector('#'+id);if(input)input.oninput=()=>{drafts.set((selected??'new')+':'+id,input.value);if(id==='question')question=input.value;};}
 }
 async function act(work){if(busy)return;captureDrafts();busy=true;render();try{await work();}catch(error){notice=error instanceof Error?error.message:'暂时无法完成，请读回保存状态。';}finally{busy=false;render();}}
 await refresh();render();return {getDrafts:()=>{captureDrafts();return [...drafts];},refresh:async()=>{captureDrafts();await refresh();render();}};
}

/** One workbench shell. Settings and projects remain local, secondary controls. */
export async function startServiceWorkspace({control:initialControl}){
 const app=document.getElementById('app'),style=document.createElement('link');style.rel='stylesheet';style.href='/styles.css';document.head.append(style);
 let control=initialControl,catalog={projects:[],current:null},settings=null,session={},busy=false,notice='',key='',inAnalysis=false,pending=null,workspace=null,settingsOpen=false,draftQuestion='',accessUnavailable=false,loadFailed=false,mountedProject=null;
 const projectDrafts=new Map();
 const pendingKey='xanthil.pending-project.v1';try{const value=JSON.parse(globalThis.sessionStorage?.getItem(pendingKey)??'null');if(value&&/^[a-f0-9-]{36}$/.test(value.command_id))pending=value;}catch{}
 const remember=value=>{pending=value;try{if(value)globalThis.sessionStorage?.setItem(pendingKey,JSON.stringify(value));else globalThis.sessionStorage?.removeItem(pendingKey);}catch{}};
 const errors={MODEL_BUSY:'AI 正在完成另一项分析，请稍后再试。',KEYCHAIN_UNAVAILABLE:'暂时无法读取这台 Mac 保存的密钥。请解锁系统钥匙串后再试，资料已保留。',TEST_REQUIRED:'启用尚未完成，请再试一次。',CREDENTIAL_INVALID:'密钥无效，请检查后重试。',NETWORK_UNAVAILABLE:'暂时无法访问 AI 服务，请检查网络后重试。',CONNECTION_TIMEOUT:'等待时间较长，请稍后重试。',QUOTA_EXCEEDED:'账户额度不足，请补充额度后重试。',CONNECTION_FAILED:'暂时无法启用 AI，请稍后重试。',CONFIGURATION_CHANGED:'账户信息已变化，请重新启用。',SAVE_FAILED:'尚未确认密钥保存成功，请稍后重试。',DELETE_FAILED:'尚未确认删除成功，请稍后查看。'};
 async function request(path,body){const response=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'content-type':'application/json',...(control?{'x-xanthil-control':control}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});if(response.status===403){control=null;session={...session,owned:true};}if(!response.ok)throw Object.assign(Error('操作尚未确认，请查看保存结果后再试。'),{definite:true});return response.json();}
 async function read(){[catalog,settings,session]=await Promise.all([request('/v1/projects'),request('/v1/settings'),request('/v1/session')]);}
 async function refreshLocalAccess(){if(!control)return;settings=null;accessUnavailable=false;try{settings=await request('/v1/settings',{operation:'refresh'});if(!settings.ok){accessUnavailable=true;notice=errors[settings.code]??'暂时无法确认 AI 是否可用，请稍后重试。';}}catch{accessUnavailable=true;notice='暂时无法确认 AI 是否可用，已保留你的资料。';}}
 async function analyze({refreshAccess=true}={}){if(!inAnalysis&&catalog.current){projectDrafts.set(catalog.current,[['new:question',draftQuestion]]);draftQuestion='';}if(workspace&&mountedProject)projectDrafts.set(mountedProject,workspace.getDrafts());key='';if(refreshAccess)await refreshLocalAccess();loadFailed=false;if(!inAnalysis){inAnalysis=true;render();}try{const nextWorkspace=await startWorkspace({control,container:app.querySelector('#analysis-workbench'),initialDrafts:projectDrafts.get(catalog.current)??[],accessAvailable:()=>!accessUnavailable,controlState:()=>!!control,projectName:catalog.projects.find(p=>p.project_id===catalog.current)?.display_name,onSetup:()=>{settingsOpen=true;renderSettings();app.querySelector('#provider-api-key')?.focus();},onControl:async next=>{control=next;await refreshLocalAccess();syncShell();}});workspace=nextWorkspace;mountedProject=catalog.current;}catch{loadFailed=true;notice='暂时无法打开分析，请重试。你的输入和已保存资料会保留。';app.querySelector('#analysis-workbench').querySelectorAll('button,input,textarea').forEach(node=>{node.disabled=true;});}syncShell();}
 function syncShell(){const projectLabel=app.querySelector('.project-picker > summary');if(projectLabel)projectLabel.textContent=catalog.projects.find(p=>p.project_id===catalog.current)?.display_name??'选择分析项目';const projectMenu=app.querySelector('.saved-projects');if(projectMenu){projectMenu.innerHTML=catalog.projects.map(p=>`<button data-project="${esc(p.project_id)}">${esc(p.display_name)}</button>`).join('');projectMenu.querySelectorAll('[data-project]').forEach(button=>button.onclick=()=>act(()=>choose({version:'1.0',command_id:crypto.randomUUID(),project_id:button.dataset.project})));}const projectDisabled=Boolean(busy||pending||session.owned&&!control);app.querySelectorAll('[data-project], #project-create input, #project-create button').forEach(node=>{node.disabled=projectDisabled;});const account=app.querySelector('#account-settings');if(account)account.disabled=busy||!control;
 const target=app.querySelector('#service-notice');if(target){target.innerHTML=`${pending?'<p class="notice" role="status">项目操作尚未确认，请先查看保存结果。</p>':notice&&notice!=='AI 分析已就绪'?`<p class="notice" role="status">${esc(notice)}</p>`:''}${session.owned&&!control?'<p class="notice">本页只读，其他页面正在操作。</p>':''}${pending?'<button id="service-refresh">查看保存结果</button>':''}${loadFailed?'<button id="retry-workbench">重试打开分析</button>':accessUnavailable&&control?'<button id="retry-access">重试</button>':''}`;const recovery=target.querySelector('#service-refresh');if(recovery)recovery.onclick=()=>act(recoverProject);const retry=target.querySelector('#retry-workbench');if(retry)retry.onclick=()=>act(()=>analyze({refreshAccess:false}));const access=target.querySelector('#retry-access');if(access)access.onclick=()=>act(async()=>{await refreshLocalAccess();if(!accessUnavailable)notice='';if(workspace)await workspace.refresh();});}
 renderSettings();}
 async function choose(body){if(pending)throw Error('项目操作尚未确认，请先查看保存结果。');remember(body);try{const result=await request('/v1/projects/select',body);remember(null);control=result.control;await read();await analyze();}catch(error){if(error.definite&&pending)remember({...body,definite:true});throw error;}}
 async function recoverProject(){await read();if(pending){const saved=pending.name?await request('/v1/projects/commands/'+pending.command_id):catalog.current===pending.project_id?{project_id:pending.project_id}:null;if(saved||pending.definite){remember(null);notice=saved?'已读回保存项目；任务未自动执行。':'已确认该请求未保存。';}else notice='项目操作尚未确认，请稍后查看保存结果。';}}
 async function act(work){if(busy)return;busy=true;if(inAnalysis)syncShell();else render();try{await work();}catch(error){notice=error.message;}finally{busy=false;if(inAnalysis)syncShell();else render();}}
 async function enable(){if(!control||!key.trim())return;const submittedKey=key;const tested=await request('/v1/settings',{operation:'test',key:submittedKey});if(!tested.ok){notice=errors[tested.code]??'AI 启用未完成，请稍后重试。';return;}if(!tested.proof){notice='AI 启用尚未确认，请稍后重试。';return;}const saved=await request('/v1/settings',{operation:'save',key:submittedKey,proof:tested.proof});settings=saved;if(!saved.ok){notice=errors[saved.code]??'尚未确认保存成功，请稍后重试。';return;}key='';settingsOpen=false;accessUnavailable=false;notice='AI 分析已就绪';if(workspace)await workspace.refresh();}
 function renderSettings(){const target=app.querySelector('#account-panel');if(!target)return;const configured=!accessUnavailable&&settings?.ok&&settings.value?.configured,show=settingsOpen||(inAnalysis&&control&&!configured&&!accessUnavailable),write=busy||!control?'disabled':'';
 target.innerHTML=show?`<section class="setup-panel" aria-label="AI 分析设置"><div class="row spread"><h2>${configured?'账户设置':'启用 AI 分析'}</h2>${configured?'<button id="close-settings" class="quiet" aria-label="关闭账户设置">关闭</button>':''}</div><p class="muted">${configured?'需要更换密钥时，在这里更新。':'只需设置一次，之后直接分析。'}</p>${notice&&notice!=='AI 分析已就绪'?`<p role="status" class="notice">${esc(notice)}</p>`:''}<form id="enable-ai"><label for="provider-api-key">分析服务密钥</label><input id="provider-api-key" type="password" autocomplete="off" spellcheck="false" required ${write}><button class="primary" ${write}>${busy?'正在启用…':configured?'更新密钥':'启用 AI 分析'}</button></form><details><summary>隐私与使用说明</summary><p>密钥仅保存在这台 Mac 的系统钥匙串中，不进入项目和报告。启用时会发送一条固定测试文字，消耗少量额度，不发送你的问题或资料。</p>${configured?`<button id="settings-delete" class="danger" ${write}>删除本机密钥</button>`:''}</details></section>`:'';
 const status=app.querySelector('#ai-status');if(status)status.textContent=accessUnavailable?'AI 分析暂不可用':configured?'AI 分析已就绪':inAnalysis?'首次使用，请启用 AI 分析':'资料保存在本机';
 const input=target.querySelector('#provider-api-key');if(input){input.value=key;input.oninput=()=>{key=input.value;};}
 const form=target.querySelector('#enable-ai');if(form)form.onsubmit=e=>{e.preventDefault();key=input.value;return act(enable);};
 const close=target.querySelector('#close-settings');if(close)close.onclick=()=>{key='';settingsOpen=false;renderSettings();};
 const remove=target.querySelector('#settings-delete');if(remove)remove.onclick=()=>act(async()=>{const result=await request('/v1/settings',{operation:'delete',confirmed:true});settings=result;key='';notice=result.ok?'已删除本机密钥；项目和报告保留。':errors[result.code]??'尚未确认删除成功。';if(workspace)await workspace.refresh();});
 }
 function render(){const blocked=busy?'disabled':'',projectBlocked=busy||pending||session.owned&&!control?'disabled':'';
 app.innerHTML=`<header class="topbar"><div class="brand"><span class="brand-mark"><img src="/assets/logo.png" alt=""></span><span class="brand-copy"><strong>JuanerAI</strong><small>持续做出更好的决策</small></span><span class="product-name">Xanthil</span></div><div class="header-actions"><span id="ai-status" class="muted"></span><button id="account-settings" class="quiet" ${!control?'disabled':''}>账户</button></div></header><div class="workbench-shell"><details class="project-picker" ${!inAnalysis?'open':''}><summary>${esc(catalog.projects.find(p=>p.project_id===catalog.current)?.display_name??'选择分析项目')}</summary><div class="project-options"><div class="saved-projects">${catalog.projects.map(p=>`<button data-project="${esc(p.project_id)}" ${projectBlocked}>${esc(p.display_name)}</button>`).join('')}</div><form id="project-create"><label for="project-name">新建项目</label><input id="project-name" maxlength="120" placeholder="例如：会员经营分析" required ${projectBlocked}><button ${projectBlocked}>创建并开始</button></form>${catalog.current&&!inAnalysis?'<button id="current-project" class="primary">继续当前分析</button>':''}</div></details><div id="service-notice">${pending?'<p class="notice" role="status">项目操作尚未确认，请先查看保存结果。</p>':notice&&!inAnalysis?`<p class="notice" role="status">${esc(notice)}</p>`:''}${session.owned&&!control?'<div class="inline-notice"><p>本页只读，其他页面正在操作。</p><button id="service-takeover">在本页继续</button></div>':''}${pending?`<button id="service-refresh" ${blocked}>查看保存结果</button>`:''}</div><div id="account-panel"></div><div id="analysis-workbench">${!inAnalysis?`<main class="analysis-workbench"><div class="workbench-heading"><p class="eyebrow">你的分析工作台</p><h1>今天，想弄清什么？</h1><p class="muted">选择或新建项目后，说出问题，添加资料，开始分析。</p></div><section class="surface question-card"><label for="entry-question">你的业务问题</label><textarea id="entry-question" maxlength="2000" placeholder="例如：核实两期会员复购发生了什么变化？">${esc(draftQuestion)}</textarea><p class="muted">选择上方项目后，接着添加资料。已写的问题会保留。</p></section><div class="welcome-flow" aria-label="分析流程"><span><b>01</b> 说出问题</span><span><b>02</b> 添加资料</span><span><b>03</b> 一起看结果</span></div></main>`:''}</div></div>`;
 app.querySelector('#project-create').onsubmit=e=>{e.preventDefault();const name=app.querySelector('#project-name').value.trim();if(!name)return;return act(()=>choose({version:'1.0',command_id:crypto.randomUUID(),name}));};
 app.querySelectorAll('[data-project]').forEach(button=>button.onclick=()=>act(()=>choose({version:'1.0',command_id:crypto.randomUUID(),project_id:button.dataset.project})));
 const recovery=app.querySelector('#service-refresh');if(recovery)recovery.onclick=()=>act(recoverProject);
 const current=app.querySelector('#current-project');if(current)current.onclick=()=>act(analyze);
 const takeover=app.querySelector('#service-takeover');if(takeover)takeover.onclick=()=>act(async()=>{const value=await request('/v1/control',{version:'1.0',command_id:crypto.randomUUID(),generation:session.generation,confirmed:true});control=value.control;await read();await analyze();});
 const draft=app.querySelector('#entry-question');if(draft)draft.oninput=()=>{draftQuestion=draft.value;};
 app.querySelector('#account-settings').onclick=()=>{settingsOpen=!settingsOpen;renderSettings();};renderSettings();
 }
 await read();render();
}
