import {createWorkspaceClient,browserSourceFiles} from './client.mjs';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metricValue=(key,value)=>key==='repurchase_rate'?(value==='not_applicable'?'不可计算':`${value.numerator}/${value.denominator}`):value;
const statusName={idle:'等待下一步',running:'正在推进',waiting:'等待必要信息',stopped:'已停止',interrupted:'执行已中断',closed:'已结束'};
export async function startWorkspace({control,service=false,onHome}) {
 if(service)return startServiceWorkspace({control});
 const style=document.createElement('link');style.rel='stylesheet';style.href='/styles.css';document.head.append(style);
 const app=document.getElementById('app'),client=createWorkspaceClient({control,storage:sessionStorage});let tasks=[],selected=null,view=null,mode='simple',busy=false,notice='',question='',modelPolicy=null;
 const disabled=()=>busy||!client.canWrite()?'disabled':'';
 async function refresh(){try{modelPolicy=await client.policy();}catch{modelPolicy=null;}const listed=await client.list();tasks=listed.tasks;if(selected&&!tasks.some(t=>t.task_id===selected))selected=null;if(!selected&&tasks.length)selected=tasks[0].task_id;view=selected?await client.read(selected):null;}
 function render(){const answeringQuestion=view?.model?.current&&view.model.answerable&&Boolean(view.model.question);const preparationFailed=view?.preparation?.current&&view.preparation.status==='failed'&&view.model?.status!=='issued';const scopeAuthorized=view?.material_grant?.active&&view.material_grant.source_set_id===(view.source_summary?.id??null)&&view.material_grant.policy_sha256===modelPolicy?.sha256;const report=view?.case.reports.at(-1),finding=view?.case.findings.find(f=>f.finding_id===report?.finding_id),metrics=finding?JSON.parse(finding.metrics):null,review=view?.task.reviews.at(-1);
  app.innerHTML=`<header class="topbar"><div class="brand"><span class="brand-mark"><img src="/assets/logo.png" alt=""></span><span class="brand-copy"><strong>JuanerAI</strong><small>持续做出更好的决策</small></span><span class="product-name">Xanthil</span></div>${onHome?'<button id="project-home">项目与模型设置</button>':''}<nav class="mode-switch" aria-label="工作模式"><button data-mode="simple" class="${mode==='simple'?'active':''}" aria-pressed="${mode==='simple'}">简单</button><button data-mode="professional" class="${mode==='professional'?'active':''}" aria-pressed="${mode==='professional'}">专业</button></nav><span class="badge">${client.canWrite()?'本页可操作':'本页只读'}</span></header>
  <div class="browser-layout"><aside class="rail" aria-label="项目和任务"><div class="rail-content"><strong>${esc(view?.case.project.display_name??'本机项目')}</strong><div class="rule"></div><div class="row spread"><strong>分析任务</strong><button id="new-task" aria-label="新建分析任务" ${disabled()}>＋</button></div>${tasks.map(t=>`<button class="task-link ${t.task_id===selected?'current':''}" data-task="${esc(t.task_id)}"><span>${esc(t.question)}</span><small>${esc(statusName[t.status]??'等待核对')}</small></button>`).join('')}</div><div class="rail-foot">AI 推进任务<br>你掌握关键判断</div></aside>
  <main class="browser-main"><div class="row spread"><h1>${esc(view?.question??'从业务问题开始')}</h1><button id="refresh">读回保存状态</button></div><p class="muted">关闭网页不会停止已启动任务。刷新只读回；明确停止或退出服务后，不会自动续跑。</p>
  <p role="status" aria-live="polite">${esc(notice)}</p>${!client.hasControl()?`<section class="surface"><h2>本页只读</h2><p>明确接管后，本页可以操作，其他页面立即失去操作权。接管不会授权模型或自动继续任务。</p><button id="take-control" ${busy||client.pending()?'disabled':''}>接管到本页</button></section>`:''}${client.pending()?'<section class="surface"><h2>提交结果尚未确认</h2><p>先读回同一命令的保存结果，期间不会再次提交。</p><button id="recover" class="primary">读回本次结果</button></section>':''}
  ${!view?`<section class="surface"><h2>你的业务问题</h2><form id="create-form"><label for="question">希望核实什么变化？</label><textarea id="question" required maxlength="2000" placeholder="例如：核实两期会员复购和复购收入有什么变化？">${esc(question)}</textarea><button class="primary" ${disabled()}>保存并开始梳理</button></form><p class="muted">保存问题不会将文字发送给模型。</p></section>`:`<section class="surface"><div class="row spread"><h2>${report?'报告与人的判断':'资料与口径'}</h2><button id="stop" class="danger" ${disabled()}>停止任务</button></div><p>当前：${esc(answeringQuestion?'等待必要信息':preparationFailed?'资料准备未通过核验':statusName[view.task.status]??'等待核对')} · ${esc(view.case.revision.state==='Completed'?'分析已闭合':report?'待审报告已保存':'尚未形成核验报告')}</p>
  ${!report?`<p>添加多份CSV或XLSX资料，工作簿可包含多个工作表。选择资料只进行本地检查。</p><label for="files">添加资料</label><input id="files" type="file" accept=".csv,.xlsx" multiple ${disabled()} ${view.case.revision.state!=='Draft'?'disabled':''}>`:''}
  <ul>${(view.source_summary?.sources??[]).map(s=>`<li><strong>${esc(s.display_name)}</strong> · ${esc(s.format.toUpperCase())}<ul>${s.sheets.map(sheet=>`<li>${esc(sheet.name)} · 已读取 ${sheet.row_count} 行（含表头）</li>`).join('')}</ul></li>`).join('')}</ul>
  ${view.case.revision.state!=='Completed'&&(!scopeAuthorized||report&&view.material_grant?.disclose_verified_result!==true)?`<section aria-label="模型与材料范围"><h3>本轮材料授权</h3>${report?'<p>本地总体事实已核验。补充解释材料授权后，只解释已有结果，不重复准备和计算。</p>':''}${modelPolicy?`<p>接收方：Xiaomi · ${esc(modelPolicy.policy.model)}。${view.source_summary?'只发送必要表头、类型与结构；不发送原始明细、样例、身份值或群组标签。':'本次只发送你明确选择的当前问题文字；尚未授权任何资料结构或本地准备。'}</p><p>不设累计消费额度；持续记录实际消耗，未回报部分保留未知。临时模型失败最多重试一次，准备纠正最多一次。</p><form id="model-authorization"><label><input id="disclose-question" type="checkbox"> ${view.source_summary?'同时发送':'允许发送'}当前问题文字：${esc(view.question)}</label>${view.source_summary?'<label><input id="disclose-verified-result" type="checkbox"> 允许发送本轮已独立核验的总体聚合、必要语义与验证摘要，用于解释；不含原始明细或群组标签。</label>':''}<button class="primary" ${disabled()} ${!modelPolicy.available?'disabled':''}>授权当前材料</button></form>${!modelPolicy.available?'<p class="muted">本机模型接入尚未就绪；资料仍保存在本地。</p>':''}`:'<p>本机模型政策尚未就绪；资料仍保存在本地，未发送给模型。</p>'}</section>`:''}
  ${(view.clarifications??[]).length?`<section><h3>已保存的补充</h3><p>补充是你的说明，仍需本轮资料与计算核验。</p>${view.clarifications.map(c=>`<p>${esc(c.reply)}</p>`).join('')}</section>`:''}
  ${view.preparation?.current&&view.preparation.failure_code?`<section aria-label="资料准备状态"><h3>资料准备尚未通过核验</h3><p>${esc(view.preparation.status==='unknown'?'实际执行状态尚未结清，已记录用量；核对前不会再次执行。':['CONVERSION_UNQUALIFIED','PREPARATION_OUTPUT_INVALID'].includes(view.preparation.failure_code)?'转换结果未通过独立核验，尚未用于计算。请核对资料与必要说明；已保留失败及累计消耗。':'本次本地准备未完成，已保留失败与用量。请检查执行条件，不会自动扩大权限或重复执行。')}</p></section>`:''}
  ${view.model?.current&&(!preparationFailed||answeringQuestion)?`<section aria-label="AI推进结果"><h3>${view.model.question?'需要你的信息':view.model.status==='issued'?'正在理解与准备':view.model.status==='unknown'?'执行状态尚未结清':'本轮模型状态'}</h3><p>${esc(view.model.question??(view.model.status==='unknown'?'仍在核对实际执行状态，不会再次发送。':view.model.failure_code?'本轮未完成；已记录已知消耗和失败状态。':view.model.status==='issued'?'任务已在本机继续推进，可稍后读回。':'模型输出已保存，继续按本地核验结果推进。'))}</p>${view.model.answerable?`<form id="clarification-form"><label for="clarification-reply">补充必要信息</label><textarea id="clarification-reply" required maxlength="12000" ${disabled()}></textarea><p>将这段补充发送给当前已授权模型，连同已选材料继续；原问题保留。</p><button class="primary" ${disabled()}>发送补充并继续</button></form>`:''}</section>`:''}
  ${metrics?`<table><caption>本轮M1总体比较</caption><thead><tr><th>指标</th><th>对比期</th><th>当前期</th></tr></thead><tbody>${[['活跃成员（分母）','active_member_count'],['复购成员','repeat_member_count'],['复购率（精确分数）','repurchase_rate'],['复购收入（分）','repeat_revenue_fen']].map(([label,key])=>`<tr><th>${label}</th><td>${esc(metricValue(key,metrics.periods.comparison[key]))}</td><td>${esc(metricValue(key,metrics.periods.current[key]))}</td></tr>`).join('')}</tbody></table><p>描述性差异不等于因果，不自动产生业务决定或行动。</p><details ${mode==='professional'?'open':''}><summary>报告、来源与核验依据</summary><pre>${esc(report.review_content?.markdown_text??'报告内容暂不可读，请保留当前状态并读回。')}</pre></details>`:''}
  ${report?`<p>服务器报告已保存；下载副本的状态单独显示。</p><button id="download-report" ${busy?'disabled':''}>下载报告副本</button>`:''}
  ${report&&report.state==='draft'&&view.case.revision.state!=='Completed'?`<div class="rule"></div><h2>审阅与闭合</h2>${!review?`<p>核对报告事实，再审阅基于本轮证据的分析闭合建议。</p><button id="open-review" ${disabled()}>审阅报告</button>`:`<form id="review-form"><label for="review-actor">审阅人</label><input id="review-actor" required maxlength="200" value="${esc(review.fields.actor)}" ${disabled()}><label for="review-reason">分析闭合说明</label><textarea id="review-reason" required maxlength="12000" ${disabled()}>${esc(review.fields.closure.insufficient_reason)}</textarea><label for="review-questions">还需调查的问题（补证时必填）</label><textarea id="review-questions" maxlength="4000" ${disabled()}>${esc(review.fields.questions)}</textarea><p>本次确认仅闭合描述性分析，不产生正式业务决定或预期结果。</p><div class="row"><button class="primary" name="outcome" value="analysis" ${disabled()}>确认分析闭合</button><button name="outcome" value="more_evidence" ${disabled()}>提出补证</button></div></form>`}`:''}
  </section><section class="surface"><h2>累计消耗</h2><p>模型调用 ${esc(view.operations.totals.calls)} 次 · 本地执行（准备与计算） ${esc(view.operations.totals.local_runs)} 次 · 未结清 ${esc(view.operations.totals.unresolved)} 项</p><p class="muted">实际未回报的消耗保留为未知，不按额度推算已用量。</p>${mode==='professional'?`<details><summary>使用明细</summary><pre>${esc(JSON.stringify(view.operations.totals,null,2))}</pre></details>`:''}</section>`}
  <details><summary>首试范围与后续能力</summary><p>M1总体比较是当前首试路径。M2、点评重算、正式决定与预期结果、Fork/Subagent首试未开放，S1继续接通。</p></details></main></div>`;
  app.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render();});app.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>act(async()=>{selected=b.dataset.task;await refresh();}));
  const home=app.querySelector('#project-home');if(home)home.onclick=()=>onHome(control);
  const takeover=app.querySelector('#take-control');if(takeover)takeover.onclick=()=>act(async()=>{control=await client.takeControl();notice='已接管到本页，任务未自动继续。';await refresh();});
  app.querySelector('#refresh').onclick=()=>act(refresh);app.querySelector('#new-task').onclick=()=>{selected=null;view=null;render();app.querySelector('#question')?.focus();};
  const input=app.querySelector('#question');if(input)input.oninput=()=>{question=input.value;};const form=app.querySelector('#create-form');if(form)form.onsubmit=e=>{e.preventDefault();void act(async()=>{const created=await client.create(question);selected=created.task_id;question='';await refresh();});};
  const files=app.querySelector('#files');if(files)files.onchange=()=>{const selectedFiles=Array.from(files.files);void act(async()=>{await client.select(view.task,await browserSourceFiles(selectedFiles));await refresh();});};
  const authorization=app.querySelector('#model-authorization');if(authorization)authorization.onsubmit=e=>{e.preventDefault();const disclose=app.querySelector('#disclose-question').checked,discloseVerified=app.querySelector('#disclose-verified-result')?.checked===true;if(!view.source_summary&&!disclose){notice='请明确选择是否发送当前问题；未授权文字不会发送。';render();return;}void act(async()=>{await client.authorizeModel(view.task,view.source_summary?.id??null,modelPolicy.sha256,disclose,discloseVerified);notice='当前材料授权已保存。';await refresh();});};
  const clarification=app.querySelector('#clarification-form');if(clarification)clarification.onsubmit=e=>{e.preventDefault();const reply=app.querySelector('#clarification-reply').value.trim();if(!reply)return;void act(async()=>{await client.answer(view.task,view.model.execution_id,modelPolicy.sha256,reply);notice='补充已保存，按当前材料授权继续。';await refresh();});};
  const download=app.querySelector('#download-report');if(download)download.onclick=()=>act(async()=>{const blob=await client.copy(selected,report.report_id),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='xanthil-report-'+report.report_id+'.html';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notice='已请求下载副本，请检查浏览器下载列表；尚未确认文件已保存到磁盘。';});
  const openReview=app.querySelector('#open-review');if(openReview)openReview.onclick=()=>act(async()=>{await client.review(view.task,'open');await refresh();});
  const reviewForm=app.querySelector('#review-form');if(reviewForm)reviewForm.onsubmit=e=>{e.preventDefault();const outcome=e.submitter?.value;if(!['analysis','more_evidence'].includes(outcome))return;const fields={...review.fields,actor:app.querySelector('#review-actor').value.trim(),questions:app.querySelector('#review-questions').value.trim(),closure:{...review.fields.closure,insufficient_reason:app.querySelector('#review-reason').value.trim(),disposition:'saved'}};if(!fields.actor||!fields.closure.insufficient_reason||outcome==='more_evidence'&&!fields.questions){notice='请填写审阅人、闭合说明；补证还需说明待调查问题。';render();return;}void act(async()=>{await client.review(view.task,'save',{review_id:review.id,review_version:review.sequence,review_sha256:review.sha256,fields});await refresh();const saved=view.task.reviews.at(-1);await client.review(view.task,'submit',{command_id:saved.intent_id,review_id:saved.id,review_version:saved.sequence,review_sha256:saved.sha256,outcome,confirmed:true});await refresh();notice=outcome==='analysis'?'分析已闭合，确认结果已保存。':'补证问题已保存，尚未形成正式闭合。';});};
  const stop=app.querySelector('#stop');if(stop)stop.onclick=()=>act(async()=>{await client.stop(selected);await refresh();});const recover=app.querySelector('#recover');if(recover)recover.onclick=()=>act(async()=>{const result=await client.recover();notice=result.status==='recorded'?'已读回保存结果。':result.status==='rejected'?'本次请求未保存，可检查后重新操作。':'尚未确认完成，继续保留并读回。';await refresh();});
 }
 async function act(work){if(busy)return;busy=true;render();try{await work();}catch(error){notice=error instanceof Error?error.message:'暂时无法完成，请读回保存状态。';}finally{busy=false;render();}}
 await refresh();render();
}

/** Independent web shell; configuration uses the existing closed settings protocol. */
export async function startServiceWorkspace({control:initialControl}){
 const app=document.getElementById('app'),style=document.createElement('link');style.rel='stylesheet';style.href='/styles.css';document.head.append(style);
 let control=initialControl,catalog={projects:[],current:null},settings=null,session={},busy=false,notice='',key='',proof=null,inAnalysis=false,pending=null;
 const pendingKey='xanthil.pending-project.v1';try{const value=JSON.parse(globalThis.sessionStorage?.getItem(pendingKey)??'null');if(value&&/^[a-f0-9-]{36}$/.test(value.command_id))pending=value;}catch{}
 const remember=value=>{pending=value;try{if(value)globalThis.sessionStorage?.setItem(pendingKey,JSON.stringify(value));else globalThis.sessionStorage?.removeItem(pendingKey);}catch{}};
 const errors={MODEL_BUSY:'另一个任务正在使用模型，请等待结清。',KEYCHAIN_UNAVAILABLE:'系统钥匙串暂不可用，请确认本机钥匙串助手已准备，再重新读取。',TEST_REQUIRED:'请先测试这份 Key，成功后保存。',CREDENTIAL_INVALID:'凭据无效，请核对 Key。',NETWORK_UNAVAILABLE:'网络暂不可用。',CONNECTION_TIMEOUT:'连接超时，没有自动重试。',QUOTA_EXCEEDED:'模型服务额度不足。',CONNECTION_FAILED:'连接未成功，请核对后再试。',CONFIGURATION_CHANGED:'本机配置已变化，请重新读取。',SAVE_FAILED:'尚未确认保存成功，请重新读取。',DELETE_FAILED:'尚未确认删除成功，请重新读取。'};
 async function request(path,body){const response=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'content-type':'application/json',...(control?{'x-xanthil-control':control}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});if(response.status===403){control=null;session={...session,owned:true};}if(!response.ok)throw Object.assign(Error('操作未确认，请读回项目或配置状态；不会自动重发。'),{definite:true});return response.json();}
 async function read(){[catalog,settings,session]=await Promise.all([request('/v1/projects'),request('/v1/settings'),request('/v1/session')]);}
 async function analyze(){key='';proof=null;inAnalysis=true;await startWorkspace({control,onHome:nextControl=>startServiceWorkspace({control:nextControl})});}
 async function choose(body){if(pending)throw Error('项目操作尚未确认，请先读回。');remember(body);try{const result=await request('/v1/projects/select',body);remember(null);control=result.control;await analyze();}catch(error){if(error.definite)remember({...body,definite:true});throw error;}}
 async function act(work){if(busy)return;busy=true;render();try{await work();}catch(error){notice=error.message;inAnalysis=false;}finally{busy=false;if(!inAnalysis)render();}}
 async function configure(operation){const payload=operation==='test'?{operation,key:key||null}:operation==='save'?{operation,key,proof}:operation==='delete'?{operation,confirmed:true}:{operation};const result=await request('/v1/settings',payload);settings=result;if(!result.ok){proof=null;notice=errors[result.code]??'操作未完成，请重新读取状态。';return;}if(operation==='test'){proof=result.proof??null;notice=proof?'连接测试通过，尚未保存。':'连接测试通过，任务不会自动开始。';}else if(operation==='save'){key='';proof=null;notice='已保存并启用，任务不会自动开始。';}else if(operation==='delete'){key='';proof=null;notice='已删除本机 Key；项目和报告保留。';}else{notice='已重新读取本机配置，没有连接模型。';}}
 function render(){const blocked=busy?'disabled':'',write=busy||!control?'disabled':'',projectBlocked=busy||pending||session.owned&&!control?'disabled':'';
 app.innerHTML=`<header class="topbar"><div class="brand"><span class="brand-mark"><img src="/assets/logo.png" alt=""></span><span class="brand-copy"><strong>JuanerAI</strong><small>持续做出更好的决策</small></span><span class="product-name">Xanthil</span></div></header><main class="workspace"><section class="surface"><h1>本机项目</h1><p>项目与资料保存在这台电脑。关闭网页不会停止已启动任务；退出服务或重开后不会自动继续。</p><p role="status">${esc(pending?'项目操作尚未确认，请先读回状态，不要重复创建。':notice)}</p>${session.owned&&!control?'<p>本页只读，另一页面持有操作权。</p><button id="service-takeover">接管到本页</button>':''}<button id="service-refresh" ${blocked}>读回状态</button><form id="project-create"><label for="project-name">新建项目</label><input id="project-name" maxlength="120" required ${projectBlocked}><button class="primary" ${projectBlocked}>创建并打开</button></form><h2>已保存项目</h2>${catalog.projects.length?catalog.projects.map(p=>`<button data-project="${esc(p.project_id)}" ${projectBlocked}>${esc(p.display_name)}</button>`).join(''):'<p>尚无已登记项目。</p>'}${catalog.current?'<button id="current-project">查看当前项目</button>':''}</section>
 <section class="surface"><h2>模型接入</h2><p>Xiaomi Token Plan · 中国区 · MiMo 2.6 Pro</p><p>${settings?.value?.configured?'已启用本机配置':'尚未读取或未配置本机 Key'} ${settings?.value?.state==='keychain_unavailable'?'· 钥匙串暂不可用':''}</p><p>Key 仅保存在这台 Mac 的系统钥匙串，不进入任务、文件或报告。</p><button id="settings-refresh" ${write}>读取本机配置</button><label for="provider-api-key">API Key（更换或首次配置）</label><input id="provider-api-key" type="password" autocomplete="off" spellcheck="false" ${write}><p>测试只发送固定文本 Reply with OK.，消耗少量额度；不发送项目或资料。一次请求，最多128输出token，30秒超时，不自动重试。</p><button id="settings-test" ${write}>测试连接</button><button id="settings-save" ${write} ${!proof?'disabled':''}>保存并启用</button><button id="settings-cancel" ${!control?'disabled':''}>取消测试</button>${settings?.value?.configured?`<details><summary>删除本机 Key</summary><p>只删除这台 Mac 的 Key，项目与报告保留，不撤销服务商账户 Key。</p><button id="settings-delete" ${write}>确认删除本机 Key</button></details>`:''}<p>配置不等于任务授权，分析前仍核对所选材料。${!control?'请先创建或选择项目；若已有其他操作页面，可明确接管。':''}</p></section></main>`;
 const input=app.querySelector('#provider-api-key');input.value=key;input.oninput=()=>{key=input.value;proof=null;app.querySelector('#settings-save').disabled=true;};
 app.querySelector('#project-create').onsubmit=e=>{e.preventDefault();const name=app.querySelector('#project-name').value.trim();if(!name)return;void act(()=>choose({version:'1.0',command_id:crypto.randomUUID(),name}));};
 app.querySelectorAll('[data-project]').forEach(button=>button.onclick=()=>act(()=>choose({version:'1.0',command_id:crypto.randomUUID(),project_id:button.dataset.project})));
 app.querySelector('#service-refresh').onclick=()=>act(async()=>{await read();if(pending){const saved=pending.name?await request('/v1/projects/commands/'+pending.command_id):catalog.current===pending.project_id?{project_id:pending.project_id}:null;if(saved||pending.definite){remember(null);notice=saved?'已读回保存项目；任务未自动执行。':'已确认该请求未保存。';}else notice='项目操作尚未确认，请保留状态继续读回。';}else notice='已读回保存状态，没有自动执行。';});
 const current=app.querySelector('#current-project');if(current)current.onclick=()=>analyze();
 const takeover=app.querySelector('#service-takeover');if(takeover)takeover.onclick=()=>act(async()=>{const value=await request('/v1/control',{version:'1.0',command_id:crypto.randomUUID(),generation:session.generation,confirmed:true});control=value.control;await read();notice='已接管到本页，任务未自动继续。';});
 for(const operation of ['refresh','test','save','delete']){const button=app.querySelector('#settings-'+operation);if(button)button.onclick=()=>act(()=>configure(operation));}
 app.querySelector('#settings-cancel').onclick=async()=>{proof=null;await request('/v1/settings',{operation:'cancel'});};
 }
 await read();render();
}
