import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readProjectControl, readReferencedDocument } from './project-control.mjs';

const HOST='127.0.0.1', args=process.argv.slice(2), p=args.indexOf('--port'), PORT=p>=0?Number(args[p+1]):41739, UI=path.dirname(fileURLToPath(import.meta.url));
if(!Number.isInteger(PORT)||PORT<1024||PORT>65535) throw new Error('Port must be between 1024 and 65535');
const headers={'Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'",'Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'};
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{...headers,'Content-Type':type});res.end(body);}
function reject(req,res){const host=req.headers.host||'',origin=req.headers.origin;if(host!==`${HOST}:${PORT}`&&host!==`localhost:${PORT}`){send(res,400,JSON.stringify({error:'Invalid Host'}));return true;}if(origin&&origin!==`http://${HOST}:${PORT}`&&origin!==`http://localhost:${PORT}`){send(res,403,JSON.stringify({error:'Invalid Origin'}));return true;}if(!['GET','HEAD'].includes(req.method)){send(res,405,JSON.stringify({error:'Read-only service'}));return true;}return false;}
const server=createServer(async(req,res)=>{if(reject(req,res))return;try{const url=new URL(req.url,`http://${HOST}:${PORT}`),head=req.method==='HEAD';if(url.pathname==='/'||url.pathname==='/index.html'){send(res,200,head?'':await readFile(path.join(UI,'index.html'),'utf8'),'text/html; charset=utf-8');return;}if(url.pathname==='/api/health'){send(res,200,head?'':JSON.stringify({status:'ok',mode:'read-only'}));return;}if(url.pathname==='/api/project-control'){send(res,200,head?'':JSON.stringify(await readProjectControl()));return;}if(url.pathname==='/api/document'){const value=await readReferencedDocument(url.searchParams.get('brief_id')||'',Number(url.searchParams.get('ref')));send(res,200,head?'':JSON.stringify(value));return;}if(url.pathname==='/favicon.ico'){res.writeHead(204,headers);res.end();return;}send(res,404,JSON.stringify({error:'Not found'}));}catch(error){const invalid=error.message.startsWith('Project control validation failed:'),missing=error.code==='ENOENT';send(res,invalid?400:missing?404:503,JSON.stringify({error:invalid?'Invalid request':missing?'Referenced record not found':'Project control unavailable',detail:error.message}));}});
server.listen(PORT,HOST,()=>{process.stdout.write(`JuanerAI project board: http://${HOST}:${PORT}\nMode: repository-backed, read-only browser surface\n`);});
