#!/usr/bin/env node
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { CONTROL_ROOT, appendEvent, atomicWriteJson, createEvent, readProjectControl, validateBrief, validateStatus } from './project-control.mjs';
const [command='help',...tokens]=process.argv.slice(2);
function flags(v){const r={};for(let i=0;i<v.length;i+=2){if(!v[i]?.startsWith('--')||v[i+1]===undefined)throw new Error(`Invalid argument near ${v[i]||'<end>'}`);r[v[i].slice(2)]=v[i+1];}return r;}const required=(v,n)=>{if(!v)throw new Error(`Missing --${n}`);return v;};
async function status(){return(await readProjectControl()).status;}
const EVENT_WARNING='{"level":"warning","code":"PROJECT_BOARD_EVENT_APPEND_FAILED"}\n';
async function appendBestEffort(event){try{await appendEvent(event);}catch{process.stderr.write(EVENT_WARNING);}}
async function persist(s,type,summary,session){s.updated_at=new Date().toISOString();s.updated_by={role:'controller',session};validateStatus(s);const event=createEvent({type,summary,statusAfter:s.health,session});await atomicWriteJson(path.join(CONTROL_ROOT,'status.json'),s,validateStatus);await appendBestEffort(event);}
async function main(){const o=flags(tokens);if(command==='show'){process.stdout.write(`${JSON.stringify(await readProjectControl(),null,2)}\n`);return;}if(command==='set'){const s=await status(),session=o.session||'status-cli';if(o.health)s.health=o.health;if(o.summary)s.summary=o.summary;if(o.objective)s.current_objective=o.objective;if(o['next-action'])s.next_action=o['next-action'];if(o['phase-id'])s.phase.id=o['phase-id'];if(o['phase-label'])s.phase.label=o['phase-label'];if(o['phase-ordinal'])s.phase.ordinal=Number(o['phase-ordinal']);await persist(s,o['event-type']||'status_updated',required(o['event-summary'],'event-summary'),session);return;}if(command==='milestone'){const s=await status(),m=s.milestones.find(x=>x.id===required(o.id,'id'));if(!m)throw new Error(`Unknown milestone: ${o.id}`);m.status=required(o.status,'status');await persist(s,o['event-type']||'phase_changed',required(o['event-summary'],'event-summary'),o.session||'status-cli');return;}if(command==='event'){const s=await status(),event=createEvent({type:required(o.type,'type'),summary:required(o.summary,'summary'),statusAfter:s.health,session:o.session||'status-cli',evidenceRefs:o.evidence?o.evidence.split(',').filter(Boolean):[]});await appendBestEffort(event);return;}if(command==='brief'){const id=required(o.id,'id');if(!/^[A-Za-z0-9_-]+$/.test(id))throw new Error('Invalid brief id');const file=path.join(CONTROL_ROOT,'decision-briefs',`${id}.json`),b=validateBrief(JSON.parse(await readFile(file,'utf8')));b.status=required(o.status,'status');b.resolution_summary=o.resolution||null;b.updated_at=new Date().toISOString();validateBrief(b);const s=await status(),event=createEvent({type:b.status==='resolved'?'decision_resolved':'status_updated',summary:o['event-summary']||`Decision brief ${id} changed to ${b.status}`,statusAfter:s.health,session:o.session||'status-cli',evidenceRefs:[path.relative(process.cwd(),file)]});await atomicWriteJson(file,b,validateBrief);await appendBestEffort(event);return;}if(command==='replace'){const s=validateStatus(JSON.parse(await readFile(path.resolve(required(o.input,'input')),'utf8')));await persist(s,o['event-type']||'status_updated',required(o['event-summary'],'event-summary'),o.session||'status-cli');return;}process.stdout.write('Commands: show | set | milestone | event | brief | replace\nUse --event-summary for material status mutations.\n');}
main().catch(error=>{process.stderr.write(`${error.message}\n`);process.exitCode=1;});
