import {randomUUID} from 'node:crypto';
import type {Authorization,AssistantSource,AssistantAttempt,AssistantTurnResult,MembershipAuthorization} from '../contracts/case-assistant.ts';
import type {CollaborationReference,ChildResultValue} from '../contracts/case-collaboration.ts';
import type {MembershipTaskStore,TaskMutation} from '../ports/member-task.ts';
import type {DesktopDecisionCaseStore} from '../ports/xanthil-desktop-decision-case.ts';
import type {createXanthilDesktopDecisionCaseApplication} from './xanthil-desktop-decision-case.ts';
import {parseDesktopCsv} from '../product-core/xanthil-desktop-decision-case.ts';
import {membershipHash} from '../product-core/member-analysis.ts';
import {closed,fail,resourceProfile,outbound,retainedOutbound,protectText,encodeTask,taskHash,totals,type TaskResourceProfile,type TaskGrant,type TaskUsage,type TaskAttempt} from '../product-core/member-task.ts';
export type RetainedMembershipDependencies={store:MembershipTaskStore;desktop:ReturnType<typeof createXanthilDesktopDecisionCaseApplication>;sourceStore:Pick<DesktopDecisionCaseStore,'readConfirmedSnapshot'>;profile:TaskResourceProfile|null;runtime?:import('../ports/case-assistant.ts').CaseAssistantRuntime|null};
export function createRetainedMembershipAccess(deps:RetainedMembershipDependencies,clock:()=>Date){
 const profile=deps.profile?resourceProfile(deps.profile):null,writes=new Map<string,Promise<unknown>>();
 const mutate=(id:string,value:NonNullable<TaskMutation['retained']>)=>{const before=writes.get(id)??Promise.resolve();const after=before.catch(()=>undefined).then(async()=>{const s=await deps.store.read(id);return deps.store.commit(id,s.row_version,{retained:value});});writes.set(id,after);return after;};
 async function snapshot(source:AssistantSource){
  const origin=source.membership_origin;if(origin)closed(origin,['version','task_id','prepared_sha256']);if(!origin||!profile||profile.activation!=='synthetic_only')fail('AUTHORITY_REQUIRED');
  const state=await deps.store.read(origin.task_id),p=state.prepared;if(!p||p.fingerprint!==origin.prepared_sha256||encodeTask(state.owner)!==encodeTask(source.owner)||encodeTask(profile)!==encodeTask(state.grants.filter(g=>!g.retained).at(-1)?.profile))fail('CONFIGURATION_CHANGED');
  const projection=await deps.desktop.readProjection(state.owner);if(projection.revision?.state!=='Completed'||projection.revision.row_version!==source.row_version||projection.revision.current_report_id!==source.report.report_id||projection.session?.current_revision_id!==source.owner.revision_id||!projection.confirmation)fail('SOURCE_CHANGED');
  const saved=await deps.sourceStore.readConfirmedSnapshot({...state.owner,confirmation_id:projection.confirmation.confirmation_id});
  const contract=JSON.parse(new TextDecoder().decode(saved.confirmation.contract_bytes)),binding=JSON.parse(new TextDecoder().decode(saved.confirmation.binding_bytes));
  if(membershipHash({column_mapping:binding,comparison_period:contract.comparison_period,current_period:contract.current_period,currency:contract.currency,time_zone:contract.time_zone,valid_statuses:contract.valid_statuses,selected_group_mode:contract.selected_group_mode})!==membershipHash(p.selection))fail('SOURCE_CHANGED');
  const protectedValues=[...Object.values(source.owner),source.finding_id,source.acceptance_id,source.closure_id,source.aggregate.artifact_id,source.report.report_id,...source.evidence_refs,...source.candidates.map(c=>c.candidate_id)];
  for(const [role,columns]of [['members',[p.selection.column_mapping.member_id_column,p.selection.column_mapping.member_group_column]],['orders',[p.selection.column_mapping.order_id_column,p.selection.column_mapping.order_member_id_column]]] as const){if(saved.snapshot[role].sha256!==p.sources[role].sha256)fail('SOURCE_CHANGED');const csv=parseDesktopCsv(saved.snapshot[role].bytes);protectedValues.push(...csv.headers,saved.snapshot[role].display_name);for(const row of csv.rows)for(const col of columns)if(col)protectedValues.push(row[csv.headers.indexOf(col)]);}
  const metrics=JSON.parse(source.aggregate.content),material=outbound({version:'1.0',source_sha256:p.fingerprint,methods:p.methods,semantics:{metric:'membership_repurchase_comparison',currency:'CNY',time_zone:'Asia/Shanghai',comparison_period:p.selection.comparison_period,current_period:p.selection.current_period,status_meanings:'explicitly_confirmed_local'},preparation:p.counts,selected_text:null,result:{periods:metrics.periods,changes:metrics.changes},tool_result:'verified'});
  const text=(value:string)=>{protectText(value,protectedValues);outbound({...material,selected_text:value});if(/\b[0-9a-f]{8}-[0-9a-f-]{27,}\b|(?:groups?|分组|群组|组别).{0,30}\d/i.test(value))fail('OUTBOUND_FORBIDDEN');return value;};
  return {state,prepared:p,material,text};
 }
 function refs(a:Authorization):CollaborationReference[]{return a.collaboration?[...a.collaboration.allowed_references]:[{kind:'case',id:a.source.owner.case_id,revision_id:a.source.owner.revision_id,version:null,sha256:null},...a.source.evidence_refs.map(id=>({kind:'evidence' as const,id,revision_id:a.source.owner.revision_id,version:null,sha256:null})),{kind:'finding',id:a.source.finding_id,revision_id:a.source.owner.revision_id,version:null,sha256:null},...a.source.candidates.map(c=>({kind:'candidate' as const,id:c.candidate_id,revision_id:a.source.owner.revision_id,version:null,sha256:null}))];}
 function aliases(a:Authorization){return refs(a).map((r,i)=>({...r,id:'reference-'+(i+1),revision_id:'current',sha256:null}));}
 async function safeValue(source:AssistantSource,value:ChildResultValue){const s=await snapshot(source);s.text(value.summary);value.limitations.forEach(s.text);value.unknowns.forEach(s.text);return value;}
 async function restrict(a:Authorization,session_id:string):Promise<Authorization>{
  const s=await snapshot(a.source);if(a.config?.provider!==profile!.provider||a.config.model!==profile!.model)fail('CONFIGURATION_CHANGED');
  const context=JSON.parse(a.payload),selected_history=[...a.selected_history,...(context.inherited_history??[])].map((e:{kind:string;text:string})=>({kind:e.kind,text:e.kind==='tool'?encodeTask(s.material):s.text(e.text)}));
  const materials=context.selected_materials??[],results=a.collaboration?.selected_results??[];
  for(const m of materials)await safeValue(a.source,m.result.value);for(const r of results)await safeValue(a.source,r.value);
  const created_at=clock().toISOString(),membership:MembershipAuthorization={version:'1.0',task_id:s.state.task_id,source_sha256:taskHash(a.source),profile:profile!,purpose:a.collaboration?.kind??'assistant',session_id,created_at,expires_at:new Date(Date.parse(created_at)+profile!.grant_ms).toISOString(),usage:totals(s.state.usage)};
  const task=context.task===undefined||context.task===null?null:s.text(context.task);
  const payload=JSON.stringify({contract_version:a.collaboration?'1.1':'1.0',source:'current',task,initial_text:s.text(a.initial_text),material:s.material,selected_history,selected_reports:a.selected_reports.map((_,i)=>({reference:'report-'+(i+1),material:s.material})),selected_materials:materials.map((m:{result:{value:ChildResultValue}})=>({classification:'MODEL',summary:m.result.value.summary,limitations:m.result.value.limitations,unknowns:m.result.value.unknowns})),selected_results:results.map(r=>({summary:r.value.summary,limitations:r.value.limitations,unknowns:r.value.unknowns})),allowed_references:aliases(a),tools:a.tools});
  return {...a,membership,payload,categories:['P1 两期总体指标','本次同意的文本','本次选择的安全摘要','原任务累计资源']};
 }
 async function check(a:Authorization){
  const m=a.membership;if(m)closed(m,['version','task_id','source_sha256','profile','purpose','session_id','created_at','expires_at','usage']);if(!m||m.source_sha256!==taskHash(a.source)||encodeTask(m.profile)!==encodeTask(profile))fail('AUTHORITY_REQUIRED');
  if(clock().getTime()>=Date.parse(m.expires_at)){await revoke(a);fail('GRANT_EXPIRED');}
  try{return await snapshot(a.source);}catch(error){await revoke(a);throw error;}
 }
 async function grant(a:Authorization,attempt:AssistantAttempt){const s=await check(a),m=a.membership!;const g:TaskGrant={version:'1.0',id:a.id,task_id:s.state.task_id,epoch:s.state.epoch,prepared:s.prepared,profile:m.profile,selected_text:a.initial_text,created_at:m.created_at,expires_at:m.expires_at,revoked_at:null,retained:{session_id:attempt.session_id,authorization_id:a.id,authorization_sha256:taskHash(a),source_sha256:m.source_sha256,purpose:m.purpose}};if(m.session_id!==attempt.session_id)fail('AUTHORITY_REQUIRED');const row:TaskAttempt={version:'1.0',id:attempt.id,grant_id:g.id,epoch:g.epoch,status:'running',phase:'explaining',started_at:attempt.started_at,ended_at:null,error:null};await mutate(s.state.task_id,{grant:g,attempt:row});}
 async function guard(a:Authorization){const s=await check(a),g=s.state.grants.find(g=>g.id===a.id);if(!g?.retained||g.revoked_at||g.epoch!==s.state.epoch||g.retained.source_sha256!==a.membership!.source_sha256||g.retained.authorization_sha256!==taskHash(a))fail('INTERRUPTED');return s;}
 async function reserve(a:Authorization,attempt:AssistantAttempt,kind:'model'|'waiting',payload:string|null){const s=await guard(a),p=a.membership!.profile;const u:TaskUsage={version:'1.0',id:randomUUID(),attempt_id:attempt.id,kind,status:'reserved',source_sha256:s.prepared.fingerprint,payload_sha256:payload===null?null:taskHash(payload),calls:kind==='model'?1:0,output_tokens:kind==='model'?p.call_output_tokens:0,active_ms:kind==='model'?p.call_ms:0,wait_ms:kind==='waiting'?p.wait_ms:0,local_runs:0,at:clock().toISOString()};if(payload!==null&&Buffer.byteLength(payload)>p.max_input_bytes)fail('BUDGET_EXHAUSTED');await mutate(s.state.task_id,{usage:u});return u;}
 async function update(a:Authorization,u:TaskUsage){await mutate(a.membership!.task_id,{usage:u});}
 async function revoke(a:Authorization){if(!a.membership)return;const s=await deps.store.read(a.membership.task_id),g=s.grants.find(g=>g.id===a.id);if(g?.retained&&!g.revoked_at)await mutate(s.task_id,{revoke:{grant_id:g.id,at:clock().toISOString()}});}
 async function finish(a:Authorization,attempt:AssistantAttempt){if(!a.membership)return;const s=await deps.store.read(a.membership.task_id),row=s.attempts.find(r=>r.id===attempt.id);if(row&&['running','waiting'].includes(row.status))await mutate(s.task_id,{attempt:{...row,status:attempt.status==='Succeeded'?'succeeded':attempt.status==='Stopped'?'stopped':'failed',ended_at:clock().toISOString(),error:attempt.reason},revoke:{grant_id:a.id,at:clock().toISOString()}});}
 async function payload(a:Authorization,events:readonly {kind:string;text:string}[],text:string,tool:unknown){const s=await guard(a);return JSON.stringify(retainedOutbound({authorized_context:JSON.parse(a.payload),current_attempt_history:events.map(e=>({kind:e.kind,text:e.kind==='tool'?encodeTask(s.material):s.text(e.text)})),visible_message:s.text(text),authorized_tool_result:tool}));}
 async function tool(a:Authorization){return (await guard(a)).material;}
 async function output(a:Authorization,value:AssistantTurnResult['output']){const s=await guard(a),list=refs(a),safe=aliases(a);if(Buffer.byteLength(JSON.stringify(value))>profile!.max_output_bytes)fail('OUTBOUND_FORBIDDEN');
  const walk=(v:unknown):unknown=>{if(typeof v==='string'){const at=safe.findIndex(r=>r.id===v);if(at>=0)return list[at].id;if(v==='current')return a.source.owner.revision_id;s.text(v);return v;}if(Array.isArray(v))return v.map(walk);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,v])=>[k,walk(v)]));return v;};
  if(value.kind==='result'){const mapped={...value,references:value.references.map(ref=>{const i=safe.findIndex(x=>encodeTask(x)===encodeTask(ref));if(i<0)fail('OUTBOUND_FORBIDDEN');return list[i];})};await safeValue(a.source,mapped);return mapped;}
  return walk(value) as AssistantTurnResult['output'];
 }
 return {restrict,check,grant,guard,reserve,update,revoke,finish,payload,tool,output,safeValue};
}
