import {reviewFields,validateReview,type MembershipReview,type ReviewSource,type ReviewSubmission} from '../product-core/member-review.ts';
import type {LocalModelAccess} from '../ports/provider-settings.ts';
import type {CaseAssistantRuntime} from '../ports/case-assistant.ts';
import type {DesktopDecisionCaseStore} from '../ports/xanthil-desktop-decision-case.ts';
import {randomUUID} from 'node:crypto';
import {membershipHash,type MembershipPlan,type MembershipResult,membershipBytesHash} from '../product-core/member-analysis.ts';
import {parseDesktopCsv,prepareDesktopData} from '../product-core/xanthil-desktop-decision-case.ts';
import type {DesktopSourcePair} from '../ports/xanthil-desktop-decision-case.ts';
import type {MembershipTaskStore} from '../ports/member-task.ts';
import {totals,taskHash,taskPeriods,type PeriodPreview,commentInput,preparedIdentity,validatePrepared,fail,encodeTask,closed,resourceProfile,protectText,outbound,memberOutput,type TaskAttempt,type TaskUsage,type TaskEvent,type TaskGrant,type TaskResourceProfile,type PreparedTask,type TaskProjection} from '../product-core/member-task.ts';
import type {createXanthilDesktopDecisionCaseApplication} from './xanthil-desktop-decision-case.ts';
export function createMembershipTaskApplication(deps:{desktop:ReturnType<typeof createXanthilDesktopDecisionCaseApplication>;project_id:string;store:MembershipTaskStore;profile?:TaskResourceProfile|null;clock?:()=>Date;runtime?:CaseAssistantRuntime|null;modelAccess?:LocalModelAccess;sourceStore?:Pick<DesktopDecisionCaseStore,'readConfirmedSnapshot'>}){
 type Control={abort:AbortController;release:()=>void;done:Promise<void>;run?:string;reason?:string;resume?:()=>void;reply?:string|null;waitTimer?:ReturnType<typeof setTimeout>};const active=new Map<string,Control>(),writes=new Map<string,Promise<unknown>>(),pendingFences=new Map<string,'stopped'|'closed'|'interrupted'>();
 const pendingReviews=new Set<string>();
 const clock=deps.clock??(()=>new Date()),profile=deps.profile?resourceProfile(deps.profile):null;
 async function read(id:string):Promise<TaskProjection>{const state=await deps.store.read(id);const latest=state.grants.at(-1);if(latest&&!latest.retained&&!latest.revoked_at&&clock().getTime()>=Date.parse(latest.expires_at))return stop(id);const p=await deps.desktop.readProjection(state.owner),history:typeof p[]=[];const seen=new Set<string>([state.owner.revision_id]);let previous=p.revision?.previous_revision_id;while(previous){if(seen.has(previous))fail('INTEGRITY_BLOCKED');seen.add(previous);const old=await deps.desktop.readProjection({...state.owner,revision_id:previous});history.push(old);previous=old.revision?.previous_revision_id;}pendingReviews.delete(id);return {...state,history,configurations:await deps.store.configurations(),question:p.revision!.question_text,profile,missing:[...(!state.prepared?['请选择会员与订单两个文件，并确认期间、状态含义和映射']:[]),...(!profile||profile.activation==='closed'?['尚未配置获准的模型及资源范围']:[])],active_physical:active.has(id),case:p,totals:totals(state.usage)};}
 async function inspect(id:string,source_files:DesktopSourcePair,configuration?:unknown){const t=await read(id);const g=t.grants.at(-1);if(g&&!g.revoked_at&&(['members','orders'] as const).some(role=>membershipBytesHash(source_files[role].bytes)!==g.prepared.sources[role].sha256)){await stop(id);fail('SOURCE_CHANGED');}const base={contract_version:'1.0',...t.owner,expected_row_version:t.case.revision!.row_version,source_files};const initial=await deps.desktop.inspectImportFiles(base);return configuration?deps.desktop.inspectImportFiles({...base,inspection_token:initial.inspection_token,configuration}):initial;}
 async function prepare(id:string,input:{source_files:DesktopSourcePair;selection:unknown;scenario:unknown;methods:readonly string[];issue_treatments:unknown}){const p=await read(id),inspection=await inspect(id,input.source_files,input.selection);const expected=inspection.reviewable_issues.map(x=>({code:x.code,count:x.count,treatment:x.treatment_options[0]}));if(encodeTask(expected)!==encodeTask(input.issue_treatments))fail('ISSUE_CONFIRMATION_REQUIRED');const source=(r:'members'|'orders')=>({sha256:inspection[r].sha256,byte_length:inspection[r].byte_length,display_name:inspection[r].display_name});const body={version:'1.0',owner:p.owner,scenario:input.scenario,selection:input.selection,methods:input.methods,sources:{members:source('members'),orders:source('orders')},counts:{members:inspection.members.row_count,orders:inspection.orders.row_count},issue_treatments:input.issue_treatments} as Omit<PreparedTask,'fingerprint'>;const prepared=validatePrepared({...body,fingerprint:preparedIdentity(body)});await deps.store.commit(id,p.row_version,{prepared});return read(id);}
 async function configuration(ref:unknown){
  const r=closed(ref,['config_id','config_version','config_sha256']);const c=(await deps.store.configurations()).find(c=>c.scenario.id===r.config_id&&c.scenario.revision===r.config_version);
  if(!c||c.sha256!==r.config_sha256)fail('CONFIGURATION_CHANGED');return c;
 }
 async function inspectConfig(id:string,source_files:DesktopSourcePair,ref:unknown){const c=await configuration(ref);return inspect(id,source_files,c.selection);}
 async function prepareConfig(id:string,source_files:DesktopSourcePair,ref:unknown,issue_treatments:unknown){const c=await configuration(ref);return prepare(id,{source_files,selection:c.selection,scenario:c.scenario,methods:c.methods,issue_treatments});}
 async function authorize(id:string,input:unknown){
  if(pendingFences.has(id))await stop(id,pendingFences.get(id)!);
  const x=closed(input,['fingerprint','source_files','authority_confirmed','text_consent']);if(x.authority_confirmed!==true||typeof x.text_consent!=='boolean')fail('AUTHORITY_REQUIRED');
  if(!profile||profile.activation!=='synthetic_only')fail('AUTHORITY_REQUIRED');
  let t=await read(id);if(t.case.revision?.state==='Completed')fail('FORBIDDEN');const p=t.prepared;if(!p||x.fingerprint!==p.fingerprint){if(t.grants.some(g=>!g.revoked_at))await stop(id);fail('SOURCE_CHANGED');}
  const pair=closed(x.source_files,['members','orders']);for(const role of ['members','orders'] as const){const f=closed(pair[role],['display_name','bytes']);if(!(f.bytes instanceof Uint8Array)||f.display_name!==p.sources[role].display_name||membershipBytesHash(f.bytes)!==p.sources[role].sha256){if(t.grants.some(g=>!g.revoked_at))await stop(id);fail('SOURCE_CHANGED');}}
  const sources=x.source_files as DesktopSourcePair;
  let selected_text:string|null=null;
  if(x.text_consent){const values:string[]=[];for(const [role,columns] of [['members',[p.selection.column_mapping.member_id_column,p.selection.column_mapping.member_group_column]],['orders',[p.selection.column_mapping.order_id_column,p.selection.column_mapping.order_member_id_column]]] as const){const csv=parseDesktopCsv(sources[role].bytes);values.push(...csv.headers,sources[role].display_name);for(const row of csv.rows)for(const col of columns)if(col)values.push(row[csv.headers.indexOf(col)]);}
    selected_text=protectText(t.question,values);outbound(payloadFor(p,selected_text));}
  if(t.attempts.some(a=>['running','waiting'].includes(a.status)))fail('BUSY');
  if(t.grants.some(g=>g.revoked_at===null)){await deps.store.commit(id,t.row_version,{fence:{status:'stopped',at:clock().toISOString()}});t=await read(id);}
  if(t.case.revision!.state==='Draft'){
   const inspection=await inspect(id,sources,p.selection);
   await deps.desktop.confirmRevision({contract_version:'1.0',command_id:randomUUID(),...t.owner,expected_row_version:t.case.revision!.row_version,inspection_token:inspection.inspection_token,source_files:sources,confirmation:{...p.selection,issue_treatments:p.issue_treatments,hypothesis_id:'current_repurchase_rate_lower_than_comparison',method_id:'membership_repurchase_comparison',method_version:'1.0',authority_confirmed:true,issues_confirmed:true,plan_confirmed:true}});
  }
  const now=clock();const grant:TaskGrant={version:'1.0',id:randomUUID(),task_id:id,epoch:t.epoch,prepared:p,profile,selected_text,created_at:now.toISOString(),expires_at:new Date(now.getTime()+profile.grant_ms).toISOString(),revoked_at:null};
  await deps.store.commit(id,t.row_version,{grant,status:'idle'});return read(id);
 }
 async function mutate(id:string,m:import('../ports/member-task.ts').TaskMutation){
  const previous=writes.get(id)??Promise.resolve();const next=previous.catch(()=>undefined).then(async()=>{const t=await deps.store.read(id);return deps.store.commit(id,t.row_version,m);});writes.set(id,next);return next;
 }
 async function guard(id:string,g:TaskGrant,c:Control){
  if(c.abort.signal.aborted)fail(c.reason??'INTERRUPTED');
  const t=await deps.store.read(id);if(t.epoch!==g.epoch||t.grants.find(x=>x.id===g.id)?.revoked_at||t.prepared?.fingerprint!==g.prepared.fingerprint)fail('INTERRUPTED');
  if(clock().getTime()>=Date.parse(g.expires_at)){await stop(id,'stopped');fail('GRANT_EXPIRED');}
  const p=await deps.desktop.readProjection(t.owner);if(p.session?.current_revision_id!==t.owner.revision_id||p.revision?.integrity_state!=='ok'){await stop(id);fail('SOURCE_CHANGED');}return p;
 }
 async function source(id:string,g:TaskGrant){try{const t=await read(id);if(!t.case.confirmation||!deps.sourceStore)fail('SOURCE_CHANGED');const s=await deps.sourceStore.readConfirmedSnapshot({...t.owner,confirmation_id:t.case.confirmation.confirmation_id});for(const role of ['members','orders'] as const)if(s.snapshot[role].sha256!==g.prepared.sources[role].sha256)fail('SOURCE_CHANGED');const contract=JSON.parse(new TextDecoder().decode(s.confirmation.contract_bytes)),binding=JSON.parse(new TextDecoder().decode(s.confirmation.binding_bytes));const selected={column_mapping:binding,comparison_period:contract.comparison_period,current_period:contract.current_period,currency:contract.currency,time_zone:contract.time_zone,valid_statuses:contract.valid_statuses,selected_group_mode:contract.selected_group_mode};if(membershipHash(selected)!==membershipHash(g.prepared.selection))fail('SOURCE_CHANGED');return s;}catch(error){if(['SOURCE_CHANGED','INTEGRITY_BLOCKED'].includes(String((error as{code?:string}).code))){await stop(id);}throw error;}}
 function protectedText(text:string,g:TaskGrant,s:Awaited<ReturnType<typeof source>>){const p=g.prepared,values:string[]=[];for(const [role,columns]of [['members',[p.selection.column_mapping.member_id_column,p.selection.column_mapping.member_group_column]],['orders',[p.selection.column_mapping.order_id_column,p.selection.column_mapping.order_member_id_column]]] as const){const csv=parseDesktopCsv(s.snapshot[role].bytes);values.push(...csv.headers,s.snapshot[role].display_name);for(const row of csv.rows)for(const col of columns)if(col)values.push(row[csv.headers.indexOf(col)]);}return protectText(text,values);}
 async function append(id:string,a:TaskAttempt,g:TaskGrant,kind:TaskEvent['kind'],text:string){return mutate(id,{event:{version:'1.0',id:randomUUID(),attempt_id:a.id,source_sha256:g.prepared.fingerprint,kind,text,at:clock().toISOString()}});}
 async function reserve(id:string,a:TaskAttempt,g:TaskGrant,kind:TaskUsage['kind'],payload:string|null){const r=g.profile;const u:TaskUsage={version:'1.0',id:randomUUID(),attempt_id:a.id,kind,status:'reserved',source_sha256:g.prepared.fingerprint,payload_sha256:payload===null?null:membershipBytesHash(new TextEncoder().encode(payload)),calls:kind==='model'?1:0,output_tokens:kind==='model'?r.call_output_tokens:0,active_ms:kind==='model'?r.call_ms:kind==='analysis'?r.run_ms:0,wait_ms:kind==='waiting'?r.wait_ms:0,local_runs:kind==='analysis'?1:0,at:clock().toISOString()};await mutate(id,{usage:u});return u;}
 async function execute(id:string,a:TaskAttempt,g:TaskGrant,c:Control){let current=a,selected=a.comment_id?(await read(id)).comments.find(x=>x.id===a.comment_id)!.text:g.selected_text;
  const update=async(p:Partial<TaskAttempt>)=>{current={...current,...p};await mutate(id,{attempt:current});};
  try{
   while(true){const p=await guard(id,g,c);await source(id,g);const finding=p.findings.find(f=>p.runs.some(r=>r.run_id===f.run_id&&r.run_contract_version==='4.0'&&r.status==='Succeeded'));
    const metrics=finding?JSON.parse(finding.metrics) as MembershipResult:null;
    const payload=encodeTask(outbound({...payloadFor(g.prepared,selected),result:metrics?{periods:metrics.periods,changes:metrics.changes}:null,tool_result:metrics?'verified':'prepared'}));
    if(Buffer.byteLength(payload)>g.profile.max_input_bytes)fail('BUDGET_EXHAUSTED');
    await update({phase:metrics?'explaining':'planning'});const u=await reserve(id,current,g,'model',payload);let issued=false;const started=clock().getTime();
    let response:Awaited<ReturnType<NonNullable<typeof deps.runtime>['turn']>>;
    const timer=setTimeout(()=>{c.reason='DEADLINE_EXCEEDED';c.abort.abort();c.resume?.();if(clock().getTime()>=Date.parse(g.expires_at))void stop(id).catch(()=>undefined);},Math.min(g.profile.call_ms,Date.parse(g.expires_at)-started));
    try{await guard(id,g,c);await append(id,current,g,'outbound',payload);await mutate(id,{usage:{...u,status:'issued'}});issued=true;await guard(id,g,c);
     response=await deps.runtime!.turn({membership:{version:'1.0',...(a.comment_id?{purpose:'comment' as const}:{})},provider:g.profile.provider,model:g.profile.model,payload,signal:c.abort.signal,cost_reservation_microunits:1});
     if(response.provider!==g.profile.provider||response.model!==g.profile.model||Buffer.byteLength(encodeTask(response.output))>g.profile.max_output_bytes)fail('OUTBOUND_FORBIDDEN');
     await mutate(id,{usage:{...u,status:'settled',active_ms:Math.min(g.profile.call_ms,Math.max(0,clock().getTime()-started)),output_tokens:response.membership_usage?.output_tokens??u.output_tokens}});
    }catch(error){await mutate(id,{usage:issued?{...u,status:'unresolved'}:{...u,status:'settled',calls:0,output_tokens:0,active_ms:0}});throw error;}finally{clearTimeout(timer);}
    await guard(id,g,c);await source(id,g);const output=memberOutput(response.output);if('text' in output){protectedText(output.text,g,await source(id,g));outbound(payloadFor(g.prepared,output.text));}selected=null;
    if(output.kind==='comment'){if(!a.comment_id||!finding)fail('OUTBOUND_FORBIDDEN');await mutate(id,{commentResolution:{comment_id:a.comment_id,attempt_id:a.id,resolution:output}});if(output.intent==='expression')await mutate(id,{expression:{comment_id:a.comment_id,attempt_id:a.id,grant_id:g.id,epoch:g.epoch,text:output.text,at:clock().toISOString()}});await update({status:'succeeded',ended_at:clock().toISOString()});await mutate(id,{status:'idle'});return;}
    if(output.kind==='report'){if(a.comment_id)fail('OUTBOUND_FORBIDDEN');if(!finding)fail('RESULT_REQUIRED');await append(id,current,g,'explanation',output.text);await update({status:'succeeded',ended_at:clock().toISOString()});await mutate(id,{status:'idle'});return;}
    if(a.comment_id)fail('COMMENT_REQUIRES_CLARIFICATION');
    if(output.kind==='question'){
     await append(id,current,g,'question',output.text);const waiting=await reserve(id,current,g,'waiting',null);await mutate(id,{usage:{...waiting,status:'issued'}});await update({status:'waiting'});await mutate(id,{status:'waiting'});const startedWait=clock().getTime();
     await new Promise<void>(resolve=>{c.resume=resolve;c.waitTimer=setTimeout(()=>{c.reason='WAIT_EXPIRED';c.abort.abort();if(clock().getTime()>=Date.parse(g.expires_at))void stop(id).catch(()=>undefined);resolve();},Math.min(g.profile.wait_ms,Date.parse(g.expires_at)-clock().getTime()));});
     clearTimeout(c.waitTimer);c.resume=undefined;await mutate(id,{usage:{...waiting,status:'settled',wait_ms:Math.min(g.profile.wait_ms,Math.max(0,clock().getTime()-startedWait))}});await guard(id,g,c);selected=c.reply??null;c.reply=null;await update({status:'running'});await mutate(id,{status:'running'});continue;
    }
    if(output.kind!=='tool')fail('OUTBOUND_FORBIDDEN');
    if(output.tool==='read_result'){if(!finding)fail('RESULT_REQUIRED');continue;}
    if(finding)continue; // A verified result is reused; tools cannot force a second Run.
    await update({phase:'calculating'});const runUsage=await reserve(id,current,g,'analysis',null);let runIssued=false;const runStarted=clock().getTime();
    try{await guard(id,g,c);const snapshot=await source(id,g);await mutate(id,{usage:{...runUsage,status:'issued'}});runIssued=true;
     const plan:MembershipPlan={task_context:{task_id:id,grant_id:g.id,epoch:String(g.epoch),reservation_id:runUsage.id,run_ms:String(g.profile.run_ms),process_seconds:String(g.profile.process_seconds)},version:'1.0',id:randomUUID(),owner:g.prepared.owner,confirmation_id:p.confirmation!.confirmation_id,snapshot_id:snapshot.snapshot.snapshot_id,scenario:g.prepared.scenario,scenario_sha256:membershipHash(g.prepared.scenario),contract_sha256:membershipHash(g.prepared.selection),binding_sha256:membershipHash(g.prepared.selection.column_mapping),sources:{members:{sha256:g.prepared.sources.members.sha256,byte_length:g.prepared.sources.members.byte_length},orders:{sha256:g.prepared.sources.orders.sha256,byte_length:g.prepared.sources.orders.byte_length}},methods:g.prepared.methods,parameters:g.prepared.selection,verification:'python_independent_exact'};
     let projection=await deps.desktop.startAnalysis({contract_version:'2.0',command_id:randomUUID(),...g.prepared.owner,expected_row_version:p.revision!.row_version,confirmation_id:plan.confirmation_id,execution_plan:plan});const run=projection.runs.at(-1)!;c.run=run.run_id;
     while(projection.runs.find(r=>r.run_id===run.run_id)?.status==='Running'){await new Promise(resolve=>setTimeout(resolve,25));if(clock().getTime()-runStarted>=g.profile.run_ms){await stop(id);fail('DEADLINE_EXCEEDED');}await guard(id,g,c);projection=await deps.desktop.waitForProjection({...g.prepared.owner,projection_token:projection.projection_token});}
     c.run=undefined;if(projection.runs.find(r=>r.run_id===run.run_id)?.status!=='Succeeded')fail('CALCULATION_FAILED');
     await mutate(id,{usage:{...runUsage,status:'settled',active_ms:Math.min(g.profile.run_ms,Math.max(0,clock().getTime()-runStarted))}});
    }catch(error){await mutate(id,{usage:runIssued?{...runUsage,status:'unresolved'}:{...runUsage,status:'settled',active_ms:0,local_runs:0}});throw error;}
   }
  }catch(error){const code=String((error as {code?:string}).code??'PROVIDER_FAILED');if(clock().getTime()>=Date.parse(g.expires_at)&&(await deps.store.read(id)).grants.some(x=>x.id===g.id&&!x.revoked_at))await stop(id);const state=await deps.store.read(id);const fenced=state.epoch!==g.epoch;await update({status:fenced?(state.status==='interrupted'?'interrupted':'stopped'):'failed',ended_at:clock().toISOString(),error:code});if(!fenced)await mutate(id,{status:'idle'});
  }finally{clearTimeout(c.waitTimer);c.release();if(active.get(id)===c)active.delete(id);}
 }
 async function continueTask(id:string,commentId?:string){
  if(pendingFences.has(id))fail('RESULT_PENDING');
  if(active.has(id))fail('MODEL_BUSY');const t=await read(id),g=t.grants.at(-1);if(g&&!g.revoked_at&&Date.parse(g.expires_at)<=clock().getTime()){await stop(id);fail('AUTHORITY_REQUIRED');}if(!g||g.revoked_at||g.epoch!==t.epoch||['closed','stopped','interrupted'].includes(t.status)||Date.parse(g.expires_at)<=clock().getTime())fail('AUTHORITY_REQUIRED');
  if(!profile||profile.activation!=='synthetic_only'||encodeTask(profile)!==encodeTask(g.profile)||!deps.runtime||!deps.modelAccess)fail('AUTHORITY_REQUIRED');
  const comment=commentId?t.comments.find(c=>c.id===commentId):undefined;if(commentId&&(!comment||!comment.text_consent||comment.result_report_id||comment.report_id!==t.case.revision?.current_report_id))fail('AUTHORITY_REQUIRED');if(comment){protectedText(comment.text,g,await source(id,g));outbound(payloadFor(g.prepared,comment.text));}
  if(comment?.resolution?.intent==='expression'){const original=t.attempts.findLast(a=>a.comment_id===comment.id);if(!original||original.status==='running'||original.status==='waiting')fail('MODEL_BUSY');await source(id,g);await mutate(id,{expression:{comment_id:comment.id,attempt_id:original.id,grant_id:g.id,epoch:g.epoch,text:comment.resolution.text,at:clock().toISOString()}});return read(id);}
  const lease=await deps.modelAccess.acquire(deps.modelAccess.snapshot().generation,{session_id:t.owner.session_id,label:'会员分析'});const c:Control={abort:new AbortController(),release:lease.release,done:Promise.resolve()};active.set(id,c);
  try{await guard(id,g,c);await source(id,g);const attempt:TaskAttempt={version:'1.0',id:randomUUID(),grant_id:g.id,epoch:g.epoch,status:'running',phase:'planning',started_at:clock().toISOString(),ended_at:null,error:null,...(comment?{comment_id:comment.id}:{})};await mutate(id,{attempt,status:'running'});if(comment)await append(id,attempt,g,'consented_text',comment.text);c.done=execute(id,attempt,g,c);void c.done.catch(()=>undefined);return read(id);}catch(error){c.release();active.delete(id);throw error;}
 }
 async function stop(id:string,status:'stopped'|'closed'|'interrupted'='stopped'){
  pendingFences.set(id,status);
  const c=active.get(id);if(c){c.reason='INTERRUPTED';c.abort.abort();c.resume?.();}
  const state=await deps.store.commit(id,null,{fence:{status,at:clock().toISOString()}});pendingFences.delete(id);const p=await deps.desktop.readProjection(state.owner);for(const r of p.runs.filter(r=>r.status==='Running'))await deps.desktop.cancelAnalysis({contract_version:'1.0',command_id:randomUUID(),...state.owner,expected_row_version:p.revision!.row_version,run_id:r.run_id});return read(id);
 }
 async function reopen(){for(const t of await deps.store.list(deps.project_id)){if(t.review_receipts.some(r=>r.outcome!=='more_evidence')){for(const g of t.grants.filter(g=>g.retained&&!g.revoked_at)){await mutate(t.task_id,{retained:{revoke:{grant_id:g.id,at:clock().toISOString()}}});}for(const u of t.usage.filter(u=>['reserved','issued'].includes(u.status)))await mutate(t.task_id,{retained:{usage:{...u,status:'unresolved'}}});for(const a of t.attempts.filter(a=>['running','waiting'].includes(a.status)))await mutate(t.task_id,{retained:{attempt:{...a,status:'interrupted',ended_at:clock().toISOString(),error:'INTERRUPTED'}}});continue;}await stop(t.task_id,'interrupted');for(const u of t.usage.filter(u=>['reserved','issued'].includes(u.status)))await mutate(t.task_id,{usage:{...u,status:'unresolved'}});for(const a of t.attempts.filter(a=>['running','waiting'].includes(a.status)))await mutate(t.task_id,{attempt:{...a,status:'interrupted',ended_at:clock().toISOString(),error:'INTERRUPTED'}});}}
 async function reply(id:string,text:string,consent:boolean){const c=active.get(id),t=await read(id),a=t.attempts.at(-1),g=t.grants.at(-1);if(!c?.resume||!a||a.status!=='waiting'||!g||typeof text!=='string'||!text.trim()||typeof consent!=='boolean')fail('FORBIDDEN');await guard(id,g,c);if(consent){protectedText(text,g,await source(id,g));outbound(payloadFor(g.prepared,text));await append(id,a,g,'consented_text',text);c.reply=text;}else{await append(id,a,g,'local_text',text);c.reply=null;}c.resume();return read(id);}

 async function submitReview(id:string,input:unknown){if(pendingReviews.has(id))fail('RESULT_PENDING');const x=closed(input,['review_id','review_version','review_sha256','intent_id','outcome','confirmed']);if(x.confirmed!==true)fail('AUTHORITY_REQUIRED');if(active.has(id)||pendingFences.has(id))fail('MODEL_BUSY');const p=await read(id),r=p.reviews.find(r=>r.id===x.review_id&&r.sequence===x.review_version);if(!r)fail('STALE_REVIEW');if(!p.review_receipts.some(v=>v.intent_id===x.intent_id)&&await deps.store.formalHead(p.owner)!==r.baseline_decision_id)fail('STALE_DECISION');const {confirmed,...command}=x;let submitted=false;try{await deps.store.submitReview({...command,task_id:id,at:clock().toISOString()} as ReviewSubmission);submitted=true;return await read(id);}catch(error){if(submitted||(error as {code?:string}).code==='RESULT_PENDING'){pendingReviews.add(id);fail('RESULT_PENDING');}throw error;}}
 async function openReview(id:string){const p=await read(id),report=p.case.reports.find(r=>r.report_id===p.case.revision?.current_report_id),finding=p.case.findings.find(f=>f.finding_id===report?.finding_id);if(!report||!finding||!p.case.revision||p.case.revision.integrity_state!=='ok'||report.state!=='draft')fail('RESULT_REQUIRED');const provenance=JSON.parse(report.source);if(typeof provenance.plan_sha256!=='string')fail('SOURCE_CHANGED');const source:ReviewSource={owner:p.owner,case_row_version:p.case.revision.row_version,finding_id:finding.finding_id,run_id:finding.run_id,plan_sha256:provenance.plan_sha256,report_id:report.report_id,report_version:report.version_sequence,report_sha256:report.markdown_sha256},baseline_decision_id=await deps.store.formalHead(p.owner);const existing=p.reviews.findLast(r=>encodeTask(r.source)===encodeTask(source)&&r.baseline_decision_id===baseline_decision_id);if(existing)return p;
  const carry=p.reviews.findLast(r=>r.source.owner.revision_id===source.owner.revision_id&&r.source.finding_id===source.finding_id&&r.source.run_id===source.run_id&&r.source.plan_sha256===source.plan_sha256&&r.baseline_decision_id===baseline_decision_id);
  const body:Omit<MembershipReview,'sha256'>={version:'1.0',id:carry?.id??randomUUID(),sequence:(carry?.sequence??0)+1,task_id:id,source,baseline_decision_id,intent_id:randomUUID(),fields:carry?structuredClone(carry.fields):{actor:'',questions:'',closure:{kind:'decision_closure',candidates:[],route:null,insufficient_reason:null,preferred_candidate_id:null,preferred_reason:null,disposition:'draft',defer_until:null},decision:null},created_at:clock().toISOString()};await mutate(id,{review:validateReview({...body,sha256:taskHash(body)})});return read(id);}
 async function saveReview(id:string,reviewId:string,sequence:number,sha256:string,fields:unknown){const p=await read(id),prior=p.reviews.filter(r=>r.id===reviewId).at(-1);if(!prior||prior.sequence!==sequence||prior.sha256!==sha256)fail('STALE_REVIEW');if(await deps.store.formalHead(p.owner)!==prior.baseline_decision_id)fail('STALE_DECISION');const {sha256:oldHash,...body}=prior;const updated={...body,sequence:sequence+1,intent_id:randomUUID(),fields:reviewFields(fields,prior.source),created_at:clock().toISOString()};await mutate(id,{review:validateReview({...updated,sha256:taskHash(updated)})});return read(id);}
 async function previewPeriods(id:string,input:unknown){const p=await read(id),after=taskPeriods(input),prepared=p.prepared;if(!prepared||!p.case.confirmation||!deps.sourceStore||p.case.revision?.integrity_state!=='ok')fail('SOURCE_REQUIRED');const snapshot=await deps.sourceStore.readConfirmedSnapshot({...p.owner,confirmation_id:p.case.confirmation.confirmation_id});for(const role of ['members','orders'] as const)if(snapshot.snapshot[role].sha256!==prepared.sources[role].sha256)fail('SOURCE_CHANGED');const qualified=prepareDesktopData({members_bytes:snapshot.snapshot.members.bytes,orders_bytes:snapshot.snapshot.orders.bytes},{...prepared.selection,...after});const before={comparison_period:prepared.selection.comparison_period,current_period:prepared.selection.current_period},changed=encodeTask(before)!==encodeTask(after),config_version=changed?String(p.configurations.filter(c=>c.scenario.id===prepared.scenario.id).reduce((max,c)=>BigInt(c.scenario.revision)>max?BigInt(c.scenario.revision):max,BigInt(prepared.scenario.revision))+1n):prepared.scenario.revision;
  const body={before,after,changed,config_version,issue_treatments:qualified.reviewable_issues.map(x=>({code:x.code,count:x.count,treatment:x.treatment_options[0]})),invalidated:changed?['原范围授权','当前计划与结果对新期间的适用性','待审报告与未提交的人审建议']:[]};const period_preview:PeriodPreview={...body,sha256:membershipHash({task_id:id,row_version:String(p.row_version),preparation:prepared.fingerprint,report_id:p.case.revision.current_report_id,...body})};return {projection:p,period_preview};}
 async function applyPeriods(id:string,input:unknown,previewHash:string,confirmed:boolean){const result=await previewPeriods(id,input);if(result.period_preview.sha256!==previewHash)fail('SOURCE_CHANGED');if(!result.period_preview.changed)return {...result,period_preview:{...result.period_preview,outcome:'NO_CHANGE' as const}};if(confirmed!==true)fail('AUTHORITY_REQUIRED');if(active.has(id))fail('MODEL_BUSY');const p=result.projection,s=await deps.sourceStore!.readConfirmedSnapshot({...p.owner,confirmation_id:p.case.confirmation!.confirmation_id}),selection={...p.prepared!.selection,...result.period_preview.after},qualified=prepareDesktopData({members_bytes:s.snapshot.members.bytes,orders_bytes:s.snapshot.orders.bytes},selection),revision_id=randomUUID();const {fingerprint,...original}=p.prepared!;const body={...original,owner:{...p.owner,revision_id},selection,scenario:{...original.scenario,revision:result.period_preview.config_version},issue_treatments:qualified.reviewable_issues.map(x=>({code:x.code,count:x.count,treatment:x.treatment_options[0]}))};const prepared=validatePrepared({...body,fingerprint:preparedIdentity(body)});const fenced=await stop(id);if(fenced.owner.revision_id!==p.owner.revision_id)fail('SOURCE_CHANGED');await deps.store.commit(id,fenced.row_version,{scope:{revision_id,expected_revision_id:p.owner.revision_id,expected_case_version:p.case.revision!.row_version,at:clock().toISOString()},prepared});return {projection:await read(id),period_preview:{...result.period_preview,outcome:'PREPARED' as const}};}
 async function comment(id:string,input:unknown){const c=commentInput(input),p=await read(id),report=p.case.reports.find(r=>r.report_id===c.report_id);if(!report||p.case.revision?.current_report_id!==c.report_id||report.markdown_sha256!==c.report_sha256||report.version_sequence!==c.report_version||p.case.revision.integrity_state!=='ok')fail('SOURCE_CHANGED');const prior=p.comments.find(x=>x.id===c.id);if(prior){const {version,task_id,created_at,result_report_id,resolution,...body}=prior;if(encodeTask(body)!==encodeTask(c))fail('COMMAND_CONFLICT');return p;}await mutate(id,{comment:{...c,version:'1.0',task_id:id,created_at:clock().toISOString(),result_report_id:null}});return read(id);}
 return {submitReview,openReview,saveReview,previewPeriods,applyPeriods,comment,processComment:(id:string,commentId:string)=>continueTask(id,commentId),read,inspect,prepare,inspectConfig,prepareConfig,authorize,async authorizationSources(id:string){const t=await read(id);if(!deps.sourceStore)fail('SOURCE_REQUIRED');const owner=t.case.confirmation?t.owner:t.grants.at(-1)?.prepared.owner;if(!owner)fail('SOURCE_REQUIRED');const prior=t.case.confirmation?t.case:await deps.desktop.readProjection(owner);if(!prior.confirmation)fail('SOURCE_REQUIRED');const s=await deps.sourceStore.readConfirmedSnapshot({...owner,confirmation_id:prior.confirmation.confirmation_id});for(const role of ['members','orders'] as const)if(s.snapshot[role].sha256!==t.prepared?.sources[role].sha256)fail('SOURCE_CHANGED');return {members:{display_name:s.snapshot.members.display_name,bytes:s.snapshot.members.bytes},orders:{display_name:s.snapshot.orders.display_name,bytes:s.snapshot.orders.bytes}};},continue:continueTask,stop,reopen,reply,hasWork:()=>active.size>0,async close(){for(const t of await deps.store.list(deps.project_id))await stop(t.task_id,'closed');},async wait(id:string){await active.get(id)?.done;return read(id);},async list(){return Promise.all((await deps.store.list(deps.project_id)).map(s=>read(s.task_id)));},async create(question:string,command_id:string){const p=await deps.desktop.createSession({contract_version:'1.0',command_id,project_id:deps.project_id,display_name:question,case_name:question,fields:{question_text:question,hypothesis_display_title:'当前期复购率低于对比期',business_context:'',alternative_explanations:[]}});const owner={project_id:deps.project_id,session_id:p.session!.session_id,case_id:p.session!.case_id,revision_id:p.revision!.revision_id};const task=await deps.store.create(owner,command_id);return read(task.task_id);}};
}

function payloadFor(p:PreparedTask,selected_text:string|null){return outbound({version:'1.0',source_sha256:p.fingerprint,methods:p.methods,semantics:{metric:'membership_repurchase_comparison',currency:'CNY',time_zone:'Asia/Shanghai',comparison_period:p.selection.comparison_period,current_period:p.selection.current_period,status_meanings:'explicitly_confirmed_local'},preparation:p.counts,selected_text,result:null,tool_result:'prepared'});}
