import type {MemberModelAttempt} from '../../packages/ports/member-model.ts';
import type {DatabaseSync,SQLOutputValue} from 'node:sqlite';
import {membershipRecord as closed,membershipUuid,membershipBytesHash} from '../../packages/product-core/member-analysis.ts';
import {taskHash,fail} from '../../packages/product-core/member-task.ts';
import {operationDigest} from '../../packages/product-core/member-operation.ts';
import {membershipMaterialText} from '../../packages/product-core/member-model.ts';
export const memberClarificationSchema=`CREATE TABLE membership_clarifications (id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES membership_tasks(task_id),command_id TEXT NOT NULL UNIQUE,question_execution_id TEXT NOT NULL UNIQUE REFERENCES membership_model_attempts(execution_id),body_json TEXT NOT NULL,body_sha256 TEXT NOT NULL UNIQUE);`;
export function readMemberClarifications(db:DatabaseSync,sha:string,context?:{task_id:string;revision_id:string;epoch:number;source_set_id:string|null;source_set_sha256:string|null}){
 const chain:{sha256:string;reply:string}[]=[],seen=new Set<string>();let next:string|null=sha;
 while(next!==null){if(seen.has(next)||seen.size>=32)fail('INTEGRITY_BLOCKED');seen.add(next);const row:Record<string,SQLOutputValue>|undefined=db.prepare('SELECT * FROM membership_clarifications WHERE body_sha256=?').get(next);if(!row)fail('SOURCE_CHANGED');const b=closed(JSON.parse(String(row.body_json)),['version','id','task_id','revision_id','epoch','source_set_id','source_set_sha256','question_execution_id','question_result_sha256','original_question_sha256','predecessor_sha256','reply','command_id','input_sha256','grant_id']);
 if(b.version!=='1.0'||![b.id,b.task_id,b.revision_id,b.question_execution_id,b.command_id,b.grant_id].every(membershipUuid)||![b.question_result_sha256,b.original_question_sha256,b.input_sha256].every(operationDigest)||!Number.isSafeInteger(b.epoch)||b.predecessor_sha256!==null&&!operationDigest(b.predecessor_sha256)||b.source_set_id!==null&&!membershipUuid(b.source_set_id)||b.source_set_sha256!==null&&!operationDigest(b.source_set_sha256)||taskHash(b)!==next||b.id!==row.id||b.task_id!==row.task_id||b.command_id!==row.command_id||b.question_execution_id!==row.question_execution_id)fail('INTEGRITY_BLOCKED');membershipMaterialText(b.reply);
 const arow:Record<string,SQLOutputValue>|undefined=db.prepare('SELECT body_json FROM membership_model_attempts WHERE execution_id=?').get(String(b.question_execution_id)),a:MemberModelAttempt|null=arow?JSON.parse(String(arow.body_json)):null,r=db.prepare('SELECT question_text FROM case_revisions WHERE revision_id=?').get(String(b.revision_id));if(!a||a.status!=='succeeded'||a.result?.output.kind!=='question'||taskHash(a.result)!==b.question_result_sha256||a.context.task_id!==b.task_id||a.context.epoch!==b.epoch||a.source_set_id!==b.source_set_id||a.payload.source_set_sha256!==b.source_set_sha256||!r||membershipBytesHash(Buffer.from(String(r.question_text)))!==b.original_question_sha256)fail('INTEGRITY_BLOCKED');
 const grant=db.prepare('SELECT body_json FROM membership_model_grants WHERE grant_id=? AND task_id=?').get(String(b.grant_id),String(b.task_id)),g=grant?JSON.parse(String(grant.body_json)):null;if(!g||g.clarification_sha256!==next||(a.payload.clarifications?.at(-1)?.sha256??null)!==b.predecessor_sha256)fail('INTEGRITY_BLOCKED');
 if(context&&Object.entries(context).some(([k,v])=>(k!=='epoch'||seen.size===1)&&b[k]!==v))fail('SOURCE_CHANGED');chain.unshift({sha256:next,reply:String(b.reply)});next=b.predecessor_sha256===null?null:String(b.predecessor_sha256);
 }return chain;
}

/** Resolve only a Store-recorded renewal lineage; old grants are provenance, never authority. */
export function readGrantClarifications(db:DatabaseSync,g:Record<string,unknown>,seen=new Set<string>()):{sha256:string;reply:string}[]|null{
 const id=String(g.grant_id);if(seen.has(id)||seen.size>=32)fail('INTEGRITY_BLOCKED');seen.add(id);
 if(Object.hasOwn(g,'reuse')){
  const reuse=closed(g.reuse,['version','predecessor_grant_id','clarification_sha256','preparation_execution_id','run_id']);
  if(reuse.version!=='1.0'||!membershipUuid(reuse.predecessor_grant_id)||reuse.clarification_sha256!==null&&!operationDigest(reuse.clarification_sha256)||reuse.preparation_execution_id!==null&&!membershipUuid(reuse.preparation_execution_id)||reuse.run_id!==null&&(typeof reuse.run_id!=='string'||! /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(reuse.run_id)))fail('INTEGRITY_BLOCKED');
  const row=db.prepare('SELECT body_json,body_sha256 FROM membership_model_grants WHERE grant_id=? AND task_id=?').get(String(reuse.predecessor_grant_id),String(g.task_id));if(!row)fail('INTEGRITY_BLOCKED');const prior=JSON.parse(String(row.body_json));
  if(taskHash(prior)!==row.body_sha256||prior.grant_id!==reuse.predecessor_grant_id||!['task_id','revision_id','source_set_id','source_set_sha256','selected_text'].every(k=>prior[k]===g[k])||Number(prior.epoch)>Number(g.epoch)||reuse.clarification_sha256!==(g.clarification_sha256??null)||reuse.clarification_sha256!==(prior.clarification_sha256??null))fail('INTEGRITY_BLOCKED');
  const inherited=readGrantClarifications(db,prior,seen);
  if(reuse.preparation_execution_id!==null){const p=db.prepare('SELECT p.body_json,u.phase,u.outcome,u.grant_id FROM membership_preparations p JOIN membership_operation_usage u ON u.execution_id=p.execution_id WHERE p.execution_id=? AND p.task_id=?').get(String(reuse.preparation_execution_id),String(g.task_id)),body=p?JSON.parse(String(p.body_json)):null;if(!p||p.phase!=='settled'||p.outcome!=='succeeded'||body.source_set_id!==g.source_set_id||body.source_set_sha256!==g.source_set_sha256||body.owner.revision_id!==g.revision_id||p.grant_id!==prior.grant_id&&prior.reuse?.preparation_execution_id!==reuse.preparation_execution_id)fail('INTEGRITY_BLOCKED');}
  if(reuse.run_id!==null){const r=db.prepare("SELECT r.status,p.body_json FROM analysis_runs r JOIN membership_run_plans rp ON rp.run_id=r.run_id JOIN membership_plans p ON p.plan_id=rp.plan_id WHERE r.run_id=? AND r.run_contract_version='5.0'").get(String(reuse.run_id)),plan=r?JSON.parse(String(r.body_json)):null;if(!r||r.status!=='Succeeded'||plan.authority.task_id!==g.task_id||plan.preparation.execution_id!==reuse.preparation_execution_id||plan.authority.grant_id!==prior.grant_id&&prior.reuse?.run_id!==reuse.run_id)fail('INTEGRITY_BLOCKED');}

  return inherited;
 }
 return g.clarification_sha256?readMemberClarifications(db,String(g.clarification_sha256),{task_id:String(g.task_id),revision_id:String(g.revision_id),epoch:Number(g.epoch),source_set_id:g.source_set_id===null?null:String(g.source_set_id),source_set_sha256:g.source_set_sha256===null?null:String(g.source_set_sha256)}):null;
}
