import {memberModelMethods} from './member-model.ts';
import {validateReview,validateReviewReceipt,validateReviewDecision,type ReviewReceipt,type MembershipReview} from '../../packages/product-core/member-review.ts';
import {createLocalCaseAssistantStore} from './case-assistant.ts';
import {randomUUID,createHash} from 'node:crypto';
const membershipHashBytes=(s:string)=>createHash('sha256').update(s).digest('hex');
import type {DatabaseSync} from 'node:sqlite';
import {withMembershipState,withBrowserMembershipState,membershipReviewPlan,appendMembershipExpression,appendMembershipRevision,appendMembershipReview} from './desktop-state.ts';
import {memberOperationMethods,fenceMemberOperations} from './member-operation.ts';
import {browserMembershipMethods} from './browser-membership.ts';
import {memberSourceMethods} from './member-source-store.ts';
import {decoded} from './member-task-codec.ts';
import {membershipHash,membershipUuid,membershipRecord} from '../../packages/product-core/member-analysis.ts';
import {taskHash,fail,encodeTask,resourceProfile,validatePrepared,validateComment,commentResolution,reserveWithin,outbound,type TaskState,type ReusableConfiguration,type TaskGrant,type TaskAttempt,type TaskUsage,type TaskEvent,type TaskComment} from '../../packages/product-core/member-task.ts';
import type {MembershipTaskStore,TaskMutation} from '../../packages/ports/member-task.ts';
import type {OwnerRef} from '../../packages/contracts/xanthil-desktop-ipc.ts';
function read(db:DatabaseSync,id:string):TaskState{
 const task=db.prepare('SELECT * FROM membership_tasks WHERE task_id=?').get(id);if(!task)fail('NOT_FOUND');
 const rows=<T>(table:string)=>db.prepare(`SELECT * FROM ${table} WHERE task_id=? ORDER BY rowid`).all(id).map(r=>decoded<T>(r));
 const prep=db.prepare("SELECT result_json FROM membership_receipts WHERE task_id=? AND json_extract(result_json,'$.kind')='prepared' ORDER BY rowid DESC LIMIT 1").get(id);
 return {task_id:id,owner:{project_id:String(task.project_id),session_id:String(task.session_id),case_id:String(task.case_id),revision_id:String(task.current_revision_id)},row_version:Number(task.row_version),epoch:Number(task.epoch),status:task.status as TaskState['status'],prepared:prep?JSON.parse(String(prep.result_json)).prepared:null,grants:rows<TaskGrant>('membership_grants'),attempts:rows<TaskAttempt>('membership_attempts'),usage:rows<TaskUsage>('membership_usage'),events:rows<TaskEvent>('membership_events'),comments:rows<TaskComment>('membership_comments'),reviews:rows<MembershipReview>('membership_reviews'),review_receipts:db.prepare("SELECT result_json FROM membership_receipts WHERE task_id=? AND json_extract(result_json,'$.kind')='human_review' ORDER BY rowid").all(id).map(r=>JSON.parse(String(r.result_json)))};
}
function configurations(db:DatabaseSync):ReusableConfiguration[]{
 if(db.prepare('PRAGMA user_version').get()?.user_version===100)return [];
 const result=new Map<string,ReusableConfiguration>();
 for(const row of db.prepare("SELECT result_json FROM membership_receipts WHERE json_extract(result_json,'$.kind')='prepared' ORDER BY rowid").all()){
  const p=validatePrepared(JSON.parse(String(row.result_json)).prepared),key=p.scenario.id+':'+p.scenario.revision;
  const config=db.prepare('SELECT body_sha256 FROM membership_configs WHERE config_id=? AND version=?').get(p.scenario.id,p.scenario.revision);
  // Earlier Stage A preparation receipts remain readable; new preparation registers
  // the version before advertising it for reuse.
  if(!config)continue;
  if(config.body_sha256!==membershipHash(p.scenario))fail('INTEGRITY_BLOCKED');
  const body={scenario:p.scenario,selection:p.selection,methods:p.methods},value={...body,sha256:taskHash(body)};
  if(!result.has(key))result.set(key,value);
 }
 return [...result.values()];
}
export function createLocalMembershipTaskStore(projectRoot:string,options:{formalFault?:(point:string,db:DatabaseSync)=>void}={}):MembershipTaskStore&ReturnType<typeof memberModelMethods>&ReturnType<typeof memberOperationMethods>&ReturnType<typeof browserMembershipMethods>&ReturnType<typeof memberSourceMethods>{
 const access=<T>(write:boolean,fn:(db:DatabaseSync)=>T)=>withMembershipState(projectRoot,write,fn);
 async function checkedRead(id:string){const state=access(false,db=>read(db,id));
  for(const r of state.review_receipts.filter(r=>r.outcome==='choice')){const review=state.reviews.find(v=>v.id===r.review_id&&v.sequence===r.review_version);if(!review)fail('INTEGRITY_BLOCKED');const history=await createLocalCaseAssistantStore({projectRoot}).formalHistory(review.source.owner),formal=history.decisions.find(d=>d.id===r.decision_id),report=history.reports.find(v=>v.id===r.report_id);if(!formal||!report||formal.origin?.intent_id!==r.intent_id||formal.origin.task_id!==id||formal.origin.review_id!==r.review_id||formal.origin.review_version!==r.review_version||formal.outcome_id!==r.expected_id||formal.report_id!==r.report_id||report.decision_id!==formal.id||formal.source_report_id!==review.source.report_id||formal.actor!==review.fields.actor||formal.adopted_at!==r.at||encodeTask(formal.source)!==encodeTask(review.source.owner))fail('INTEGRITY_BLOCKED');
   access(false,db=>{const finding=db.prepare('SELECT * FROM findings WHERE finding_id=?').get(review.source.finding_id);if(!finding||encodeTask(formal.fields)!==encodeTask(validateReviewDecision(review.fields.decision,{evidence_refs:JSON.parse(String(finding.evidence_refs_json)),finding_id:review.source.finding_id,candidates:review.fields.closure.candidates})))fail('INTEGRITY_BLOCKED');const row=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(r.report_id!);if(!row||row.markdown_sha256!==report.markdown_sha256||row.html_sha256!==report.html_sha256||membershipHashBytes(report.markdown)!==report.markdown_sha256||membershipHashBytes(report.html)!==report.html_sha256)fail('INTEGRITY_BLOCKED');});
  }return state;
 }

 return {
 async reviewPlan(taskId,runId){return access(false,db=>membershipReviewPlan(db,taskId,runId));},
 ...memberModelMethods(projectRoot,(write,work)=>withBrowserMembershipState(projectRoot,write,work)),
 ...memberOperationMethods((write,work)=>withBrowserMembershipState(projectRoot,write,work)),
 ...memberSourceMethods(projectRoot,(write,work)=>withBrowserMembershipState(projectRoot,write,work),options.formalFault),
 ...browserMembershipMethods((write,work)=>withBrowserMembershipState(projectRoot,write,work),read,projectRoot),
 async submitReview(input){const identity=await checkedRead(input.task_id);if(input.outcome==='choice'){const review=identity.reviews.find(r=>r.id===input.review_id&&r.sequence===input.review_version);if(review&&access(false,db=>membershipReviewPlan(db,input.task_id,review.source.run_id)).version==='2.0')fail('FORBIDDEN');}return withMembershipState(projectRoot,true,db=>{const old=read(db,input.task_id),prior=old.review_receipts.find(r=>r.intent_id===input.intent_id);if(prior){if(prior.review_id!==input.review_id||prior.review_version!==input.review_version||prior.review_sha256!==input.review_sha256||prior.outcome!==input.outcome)fail('COMMAND_CONFLICT');return old;}const r=old.reviews.filter(r=>r.id===input.review_id).at(-1);if(!r||r.sequence!==input.review_version||r.sha256!==input.review_sha256||r.intent_id!==input.intent_id)fail('STALE_REVIEW');const revision=db.prepare('SELECT * FROM case_revisions WHERE revision_id=?').get(old.owner.revision_id);if(!revision||revision.current_report_id!==r.source.report_id||String(revision.row_version)!==r.source.case_row_version||revision.integrity_state!=='ok'||!r.fields.actor.trim())fail('SOURCE_CHANGED');if(old.attempts.some(a=>['running','waiting'].includes(a.status)))fail('MODEL_BUSY');const plan=membershipReviewPlan(db,input.task_id,r.source.run_id);if(plan.version==='2.0'&&input.outcome==='choice')fail('FORBIDDEN');if(input.outcome==='more_evidence'&&!r.fields.questions.trim())fail('VALIDATION_FAILED');const receipt:ReviewReceipt=validateReviewReceipt(input.outcome==='more_evidence'?{...input,kind:'human_review',acceptance_id:null,closure_id:null,report_id:null,decision_id:null,expected_id:null}:appendMembershipReview(projectRoot,db,r,input,point=>options.formalFault?.(point,db)));options.formalFault?.('before_receipt',db);db.prepare('INSERT INTO membership_receipts VALUES(?,?,?,?,?,?)').run(input.intent_id,input.task_id,taskHash(receipt),r.id,r.sequence,encodeTask(receipt));options.formalFault?.('after_receipt',db);if(input.outcome!=='more_evidence'){options.formalFault?.('before_task_close',db);if(plan.version==='2.0')fenceMemberOperations(db,input.task_id);for(const g of old.grants.filter(g=>!g.revoked_at)){const revoked={...g,revoked_at:input.at};db.prepare('UPDATE membership_grants SET revoked_at=?,body_json=?,body_sha256=? WHERE grant_id=?').run(input.at,encodeTask(revoked),taskHash(revoked),g.id);}db.prepare("UPDATE membership_tasks SET epoch=epoch+1,status='closed' WHERE task_id=?").run(input.task_id);options.formalFault?.('after_task_close',db);}db.prepare('UPDATE membership_tasks SET row_version=row_version+1 WHERE task_id=?').run(input.task_id);return read(db,input.task_id);},{project_id:identity.owner.project_id,choice:input.outcome==='choice',fault:options.formalFault});},
 async formalHead(owner){return (await createLocalCaseAssistantStore({projectRoot}).formalHistory(owner)).decisions.at(-1)?.id??null;},
 async configurations(){return access(false,configurations);},
 async create(owner:OwnerRef,commandId:string){return access(true,db=>{const old=db.prepare('SELECT task_id FROM membership_receipts WHERE command_id=?').get(commandId);if(old){const prior=read(db,String(old.task_id));if(encodeTask(prior.owner)!==encodeTask(owner))fail('COMMAND_CONFLICT');return prior;}const existing=db.prepare('SELECT task_id FROM membership_tasks WHERE project_id=? AND session_id=? AND case_id=?').get(owner.project_id,owner.session_id,owner.case_id);const id=existing?String(existing.task_id):randomUUID();if(!existing)db.prepare("INSERT INTO membership_tasks VALUES(?,?,?,?,?,1,0,'idle')").run(id,owner.project_id,owner.session_id,owner.case_id,owner.revision_id);const result={kind:'task_created',owner};db.prepare('INSERT INTO membership_receipts VALUES(?,?,?,NULL,NULL,?)').run(commandId,id,taskHash(result),encodeTask(result));return read(db,id);});},
 async read(id){return checkedRead(id);},
 async list(projectId){return access(false,db=>{if(db.prepare('PRAGMA user_version').get()?.user_version===100)return [];return db.prepare('SELECT task_id FROM membership_tasks WHERE project_id=? ORDER BY rowid').all(projectId).map(r=>read(db,String(r.task_id)));});},
 async commit(id,version,m){return access(true,db=>{
  const old=read(db,id);
  if(m.browser_review){const b=membershipRecord(m.browser_review,['command_id','input_sha256','epoch','kind','review_id','review_version','review_sha256']);if(!membershipUuid(b.command_id)||!membershipUuid(b.review_id)||!Number.isSafeInteger(b.epoch)||!Number.isSafeInteger(b.review_version)||Number(b.review_version)<1||!['browser_review_opened','browser_review_saved'].includes(String(b.kind))||![b.input_sha256,b.review_sha256].every(v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v))||Object.keys(m).some(k=>!['review','browser_review'].includes(k)))fail();const prior=db.prepare('SELECT * FROM membership_browser_receipts WHERE command_id=?').get(String(b.command_id));if(prior){const receipt=JSON.parse(String(prior.body_json));if(receipt.task_id!==id||receipt.kind!==b.kind||receipt.input_sha256!==b.input_sha256)fail('COMMAND_CONFLICT');return old;}if(db.prepare('SELECT command_id FROM membership_receipts WHERE command_id=?').get(String(b.command_id))||db.prepare('SELECT command_id FROM membership_source_sets WHERE command_id=?').get(String(b.command_id))||db.prepare('SELECT command_id FROM membership_model_grants WHERE command_id=?').get(String(b.command_id))||db.prepare('SELECT command_id FROM command_receipts WHERE command_id=?').get(String(b.command_id)))fail('COMMAND_CONFLICT');if(old.epoch!==b.epoch||['stopped','closed','interrupted'].includes(old.status))fail('AUTHORITY_REQUIRED');}
  if(version===null&&(!m.fence||Object.keys(m).length!==1))fail('FORBIDDEN');if(version!==null&&old.row_version!==version)fail('STALE_REVISION');
  if(m.retained){
   if(Object.keys(m).length!==1)fail('FORBIDDEN');const v=m.retained;
   const valid=(g:TaskGrant)=>{if(!g.retained||g.revoked_at||g.epoch!==old.epoch||g.prepared.fingerprint!==old.prepared?.fingerprint||Date.now()>=Date.parse(g.expires_at))fail('AUTHORITY_REQUIRED');};
   if(v.grant){const g=v.grant;resourceProfile(g.profile);if(!g.retained||g.task_id!==id||g.epoch!==old.epoch||g.prepared.fingerprint!==old.prepared?.fingerprint||g.profile.activation!=='synthetic_only'||!old.review_receipts.some(r=>r.outcome!=='more_evidence')||old.grants.some(x=>!x.revoked_at)||encodeTask(g.profile)!==encodeTask(old.grants.filter(x=>!x.retained).at(-1)?.profile))fail('AUTHORITY_REQUIRED');valid(g);db.prepare('INSERT INTO membership_grants VALUES(?,?,?,?,?,?,NULL)').run(g.id,id,old.grants.at(-1)?.id??null,g.epoch,encodeTask(g),taskHash(g));}
   const grants=v.grant?[...old.grants,v.grant]:old.grants;
   if(v.attempt){const a=v.attempt,g=grants.find(x=>x.id===a.grant_id),prior=old.attempts.find(x=>x.id===a.id);if(!g?.retained||a.epoch!==g.epoch)fail('AUTHORITY_REQUIRED');if(!prior){valid(g);db.prepare('INSERT INTO membership_attempts VALUES(?,?,?,?,?,?,?)').run(a.id,id,g.id,a.epoch,'issued',encodeTask(a),taskHash(a));}else{if(a.grant_id!==prior.grant_id||a.started_at!==prior.started_at||!['running','waiting'].includes(prior.status))fail('FORBIDDEN');db.prepare('UPDATE membership_attempts SET status=?,body_json=?,body_sha256=? WHERE attempt_id=?').run(a.status==='running'?'issued':a.status==='waiting'?'waiting':'settled',encodeTask(a),taskHash(a),a.id);}}
   if(v.usage){const u=v.usage,a=(v.attempt?[...old.attempts,v.attempt]:old.attempts).find(x=>x.id===u.attempt_id),g=grants.find(x=>x.id===a?.grant_id),prior=old.usage.find(x=>x.id===u.id);if(!g?.retained||u.source_sha256!==g.prepared.fingerprint||u.kind==='analysis')fail('AUTHORITY_REQUIRED');if(!prior){valid(g);if(u.status!=='reserved')fail('FORBIDDEN');reserveWithin(g.profile,old.usage,u);db.prepare('INSERT INTO membership_usage VALUES(?,?,?,?,NULL,?,?,?)').run(u.id,id,g.id,u.attempt_id,u.status,encodeTask(u),taskHash(u));}else{if(u.status==='issued')valid(g);if(!['reserved','issued'].includes(prior.status)||!['issued','settled','unresolved'].includes(u.status)||u.status==='issued'&&prior.status!=='reserved'||u.attempt_id!==prior.attempt_id||u.kind!==prior.kind||u.source_sha256!==prior.source_sha256||u.payload_sha256!==prior.payload_sha256)fail('FORBIDDEN');for(const k of ['calls','output_tokens','active_ms','wait_ms','local_runs'] as const)if(u[k]>prior[k]||u.status==='unresolved'&&u[k]!==prior[k])fail('BUDGET_EXHAUSTED');db.prepare('UPDATE membership_usage SET status=?,body_json=?,body_sha256=? WHERE reservation_id=?').run(u.status,encodeTask(u),taskHash(u),u.id);}}
   if(v.revoke){const g=grants.find(g=>g.id===v.revoke!.grant_id);if(!g?.retained)fail('AUTHORITY_REQUIRED');const next={...g,revoked_at:g.revoked_at??v.revoke.at};db.prepare('UPDATE membership_grants SET revoked_at=?,body_json=?,body_sha256=? WHERE grant_id=?').run(next.revoked_at,encodeTask(next),taskHash(next),g.id);}
   db.prepare('UPDATE membership_tasks SET row_version=row_version+1 WHERE task_id=?').run(id);return read(db,id);
  }
  const mutable=()=>{if(['stopped','closed','interrupted'].includes(old.status))fail('INTERRUPTED');};
  if(m.review){const r=validateReview(m.review);const plan=membershipReviewPlan(db,id,r.source.run_id);if(membershipHash(plan)!==r.source.plan_sha256)fail('SOURCE_CHANGED');const prior=old.reviews.filter(x=>x.id===r.id).at(-1),revision=db.prepare('SELECT * FROM case_revisions WHERE revision_id=?').get(old.owner.revision_id),report=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(r.source.report_id);if(r.task_id!==id||encodeTask(r.source.owner)!==encodeTask(old.owner)||r.sequence!==(prior?.sequence??0)+1||!revision||String(revision.row_version)!==r.source.case_row_version||revision.current_finding_id!==r.source.finding_id||revision.current_report_id!==r.source.report_id||!report||report.markdown_sha256!==r.source.report_sha256)fail('SOURCE_CHANGED');db.prepare('INSERT INTO membership_reviews VALUES(?,?,?,?,?)').run(r.id,r.sequence,id,encodeTask(r),taskHash(r));}
  if(m.browser_review){const b=m.browser_review,r=db.prepare('SELECT body_json FROM membership_reviews WHERE task_id=? AND review_id=? AND version=?').get(id,b.review_id,b.review_version);if(!r)fail('SOURCE_CHANGED');const review=validateReview(JSON.parse(String(r.body_json)));if(review.sha256!==b.review_sha256)fail('SOURCE_CHANGED');membershipReviewPlan(db,id,review.source.run_id);const {epoch,...identity}=b;void epoch;const receipt={version:'1.0',...identity,task_id:id};options.formalFault?.('before_browser_review_receipt',db);db.prepare('INSERT INTO membership_browser_receipts VALUES(?,?,?,?)').run(b.command_id,id,encodeTask(receipt),taskHash(receipt));options.formalFault?.('after_browser_review_receipt',db);}
  if(m.scope){if(!m.prepared||m.prepared.owner.revision_id!==m.scope.revision_id||m.scope.expected_revision_id!==old.owner.revision_id||old.grants.some(g=>!g.revoked_at)||old.attempts.some(a=>['running','waiting'].includes(a.status)))fail('AUTHORITY_REQUIRED');appendMembershipRevision(db,id,m.scope);old.owner={...old.owner,revision_id:m.scope.revision_id};}
  if(m.commentResolution){const value=m.commentResolution,c=old.comments.find(c=>c.id===value.comment_id),a=old.attempts.find(a=>a.id===value.attempt_id),g=old.grants.find(g=>g.id===a?.grant_id);if(!c||!a||!g||!c.text_consent||c.result_report_id||a.comment_id!==c.id||a.status!=='running'||g.revoked_at||g.epoch!==old.epoch)fail('INTERRUPTED');const updated={...c,resolution:commentResolution(value.resolution)};db.prepare('UPDATE membership_comments SET body_json=?,body_sha256=? WHERE comment_id=?').run(encodeTask(updated),taskHash(updated),c.id);}
  if(m.expression)appendMembershipExpression(projectRoot,db,id,m.expression);
  if(m.comment){const c=validateComment(m.comment),r=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(c.report_id),revision=db.prepare('SELECT current_report_id FROM case_revisions WHERE revision_id=?').get(old.owner.revision_id);if(c.task_id!==id||!r||r.case_id!==old.owner.case_id||r.revision_id!==old.owner.revision_id||r.markdown_sha256!==c.report_sha256||String(r.version_sequence)!==c.report_version||revision?.current_report_id!==c.report_id||c.result_report_id!==null)fail('SOURCE_CHANGED');const prior=old.comments.find(x=>x.id===c.id);if(prior){if(encodeTask(prior)!==encodeTask(c))fail('COMMAND_CONFLICT');}else db.prepare('INSERT INTO membership_comments VALUES(?,?,?,?,?,?)').run(c.id,id,c.report_id,c.report_sha256,encodeTask(c),taskHash(c));}
  if(m.prepared){validatePrepared(m.prepared);
   const p=m.prepared,oldConfig=db.prepare('SELECT body_sha256 FROM membership_configs WHERE config_id=? AND version=?').get(p.scenario.id,p.scenario.revision);
   const prior=configurations(db).find(c=>c.scenario.id===p.scenario.id&&c.scenario.revision===p.scenario.revision);
   if(oldConfig&&oldConfig.body_sha256!==membershipHash(p.scenario)||prior&&prior.sha256!==taskHash({scenario:p.scenario,selection:p.selection,methods:p.methods}))fail('CONFIGURATION_CHANGED');
   if(!oldConfig)db.prepare('INSERT INTO membership_configs VALUES(?,?,?,?)').run(p.scenario.id,p.scenario.revision,encodeTask(p.scenario),membershipHash(p.scenario));
if(old.attempts.some(a=>['running','waiting'].includes(a.status)))fail('BUSY');if(old.grants.some(g=>!g.revoked_at))fail('AUTHORITY_REQUIRED');if(encodeTask(old.owner)!==encodeTask(m.prepared.owner))fail('SOURCE_CHANGED');const r={kind:'prepared',prepared:m.prepared};db.prepare('INSERT INTO membership_receipts VALUES(?,?,?,NULL,NULL,?)').run(randomUUID(),id,taskHash(r),encodeTask(r));}
  if(m.grant){const g=m.grant;if(!old.prepared||g.prepared.fingerprint!==old.prepared.fingerprint||g.epoch!==old.epoch||g.task_id!==id)fail('SOURCE_CHANGED');if(old.grants.some(x=>!x.revoked_at))fail('AUTHORITY_REQUIRED');db.prepare('INSERT INTO membership_grants VALUES(?,?,?,?,?,?,NULL)').run(g.id,id,old.grants.at(-1)?.id??null,g.epoch,encodeTask(g),taskHash(g));}
  if(m.attempt){const a=m.attempt,prior=old.attempts.find(x=>x.id===a.id),grant=old.grants.find(g=>g.id===a.grant_id);if(!grant||a.epoch!==grant.epoch)fail('AUTHORITY_REQUIRED');if(!prior){mutable();if(grant.revoked_at||a.epoch!==old.epoch)fail('INTERRUPTED');db.prepare('INSERT INTO membership_attempts VALUES(?,?,?,?,?,?,?)').run(a.id,id,a.grant_id,a.epoch,a.status==='waiting'?'waiting':'issued',encodeTask(a),taskHash(a));}else{if(a.grant_id!==prior.grant_id||a.epoch!==prior.epoch||a.started_at!==prior.started_at)fail('SOURCE_CHANGED');if(['running','waiting'].includes(a.status)){mutable();if(grant.revoked_at||grant.epoch!==old.epoch)fail('INTERRUPTED');}if(!['running','waiting'].includes(prior.status)&&encodeTask(a)!==encodeTask(prior))fail('FORBIDDEN');db.prepare('UPDATE membership_attempts SET status=?,body_json=?,body_sha256=? WHERE attempt_id=?').run(a.status==='running'?'issued':a.status==='waiting'?'waiting':'settled',encodeTask(a),taskHash(a),a.id);}}
  if(m.usage){const u=m.usage,prior=old.usage.find(x=>x.id===u.id),attempt=(m.attempt?[...old.attempts,m.attempt]:old.attempts).find(a=>a.id===u.attempt_id),grant=old.grants.find(g=>g.id===attempt?.grant_id);if(!attempt||!grant||u.source_sha256!==grant.prepared.fingerprint)fail('AUTHORITY_REQUIRED');if(!prior){if(u.status!=='reserved')fail('FORBIDDEN');mutable();if(grant.revoked_at||grant.epoch!==old.epoch)fail('INTERRUPTED');reserveWithin(grant.profile,old.usage,u);db.prepare('INSERT INTO membership_usage VALUES(?,?,?,?,NULL,?,?,?)').run(u.id,id,grant.id,u.attempt_id,u.status,encodeTask(u),taskHash(u));}else{if(u.status==='issued'){mutable();if(grant.revoked_at||grant.epoch!==old.epoch)fail('INTERRUPTED');}if(['settled','unresolved'].includes(prior.status))fail('FORBIDDEN');if(prior.status==='issued'&&!['settled','unresolved'].includes(u.status)||prior.status==='reserved'&&!['issued','settled','unresolved'].includes(u.status))fail('FORBIDDEN');if(u.attempt_id!==prior.attempt_id||u.kind!==prior.kind||u.source_sha256!==prior.source_sha256||u.payload_sha256!==prior.payload_sha256)fail('SOURCE_CHANGED');for(const k of ['calls','output_tokens','active_ms','wait_ms','local_runs'] as const)if(u[k]>prior[k]||u.status==='unresolved'&&u[k]!==prior[k])fail('BUDGET_EXHAUSTED');db.prepare('UPDATE membership_usage SET status=?,body_json=?,body_sha256=? WHERE reservation_id=?').run(u.status,encodeTask(u),taskHash(u),u.id);}}
  if(m.event){const e=m.event;if(!['status'].includes(e.kind))mutable();const a=old.attempts.find(a=>a.id===e.attempt_id),g=old.grants.find(g=>g.id===a?.grant_id);if(!g||e.source_sha256!==g.prepared.fingerprint||g.revoked_at||g.epoch!==old.epoch)fail('SOURCE_CHANGED');if(e.kind==='outbound'){const p=outbound(JSON.parse(e.text));if(p.source_sha256!==g.prepared.fingerprint)fail('SOURCE_CHANGED');if(p.selected_text!==g.selected_text&&!old.events.some(x=>x.attempt_id===e.attempt_id&&x.kind==='consented_text'&&x.text===p.selected_text)&&p.selected_text!==null)fail('AUTHORITY_REQUIRED');}db.prepare('INSERT INTO membership_events VALUES(?,?,?,?,?)').run(e.id,id,e.attempt_id,encodeTask(e),taskHash(e));}
  if(m.fence){for(const g of old.grants.filter(g=>g.revoked_at===null)){const next={...g,revoked_at:m.fence.at};db.prepare('UPDATE membership_grants SET revoked_at=?,body_json=?,body_sha256=? WHERE grant_id=?').run(m.fence.at,encodeTask(next),taskHash(next),g.id);}fenceMemberOperations(db,id);db.prepare('UPDATE membership_tasks SET epoch=epoch+1,status=? WHERE task_id=?').run(m.fence.status,id);}
  else if(m.status){if(['stopped','closed','interrupted'].includes(old.status)&&!m.grant)fail('INTERRUPTED');db.prepare('UPDATE membership_tasks SET status=? WHERE task_id=?').run(m.status,id);}
  db.prepare('UPDATE membership_tasks SET row_version=row_version+1 WHERE task_id=?').run(id);return read(db,id);
 });}
 };
}
