import {validateReview,validateReviewReceipt,type MembershipReview} from '../../packages/product-core/member-review.ts';
import type {DatabaseSync} from 'node:sqlite';
import {membershipHash,membershipUuid} from '../../packages/product-core/member-analysis.ts';
import {taskHash,closed,fail,validatePrepared,validateComment,resourceProfile,outbound,type TaskGrant,type TaskAttempt,type TaskUsage,type TaskEvent,type TaskComment} from '../../packages/product-core/member-task.ts';
export const decoded=<T>(row:Record<string,unknown>):T=>{const body=JSON.parse(String(row.body_json));if(taskHash(body)!==row.body_sha256)fail('INTEGRITY_BLOCKED');return body as T;};
export function validateTaskRows(db:DatabaseSync){
 const tasks=db.prepare('SELECT * FROM membership_tasks').all(),grants=db.prepare('SELECT * FROM membership_grants').all(),attempts=db.prepare('SELECT * FROM membership_attempts').all();
 for(const row of db.prepare('SELECT * FROM membership_reviews').all()){const r=validateReview(decoded<MembershipReview>(row)),t=tasks.find(t=>t.task_id===r.task_id),report=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(r.source.report_id);if(r.id!==row.review_id||r.sequence!==row.version||r.task_id!==row.task_id||!t||!report||report.case_id!==t.case_id||report.revision_id!==r.source.owner.revision_id||report.markdown_sha256!==r.source.report_sha256||report.finding_id!==r.source.finding_id)fail('INTEGRITY_BLOCKED');}
 for(const row of db.prepare('SELECT * FROM membership_comments').all()){const c=validateComment(decoded<TaskComment>(row)),t=tasks.find(t=>t.task_id===c.task_id),r=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(c.report_id);if(c.id!==row.comment_id||c.task_id!==row.task_id||c.report_id!==row.report_id||c.report_sha256!==row.report_sha256||!t||!r||r.case_id!==t.case_id||r.markdown_sha256!==c.report_sha256||String(r.version_sequence)!==c.report_version)fail('INTEGRITY_BLOCKED');}
 for(const row of db.prepare('SELECT * FROM membership_receipts').all()){const p=JSON.parse(String(row.result_json));if(p.kind==='task_created'){closed(p,['kind','owner']);if(row.fingerprint!==taskHash(p)||!tasks.some(t=>t.task_id===row.task_id&&t.project_id===p.owner.project_id&&t.case_id===p.owner.case_id&&t.session_id===p.owner.session_id))fail('INTEGRITY_BLOCKED');}else if(p.kind==='prepared'){closed(p,['kind','prepared']);validatePrepared(p.prepared);if(row.fingerprint!==taskHash(p)||!tasks.some(t=>t.task_id===row.task_id&&t.project_id===p.prepared.owner.project_id&&t.session_id===p.prepared.owner.session_id&&t.case_id===p.prepared.owner.case_id&&db.prepare('SELECT revision_id FROM case_revisions WHERE revision_id=? AND case_id=?').get(p.prepared.owner.revision_id,p.prepared.owner.case_id)))fail('INTEGRITY_BLOCKED');}else if(p.kind==='human_review'){validateReviewReceipt(p);const rowReview=db.prepare('SELECT * FROM membership_reviews WHERE review_id=? AND version=? AND task_id=?').get(p.review_id,p.review_version,p.task_id);if(!rowReview||decoded<MembershipReview>(rowReview).sha256!==p.review_sha256||p.intent_id!==row.command_id||row.fingerprint!==taskHash(p)||row.review_id!==p.review_id||row.review_version!==p.review_version)fail('INTEGRITY_BLOCKED');}else if(p.kind==='expression_report'){closed(p,['kind','comment_id','parent_report_id','report_id','text','at']);const c=db.prepare('SELECT * FROM membership_comments WHERE comment_id=? AND task_id=?').get(p.comment_id,String(row.task_id)),parent=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(p.parent_report_id),report=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(p.report_id);if(!c||!parent||!report||decoded<TaskComment>(c).result_report_id!==p.report_id||c.report_id!==p.parent_report_id||row.fingerprint!==taskHash(p)||typeof p.text!=='string'||!p.text.trim()||parent.source_json!==report.source_json||parent.evidence_refs_json!==report.evidence_refs_json||parent.finding_id!==report.finding_id||report.state!=='draft'||report.created_at!==p.at||Number(parent.version_sequence)>=Number(report.version_sequence))fail('INTEGRITY_BLOCKED');}else fail('INTEGRITY_BLOCKED');}
 for(const row of grants){const g=decoded<TaskGrant>(row);closed(g,['version','id','task_id','epoch','prepared','profile','selected_text','created_at','expires_at','revoked_at',...(g.retained?['retained']:[])]);if(g.retained){closed(g.retained,['session_id','authorization_id','authorization_sha256','source_sha256','purpose']);if(!membershipUuid(g.retained.session_id)||!membershipUuid(g.retained.authorization_id)||! /^[a-f0-9]{64}$/.test(g.retained.source_sha256)||! /^[a-f0-9]{64}$/.test(g.retained.authorization_sha256)||!['assistant','fork','subagent'].includes(g.retained.purpose))fail('INTEGRITY_BLOCKED');}validatePrepared(g.prepared);resourceProfile(g.profile);if(g.version!=='1.0'||g.id!==row.grant_id||g.task_id!==row.task_id||g.epoch!==row.epoch||g.revoked_at!==row.revoked_at||!tasks.some(t=>t.task_id===g.task_id&&t.project_id===g.prepared.owner.project_id&&t.session_id===g.prepared.owner.session_id&&t.case_id===g.prepared.owner.case_id)||Date.parse(g.expires_at)-Date.parse(g.created_at)!==g.profile.grant_ms)fail('INTEGRITY_BLOCKED');}
 for(const row of attempts){const a=decoded<TaskAttempt>(row);closed(a,['version','id','grant_id','epoch','status','phase','started_at','ended_at','error',...(a.comment_id?['comment_id']:[])]);if(a.comment_id&&!db.prepare('SELECT comment_id FROM membership_comments WHERE comment_id=? AND task_id=?').get(a.comment_id,String(row.task_id)))fail('INTEGRITY_BLOCKED');if(a.version!=='1.0'||a.id!==row.attempt_id||a.grant_id!==row.grant_id||a.epoch!==row.epoch||!['running','waiting','succeeded','failed','stopped','interrupted'].includes(a.status)||!['planning','calculating','explaining'].includes(a.phase)||row.status!==(a.status==='running'?'issued':a.status==='waiting'?'waiting':'settled'))fail('INTEGRITY_BLOCKED');}
 for(const row of db.prepare('SELECT * FROM membership_usage').all()){const u=decoded<TaskUsage>(row);closed(u,['version','id','attempt_id','kind','status','source_sha256','payload_sha256','calls','output_tokens','active_ms','wait_ms','local_runs','at']);if(u.version!=='1.0'||u.id!==row.reservation_id||u.attempt_id!==row.attempt_id||u.status!==row.status||!['model','analysis','waiting'].includes(u.kind)||!['reserved','issued','settled','unresolved'].includes(u.status))fail('INTEGRITY_BLOCKED');for(const key of ['calls','output_tokens','active_ms','wait_ms','local_runs'] as const)if(!Number.isSafeInteger(u[key])||u[key]<0)fail('INTEGRITY_BLOCKED');const g=grants.find(g=>g.grant_id===row.grant_id);if(!g||decoded<TaskGrant>(g).prepared.fingerprint!==u.source_sha256)fail('INTEGRITY_BLOCKED');}
 for(const row of db.prepare('SELECT * FROM membership_events').all()){const e=decoded<TaskEvent>(row);closed(e,['version','id','attempt_id','source_sha256','kind','text','at']);if(e.version!=='1.0'||e.id!==row.event_id||e.attempt_id!==row.attempt_id||!['outbound','question','explanation','status','consented_text','local_text'].includes(e.kind)||typeof e.text!=='string')fail('INTEGRITY_BLOCKED');const attempt=attempts.find(a=>a.attempt_id===e.attempt_id),grant=grants.find(g=>g.grant_id===attempt?.grant_id);if(!grant||decoded<TaskGrant>(grant).prepared.fingerprint!==e.source_sha256)fail('INTEGRITY_BLOCKED');if(e.kind==='outbound'){const p=outbound(JSON.parse(e.text));if(p.source_sha256!==e.source_sha256)fail('INTEGRITY_BLOCKED');}}
 for(const row of tasks){if(!membershipUuid(row.task_id)||!Number.isSafeInteger(row.row_version)||Number(row.row_version)<1||!Number.isSafeInteger(row.epoch)||Number(row.epoch)<0)fail('INTEGRITY_BLOCKED');}
}
