import {memberClarificationSchema,readMemberClarifications,readGrantClarifications} from './member-clarification.ts';
import {canonicalDesktopJson} from '../../packages/product-core/xanthil-desktop-decision-case.ts';
import {readFileSync,lstatSync,mkdirSync,writeFileSync,openSync,fsyncSync,closeSync,constants} from 'node:fs';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import type {DatabaseSync} from 'node:sqlite';
import {membershipRecord as closed,membershipUuid,membershipHash,membershipBytesHash,validateMembershipPlan,validateMembershipResult,membershipFindingFacts} from '../../packages/product-core/member-analysis.ts';
import {taskHash,encodeTask,fail,expressionReport} from '../../packages/product-core/member-task.ts';
import {operationPolicy,operationUsage,operationDigest,reconcileOperationUsage} from '../../packages/product-core/member-operation.ts';
import {membershipModelPayload,membershipModelOutput,membershipModelResultHash,membershipMaterialText} from '../../packages/product-core/member-model.ts';
import type {MemberModelAttempt,MemberModelStore} from '../../packages/ports/member-model.ts';
import {resolveMemberPlanPreparation,memberSourceReaders} from './member-source-store.ts';
import {reserveMemberOperation,issueMemberOperation,settleMemberOperation} from './member-operation.ts';
const memberModelBaseSchema=`
CREATE TABLE membership_model_grants (
 grant_id TEXT NOT NULL PRIMARY KEY, command_id TEXT NOT NULL UNIQUE, task_id TEXT NOT NULL, source_set_id TEXT, body_json TEXT NOT NULL, body_sha256 TEXT NOT NULL,
 FOREIGN KEY(task_id,grant_id) REFERENCES membership_operation_grants(task_id,grant_id), FOREIGN KEY(task_id,source_set_id) REFERENCES membership_source_sets(task_id,source_set_id)
);
CREATE TABLE membership_model_attempts (
 execution_id TEXT NOT NULL PRIMARY KEY, task_id TEXT NOT NULL, body_json TEXT NOT NULL, body_sha256 TEXT NOT NULL,
 FOREIGN KEY(execution_id) REFERENCES membership_operation_usage(execution_id), FOREIGN KEY(task_id) REFERENCES membership_tasks(task_id)
);
`;
export const memberModelReportSchema=`
CREATE TABLE membership_model_reports (
 execution_id TEXT NOT NULL PRIMARY KEY REFERENCES membership_model_attempts(execution_id),
 task_id TEXT NOT NULL REFERENCES membership_tasks(task_id),
 parent_report_id TEXT NOT NULL REFERENCES report_versions(report_id),
 report_id TEXT NOT NULL UNIQUE REFERENCES report_versions(report_id)
);
`;
export const memberModelSchema=memberModelBaseSchema+memberModelReportSchema+memberClarificationSchema;
function explanationSource(a:MemberModelAttempt,parent:Record<string,unknown>){return {version:'1.0',execution_id:a.context.execution_id,result_sha256:membershipModelResultHash(a.result!),payload_sha256:taskHash(a.payload),parent_report_id:String(parent.report_id),parent_report_sha256:String(parent.markdown_sha256)};}
type Access=<T>(write:boolean,work:(db:DatabaseSync)=>T)=>T;
function modelGrant(value:unknown){
 const g=closed(value,['version','grant_id','command_id','input_sha256','task_id','source_set_id','source_set_sha256','scope_sha256','revision_id','policy_sha256','epoch','selected_text','structure','expires_at',...(Object.hasOwn(value as object,'disclose_verified_result')?['disclose_verified_result']:[]),...(Object.hasOwn(value as object,'clarification_sha256')?['clarification_sha256']:[]),...(Object.hasOwn(value as object,'reuse')?['reuse']:[])]);
 if(Object.hasOwn(g,'clarification_sha256')&&!operationDigest(g.clarification_sha256))fail('INTEGRITY_BLOCKED');
 if(Object.hasOwn(g,'disclose_verified_result')&&typeof g.disclose_verified_result!=='boolean'||g.source_set_id===null&&g.disclose_verified_result===true)fail('INTEGRITY_BLOCKED');
 if(g.version!=='1.0'||![g.grant_id,g.command_id,g.task_id,g.revision_id].every(membershipUuid)||![g.scope_sha256,g.policy_sha256,g.input_sha256].every(operationDigest)||!Number.isSafeInteger(g.epoch)||g.selected_text!==null&&typeof g.selected_text!=='string'||!Number.isFinite(Date.parse(String(g.expires_at))))fail('INTEGRITY_BLOCKED');
 if(g.source_set_id===null){if(g.structure!==false||g.source_set_sha256!==null||typeof g.selected_text!=='string'||g.scope_sha256!==taskHash({task_id:g.task_id,revision_id:g.revision_id,selected_text:g.selected_text}))fail('INTEGRITY_BLOCKED');}
 else if(!membershipUuid(g.source_set_id)||!operationDigest(g.source_set_sha256)||g.scope_sha256!==g.source_set_sha256||g.structure!==true)fail('INTEGRITY_BLOCKED');
 return g;
}
function attempt(value:unknown):MemberModelAttempt{const a=closed(value,['version','context','source_set_id','policy','payload','status','failure_code','result']),c=closed(a.context,['task_id','operation_id','execution_id','epoch']);if(a.version!=='1.0'||![c.task_id,c.operation_id,c.execution_id].every(membershipUuid)||a.source_set_id!==null&&!membershipUuid(a.source_set_id)||!Number.isSafeInteger(c.epoch)||!['issued','succeeded','failed','unknown','stopped'].includes(String(a.status))||a.failure_code!==null&&(typeof a.failure_code!=='string'||!/^[A-Z0-9_]{1,80}$/.test(a.failure_code)))fail('INTEGRITY_BLOCKED');operationPolicy(a.policy);const payload=membershipModelPayload(a.payload);if(a.result!==null){const result=closed(a.result,['version','context','provider','model','output','usage']);if(result.version!=='2.0'||taskHash(result.context)!==taskHash(c)||result.provider!=='xiaomi-token-plan-cn'||result.model!=='mimo-v2.6-pro'||a.status!=='succeeded')fail('INTEGRITY_BLOCKED');membershipModelOutput(result.output,payload);operationUsage(result.usage);}else if(a.status==='succeeded')fail('INTEGRITY_BLOCKED');return structuredClone(value) as MemberModelAttempt;}
/** Select saved model provenance for a qualified preparation; authority is checked by the caller. */
export function resolvePreparedModelReuse(db:DatabaseSync,task_id:string,generated_execution_id:string,preparation:import('../../packages/product-core/member-preparation.ts').QualifiedMemberPreparation,payload:MemberModelAttempt['payload']):MemberModelAttempt{
 const original=db.prepare('SELECT body_json FROM membership_model_attempts WHERE task_id=? AND execution_id=?').get(task_id,generated_execution_id);if(!original||taskHash(attempt(JSON.parse(String(original.body_json))).payload)!==taskHash(payload)||preparation.context.task_id!==task_id)fail('SOURCE_CHANGED');
 for(const row of db.prepare("SELECT a.body_json,a.body_sha256,u.phase,u.outcome FROM membership_model_attempts a JOIN membership_operation_usage u ON u.execution_id=a.execution_id WHERE a.task_id=? ORDER BY a.rowid DESC").all(task_id)){
  const a=attempt(JSON.parse(String(row.body_json)));if(taskHash(a)!==row.body_sha256)fail('INTEGRITY_BLOCKED');const output=a.result?.output;
  if(row.phase==='settled'&&row.outcome==='succeeded'&&a.status==='succeeded'&&a.context.epoch===preparation.context.epoch&&output?.kind==='preparation'&&['generate_preparation','correct_preparation'].includes(a.payload.stage)&&a.source_set_id===preparation.source_set_id&&membershipBytesHash(Buffer.from(output.code))===preparation.code_sha256&&taskHash(output.bindings)===preparation.bindings_sha256&&taskHash({...a.payload,stage:'generate_preparation',diagnostic:null})===taskHash(payload))return a;
 }
 fail('SOURCE_CHANGED');
}
function resultUsageMatches(result:MemberModelAttempt['result'],ledger:Record<string,unknown>):boolean{
 if(!result)return true;
 try{return taskHash(reconcileOperationUsage(operationUsage(JSON.parse(String(ledger.usage_json))),result.usage))===ledger.usage_sha256;}catch{return false;}
}
export function assertMemberModels(db:DatabaseSync){
 for(const c of db.prepare('SELECT body_sha256 FROM membership_clarifications').all())readMemberClarifications(db,String(c.body_sha256));
 for(const row of db.prepare('SELECT * FROM membership_model_grants').all()){const g=modelGrant(JSON.parse(String(row.body_json))),grant=db.prepare('SELECT * FROM membership_operation_grants WHERE grant_id=? AND task_id=?').get(String(row.grant_id),String(row.task_id));readGrantClarifications(db,g);if(taskHash(g)!==row.body_sha256||g.grant_id!==row.grant_id||g.command_id!==row.command_id||g.task_id!==row.task_id||g.source_set_id!==row.source_set_id||!grant||g.scope_sha256!==grant.scope_sha256||g.policy_sha256!==grant.policy_sha256||g.epoch!==grant.epoch||g.expires_at!==grant.expires_at)fail('INTEGRITY_BLOCKED');}
 for(const row of db.prepare('SELECT * FROM membership_model_attempts').all()){const a=attempt(JSON.parse(String(row.body_json))),u=db.prepare('SELECT * FROM membership_operation_usage WHERE execution_id=?').get(String(row.execution_id));if(taskHash(a)!==row.body_sha256||a.context.execution_id!==row.execution_id||a.context.task_id!==row.task_id||!u||a.context.operation_id!==u.operation_id||a.context.epoch!==u.epoch||a.context.task_id!==u.task_id)fail('INTEGRITY_BLOCKED');const op=db.prepare('SELECT * FROM membership_operations WHERE operation_id=?').get(String(u.operation_id)),grant=db.prepare('SELECT * FROM membership_operation_grants WHERE grant_id=?').get(String(u.grant_id)),material=db.prepare('SELECT source_set_id,body_json FROM membership_model_grants WHERE grant_id=?').get(String(u.grant_id));if(!op||op.kind!=='model'||op.stage!==a.payload.stage||op.input_sha256!==taskHash(a.payload)||op.scope_sha256!==grant?.scope_sha256||!grant||grant.policy_sha256!==taskHash(a.policy)||!material||material.source_set_id!==a.source_set_id||JSON.parse(String(material.body_json)).source_set_sha256!==a.payload.source_set_sha256||a.status==='issued'&&u.phase!=='issued'||a.status==='unknown'&&u.phase!=='unresolved'||['succeeded','failed','stopped'].includes(a.status)&&u.phase!=='settled'||a.status==='succeeded'&&u.outcome!=='succeeded'||a.status==='stopped'&&u.outcome!=='stopped'||!resultUsageMatches(a.result,u))fail('INTEGRITY_BLOCKED');const g=JSON.parse(String(material.body_json));if(a.payload.stage!=='explain'&&taskHash(a.payload.clarifications??null)!==taskHash(g.clarification_sha256?readMemberClarifications(db,String(g.clarification_sha256)):null))fail('INTEGRITY_BLOCKED');}
 for(const link of db.prepare('SELECT * FROM membership_model_reports').all()){
  const parent=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(String(link.parent_report_id)),report=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(String(link.report_id)),row=db.prepare('SELECT body_json FROM membership_model_attempts WHERE execution_id=? AND task_id=?').get(String(link.execution_id),String(link.task_id));
  if(!parent||!report||!row)fail('INTEGRITY_BLOCKED');const a=attempt(JSON.parse(String(row.body_json))),v=a.payload.verification;
  if(a.status!=='succeeded'||a.payload.stage!=='explain'||a.result?.output.kind!=='report'||!v||v.parent_report_id!==parent.report_id||v.parent_report_sha256!==parent.markdown_sha256||v.finding_id!==parent.finding_id||report.finding_id!==parent.finding_id||report.state!=='draft'||report.schema_version!=='1.0'||report.acceptance_id!==null||report.closure_id!==null||BigInt(String(report.version_sequence))<=BigInt(String(parent.version_sequence))||['project_id','session_id','case_id','revision_id'].some(k=>report[k]!==parent[k])||report.evidence_refs_json!==parent.evidence_refs_json||report.source_json!==canonicalDesktopJson({...JSON.parse(String(parent.source_json)),model_explanation:explanationSource(a,parent)}))fail('INTEGRITY_BLOCKED');
 }
 for(const report of db.prepare("SELECT report_id FROM report_versions WHERE state='draft' AND json_type(source_json,'$.model_explanation') IS NOT NULL").all())if(!db.prepare('SELECT report_id FROM membership_model_reports WHERE report_id=?').get(String(report.report_id)))fail('INTEGRITY_BLOCKED');
}
function verifiedPayload(db:DatabaseSync,projectRoot:string,task_id:string,grant_id:string,g:ReturnType<typeof modelGrant>){
 if(g.disclose_verified_result!==true)fail('MATERIAL_AUTHORITY_REQUIRED');
 const row=db.prepare("SELECT c.current_report_id,r.run_id,p.body_json,p.body_sha256,f.finding_id,f.metrics_json,f.facts_json,f.facts_sha256,a.artifact_id,a.locator,a.sha256,a.byte_length FROM membership_tasks t JOIN case_revisions c ON c.revision_id=t.current_revision_id JOIN findings f ON f.finding_id=c.current_finding_id JOIN analysis_runs r ON r.run_id=f.run_id JOIN membership_run_plans rp ON rp.run_id=r.run_id JOIN membership_plans p ON p.plan_id=rp.plan_id JOIN aggregate_artifacts a ON a.artifact_id=f.aggregate_id WHERE t.task_id=? AND r.status='Succeeded' AND r.run_contract_version='5.0' AND f.schema_version='2.0'").get(task_id);
 if(!row)fail('RESULT_REQUIRED');const plan=validateMembershipPlan(JSON.parse(String(row.body_json)));if(plan.version!=='2.0'||membershipHash(plan)!==row.body_sha256||plan.authority.task_id!==task_id||plan.preparation.source_set_sha256!==g.source_set_sha256)fail('SOURCE_CHANGED');
 const reused=plan.authority.epoch!==String(g.epoch);if(reused&&(g.reuse as {run_id?:unknown}|undefined)?.run_id!==row.run_id)fail('SOURCE_CHANGED');
 resolveMemberPlanPreparation(db,projectRoot,{version:'2.0',preparation:plan.preparation,intent:plan.intent,authority:{...plan.authority,grant_id,epoch:String(g.epoch),...(reused?{resume_preparation_sha256:plan.preparation.sha256}:{})}},true);
 const facts=JSON.parse(String(row.facts_json)),metrics=validateMembershipResult(JSON.parse(String(row.metrics_json)),plan);if(membershipHash(facts)!==row.facts_sha256||membershipHash(facts)!==membershipHash(membershipFindingFacts(metrics,plan)))fail('INTEGRITY_BLOCKED');
 const locator=String(row.locator);if(locator!==`${plan.owner.session_id}/020_clean/${row.artifact_id}/aggregate.json`||!membershipUuid(row.artifact_id))fail('INTEGRITY_BLOCKED');let path=projectRoot;for(const part of locator.split('/')){path=join(path,part);if(lstatSync(path).isSymbolicLink())fail('INTEGRITY_BLOCKED');}const bytes=readFileSync(path);if(String(bytes.length)!==String(row.byte_length)||membershipBytesHash(bytes)!==row.sha256||membershipHash(JSON.parse(bytes.toString()).result)!==membershipHash(metrics))fail('INTEGRITY_BLOCKED');
 const relation=db.prepare('SELECT parent_report_id FROM membership_model_reports WHERE report_id=?').get(String(row.current_report_id)),parent=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(String(relation?.parent_report_id??row.current_report_id));if(!parent||parent.finding_id!==row.finding_id||parent.state!=='draft')fail('SOURCE_CHANGED');
 return membershipModelPayload({version:'2.0',stage:'explain',source_set_sha256:g.source_set_sha256,selected_text:null,structure:[],semantics:{metric:'membership_repurchase_comparison',currency:plan.parameters.currency,time_zone:plan.parameters.time_zone,comparison_period:plan.parameters.comparison_period,current_period:plan.parameters.current_period,status_meanings:'explicitly_confirmed_local'},result:{periods:metrics.periods,changes:metrics.changes},diagnostic:null,verification:{parent_report_id:parent.report_id,parent_report_sha256:parent.markdown_sha256,run_id:row.run_id,plan_sha256:row.body_sha256,preparation_sha256:plan.preparation.sha256,finding_id:row.finding_id,aggregate_sha256:row.sha256,direction:facts.comparison_direction,status:'verified'}});
}
export function memberModelMethods(projectRoot:string,access:Access):MemberModelStore{
 const readers=memberSourceReaders(projectRoot);
 function read(db:DatabaseSync,task_id:string,execution_id:string){const row=db.prepare('SELECT * FROM membership_model_attempts WHERE task_id=? AND execution_id=?').get(task_id,execution_id);if(!row)fail('NOT_FOUND');const a=attempt(JSON.parse(String(row.body_json)));if(taskHash(a)!==row.body_sha256)fail('INTEGRITY_BLOCKED');return a;}
 function sources(db:DatabaseSync,task_id:string,source_set_id:string){const selected=readers.read(db,task_id,source_set_id);if(db.prepare('SELECT source_set_id FROM membership_source_sets WHERE task_id=? ORDER BY rowid DESC LIMIT 1').get(task_id)?.source_set_id!==source_set_id)fail('SOURCE_CHANGED');return selected.source_set;}
 return {
  async answerMemberQuestion(input){
   const x=closed(input,['version','command_id','task_id','expected_row_version','epoch','question_execution_id','policy_sha256','reply','confirmed']);if(x.version!=='1.0'||x.confirmed!==true||![x.command_id,x.task_id,x.question_execution_id].every(membershipUuid)||!Number.isSafeInteger(x.expected_row_version)||!Number.isSafeInteger(x.epoch)||!operationDigest(x.policy_sha256))fail('AUTHORITY_REQUIRED');const reply=membershipMaterialText(x.reply),input_sha256=taskHash(x);
   return access(true,db=>{
    const prior=db.prepare('SELECT body_json,body_sha256 FROM membership_clarifications WHERE command_id=?').get(String(x.command_id));if(prior){const b=JSON.parse(String(prior.body_json));if(b.input_sha256!==input_sha256)fail('COMMAND_CONFLICT');return {grant_id:String(b.grant_id),task_id:String(b.task_id),epoch:Number(b.epoch),source_set_id:b.source_set_id as string|null,clarification_sha256:String(prior.body_sha256),created:false};}
    if(db.prepare('SELECT command_id FROM membership_model_grants WHERE command_id=?').get(String(x.command_id))||db.prepare('SELECT id FROM membership_clarifications WHERE question_execution_id=?').get(String(x.question_execution_id)))fail('COMMAND_CONFLICT');
    if(db.prepare("SELECT execution_id FROM membership_operation_usage WHERE phase IN ('reserved','issued','unresolved')").get())fail('PHYSICAL_PENDING');
    const task=db.prepare('SELECT * FROM membership_tasks WHERE task_id=?').get(String(x.task_id)),latest=db.prepare('SELECT execution_id FROM membership_model_attempts WHERE task_id=? ORDER BY rowid DESC LIMIT 1').get(String(x.task_id));if(!task||task.epoch!==x.epoch||task.row_version!==x.expected_row_version||['stopped','interrupted','closed'].includes(String(task.status))||latest?.execution_id!==x.question_execution_id)fail('AUTHORITY_REQUIRED');
    const a=read(db,String(x.task_id),String(x.question_execution_id)),u=db.prepare('SELECT * FROM membership_operation_usage WHERE execution_id=?').get(String(x.question_execution_id)),gRow=u&&db.prepare('SELECT m.body_json,g.revoked FROM membership_model_grants m JOIN membership_operation_grants g ON g.grant_id=m.grant_id WHERE m.grant_id=?').get(String(u.grant_id));if(a.status!=='succeeded'||a.result?.output.kind!=='question'||!u||u.phase!=='settled'||u.outcome!=='succeeded'||!gRow||gRow.revoked!==0)fail('AUTHORITY_REQUIRED');const g=modelGrant(JSON.parse(String(gRow.body_json)));
    if(g.epoch!==task.epoch||g.revision_id!==task.current_revision_id||g.policy_sha256!==x.policy_sha256||Date.now()>=Date.parse(String(g.expires_at)))fail('AUTHORITY_REQUIRED');const selected=db.prepare('SELECT source_set_id FROM membership_source_sets WHERE task_id=? ORDER BY rowid DESC LIMIT 1').get(String(x.task_id));if((selected?.source_set_id??null)!==g.source_set_id)fail('SOURCE_CHANGED');if(g.source_set_id!==null&&taskHash(sources(db,String(x.task_id),String(g.source_set_id)))!==g.source_set_sha256)fail('SOURCE_CHANGED');
    const revision=db.prepare('SELECT question_text FROM case_revisions WHERE revision_id=?').get(String(task.current_revision_id))!,id=randomUUID(),grant_id=randomUUID(),body={version:'1.0',id,task_id:String(x.task_id),revision_id:String(task.current_revision_id),epoch:Number(task.epoch),source_set_id:g.source_set_id,source_set_sha256:g.source_set_sha256,question_execution_id:x.question_execution_id,question_result_sha256:membershipModelResultHash(a.result),original_question_sha256:membershipBytesHash(Buffer.from(String(revision.question_text))),predecessor_sha256:g.clarification_sha256??null,reply,command_id:x.command_id,input_sha256,grant_id},clarification_sha256=taskHash(body);
    const {reuse:previousReuse,...currentGrant}=g;void previousReuse;const successor={...currentGrant,grant_id,command_id:x.command_id,input_sha256,clarification_sha256};db.prepare('UPDATE membership_operation_grants SET revoked=1 WHERE task_id=?').run(String(x.task_id));db.prepare('INSERT INTO membership_operation_grants VALUES(?,?,?,?,?,?,?,0)').run(grant_id,String(x.task_id),Number(task.epoch),String(g.scope_sha256),encodeTask(a.policy),String(g.policy_sha256),String(g.expires_at));db.prepare('INSERT INTO membership_model_grants VALUES(?,?,?,?,?,?)').run(grant_id,String(x.command_id),String(x.task_id),g.source_set_id===null?null:String(g.source_set_id),encodeTask(successor),taskHash(successor));db.prepare('INSERT INTO membership_clarifications VALUES(?,?,?,?,?,?)').run(id,String(x.task_id),String(x.command_id),String(x.question_execution_id),encodeTask(body),clarification_sha256);db.prepare("UPDATE membership_tasks SET status='idle',row_version=row_version+1 WHERE task_id=?").run(String(x.task_id));return {grant_id,task_id:String(x.task_id),epoch:Number(task.epoch),source_set_id:g.source_set_id===null?null:String(g.source_set_id),clarification_sha256,created:true};
   });
  },
  async authorizeMemberModel(input){const x=closed(input,['version','command_id','task_id','source_set_id','expected_row_version','epoch','policy','disclose_question','disclose_structure','expires_at',...(Object.hasOwn(input as object,'disclose_verified_result')?['disclose_verified_result']:[])]),policy=operationPolicy(x.policy);if(Object.hasOwn(x,'disclose_verified_result')&&typeof x.disclose_verified_result!=='boolean'||x.source_set_id===null&&x.disclose_verified_result===true)fail('AUTHORITY_REQUIRED');if(x.version!=='1.0'||!membershipUuid(x.command_id)||!membershipUuid(x.task_id)||x.source_set_id!==null&&!membershipUuid(x.source_set_id)||typeof x.disclose_question!=='boolean'||(x.source_set_id===null?(x.disclose_question!==true||x.disclose_structure!==false):x.disclose_structure!==true)||!Number.isSafeInteger(x.epoch)||!Number.isSafeInteger(x.expected_row_version)||typeof x.expires_at!=='string'||Date.parse(x.expires_at)<=Date.now()||!Number.isFinite(Date.parse(x.expires_at)))fail('AUTHORITY_REQUIRED');const task_id=x.task_id,source_set_id=x.source_set_id;
   return access(true,db=>{const {expires_at,...stable}=x;void expires_at;const input_sha256=taskHash(stable),prior=db.prepare('SELECT * FROM membership_model_grants WHERE command_id=?').get(String(x.command_id));if(prior){const body=modelGrant(JSON.parse(String(prior.body_json)));if(body.task_id!==task_id||body.input_sha256!==input_sha256)fail('COMMAND_CONFLICT');return {grant_id:String(body.grant_id),task_id,epoch:Number(body.epoch),policy,created:false};}if(db.prepare("SELECT execution_id FROM membership_operation_usage WHERE task_id=? AND phase IN ('reserved','issued','unresolved')").get(task_id))fail('PHYSICAL_PENDING');if(db.prepare('SELECT command_id FROM membership_browser_receipts WHERE command_id=?').get(String(x.command_id))||db.prepare('SELECT command_id FROM membership_receipts WHERE command_id=?').get(String(x.command_id))||db.prepare('SELECT command_id FROM membership_source_sets WHERE command_id=?').get(String(x.command_id)))fail('COMMAND_CONFLICT');const task=db.prepare('SELECT * FROM membership_tasks WHERE task_id=?').get(task_id);if(!task||task.status==='closed'||task.epoch!==x.epoch||task.row_version!==x.expected_row_version)fail('AUTHORITY_REQUIRED');const selected=source_set_id===null?null:sources(db,task_id,String(source_set_id));if(selected&&selected.owner.revision_id!==task.current_revision_id)fail('SOURCE_CHANGED');const question=db.prepare('SELECT question_text FROM case_revisions WHERE revision_id=?').get(String(task.current_revision_id));if(!question)fail('INTEGRITY_BLOCKED');const grant_id=randomUUID(),body={version:'1.0',grant_id,command_id:x.command_id,input_sha256,task_id,source_set_id,source_set_sha256:selected?taskHash(selected):null,scope_sha256:selected?taskHash(selected):taskHash({task_id,revision_id:task.current_revision_id,selected_text:String(question.question_text)}),revision_id:task.current_revision_id,policy_sha256:taskHash(policy),epoch:Number(task.epoch),selected_text:x.disclose_question?String(question.question_text):null,structure:x.disclose_structure,disclose_verified_result:x.disclose_verified_result===true,expires_at:x.expires_at};
    const predecessorRow=db.prepare('SELECT body_json FROM membership_model_grants WHERE task_id=? ORDER BY rowid DESC LIMIT 1').get(task_id);
    if(predecessorRow){const predecessor=modelGrant(JSON.parse(String(predecessorRow.body_json)));
     if(predecessor.revision_id===body.revision_id&&predecessor.source_set_id===body.source_set_id&&predecessor.source_set_sha256===body.source_set_sha256&&predecessor.selected_text===body.selected_text){
      readGrantClarifications(db,predecessor);
      const prepRow=db.prepare('SELECT p.execution_id,u.grant_id FROM membership_preparations p JOIN membership_operation_usage u ON u.execution_id=p.execution_id WHERE p.task_id=? ORDER BY p.rowid DESC LIMIT 1').get(task_id);
      let preparation_execution_id:string|null=null,run_id:string|null=null;
      if(prepRow&&(prepRow.grant_id===predecessor.grant_id||(predecessor.reuse as {preparation_execution_id?:unknown}|undefined)?.preparation_execution_id===prepRow.execution_id)){
       const qualified=readers.qualified(db,task_id,String(prepRow.execution_id)).preparation;
       if(qualified.source_set_id===body.source_set_id&&qualified.source_set_sha256===body.source_set_sha256&&qualified.owner.revision_id===body.revision_id)preparation_execution_id=String(prepRow.execution_id);
      }
      const run=db.prepare("SELECT r.run_id,p.body_json FROM membership_tasks t JOIN case_revisions c ON c.revision_id=t.current_revision_id JOIN findings f ON f.finding_id=c.current_finding_id JOIN analysis_runs r ON r.run_id=f.run_id JOIN membership_run_plans rp ON rp.run_id=r.run_id JOIN membership_plans p ON p.plan_id=rp.plan_id WHERE t.task_id=? AND r.status='Succeeded' AND r.run_contract_version='5.0'").get(task_id);
      if(run){const plan=validateMembershipPlan(JSON.parse(String(run.body_json)));if(plan.version==='2.0'&&plan.preparation.execution_id===preparation_execution_id&&(plan.authority.grant_id===predecessor.grant_id||(predecessor.reuse as {run_id?:unknown}|undefined)?.run_id===run.run_id)){resolveMemberPlanPreparation(db,projectRoot,{version:'2.0',preparation:plan.preparation,intent:plan.intent,authority:plan.authority},false);run_id=String(run.run_id);}}
      if(predecessor.clarification_sha256||preparation_execution_id||run_id)Object.assign(body,{...(predecessor.clarification_sha256?{clarification_sha256:predecessor.clarification_sha256}:{}),reuse:{version:'1.0',predecessor_grant_id:predecessor.grant_id,clarification_sha256:predecessor.clarification_sha256??null,preparation_execution_id,run_id}});
     }
    }
    db.prepare('UPDATE membership_operation_grants SET revoked=1 WHERE task_id=?').run(task_id);db.prepare('INSERT INTO membership_operation_grants VALUES(?,?,?,?,?,?,?,0)').run(grant_id,task_id,Number(task.epoch),body.scope_sha256,encodeTask(policy),body.policy_sha256,String(x.expires_at));db.prepare('INSERT INTO membership_model_grants VALUES(?,?,?,?,?,?)').run(grant_id,String(x.command_id),task_id,source_set_id===null?null:String(source_set_id),encodeTask(body),taskHash(body));db.prepare("UPDATE membership_tasks SET status='idle',row_version=row_version+1 WHERE task_id=?").run(task_id);return {grant_id,task_id,epoch:Number(task.epoch),policy,created:true};});
  },
  async beginMemberModel(input){const x=closed(input,['task_id','grant_id','stage','policy_sha256']);if(!membershipUuid(x.task_id)||!membershipUuid(x.grant_id)||!['clarify','generate_preparation','correct_preparation','explain'].includes(String(x.stage)))fail();const task_id=x.task_id,grant_id=x.grant_id;
   return access(true,db=>{const row=db.prepare('SELECT body_json FROM membership_model_grants WHERE task_id=? AND grant_id=?').get(task_id,grant_id);if(!row)fail('AUTHORITY_REQUIRED');const g=modelGrant(JSON.parse(String(row.body_json))),selected=g.source_set_id===null?null:sources(db,task_id,String(g.source_set_id));if(selected&&taskHash(selected)!==g.source_set_sha256)fail('SOURCE_CHANGED');const task=db.prepare('SELECT * FROM membership_tasks WHERE task_id=?').get(task_id),question=task&&db.prepare('SELECT question_text FROM case_revisions WHERE revision_id=?').get(String(task.current_revision_id));if(!task||g.revision_id!==task.current_revision_id||selected&&selected.owner.revision_id!==task.current_revision_id||g.selected_text!==null&&g.selected_text!==question?.question_text)fail('SOURCE_CHANGED');const grant=db.prepare('SELECT * FROM membership_operation_grants WHERE task_id=? AND grant_id=?').get(task_id,grant_id)!;const policy=operationPolicy(JSON.parse(String(grant.policy_json)));if(x.policy_sha256!==taskHash(policy))fail('MODEL_POLICY_CHANGED');
    if(!selected&&x.stage!=='clarify')fail('AUTHORITY_REQUIRED');
    const clarifications=readGrantClarifications(db,g);
    let diagnostic:null|'CONVERSION_UNQUALIFIED'|'PREPARATION_OUTPUT_INVALID'=null;
    if(x.stage==='correct_preparation'){
     const failed=db.prepare('SELECT a.body_json,u.phase,u.outcome,u.execution_index,u.grant_id,u.epoch FROM membership_preparation_attempts a JOIN membership_operation_usage u ON u.execution_id=a.execution_id WHERE a.task_id=? AND a.source_set_id=? ORDER BY a.rowid DESC LIMIT 1').get(task_id,String(g.source_set_id));
     const prior=failed?JSON.parse(String(failed.body_json)):null;
     if(!failed||failed.phase!=='settled'||failed.outcome!=='conversion_failure'||failed.execution_index!==0||failed.grant_id!==grant_id||failed.epoch!==task.epoch||prior?.status!=='failed'||prior.physical_status!=='settled'||!['CONVERSION_UNQUALIFIED','PREPARATION_OUTPUT_INVALID'].includes(prior.failure_code))fail('RETRY_EXHAUSTED');
     diagnostic=prior.failure_code;
    }
    const payload=x.stage==='explain'?verifiedPayload(db,projectRoot,task_id,grant_id,g):membershipModelPayload({version:'2.0',stage:x.stage,source_set_sha256:g.source_set_sha256,selected_text:g.selected_text,structure:(selected?.inspection.sources??[]).map(s=>({source_id:s.source_id,sheets:s.sheets.map(sheet=>({sheet_id:sheet.sheet_id,columns:(sheet.rows[0]?.cells??[]).map(header=>{const types=[...new Set(sheet.rows.slice(1).flatMap(r=>r.cells.filter(c=>c.column===header.column).map(c=>c.type)))].sort();return {name:header.value,types:types.length?types:['blank']};})}))})),semantics:null,result:null,diagnostic,...(clarifications?{clarifications}:{})});
    const reserved=reserveMemberOperation(db,{task_id,grant_id,kind:'model',stage:x.stage,input_sha256:taskHash(payload)});if(reserved.phase==='settled'&&reserved.outcome==='succeeded'){const reuse=g.reuse as {preparation_execution_id?:string|null}|undefined;if(x.stage==='generate_preparation'&&reuse?.preparation_execution_id){if(db.prepare("SELECT execution_id FROM membership_operation_usage WHERE phase IN ('reserved','issued','unresolved')").get())fail('PHYSICAL_PENDING');const p=readers.qualified(db,task_id,reuse.preparation_execution_id).preparation;return resolvePreparedModelReuse(db,task_id,reserved.execution_id,p,payload);}return read(db,task_id,reserved.execution_id);}const execution=issueMemberOperation(db,{task_id,execution_id:reserved.execution_id}),body:MemberModelAttempt={version:'1.0',context:{task_id,operation_id:execution.operation_id,execution_id:execution.execution_id,epoch:execution.epoch},source_set_id:selected?.id??null,policy,payload,status:'issued',failure_code:null,result:null};db.prepare('INSERT INTO membership_model_attempts VALUES(?,?,?,?)').run(execution.execution_id,task_id,encodeTask(body),taskHash(body));return body;});
  },
  async finishMemberModel(input){return access(true,db=>{const a=read(db,input.task_id,input.execution_id),u=db.prepare('SELECT * FROM membership_operation_usage WHERE task_id=? AND execution_id=?').get(input.task_id,input.execution_id)!;if(!['issued','unresolved'].includes(String(u.phase)))fail('COMMAND_CONFLICT');const proof=input.proof;if(proof&&taskHash(proof.context)!==taskHash(a.context))fail('AUTHORITY_REQUIRED');const physical=proof?.physical_status==='settled'||proof?.physical_status==='not_started'?'settled':'unresolved';const unknown={input_tokens:{kind:'unknown',reason:'unconfirmed_transport'},output_tokens:{kind:'unknown',reason:'unconfirmed_transport'},active_ms:{kind:'unknown',reason:'unconfirmed_transport'},wait_ms:{kind:'known',value:'0'}},usage=operationUsage(proof?.usage??unknown);
    const task=db.prepare('SELECT * FROM membership_tasks WHERE task_id=?').get(input.task_id)!,grant=db.prepare('SELECT * FROM membership_operation_grants WHERE grant_id=?').get(String(u.grant_id))!;let fenced=task.epoch!==a.context.epoch||grant.revoked!==0||Date.now()>=Date.parse(String(grant.expires_at))||['stopped','interrupted','closed'].includes(String(task.status));try{const material=modelGrant(JSON.parse(String(db.prepare('SELECT body_json FROM membership_model_grants WHERE grant_id=?').get(String(u.grant_id))!.body_json))),question=db.prepare('SELECT question_text FROM case_revisions WHERE revision_id=?').get(String(task.current_revision_id));if(material.revision_id!==task.current_revision_id||material.selected_text!==null&&material.selected_text!==question?.question_text||a.source_set_id!==null&&taskHash(sources(db,input.task_id,a.source_set_id))!==a.payload.source_set_sha256)fenced=true;}catch{fenced=true;}

    const result=input.result;if(result&&(physical!=='settled'||proof?.physical_status!=='settled'||proof.result_sha256!==membershipModelResultHash(result)||taskHash(result.context)!==taskHash(a.context)))fail('AUTHORITY_REQUIRED');if(result)membershipModelOutput(result.output,a.payload);
    const outcome=fenced?'stopped':result?'succeeded':['NETWORK_UNAVAILABLE','CONNECTION_TIMEOUT'].includes(String(input.failure_code))?'temporary_failure':'permanent_failure';let settled=settleMemberOperation(db,{task_id:input.task_id,execution_id:input.execution_id,physical,outcome,usage});
    if(a.payload.stage==='explain'){try{const material=modelGrant(JSON.parse(String(db.prepare('SELECT body_json FROM membership_model_grants WHERE grant_id=?').get(String(u.grant_id))!.body_json)));if(taskHash(verifiedPayload(db,projectRoot,input.task_id,String(u.grant_id),material))!==taskHash(a.payload))fenced=true;}catch{fenced=true;}}
    if(fenced&&settled.outcome!=='stopped'){db.prepare("UPDATE membership_operation_usage SET outcome='stopped' WHERE execution_id=?").run(input.execution_id);settled={...settled,outcome:'stopped'};}const next:MemberModelAttempt={...a,status:physical==='unresolved'?'unknown':settled.outcome==='stopped'?'stopped':result?'succeeded':'failed',failure_code:result?null:input.failure_code,result:!fenced&&physical==='settled'?result:null};if(next.status!=='succeeded')next.result=null;attempt(next);db.prepare('UPDATE membership_model_attempts SET body_json=?,body_sha256=? WHERE execution_id=?').run(encodeTask(next),taskHash(next),input.execution_id);return next;});},
  async readCurrentMemberAnalysis(input){const x=closed(input,['task_id']);if(!membershipUuid(x.task_id))fail();return access(false,db=>{const row=db.prepare("SELECT r.run_id FROM membership_tasks t JOIN case_revisions c ON c.revision_id=t.current_revision_id JOIN findings f ON f.finding_id=c.current_finding_id JOIN analysis_runs r ON r.run_id=f.run_id WHERE t.task_id=? AND r.status='Succeeded' AND r.run_contract_version='5.0' AND f.schema_version='2.0'").get(String(x.task_id));return row?{run_id:String(row.run_id)}:null;});},
  async publishMemberExplanation(input){
   const x=closed(input,['task_id','execution_id']);if(![x.task_id,x.execution_id].every(membershipUuid))fail();
   return access(true,db=>{
    const a=read(db,String(x.task_id),String(x.execution_id)),prior=db.prepare('SELECT report_id FROM membership_model_reports WHERE task_id=? AND execution_id=?').get(String(x.task_id),String(x.execution_id));if(prior)return {report_id:String(prior.report_id)};
    const u=db.prepare('SELECT * FROM membership_operation_usage WHERE execution_id=? AND task_id=?').get(String(x.execution_id),String(x.task_id));if(!u||u.phase!=='settled'||u.outcome!=='succeeded'||a.status!=='succeeded'||a.payload.stage!=='explain'||a.result?.output.kind!=='report')fail('AUTHORITY_REQUIRED');
    const g=modelGrant(JSON.parse(String(db.prepare('SELECT body_json FROM membership_model_grants WHERE grant_id=?').get(String(u.grant_id))!.body_json)));if(taskHash(verifiedPayload(db,projectRoot,String(x.task_id),String(u.grant_id),g))!==taskHash(a.payload))fail('SOURCE_CHANGED');
    const v=a.payload.verification!,parent=db.prepare('SELECT * FROM report_versions WHERE report_id=?').get(v.parent_report_id),t=db.prepare('SELECT * FROM membership_tasks WHERE task_id=?').get(String(x.task_id)),revision=t&&db.prepare('SELECT * FROM case_revisions WHERE revision_id=?').get(String(t.current_revision_id));if(!parent||!t||!revision||revision.state!=='Review'||revision.integrity_state!=='ok'||revision.current_report_id!==parent.report_id||revision.current_finding_id!==parent.finding_id||parent.markdown_sha256!==v.parent_report_sha256)fail('SOURCE_CHANGED');
    const reports=join(projectRoot,String(t.session_id),'060_reports'),parentDir=join(reports,String(parent.report_id));for(const path of [projectRoot,join(projectRoot,String(t.session_id)),reports,parentDir]){const stat=lstatSync(path);if(!stat.isDirectory()||stat.isSymbolicLink())fail('INTEGRITY_BLOCKED');}
    const fd=openSync(join(parentDir,'report.md'),constants.O_RDONLY|constants.O_NOFOLLOW);let bytes:Buffer;try{bytes=readFileSync(fd);}finally{closeSync(fd);}if(membershipBytesHash(bytes)!==parent.markdown_sha256||String(bytes.length)!==String(parent.markdown_byte_length))fail('INTEGRITY_BLOCKED');
    const body=expressionReport(new TextDecoder('utf-8',{fatal:true}).decode(bytes),'AI解释，非独立核验结论\n\n'+a.result.output.text),id=randomUUID(),target=join(reports,id);mkdirSync(target,{mode:0o700});for(const [name,content] of [['report.md',body.markdown],['report.html',body.html]]){const file=openSync(join(target,name),constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY|constants.O_NOFOLLOW,0o600);try{writeFileSync(file,content);fsyncSync(file);}finally{closeSync(file);}}for(const path of [target,reports]){const dir=openSync(path,constants.O_RDONLY);try{fsyncSync(dir);}finally{closeSync(dir);}}
    const sequence=BigInt(String(db.prepare('SELECT max(version_sequence) n FROM report_versions WHERE revision_id=?').get(String(t.current_revision_id))!.n))+1n,at=new Date().toISOString(),source={...JSON.parse(String(parent.source_json)),model_explanation:explanationSource(a,parent)};
    db.prepare("INSERT INTO report_versions VALUES(?,?,?,?,?,?,NULL,NULL,?,'draft',?,?,?,?,?,?,?,?,?,'1.0')").run(id,t.project_id,t.session_id,t.case_id,t.current_revision_id,parent.finding_id,sequence,`${t.session_id}/060_reports/${id}/report.md`,membershipBytesHash(Buffer.from(body.markdown)),Buffer.byteLength(body.markdown),`${t.session_id}/060_reports/${id}/report.html`,membershipBytesHash(Buffer.from(body.html)),Buffer.byteLength(body.html),canonicalDesktopJson(source),parent.evidence_refs_json,at);
    db.prepare('INSERT INTO membership_model_reports VALUES(?,?,?,?)').run(String(x.execution_id),String(x.task_id),parent.report_id,id);db.prepare('UPDATE case_revisions SET current_report_id=? WHERE revision_id=?').run(id,t.current_revision_id);return {report_id:id};
   });
  },
  async readMemberModelForPreparation(input){
   const x=closed(input,['task_id','execution_id','grant_id']);if(![x.task_id,x.execution_id,x.grant_id].every(membershipUuid))fail();
   return access(false,db=>{
    const a=read(db,String(x.task_id),String(x.execution_id)),u=db.prepare('SELECT * FROM membership_operation_usage WHERE execution_id=? AND task_id=?').get(String(x.execution_id),String(x.task_id)),t=db.prepare('SELECT * FROM membership_tasks WHERE task_id=?').get(String(x.task_id)),g=db.prepare('SELECT * FROM membership_operation_grants WHERE task_id=? AND grant_id=?').get(String(x.task_id),String(x.grant_id)),material=db.prepare('SELECT body_json FROM membership_model_grants WHERE task_id=? AND grant_id=?').get(String(x.task_id),String(x.grant_id));
    if(!u||!t||!g||!material||u.phase!=='settled'||u.outcome!=='succeeded'||a.status!=='succeeded'||!a.result||!['generate_preparation','correct_preparation'].includes(a.payload.stage)||a.source_set_id===null||g.revoked!==0||Date.now()>=Date.parse(String(g.expires_at))||['stopped','interrupted','closed'].includes(String(t.status)))fail('AUTHORITY_REQUIRED');
    const m=modelGrant(JSON.parse(String(material.body_json))),selected=sources(db,String(x.task_id),a.source_set_id),revision=db.prepare('SELECT question_text FROM case_revisions WHERE revision_id=?').get(String(t.current_revision_id));
    if(m.revision_id!==t.current_revision_id||m.source_set_id!==a.source_set_id||m.source_set_sha256!==taskHash(selected)||a.payload.source_set_sha256!==m.source_set_sha256||m.selected_text!==a.payload.selected_text||m.selected_text!==null&&m.selected_text!==revision?.question_text)fail('SOURCE_CHANGED');
    if(g.epoch!==t.epoch)fail('AUTHORITY_REQUIRED');
    if(u.grant_id!==x.grant_id||a.context.epoch!==t.epoch){readGrantClarifications(db,m);const reuse=m.reuse as {preparation_execution_id?:string|null}|undefined;if(!reuse?.preparation_execution_id)fail('AUTHORITY_REQUIRED');const prepared=readers.qualified(db,String(x.task_id),reuse.preparation_execution_id).preparation;if(a.result.output.kind!=='preparation'||prepared.context.epoch!==a.context.epoch||prepared.code_sha256!==membershipBytesHash(Buffer.from(a.result.output.code))||prepared.bindings_sha256!==taskHash(a.result.output.bindings)||taskHash(a.payload.clarifications??null)!==taskHash(readGrantClarifications(db,m)))fail('SOURCE_CHANGED');}
    if(db.prepare("SELECT execution_id FROM membership_operation_usage WHERE phase IN ('reserved','issued','unresolved')").get())fail('PHYSICAL_PENDING');
    return a;
   });
  },
  async readMemberModel(input){if(!membershipUuid(input.task_id)||!membershipUuid(input.execution_id))fail();return access(false,db=>read(db,input.task_id,input.execution_id));},
 };
}
