import type {ParentCollaborationProjection,ChildResult} from '../../packages/contracts/case-collaboration.ts';
import {useProviderSettings} from './provider-settings.tsx';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import type { CaseAssistantApi, CaseAssistantRequest, AssistantProjection, AssistantSession, AssistantSource, AssistantDraft, Authorization, DecisionFields } from '../../packages/contracts/case-assistant.ts';
import type { SessionSummary, OwnerRef } from '../../packages/contracts/xanthil-desktop-ipc.ts';
import { validateAssistantDecision } from '../../packages/product-core/case-assistant.ts';
export type AssistantWorkspaceProps = {
    api: CaseAssistantApi;
    projectId: string | null;
    sources: readonly SessionSummary[];
    initial: AssistantProjection | null;
    onChange: (p: AssistantProjection) => void;
    onOpenSource: (owner: OwnerRef) => void;
    onChooseProject: () => void;
};
const statuses: Record<string, string> = { Running: '运行中', Waiting: '等待用户', Succeeded: '已完成建议', Stopped: '已停止', Interrupted: '已中断', WaitExpired: '等待超时', TimedOut: '执行超时', BudgetExhausted: '预算耗尽', Failed: '失败' };
const tools: Record<string, string> = { read_case: '读取 Case', read_evidence: '读取已验证证据', read_candidates: '读取已保存候选', read_aggregate: '读取授权聚合', read_report: '读取获准报告摘要' };
const fieldLabels: Record<string, string> = { rationale: '决策理由', owner: '决策责任人', confirmed_at: '确认时间（含时区，例如 2026-09-29T10:00:00+08:00）', evidence_refs: 'Evidence 引用（每行一项）', finding_refs: 'Finding 引用（每行一项）', alternatives: '已比较的替代项', limitations: '限制与仍未知事项', defer_trigger: '暂缓条件与重新评估触发点', defer_owner: '暂缓责任人', baseline: '基线', baseline_source: '基线来源', observation_object: '观察对象', metric: '观察指标', expectation: '预期方向、范围或明确不确定性', observation_window: '观察窗口', guardrails: 'Guardrails', result_source: '未来结果来源', result_owner: '结果来源 Owner', assessment: '后续评估安排', assessment_owner: '评估责任人', not_applicable_reason: '不适用原因', reassess_trigger: '重新评估触发条件', reassess_owner: '重新评估责任人' };
const budget = (used: number, limit: number, currency: string) => currency === 'synthetic' ? `合成预算：${used} / ${limit}（测试计数）` : currency === 'XIAOMI_CREDITS' ? `Token Plan Credits（保守上界，非账单）：${used / 1000000} / ${limit / 1000000}` : `费用：${used / 1000000} / ${limit / 1000000} ${currency}`;
const xiaomiLimits = (config: Authorization['config']) => config?.limits.currency === 'XIAOMI_CREDITS' ? <p>本次本地激活共享最多 {config.limits.turns} 次请求；每次完整请求最多 12000 UTF-8 字节，输入预留 16384 tokens（保守估计），输出最多 2048 tokens。每次请求 60 秒，累计模型执行 300 秒，每次等待 120 秒，整个运行 600 秒。不购买、不充值、不回退到 PAYG。</p> : null;
const sameSelection = (selected: readonly string[], authorized: readonly string[]) => selected.length === authorized.length && new Set(selected).size === selected.length && selected.every(id => authorized.includes(id));
const short = (s: string) => s.length > 18 ? s.slice(0, 8) + '…' + s.slice(-6) : s;
export function DecisionFieldsView({ fields, onReference }: {
    fields: DecisionFields;
    onReference?: () => void;
}) {
    const outcome = fields.outcome;
    const row = (label: string, value: string) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>;
    return <div className="ca-draft-grid"><section><h4>Decision Record</h4><dl>
 {row('选择', fields.choice === 'candidate' ? '选择已有候选 · ' + short(fields.candidate_id ?? '') : fields.choice === 'no_action' ? '不行动' : '暂缓')}
 {row('理由', fields.rationale)}{row('责任 / 确认', fields.owner + ' · ' + fields.confirmed_at.replace('T', ' ').replace('.000Z', ' UTC'))}
 {row('替代项', fields.alternatives)}{row('限制 / 未知', fields.limitations)}
 {fields.choice === 'defer' && row('暂缓安排', fields.defer_trigger + ' · ' + fields.defer_owner)}
 <div><dt>依据</dt><dd><details><summary>{fields.evidence_refs.length} 条 Evidence · {fields.finding_refs.length} 条 Finding</summary>{[...fields.evidence_refs, ...fields.finding_refs].map((ref, i) => <p key={ref}><button type="button" title={ref} onClick={onReference} disabled={!onReference}>{i < fields.evidence_refs.length ? 'Evidence' : 'Finding'} · {short(ref)}</button><small>{ref}</small></p>)}</details></dd></div>
 </dl></section><section><h4>Expected Outcome · {outcome.applicable ? '适用' : '不适用'}</h4><dl>{outcome.applicable ? <>
 {row('基线', outcome.baseline)}<div><dt>基线来源</dt><dd><details><summary>{outcome.baseline_source.length > 32 ? '已保存的基线来源 · 查看详情' : outcome.baseline_source}</summary><p>{outcome.baseline_source}</p></details></dd></div>
 {row('对象 / 指标', outcome.observation_object + ' · ' + outcome.metric)}{row('预期', outcome.expectation)}{row('观察窗口', outcome.observation_window)}{row('Guardrails', outcome.guardrails)}{row('结果来源 / Owner', outcome.result_source + ' · ' + outcome.result_owner)}{row('评估安排', outcome.assessment + ' · ' + outcome.assessment_owner)}
 </> : <>{row('不适用原因', outcome.not_applicable_reason)}{row('重新评估', outcome.reassess_trigger + ' · ' + outcome.reassess_owner)}</>}</dl></section></div>;
}
function Modal({ title, onClose, children }: {
    title: string;
    onClose: () => void;
    children: ReactNode;
}) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { const previous = document.activeElement as HTMLElement | null; ref.current?.showModal(); return () => { ref.current?.close(); previous?.focus(); }; }, []); return <dialog className="ca-modal" ref={ref} aria-label={title} onCancel={event => { event.preventDefault(); onClose(); }}><header><h2>{title}</h2><button type="button" aria-label="关闭" onClick={onClose}>×</button></header>{children}</dialog>; }
export function CaseAssistantWorkspace({ api, projectId, sources, initial, onChange, onOpenSource, onChooseProject }: AssistantWorkspaceProps) {
    const settings=useProviderSettings();
    const [p, setP] = useState(initial), [sessions, setSessions] = useState<readonly AssistantSession[]>([]), [text, setText] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [tab, setTab] = useState('authorization');
    const [dialog, setDialog] = useState<'close-parent' | 'link' | 'authorization' | 'edit' | 'reject' | 'adopt' | 'prompt' | 'difference' | 'report' | null>(null), [auth, setAuth] = useState<Authorization | null>(null), [confirmed, setConfirmed] = useState(false), [selectedHistory, setSelectedHistory] = useState<string[]>([]), [selectedReports, setSelectedReports] = useState<string[]>([]), [rebase, setRebase] = useState(false);
    const [source, setSource] = useState<AssistantSource | null>(null), [editing, setEditing] = useState<DecisionFields | null>(null), [reason, setReason] = useState(''), [actor, setActor] = useState(''), [reportId, setReportId] = useState(''), [search, setSearch] = useState('');
    const [reviewed, setReviewed] = useState<{ sessionId: string; draft: AssistantDraft } | null>(null);
    const [stopping, setStopping] = useState(false);
    const [collaboration,setCollaboration]=useState<ParentCollaborationProjection|null>(null),[selectedMaterials,setSelectedMaterials]=useState<string[]>([]);
    async function refreshCollaboration(id:string){const value=await collaborationCall<ParentCollaborationProjection>(api,{version:'1.1',operation:'read_parent',session_id:id});if(liveSession.current===id)setCollaboration(value);}
    useEffect(()=>{setCollaboration(null);setSelectedMaterials([]);if(!p)return;const id=p.session.id;void refreshCollaboration(id).catch(()=>undefined);const timer=setInterval(()=>void refreshCollaboration(id).catch(()=>undefined),500);return()=>clearInterval(timer);},[p?.session.id]);
    const [closeTarget,setCloseTarget]=useState<{id:string;epoch:number;title:string}|null>(null);
    const parentClosed=collaboration?.lifecycle.open===false;
    const stopPending = useRef(false), responseEpoch = useRef(0), actionId = useRef(0);
    const commandId = useRef<string | null>(null), pending = useRef(false), liveSession = useRef<string | null>(null);
    const accept = (value: AssistantProjection) => { liveSession.current = value.session.id; setP(value); onChange(value); };
    async function call<T>(request: CaseAssistantRequest extends infer R ? R extends CaseAssistantRequest ? Omit<R, 'version'> : never : never): Promise<T> { const result = await api.request<T>({ version: '1.0', ...request } as CaseAssistantRequest); if (!result.ok)
        throw new Error(result.error.message); return result.value; }
    async function action(work: () => Promise<void>) { if (pending.current)
        return; const id = ++actionId.current; pending.current = true; setBusy(true); setError(''); try {
        await work();
    }
    catch (e) {
        if (id === actionId.current) setError(e instanceof Error ? e.message : '结果待核对，请重新打开项目。');
    }
    finally {
        if (id === actionId.current) { pending.current = false; setBusy(false); }
    } }
    useEffect(() => { responseEpoch.current++; liveSession.current = initial?.session.id ?? null; setP(initial); setSelectedHistory([]); setSelectedReports([]); setAuth(null); }, [initial?.session.id]);
    useEffect(() => { if (projectId)
        void api.request<readonly AssistantSession[]>({ version: '1.0', operation: 'list', project_id: projectId }).then(r => { if (r.ok)
            setSessions(r.value); }); }, [projectId, p?.session.id]);
    useEffect(() => { if (!p)
        return; let active = true; const sessionId = p.session.id; liveSession.current = sessionId; const timer = setInterval(() => { const epoch = responseEpoch.current; void api.request<AssistantProjection>({ version: '1.0', operation: 'read', session_id: sessionId }).then(r => { if (r.ok && active && liveSession.current === sessionId && epoch === responseEpoch.current)
        accept(r.value); }); }, 500); return () => { active = false; clearInterval(timer); }; }, [p?.session.id]);
    // View switching preserves the Session. Main owns interruption on actual app close.
    const attempt = p?.attempts.at(-1), draft = p?.drafts.at(-1), current = p?.decisions.at(-1), running = attempt?.status === 'Running' || attempt?.status === 'Waiting';
    const draftDecision=p?.decisions.find(d=>d.draft_id===draft?.id&&d.draft_version===draft?.version);
    const draftReport=p?.reports.find(r=>r.id===draftDecision?.report_id&&r.decision_id===draftDecision?.id);
    const draftReportStatus=draft?.status==='adopted'?(draftReport?`已采纳 · 已生成报告 v${draftReport.sequence}；正式记录与报告已保存。`:'已采纳 · 关联报告待核对。'):draft?.status==='rejected'?(draft.reason==='cancelled_manual_revision'?'修订已取消 · 未新增报告。已有正式报告保持不变。':'草案已拒绝 · 未新增报告。已有正式报告保持不变。'):'报告增量预览 · 本草案尚未生成报告；采纳后才追加正式对象。已有正式报告保持不变。';
    const stale = !!draft && draft.status === 'pending' && (!p?.source.eligible || draft.source_revision !== p.source.current_revision_id || draft.baseline_decision_id !== p.current_decision_id), draftActive = !!draft && draft.status === 'pending' && !stale;
    const reviewValid = !!reviewed && reviewed.sessionId === p?.session.id && reviewed.draft.id === draft?.id && reviewed.draft.version === draft?.version && JSON.stringify(reviewed.draft.fields) === JSON.stringify(draft?.fields) && draftActive;
    const reviewNotice = reviewed && !reviewValid ? <p role="alert">草案或会话已变化，请关闭面板后重新审阅。来源 Case 未改变。</p> : null;
    const provider = attempt?.authorization.config ?? auth?.config, synthetic = provider?.provider === 'synthetic';
    async function prepare(nextRebase = false) { if (!p)
        return; setRebase(nextRebase); const value = selectedMaterials.length?await collaborationCall<Authorization>(api,{version:'1.1',operation:'prepare_parent',session_id:p.session.id,text,history_ids:selectedHistory,report_ids:selectedReports,material_ids:selectedMaterials,rebase:nextRebase}):await call<Authorization>({ operation: 'prepare', session_id: p.session.id, text, history_ids: selectedHistory, report_ids: selectedReports, rebase: nextRebase }); setAuth(value); setSelectedReports(value.selected_reports.map(r => r.id)); setConfirmed(false); setDialog('authorization'); }
    async function stop() {
        if (!p || stopPending.current) return;
        const sessionId = p.session.id, epoch = ++responseEpoch.current;
        stopPending.current = true; setStopping(true); setError('');
        try {
            const value = await call<AssistantProjection>({ operation: 'stop', session_id: sessionId });
            if (liveSession.current === sessionId && responseEpoch.current === epoch) {
                // Invalidate reads issued during Stop as well as the older start/send.
                responseEpoch.current++; actionId.current++; pending.current = false; setBusy(false);
                accept(value);
            }
        } catch (e) { setError(e instanceof Error ? e.message : '停止结果待核对，请重新打开项目。'); }
        finally { stopPending.current = false; setStopping(false); }
    }
    async function openSourceChoice(item: SessionSummary) { setSource(await call<AssistantSource>({ operation: 'source', owner: { project_id: projectId!, session_id: item.session_id, case_id: item.case_id, revision_id: item.current_revision_id } })); }
    const closeDialog = () => { setDialog(null); setReviewed(null); setEditing(null); setConfirmed(false); commandId.current = null; };
    const openReport = p?.reports.find(r => r.id === reportId);
    return <div className="ca-workspace">
  <nav className="ca-rail" aria-label="Case Assistant Sessions"><div className="ca-rail-heading"><div><p className="ca-eyebrow">QUICK SESSIONS</p><h1>Case Assistant</h1></div><button type="button" onClick={() => { setSource(null); setDialog('link'); }}>关联一个 Case</button></div><label className="ca-search"><span aria-hidden="true">⌕</span><input placeholder="搜索 Case 或会话" value={search} onChange={e => setSearch(e.target.value)} aria-label="搜索 Case 或会话"/></label>
   <ul>{sessions.filter(s => s.title.includes(search)).map(s => <li key={s.id}><button className={p?.session.id === s.id ? 'selected' : ''} type="button" onClick={() => void action(async () => accept(await openRootConversation(api,s.id)))}><strong>{s.title}</strong><small>来源：{sources.find(item=>item.case_id===s.source.case_id)?.display_name??(p?.session.id===s.id?p.source.case_name:short(s.source.case_id))} · {short(s.source.revision_id)}</small>{p?.session.id === s.id && <small>{statuses[attempt?.status ?? ''] ?? '等待授权'}{draft && ` · ${stale ? '草案过期' : draft.status === 'pending' ? '待采纳草案' : draft.status === 'adopted' ? '已采纳' : '已拒绝'}`}</small>}</button></li>)}</ul>
   {collaboration?.children.map(child=>{const activity=collaboration.activity.find(a=>a.session_id===child.child_session_id);return <button type="button" key={child.child_session_id} onClick={()=>void action(async()=>{await collaborationCall(api,{version:'1.1',operation:'open_child_window',session_id:child.child_session_id});})}><strong>{child.kind==='fork'?'Fork':'Subagent'} · {child.task}</strong><small>{activity?.open?(statuses[activity.status??'']??'等待授权'):'已关闭 · 可重开历史'} · {collaboration.results.filter(r=>r.child_session_id===child.child_session_id).length} 份已保存结果</small></button>;})}
   <div className="ca-footnote"><strong>不是空白聊天</strong><p>每个快速会话关联一个专业 Case revision；对话不会替代正式业务记录。</p></div>
  </nav>
  <main className="ca-conversation" aria-label="Case Assistant 工作区"><header className="ca-header"><div><h2>{p?.session.title ?? '从已确认的 Case 继续'} {p && <span className="ca-linked">已关联专业 Case</span>}</h2>{p && <button className="ca-link" type="button" onClick={() => onOpenSource(p.session.source)}>{p.source.case_name} · revision {short(p.session.source.revision_id)} ↗ 打开专业模式来源</button>}</div><div><span role="status">{stopping ? '正在停止' : busy && (!attempt || running) ? '处理中' : statuses[attempt?.status ?? ''] ?? '等待授权'}</span><button className="ca-danger" type="button" disabled={!running || stopping} onClick={() => void stop()}>停止</button>{p&&<button type="button" disabled={parentClosed} onClick={()=>void(async()=>{try{const state=await collaborationCall<ParentCollaborationProjection>(api,{version:'1.1',operation:'read_parent',session_id:p.session.id});setCloseTarget({id:p.session.id,epoch:state.lifecycle.epoch,title:p.session.title});setDialog('close-parent');}catch(e){setError(String(e));}})()}>关闭父会话</button>}</div></header>
   <div className="ca-scroll">{parentClosed&&<p role="status">父会话已关闭；选择左侧会话可重新打开历史，不会自动运行。</p>}<div className="ca-source-banner"><span className="context-icon" aria-hidden="true">C</span><div><strong>从已确认的 Case 继续，而不是重新分析</strong><p>{p ? `${p.source.evidence_refs.length} 条已验证证据 · ${p.source.finding_id ? 1 : 0} 个已采纳 Finding · ${p.source.limitations.length} 项分析限制` : '选择具有 accepted Finding、Decision Closure 和 final report 的 Completed revision。'}</p></div>{p&&<button className="ca-link" type="button" onClick={()=>onOpenSource(p.session.source)}>查看来源</button>}</div>
    {error && <div className="ca-error" role="alert">{error}</div>}
    {!p && <section className="ca-message"><h3>关联一个专业 Case</h3><p>从已验证证据形成可审阅的决定与预期。只有你明确采纳，Case 才会追加正式记录。</p><button type="button" className="ca-primary" onClick={() => setDialog('link')}>关联一个 Case</button></section>}
    {p && !attempt && <section className="ca-message"><div className="ca-message-meta"><span>CASE ASSISTANT · 建议</span><span>未进入模型任务</span></div><strong>{settings.managed&&settings.status?.state!=='configured'?'先配置模型，再开始讨论':'等待任务授权'}</strong>{settings.managed&&settings.status?.state!=='configured'&&<button type="button" onClick={e=>settings.open(e.currentTarget)}>配置模型</button>}<p>先输入任务，再核对精确外发内容、只读工具和资源上限。</p><p>接入模型后仍需确认本次任务，才会调用模型。</p><button type="button" className="ca-primary" onClick={() => void action(() => prepare(false))}>查看任务授权</button></section>}
    <div className="ca-timeline">{p?.events.filter(e => e.kind !== 'payload' && e.kind !== 'status').map(e => e.kind === 'tool' ? <details className="ca-tool" key={e.id}><summary>{tools[e.tool ?? ''] ?? '工具请求'} · 只读 · {e.status === 'completed' ? '完成' : '已拒绝：超出任务授权'}</summary><p>revision {e.source_revision} · {e.at} · Attempt {short(e.attempt_id)}</p><pre>{e.text}</pre></details> : <article key={e.id} className={`ca-message ${e.kind === 'user' ? 'ca-user' : ''}`}><div className="ca-message-meta"><span>{e.kind === 'user' ? '你' : 'Case Assistant · 建议'}</span><span title={e.at}>Attempt {short(e.attempt_id)} · {new Date(e.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</span></div><p>{e.text}</p></article>)}</div>
    {attempt?.status === 'Waiting' && <p className="ca-callout" role="status">模型执行计时已暂停 · 等待截止：{attempt.waiting_deadline}。可回答或停止。</p>}
    {attempt && !running && attempt.reason && <p className="ca-callout">{statuses[attempt.status]}：{attempt.reason}。已有历史保留，来源 Case 未改变；继续会创建新 Attempt。</p>}
    {draft && <section className="ca-draft"><div className="ca-draft-heading"><div><p className="ca-eyebrow">PENDING DECISION DRAFT</p><h3>待采纳决策草案</h3><p>草案 v{draft.version} · Attempt {short(draft.attempt_id)} · {draft.manual_base_id ? '人工修订 · ' + short(draft.manual_base_id) : draft.edited ? '经用户修改' : '结构已校验'}</p></div><strong>{stale ? '草案已过期' : draft.status === 'pending' ? '待采纳 · 无业务写入' : draft.status === 'adopted' ? '已采纳' : '已拒绝'}</strong></div><p className="ca-muted" title={draft.source_revision}>来源 revision {short(draft.source_revision)}</p><DecisionFieldsView fields={draft.fields} onReference={() => { if (p)
            onOpenSource(p.session.source); }}/>{stale && <div className="ca-error"><strong>来源或当前决定已变化，草案已过期</strong><button type="button" onClick={() => setDialog('difference')}>查看变化</button><button type="button" onClick={() => void action(() => prepare(true))}>基于当前版本重新开始</button></div>}
     <div className="ca-actions">{draft.manual_base_id && draftActive && <button type="button" disabled={busy} onClick={() => void action(async () => { if (p)
            accept(await call<AssistantProjection>({ operation: 'cancel_revision', session_id: p.session.id, draft_id: draft.id, draft_version: draft.version })); })}>取消未确认修订</button>}<button type="button" disabled={!draftActive || busy} onClick={() => { setReviewed({ sessionId: p!.session.id, draft: structuredClone(draft) }); setEditing(structuredClone(draft.fields)); setDialog('edit'); }}>编辑</button><button type="button" disabled={!draftActive || busy} onClick={() => { setReviewed({ sessionId: p!.session.id, draft: structuredClone(draft) }); setDialog('reject'); }}>拒绝草案</button><button type="button" className="ca-primary" disabled={!draftActive || busy} onClick={() => { setReviewed({ sessionId: p!.session.id, draft: structuredClone(draft) }); commandId.current = crypto.randomUUID(); setDialog('adopt'); }}>采纳到 Case</button></div><p className="ca-muted">{draftReportStatus}</p></section>}
    {p&&collaboration&&<ParentCollaborationResults api={api} parent={p} state={collaboration} selected={selectedMaterials} onSelect={ids=>{setSelectedMaterials(ids);setAuth(null);}} onRefresh={()=>refreshCollaboration(p.session.id)}/>}
    {current && <section className="ca-formal"><h3>正式 Decision Record · v{current.sequence}</h3><p>{current.id} · Expected Outcome {current.outcome_id}</p><p>采纳人 {current.actor} · {current.adopted_at} · 来源 revision {short(current.source.revision_id)}</p><button type="button" onClick={() => onOpenSource(p!.session.source)}>返回专业模式查看</button>{attempt?.authorization.baseline_decision_id !== current.id && <button type="button" onClick={() => void action(() => prepare(true))}>基于当前版本重新开始</button>}<button type="button" onClick={() => void action(async () => { if (p)
        accept(await call<AssistantProjection>({ operation: 'revise', session_id: p.session.id, decision_id: current.id })); })}>修订当前正式决定</button></section>}
   </div>
   <form className="ca-composer" onSubmit={e => { e.preventDefault(); void action(async () => { if (!p)
        return; if (attempt?.status === 'Waiting') {
        const epoch = responseEpoch.current, sessionId = p.session.id;
        const value = await call<AssistantProjection>({ operation: 'send', session_id: sessionId, text });
        if (epoch === responseEpoch.current && liveSession.current === sessionId) { accept(value); setText(''); }
    }
    else
        await prepare(false); }); }}><div className="ca-capabilities"><ChildCreationControl kind="fork" api={api} parent={p} disabled={parentClosed||running||busy||stopping}/><ChildCreationControl kind="subagent" api={api} parent={p} disabled={parentClosed||running||busy||stopping}/><button type="button" disabled={!p || parentClosed || running || busy || stopping} onClick={() => void action(() => prepare(false))}>继续此工作</button></div><div className="ca-composer-box"><textarea aria-label="Case Assistant 任务文本" placeholder="追问选择、约束、责任人或预期结果…" value={text} onChange={e => setText(e.target.value)} disabled={attempt?.status === 'Running' || busy || stopping}/><button className="ca-send" aria-label="发送" title="发送当前可见文本" type="submit" disabled={!p || parentClosed || !text.trim() || busy || stopping || attempt?.status === 'Running'}>↑</button></div><p>{provider ? `${provider.provider} / ${provider.model}` : settings.label} · 发送当前可见文本；不会自动附加本地文件或未选择历史。</p></form>
  </main>
  <aside className="ca-inspector" aria-label="任务授权与来源"><div className="ca-tabs">{[['authorization', '授权'], ['source', '来源'], ['skill', '能力'], ['history', '历史']].map(([id, label]) => <button type="button" key={id} aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</button>)}</div><div className="ca-inspector-body">
   {collaboration?.occupant&&<p role="status">模型占用：{collaboration.occupant.label} · {collaboration.occupant.session_id??'接入设置'}{collaboration.occupant.session_id&&collaboration.occupant.session_id!==p?.session.id&&collaboration.children.some(c=>c.child_session_id===collaboration.occupant!.session_id)&&<button type="button" onClick={()=>void action(async()=>{await collaborationCall(api,{version:'1.1',operation:'open_child_window',session_id:collaboration.occupant!.session_id!});})}>打开占用子任务并停止</button>}</p>}<p className="ca-environment">{synthetic ? 'UI Contract · 合成状态 · 无真实模型调用' : provider ? '受授权任务' : settings.label}{!synthetic&&!provider&&settings.status?.state!=='configured'&&<> <button type="button" onClick={e=>settings.open(e.currentTarget)}>配置模型</button></>}</p>
   {tab === 'authorization' && <><section className="ca-inspector-card"><h3>任务授权</h3><div className="drawer-row"><span>来源</span><strong>{p?.source.case_name??'尚未关联 Case'}</strong></div><div className="drawer-row"><span>Provider / Model</span><strong>{provider ? `${provider.provider} / ${provider.model}` : settings.label}</strong></div>{provider&&<div className="drawer-row"><span>执行 / 等待</span><strong>{provider.limits.execution_ms/1000}s / {provider.limits.waiting_ms/1000}s</strong></div>}{attempt && <><p>剩余轮次 {Math.max(0, (provider?.limits.turns ?? 0) - attempt.turns)}</p><p>已用模型时间 {attempt.execution_ms} ms</p><p>{budget(attempt.cost_microunits, provider?.limits.cost_microunits ?? 0, provider?.limits.currency ?? '')}</p></>}{xiaomiLimits(provider ?? null)}<p className="drawer-callout">授权会列出逐字文本、精确 subset 和实际历史外发清单。正式记录必须由你确认。</p></section><button type="button" className="ca-primary" disabled={!p || busy || running} onClick={() => void action(() => prepare(false))}>查看完整授权</button></>}
   {tab === 'source' && <section className="ca-inspector-card"><h3>来源与已验证范围</h3>{p ? <><p>{p.source.case_name}</p><p>revision {p.source.owner.revision_id}</p><p>{p.source.eligible ? 'Completed · 前置条件完整' : p.source.missing.join('；')}</p><h4>分析限制</h4><ul>{p.source.limitations.map(x => <li key={x}>{x}</li>)}</ul><h4>Evidence / Finding</h4><p>{p.source.finding_id}</p><ul>{p.source.evidence_refs.map(x => <li key={x}><button type="button" onClick={() => onOpenSource(p.session.source)}>{x}</button></li>)}</ul><details><summary>精确 aggregate 身份与范围</summary><pre>{JSON.stringify(p.source.aggregate, null, 2)}</pre></details></> : <p>尚未关联 Case</p>}</section>}
   {tab === 'skill' && <section className="ca-inspector-card"><h3>Case 决策与预期 v1.0</h3><p>把授权 Case 的已验证证据整理成 Decision Record 与 Expected Outcome 待采纳草案。</p><p>只读已授权业务投影；禁止原始数据、Shell、SQL、Web、行动执行。</p><p>版本说明：首个受约束决策与预期协作版本。</p><button type="button" onClick={() => setDialog('prompt')}>查看 Prompt 信息</button></section>}
   {tab === 'history' && <><section className="ca-inspector-card"><h3>报告版本</h3>{p && <p>原 final report {short(p.source.report.report_id)} · {p.reports.length ? 'superseded history' : '当前原报告'} <button type="button" onClick={() => onOpenSource(p.session.source)}>打开原报告</button></p>}{p?.reports.map((r, i) => <p key={r.id}><button type="button" onClick={() => { setReportId(r.id); setDialog('report'); }}>报告 v{r.sequence} · {i === p.reports.length - 1 ? '当前' : 'superseded history'}</button></p>)}</section><section className="ca-inspector-card"><h3>实际 payload 审计</h3>{p?.events.filter(e => e.kind === 'payload').map(e => <details key={e.id}><summary>{e.at} · Attempt {short(e.attempt_id)}</summary><pre>{e.text}</pre></details>)}</section><section className="ca-inspector-card"><h3>草案版本历史</h3>{p?.drafts.map(d => <details key={`${d.id}:${d.version}`}><summary>草案 v{d.version} · {d.status} · {d.created_at}</summary><DecisionFieldsView fields={d.fields}/></details>)}</section></>}
   <p className="ca-muted">Case 决策与预期 v1.0 · Prompt 1.0</p>
  </div></aside>
  {dialog==='close-parent'&&closeTarget&&<Modal title="关闭父会话" onClose={closeDialog}><p>关闭“{closeTarget.title}”并停止其所有未结束子任务。已有历史与结果保留，其他父会话不变。重新打开不会自动调用模型或回流。</p><div className="ca-actions"><button type="button" onClick={closeDialog}>取消</button><button type="button" className="ca-danger" onClick={()=>void(async()=>{const target=closeTarget;responseEpoch.current++;actionId.current++;pending.current=false;setAuth(null);setBusy(false);try{await collaborationCall(api,{version:'1.1',operation:'close',session_id:target.id,expected_epoch:target.epoch,confirmed:true});closeDialog();if(liveSession.current===target.id){accept(await call<AssistantProjection>({operation:'read',session_id:target.id}));await refreshCollaboration(target.id);}}catch(e){setError(String(e));}})()}>关闭并停止</button></div></Modal>}
  {dialog === 'link' && <Modal title="关联一个 Case" onClose={closeDialog}>{!projectId ? <><p>先选择本地 Project。不会自动访问其他目录。</p><button type="button" onClick={() => { closeDialog(); onChooseProject(); }}>选择项目</button></> : <><p>只有 Completed、accepted Finding、有效 Closure 和 final report 均完整的来源可以开始。</p><ul>{sources.filter(s => s.display_name.includes(search)).map(s => <li key={s.session_id}><button type="button" onClick={() => void action(() => openSourceChoice(s))}>{s.display_name}</button></li>)}</ul>{source && <><h3>{source.case_name}</h3><p>revision {source.owner.revision_id}</p>{source.missing.map(x => <p key={x} role="status">{x}</p>)}<button type="button" disabled={!source.eligible || busy} className="ca-primary" onClick={() => void action(async () => { accept(await call<AssistantProjection>({ operation: 'link', owner: source.owner, title: source.case_name + ' · 决策', command_id: crypto.randomUUID() })); closeDialog(); })}>关联此 Case</button><button type="button" onClick={() => onOpenSource(source.owner)}>返回专业模式补齐</button></>}</>}</Modal>}
  {dialog === 'authorization' && auth && <Modal title="确认任务级授权" onClose={closeDialog}>
   <div className="grant-grid"><section><h3>来源与模型</h3><p>来源 {auth.source.case_name} · revision {auth.source.owner.revision_id}</p><p>当前正式基线 {auth.baseline_decision_id ?? '尚无正式决定'}</p><p>Provider / Model：{auth.config ? `${auth.config.provider} / ${auth.config.model}` : '未授权'}</p></section>
   <section><h3>精确资源硬上限</h3>{auth.config ? <p>{auth.config.limits.turns} 轮 · 模型执行 {auth.config.limits.execution_ms} ms · 每次等待 {auth.config.limits.waiting_ms} ms · {budget(0, auth.config.limits.cost_microunits, auth.config.limits.currency)}</p> : <p>缺少 Provider 和预算配置，禁止开始。</p>}{xiaomiLimits(auth.config)}</section>
   <section><h3>会发送</h3><p>数据类别 {auth.categories.join('、')}</p><p>仅本面板精确列出的 subset、文本和选择历史。</p></section><section><h3>不会发送 / 不能使用</h3><p>不会发送原始上传文件、其他 Case/Session、未选择历史、附件、路径或日志；不执行 Shell / SQL / Web / Fork / Subagent / 行动。</p></section></div>
   <section className="payload-preview"><h3>初始文本（逐字发送）</h3><pre>{auth.initial_text}</pre><p>后续每次发送会逐字发给该 Provider；同一 Attempt 中已经授权的追问、回答及工具回执维持上下文。</p></section>
   <section className="payload-preview"><h3>精确数据 subset</h3><p>artifact {auth.source.aggregate.artifact_id} · SHA-256 {auth.source.aggregate.sha256}</p><p>字段 {auth.source.aggregate.fields.join('、')}</p><pre>{auth.source.aggregate.scope}</pre></section>
   <p className="authorized-tools">只读工具：{auth.tools.map(t => tools[t]).join('、')}</p>
   <ParentMaterialDisclosure authorization={auth}/>
   <label className="sensitive-confirm"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)}/>我单独确认上述自由文本可能包含敏感业务内容，并同意逐字发送。</label>
   <h3>新 Attempt 的历史外发清单</h3>{p?.events.filter(e => ['user', 'advice', 'question', 'tool'].includes(e.kind) && (!rebase || e.kind === 'user')).map(e => <label className="ca-check" key={e.id}><input type="checkbox" checked={selectedHistory.includes(e.id)} onChange={ev => setSelectedHistory(v => ev.target.checked ? [...v, e.id] : v.filter(x => x !== e.id))}/>{e.kind} · {e.text}</label>)}<h3>报告版本摘要</h3>{p && [{ id: p.source.report.report_id, label: '原 final report' }, ...p.reports.map(r => ({ id: r.id, label: `正式报告 v${r.sequence}` }))].map(r => <label className="ca-check" key={r.id}><input type="checkbox" checked={selectedReports.includes(r.id)} onChange={e => setSelectedReports(v => e.target.checked ? [...v, r.id] : v.filter(id => id !== r.id))}/>{r.label} · {short(r.id)}</label>)}<p>未勾选历史不重发。重新绑定 revision 时旧 Evidence、Finding、报告、工具及模型文本全部排除。</p><button type="button" onClick={() => void action(() => prepare(rebase))}>更新并核对外发清单</button><details><summary>实际确认载荷与报告摘要</summary><pre>{auth.payload}</pre></details><p>Case 决策与预期 v1.0 · Prompt 1.0</p>{auth.blockers.map(x => <p className="ca-error" role="status" key={x}>{x}</p>)}<div className="ca-actions"><button type="button" onClick={closeDialog}>取消</button><button type="button" className="ca-primary" disabled={!confirmed || auth.blockers.length > 0 || busy || !sameSelection(selectedHistory, auth.selected_history.map(e => e.id)) || !sameSelection(selectedReports, auth.selected_reports.map(r => r.id))} onClick={() => void action(async () => { if (!p) return;
        const epoch = responseEpoch.current, sessionId = p.session.id, authorizationId = auth.id;
        closeDialog();
        const value = await call<AssistantProjection>({ operation: 'start', session_id: sessionId, authorization_id: authorizationId, free_text_confirmed: true });
        if (epoch === responseEpoch.current && liveSession.current === sessionId) {accept(value);setSelectedMaterials([]);} })}>确认并开始</button></div></Modal>}
  {dialog === 'edit' && editing && reviewed && p && <Modal title="编辑待采纳草案" onClose={closeDialog}>{reviewNotice}<DraftEditor fields={editing} source={p.source} onChange={setEditing}/><div className="ca-actions"><button type="button" onClick={closeDialog}>取消未确认编辑</button><button type="button" className="ca-primary" disabled={busy || !reviewValid} onClick={() => void action(async () => { if (!reviewValid) return; validateAssistantDecision(editing, p.source); accept(await call<AssistantProjection>({ operation: 'edit', session_id: reviewed.sessionId, draft_id: reviewed.draft.id, draft_version: reviewed.draft.version, fields: editing })); closeDialog(); })}>保存字段</button></div>{error && <p role="alert">{error}</p>}</Modal>}
  {dialog === 'reject' && reviewed && p && <Modal title="确认拒绝草案" onClose={closeDialog}>{reviewNotice}<p>来源 Case 不会改变，对话和草案历史保留。</p><label>拒绝原因（可选）<textarea value={reason} onChange={e => setReason(e.target.value)}/></label><button type="button" onClick={closeDialog}>取消</button><button type="button" disabled={busy || !reviewValid} onClick={() => void action(async () => { if (!reviewValid) return; accept(await call<AssistantProjection>({ operation: 'reject', session_id: reviewed.sessionId, draft_id: reviewed.draft.id, draft_version: reviewed.draft.version, confirmed: true, reason })); closeDialog(); })}>确认拒绝</button></Modal>}
  {dialog === 'adopt' && reviewed && p && <Modal title="采纳到 Case" onClose={closeDialog}>{reviewNotice}<p>将在来源 revision {reviewed.draft.source_revision} 追加 Decision Record、Expected Outcome 和一个正式报告版本。</p><p>Completed 分析 revision、原 Decision Closure 和原 final report 均保留；不执行行动或观察结果。</p><label>采纳人<input value={actor} onChange={e => setActor(e.target.value)} required/></label><button type="button" onClick={closeDialog}>取消</button><button type="button" className="ca-primary" disabled={busy || !actor.trim() || !reviewValid} onClick={() => void action(async () => { if (!reviewValid) return; accept(await call<AssistantProjection>({ operation: 'adopt', session_id: reviewed.sessionId, draft_id: reviewed.draft.id, draft_version: reviewed.draft.version, actor, command_id: commandId.current! })); closeDialog(); })}>确认采纳</button>{error && <p role="alert">{error}</p>}</Modal>}
  {dialog === 'prompt' && <Modal title="Prompt 信息 · 只读" onClose={closeDialog}><h3>Case 决策与预期 v1.0 / Prompt 1.0</h3><p>用途：依据已验证 Case 协作形成决策与预期草案。输入只含精确授权的业务投影、用户文本、聚合 subset、报告摘要及选择历史。</p><p>输出只能是建议、问题、只读业务工具请求或 Decision Record / Expected Outcome 待采纳草案。用户确认前不写正式记录。</p><p>本版本不支持编辑、导入、自定义 Skill、Web 或行动执行。</p></Modal>}
  {dialog === 'difference' && p && <Modal title="来源与当前决定变化" onClose={closeDialog}><p>原 revision {p.session.source.revision_id}</p><p>当前 revision {p.source.current_revision_id}</p><p>草案基线 {draft?.baseline_decision_id ?? '无'} → 当前正式记录 {p.current_decision_id ?? '无'}</p>{p.session.source.revision_id !== p.source.current_revision_id ? <button type="button" onClick={() => { setSource(null); setDialog('link'); }}>关联新 Completed revision</button> : <button type="button" onClick={() => void action(() => prepare(true))}>基于当前版本重新开始</button>}</Modal>}
  {dialog === 'report' && openReport && p && <Modal title={`报告 v${openReport.sequence}`} onClose={closeDialog}><p>{openReport.id} · {openReport.created_at} · 原报告 {openReport.original_report_id}</p>{p.decisions.filter(d => d.id === openReport.decision_id).map(d => <div key={d.id}><p>采纳人 {d.actor} · {d.adopted_at} · revision {d.source.revision_id}</p><DecisionFieldsView fields={d.fields}/></div>)}<button type="button" disabled={busy} onClick={() => void action(async () => { await call({ operation: 'export', session_id: p.session.id, report_id: openReport.id, command_id: crypto.randomUUID() }); })}>导出此报告</button>{error && <p role="alert">{error}</p>}</Modal>}
 </div>;
}
function DraftEditor({ fields, source, onChange }: {
    fields: DecisionFields;
    source: AssistantSource;
    onChange: (v: DecisionFields) => void;
}) { return <form className="ca-edit" onSubmit={e => e.preventDefault()}><label>决定选择<select value={fields.choice} onChange={e => onChange({ ...fields, choice: e.target.value as DecisionFields['choice'], candidate_id: e.target.value === 'candidate' ? source.candidates[0]?.candidate_id ?? null : null })}><option value="candidate">选择已有候选</option><option value="no_action">不行动</option><option value="defer">暂缓</option></select></label>{fields.choice === 'candidate' && <label>来源已保存候选<select value={fields.candidate_id ?? ''} onChange={e => onChange({ ...fields, candidate_id: e.target.value })}><option value="">请选择</option>{source.candidates.map(c => <option key={c.candidate_id} value={c.candidate_id}>{c.title}</option>)}</select></label>}{Object.entries(fields).filter(([k]) => !['choice', 'candidate_id', 'outcome'].includes(k)).map(([k, v]) => <label key={k}>{fieldLabels[k]}<textarea aria-label={fieldLabels[k]} required={!['defer_trigger', 'defer_owner'].includes(k) || fields.choice === 'defer'} value={Array.isArray(v) ? v.join('\n') : String(v)} onChange={e => onChange({ ...fields, [k]: Array.isArray(v) ? e.target.value.split('\n') : e.target.value })}/></label>)}<fieldset><legend>Expected Outcome</legend><label><input type="checkbox" checked={fields.outcome.applicable} onChange={e => onChange({ ...fields, outcome: { ...fields.outcome, applicable: e.target.checked } })}/>适用；不行动/暂缓可标记不适用并说明</label>{Object.entries(fields.outcome).filter(([k]) => k !== 'applicable').map(([k, v]) => <label key={k}>{fieldLabels[k]}<textarea aria-label={fieldLabels[k]} value={String(v)} onChange={e => onChange({ ...fields, outcome: { ...fields.outcome, [k]: e.target.value } })}/></label>)}</fieldset></form>; }

async function collaborationCall<T>(api:CaseAssistantApi,input:import('../../packages/contracts/case-collaboration.ts').CollaborationRequest):Promise<T>{const r=await api.request<T>(input);if(!r.ok)throw new Error(r.error.message);return r.value;}
export async function openRootConversation(api:CaseAssistantApi,id:string):Promise<AssistantProjection>{
 const state=await collaborationCall<ParentCollaborationProjection>(api,{version:'1.1',operation:'read_parent',session_id:id});
 if(!state.lifecycle.open)await collaborationCall(api,{version:'1.1',operation:'reopen',session_id:id,expected_epoch:state.lifecycle.epoch});
 const r=await api.request<AssistantProjection>({version:'1.0',operation:'read',session_id:id});if(!r.ok)throw new Error(r.error.message);return r.value;
}
function ChildCreationControl({api,parent,disabled,kind}:{api:CaseAssistantApi;parent:AssistantProjection|null;disabled:boolean;kind:'fork'|'subagent'}){
 const label=kind==='fork'?'Fork':'Subagent';
 const [open,setOpen]=useState(false),[task,setTask]=useState(''),[cutoff,setCutoff]=useState(''),[history,setHistory]=useState<string[]>([]),[reports,setReports]=useState<string[]>([]),[data,setData]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState<string|null>(null);
 const command=useRef<string|null>(null),visible=parent?.events.filter(e=>['user','advice','question','tool'].includes(e.kind))??[],position=visible.findIndex(e=>e.id===cutoff);
 async function create(){if(!parent||busy)return;setBusy(true);setError('');try{
  const preview=await collaborationCall<import('../../packages/contracts/case-collaboration.ts').ChildPreview>(api,{version:'1.1',operation:'prepare_child',session_id:parent.session.id,kind,task,cutoff_id:kind==='fork'?cutoff:null,history_ids:history,report_ids:reports,include_aggregate:data});
  if(JSON.stringify(preview.source)!==JSON.stringify(parent.source)||preview.baseline_decision_id!==parent.current_decision_id)throw new Error('来源已变化，请关闭后重新核对。');
  const child=await collaborationCall<import('../../packages/contracts/case-collaboration.ts').CollaborationProjection>(api,{version:'1.1',operation:'create_child',session_id:parent.session.id,preview_id:preview.id,command_id:command.current??(command.current=crypto.randomUUID()),confirmed:true});
  setSaved(child.session.id);await collaborationCall(api,{version:'1.1',operation:'open_child_window',session_id:child.session.id});setOpen(false);
 }catch(e){setError(e instanceof Error?e.message:'创建结果待核对');}finally{setBusy(false);}}
 return <><button type="button" disabled={disabled||!parent?.source.eligible||kind==='fork'&&visible.length===0} onClick={()=>{setOpen(true);setTask('');setCutoff('');setHistory([]);setReports([]);setData(false);setError('');setSaved(null);command.current=null;}}>{label}</button>
 {open&&parent&&<Modal title={`创建 ${label} · 预览继承范围`} onClose={()=>setOpen(false)}><p>仅创建独立子对话。模型运行需要之后在子窗口单独授权。</p><p>{parent.source.case_name} · revision {parent.source.owner.revision_id} · 正式基线 {parent.current_decision_id??'无'}</p>
 <label>{kind==='fork'?'本次讨论目的':'本次有界任务'}<textarea value={task} onChange={e=>{setTask(e.target.value);command.current=null;}}/></label>
 {kind==='fork'&&<label>选择父对话历史位置<select value={cutoff} onChange={e=>{setCutoff(e.target.value);setHistory([]);command.current=null;}}><option value="">请选择已保存分叉点</option>{visible.map(e=><option key={e.id} value={e.id}>{e.kind} · {e.text.slice(0,60)}</option>)}</select></label>}
 <fieldset><legend>{kind==='fork'?'截至该位置，逐项选择继承历史':'逐项选择任务所需历史'}</legend>{visible.map((e,i)=><label className="ca-check" key={e.id}><input type="checkbox" disabled={kind==='fork'&&(position<0||i>position)} checked={history.includes(e.id)} onChange={ev=>{setHistory(v=>ev.target.checked?[...v,e.id]:v.filter(id=>id!==e.id));command.current=null;}}/>{e.text}<small>Attempt {e.attempt_id} · {e.status}</small></label>)}</fieldset>
 <fieldset><legend>获准材料（可选）</legend><label className="ca-check"><input type="checkbox" checked={data} onChange={e=>{setData(e.target.checked);command.current=null;}}/>已验证聚合与 Evidence / Finding / 候选业务投影；不含原始行。<small>{parent.source.aggregate?.artifact_id} · {parent.source.aggregate?.sha256}</small></label>{[{id:parent.source.report.report_id,title:'原 final report 摘要'},...parent.reports.map(r=>({id:r.id,title:`报告 v${r.sequence} 摘要`}))].map(r=><label className="ca-check" key={r.id}><input type="checkbox" checked={reports.includes(r.id)} onChange={e=>{setReports(v=>e.target.checked?[...v,r.id]:v.filter(id=>id!==r.id));command.current=null;}}/>{r.title} · {r.id}</label>)}</fieldset>
 <p>未勾选历史不继承；父对话后续消息不会自动追加。</p>{kind==='subagent'&&<p>完成本次任务后自动回流待审结果；失败或停止不产生完整结果。</p>}{error&&<p role="alert">{error}</p>}{saved?<button type="button" onClick={()=>void collaborationCall(api,{version:'1.1',operation:'open_child_window',session_id:saved}).catch(e=>setError(e.message))}>重新打开已创建子窗口</button>:<div className="ca-actions"><button type="button" onClick={()=>setOpen(false)}>取消</button><button type="button" className="ca-primary" disabled={busy||!task.trim()||kind==='fork'&&position<0} onClick={()=>void create()}>创建独立子窗口</button></div>}</Modal>}</>;
}
export function ChildAssistantWorkspace({api,sessionId}:{api:CaseAssistantApi;sessionId:string}){
 const [p,setP]=useState<import('../../packages/contracts/case-collaboration.ts').CollaborationProjection|null>(null),[error,setError]=useState(''),[text,setText]=useState(''),[auth,setAuth]=useState<Authorization|null>(null),[confirmed,setConfirmed]=useState(false),[history,setHistory]=useState<string[]>([]),[results,setResults]=useState<string[]>([]),[busy,setBusy]=useState(false),[stopping,setStopping]=useState(false);
 const epoch=useRef(0),pending=useRef(false),returnCommands=useRef(new Map<string,string>());
 const read=()=>collaborationCall<import('../../packages/contracts/case-collaboration.ts').CollaborationProjection>(api,{version:'1.1',operation:'read_collaboration',session_id:sessionId});
 useEffect(()=>{let active=true;const poll=()=>{const at=epoch.current;void read().then(value=>{if(active&&at===epoch.current)setP(value);}).catch(e=>{if(active)setError(e.message);});};poll();const timer=setInterval(poll,500);return()=>{active=false;clearInterval(timer);epoch.current++;};},[api,sessionId]);
 async function action(work:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:'结果待核对');}finally{pending.current=false;setBusy(false);}}
 const r=p?.relation,attempt=p?.attempts.at(-1),running=!!attempt&&['Running','Waiting'].includes(attempt.status),valid=!!p?.valid&&p.lifecycle.open&&p.parent_lifecycle.open;
 async function prepare(){const value=await collaborationCall<Authorization>(api,{version:'1.1',operation:'prepare',session_id:sessionId,text,history_ids:history,result_ids:results});setAuth(value);setConfirmed(false);}
 async function stop(){if(stopping)return;setStopping(true);epoch.current++;setAuth(null);try{await collaborationCall(api,{version:'1.1',operation:'stop',session_id:sessionId});epoch.current++;setP(await read());}catch(e){setError(String(e));}finally{setStopping(false);}}
 const select=(value:string,checked:boolean,update:(f:(old:string[])=>string[])=>void)=>{setAuth(null);setConfirmed(false);update(old=>checked?[...old,value]:old.filter(id=>id!==value));};
 const limits=auth?.config??attempt?.authorization.config;
 return <div className="ca-workspace"><nav className="ca-rail" aria-label="父子会话"><div className="ca-rail-heading"><h1>{r?.kind==='subagent'?'Subagent':'Fork'}</h1></div><button type="button" disabled={!r} onClick={()=>void action(async()=>{await collaborationCall(api,{version:'1.1',operation:'focus_parent',session_id:sessionId});})}>返回父对话</button><p>父对话 {r?.parent_session_id}</p><strong>{p?.session.title}</strong><h3>Attempt 历史</h3>{p?.attempts.map(a=><p key={a.id}>Attempt {short(a.id)} · {statuses[a.status]} · {a.reason}</p>)}</nav>
 <main className="ca-conversation" aria-label="独立子对话"><header className="ca-header"><div><h2>{p?.session.title??'正在读取已保存子对话'}</h2><p>{r?.kind==='subagent'?'Subagent':'Fork'} · 独立历史</p></div><div><span role="status">{attempt?.status==='Succeeded'?'结果已保存':statuses[attempt?.status??'']??'等待任务授权'}</span><button type="button" className="ca-danger" disabled={(!running&&!busy)||stopping} onClick={()=>void stop()}>停止</button></div></header>
 <div className="ca-scroll">{error&&<p role="alert">{error}</p>}{p&&!valid&&<section className="ca-error"><strong>来源或会话已失效，保留历史</strong><p>revision {r?.source.owner.revision_id} → {p.current_source.current_revision_id}</p><p>正式基线 {r?.baseline_decision_id??'无'} → {p.current_decision_id??'无'}</p>{p.current_source.missing.map(x=><p key={x}>{x}</p>)}<p>返回父对话核对来源；不自动重新绑定。</p></section>}
 <section className="ca-source-banner"><div><strong>{r?.source.case_name}</strong><p>分叉点 {r?.cutoff_id??'有界任务'} · revision {r?.source.owner.revision_id}</p></div></section><p>{r?.task}</p><details><summary>继承自父对话 · 只读历史快照</summary>{r?.selected_history.map(e=><article className="ca-message" key={e.id}><small>{e.kind} · Attempt {e.attempt_id} · {e.status}</small><p>{e.text}</p></article>)}</details>
 <h3>自己的历史</h3>{p?.events.filter(e=>!['payload','status'].includes(e.kind)).map(e=><article className={'ca-message '+(e.kind==='user'?'ca-user':'')} key={e.id}><small>{e.kind} · Attempt {short(e.attempt_id)} · {e.status}</small><p>{e.text}</p></article>)}{attempt?.status==='Waiting'&&<p role="status">等待用户 · 截止 {attempt.waiting_deadline}；回答只发送当前可见文本。</p>}
 <h3>完整结果</h3>{p?.results.map(result=>{const delivery=p.deliveries.find(d=>d.result_id===result.id);return <section className="ca-message" key={result.id}><ChildResultView result={result}/><p>{delivery?.status==='returned'?'已回流 · 待父对话处理':delivery?.status==='failed'?'结果已保存 · 回流失败':'结果已保存 · 尚未回流'}{delivery?.error&&' · '+delivery.error}</p><button type="button" disabled={busy||!valid||delivery?.status==='returned'} onClick={()=>void action(async()=>{let command=returnCommands.current.get(result.id);if(!command){command=crypto.randomUUID();returnCommands.current.set(result.id,command);}await collaborationCall(api,{version:'1.1',operation:'return_result',session_id:sessionId,result_id:result.id,result_version:result.version,result_sha256:result.sha256,command_id:command});setP(await read());})}>{delivery?.status==='failed'?'重试回流':'回流到来源对话'}</button></section>;})}</div>
 <form className="ca-composer" onSubmit={e=>{e.preventDefault();void action(async()=>{if(attempt?.status==='Waiting'){await collaborationCall(api,{version:'1.1',operation:'send',session_id:sessionId,text});setText('');setP(await read());}else await prepare();});}}><div className="ca-composer-box"><textarea aria-label="子任务文本" placeholder="继续讨论前，核对本次任务与材料…" value={text} disabled={attempt?.status==='Running'||busy||!valid} onChange={e=>{setText(e.target.value);setAuth(null);}}/><button className="ca-send" aria-label={attempt?.status==='Waiting'?'确认并发送当前文本':'查看任务授权'} title={attempt?.status==='Waiting'?'确认并发送当前文本':'查看任务授权'} type="submit" disabled={!valid||!text.trim()||busy||attempt?.status==='Running'}>↑</button></div><p>新 Attempt 默认不包含自身历史或完整结果。</p></form></main>
 <aside className="ca-inspector ca-child-inspector" aria-label="子任务来源与授权"><div className="ca-inspector-body"><div className="ca-child-source"><h3>固定来源</h3><p>{r?.source.case_name}</p><p>正式基线 {r?.baseline_decision_id??'无'}</p>{p?.occupant&&<p role="status">模型占用：{p.occupant.label} · {p.occupant.session_id??'接入设置'}</p>}<h3>所选报告</h3>{r?.selected_reports.map(v=><details key={v.id}><summary>{v.id}</summary><pre>{v.summary}</pre></details>)}<h3>聚合与业务投影</h3><p>{r?.aggregate?`${r.aggregate.artifact_id} · ${r.aggregate.sha256}`:'未选择，不外发'}</p><p>MODEL 意见须回流后人工处理；子对话不发布正式记录。</p>
</div>
 <ChildContextSelection projection={p} history={history} results={results} disabled={running||busy} onHistory={(id,checked)=>select(id,checked,setHistory)} onResult={(id,checked)=>select(id,checked,setResults)}/></div></aside>
 {auth&&<Modal title="子任务精确授权" onClose={()=>{setAuth(null);setConfirmed(false);}}><p>任务：{auth.initial_text}</p><p>Provider / Model：{auth.config?`${auth.config.provider} / ${auth.config.model}`:'未配置'}</p><p>Skill {auth.skill_version} · Prompt {auth.prompt_version}</p><p>只读工具：{auth.tools.map(t=>tools[t]).join('、')}</p>{limits&&<><p>最多 {limits.limits.turns} 轮 · 执行 {limits.limits.execution_ms/1000}s · 等待 {limits.limits.waiting_ms/1000}s</p><p>{budget(0,limits.limits.cost_microunits,limits.limits.currency)}</p>{xiaomiLimits(limits)}</>}<details open><summary>精确外发内容、来源与选择范围</summary><pre>{auth.payload}</pre></details>{auth.blockers.map(b=><p role="status" key={b}>{b}</p>)}<label className="sensitive-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我确认上述自由文本及所选内容，并同意逐字发送。</label><div className="ca-actions"><button type="button" onClick={()=>setAuth(null)}>取消</button><button type="button" className="ca-primary" disabled={!valid||busy||!confirmed||auth.blockers.length>0} onClick={()=>void action(async()=>{const grant=auth;setAuth(null);setConfirmed(false);await collaborationCall(api,{version:'1.1',operation:'start',session_id:sessionId,authorization_id:grant.id,free_text_confirmed:true});setHistory([]);setResults([]);setText('');setP(await read());})}>确认并开始</button></div></Modal>}</div>;
}
function ChildResultView({result}:{result:import('../../packages/contracts/case-collaboration.ts').ChildResult}){return <><h4>MODEL · 结果 v{result.version}</h4><p>{result.value.summary}</p><p>来源 {result.source.case_name} · revision {result.source.owner.revision_id} · Attempt {result.attempt_id}</p><p>正式基线 {result.baseline_decision_id??'无'} · {result.sha256}</p><h5>引用</h5>{result.value.references.map(ref=><p key={ref.kind+ref.id}>{ref.kind} · {ref.id} · {ref.version} · {ref.sha256}</p>)}<h5>限制</h5>{result.value.limitations.map((x,i)=><p key={i}>{x}</p>)}<h5>未知事项</h5>{result.value.unknowns.map((x,i)=><p key={i}>{x}</p>)}</>;}

export function ParentMaterialDisclosure({authorization}:{authorization:Authorization}){
 const materials=JSON.parse(authorization.payload).selected_materials as readonly {id:string;classification:'MODEL';review:import('../../packages/contracts/case-collaboration.ts').ChildReview;result:Pick<ChildResult,'id'|'version'|'sha256'|'child_session_id'|'attempt_id'|'value'>&{source:OwnerRef}}[]|undefined;
 return <section className="ca-material-disclosure" aria-label="本次授权的 MODEL 材料"><h3>本次选择的 MODEL 材料</h3>{!materials?.length?<p>未选择子材料，本次不发送。</p>:materials.map(m=><article className="ca-inspector-card" key={m.id}><h4>MODEL · 结果 v{m.result.version}</h4><p>{m.result.value.summary}</p><dl><dt>来源 Case / revision</dt><dd>{authorization.source.case_name} · {m.result.source.case_id} · {m.result.source.revision_id}</dd><dt>子对话 / 原 Attempt</dt><dd>{m.result.child_session_id} · {m.result.attempt_id}</dd><dt>结果身份 / SHA-256</dt><dd>{m.result.id} · {m.result.sha256}</dd><dt>正式决定基线</dt><dd>{authorization.baseline_decision_id??'无'}</dd><dt>人工采纳 / 材料身份</dt><dd>{m.review.at} · {m.review.reason||'未填写说明'} · {m.id}</dd></dl><h5>引用</h5>{m.result.value.references.map(ref=><p key={ref.kind+ref.id}>{ref.kind} · {ref.id} · revision {ref.revision_id} · 版本 {ref.version??'不适用'} · SHA-256 {ref.sha256??'不适用'}</p>)}<h5>限制</h5>{m.result.value.limitations.map((x,i)=><p key={i}>{x}</p>)}<h5>未知事项</h5>{m.result.value.unknowns.map((x,i)=><p key={i}>{x}</p>)}</article>)}</section>;
}

export function ChildContextSelection({projection,history,results,disabled,onHistory,onResult}:{projection:import('../../packages/contracts/case-collaboration.ts').CollaborationProjection|null;history:readonly string[];results:readonly string[];disabled:boolean;onHistory(id:string,checked:boolean):void;onResult(id:string,checked:boolean):void}){
 return <fieldset className="ca-history-selection" disabled={disabled}><legend>新 Attempt 的自身历史与结果（默认不选）</legend><div className="ca-selection-list">{projection?.events.filter(e=>['user','advice','question','tool'].includes(e.kind)).map(e=><label className="ca-selection-item" key={e.id}><input type="checkbox" checked={history.includes(e.id)} onChange={v=>onHistory(e.id,v.target.checked)}/><span><strong>{e.text}</strong><small>{e.kind} · 消息状态 {e.status}</small><small>来源 {projection.relation.source.case_name} · revision {e.source_revision}</small><small>原 Attempt {e.attempt_id}</small><small>消息 {e.id}</small></span></label>)}{projection?.results.map(result=><label className="ca-selection-item" key={result.id}><input type="checkbox" checked={results.includes(result.id)} onChange={v=>onResult(result.id,v.target.checked)}/><span><strong>结果 v{result.version} · {result.value.summary}</strong><small>MODEL · 已成功保存</small><small>来源 {result.source.case_name} · revision {result.source.owner.revision_id}</small><small>原 Attempt {result.attempt_id}</small><small>结果 {result.id}</small><small>SHA-256 {result.sha256}</small></span></label>)}</div></fieldset>;
}

export function ParentCollaborationResults({api,parent,state,selected,onSelect,onRefresh}:{api:CaseAssistantApi;parent:AssistantProjection;state:ParentCollaborationProjection;selected:readonly string[];onSelect(ids:string[]):void;onRefresh():Promise<void>|void}){
 const [review,setReview]=useState<{result:ChildResult;disposition:'adopted'|'declined';command:string}|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const valid=(result:ChildResult)=>state.lifecycle.open&&parent.source.eligible&&result.baseline_decision_id===parent.current_decision_id&&result.source.owner.revision_id===parent.source.current_revision_id&&result.source.aggregate.sha256===parent.source.aggregate.sha256&&result.source.report.sha256===parent.source.report.sha256&&result.source.row_version===parent.source.row_version;
 const pending=state.results.filter(r=>state.deliveries.some(d=>d.result_id===r.id&&d.status==='returned')&&!state.reviews.some(v=>v.result_id===r.id));
 return <section><h3>待审子结果</h3>{pending.length===0&&<p>暂无待审子结果</p>}{pending.map(result=><article className="ca-message" key={result.id}><ChildResultView result={result}/><p>子对话 {result.child_session_id} · 已回流待审</p>{!valid(result)&&<p role="status">来源或正式基线已过期，仅保留历史</p>}<button type="button" disabled={!valid(result)||busy} onClick={()=>{setReason('');setError('');setReview({result:structuredClone(result),disposition:'adopted',command:crypto.randomUUID()});}}>采纳为材料</button><button type="button" disabled={!valid(result)||busy} onClick={()=>{setReason('');setError('');setReview({result:structuredClone(result),disposition:'declined',command:crypto.randomUUID()});}}>不采纳</button></article>)}<h3>已采纳子材料</h3>{state.materials.map(material=><div key={material.id}><label className="ca-check"><input type="checkbox" checked={selected.includes(material.id)} disabled={!valid(material.result)} onChange={e=>onSelect(e.target.checked?[...selected,material.id]:selected.filter(id=>id!==material.id))}/>MODEL · 结果 v{material.result.version} · {material.result.value.summary}</label><details><summary>查看材料来源与完整内容</summary><ChildResultView result={material.result}/><p>人工采纳 {material.review.at} · {material.review.reason}</p></details></div>)}<p>只在父对话新 Attempt 中明确选择后外发；采纳材料不改写正式记录。</p>{state.reviews.filter(v=>v.disposition==='declined').map(v=><p key={v.result_id}>未采纳 · 结果 v{v.result_version} · {v.reason}</p>)}
 {review&&<Modal title={review.disposition==='adopted'?'确认采纳为 MODEL 材料':'确认不采纳子结果'} onClose={()=>setReview(null)}><ChildResultView result={review.result}/><p>绑定以上结果版本。不会启动父模型或修改 Evidence、Finding、正式决定、预期或报告。</p><label>处理说明（可选）<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className="ca-actions"><button type="button" onClick={()=>setReview(null)}>取消</button><button type="button" className="ca-primary" disabled={busy||!valid(review.result)||state.reviews.some(v=>v.result_id===review.result.id)} onClick={()=>{setBusy(true);void collaborationCall(api,{version:'1.1',operation:'review_result',session_id:parent.session.id,result_id:review.result.id,result_version:review.result.version,result_sha256:review.result.sha256,command_id:review.command,disposition:review.disposition,reason,confirmed:true}).then(async()=>{setReview(null);await onRefresh();}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>确认{review.disposition==='adopted'?'采纳为材料':'不采纳'}</button></div></Modal>}</section>;
}
