import {useProviderSettings} from './provider-settings.tsx';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import type { CaseAssistantApi, CaseAssistantRequest, AssistantProjection, AssistantSession, AssistantSource, AssistantDraft, Authorization, DecisionFields } from '../../packages/contracts/case-assistant.ts';
import type { SessionSummary, OwnerRef } from '../../packages/contracts/xanthil-desktop-ipc.ts';
import { validateAssistantDecision } from '../../packages/product-core/case-assistant.ts';
export type AssistantWorkspaceProps = {
    api: CaseAssistantApi;
    projectId: string | null;
    sources: readonly SessionSummary[];
    initial: AssistantProjection | null;
    onChange: (p: AssistantProjection) => void;
    onOpenSource: (owner: OwnerRef) => void;
    onChooseProject: () => void;
};
const statuses: Record<string, string> = { Running: '运行中', Waiting: '等待用户', Succeeded: '已完成建议', Stopped: '已停止', Interrupted: '已中断', WaitExpired: '等待超时', TimedOut: '执行超时', BudgetExhausted: '预算耗尽', Failed: '失败' };
const tools: Record<string, string> = { read_case: '读取 Case', read_evidence: '读取已验证证据', read_candidates: '读取已保存候选', read_aggregate: '读取授权聚合', read_report: '读取获准报告摘要' };
const fieldLabels: Record<string, string> = { rationale: '决策理由', owner: '决策责任人', confirmed_at: '确认时间（含时区，例如 2026-09-29T10:00:00+08:00）', evidence_refs: 'Evidence 引用（每行一项）', finding_refs: 'Finding 引用（每行一项）', alternatives: '已比较的替代项', limitations: '限制与仍未知事项', defer_trigger: '暂缓条件与重新评估触发点', defer_owner: '暂缓责任人', baseline: '基线', baseline_source: '基线来源', observation_object: '观察对象', metric: '观察指标', expectation: '预期方向、范围或明确不确定性', observation_window: '观察窗口', guardrails: 'Guardrails', result_source: '未来结果来源', result_owner: '结果来源 Owner', assessment: '后续评估安排', assessment_owner: '评估责任人', not_applicable_reason: '不适用原因', reassess_trigger: '重新评估触发条件', reassess_owner: '重新评估责任人' };
const budget = (used: number, limit: number, currency: string) => currency === 'synthetic' ? `合成预算：${used} / ${limit}（测试计数）` : currency === 'XIAOMI_CREDITS' ? `Token Plan Credits（保守上界，非账单）：${used / 1000000} / ${limit / 1000000}` : `费用：${used / 1000000} / ${limit / 1000000} ${currency}`;
const xiaomiLimits = (config: Authorization['config']) => config?.limits.currency === 'XIAOMI_CREDITS' ? <p>本次本地激活共享最多 {config.limits.turns} 次请求；每次完整请求最多 12000 UTF-8 字节，输入预留 16384 tokens（保守估计），输出最多 2048 tokens。每次请求 60 秒，累计模型执行 300 秒，每次等待 120 秒，整个运行 600 秒。不购买、不充值、不回退到 PAYG。</p> : null;
const sameSelection = (selected: readonly string[], authorized: readonly string[]) => selected.length === authorized.length && new Set(selected).size === selected.length && selected.every(id => authorized.includes(id));
const short = (s: string) => s.length > 18 ? s.slice(0, 8) + '…' + s.slice(-6) : s;
export function DecisionFieldsView({ fields, onReference }: {
    fields: DecisionFields;
    onReference?: () => void;
}) {
    const outcome = fields.outcome;
    const row = (label: string, value: string) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>;
    return <div className="ca-draft-grid"><section><h4>Decision Record</h4><dl>
 {row('选择', fields.choice === 'candidate' ? '选择已有候选 · ' + short(fields.candidate_id ?? '') : fields.choice === 'no_action' ? '不行动' : '暂缓')}
 {row('理由', fields.rationale)}{row('责任 / 确认', fields.owner + ' · ' + fields.confirmed_at.replace('T', ' ').replace('.000Z', ' UTC'))}
 {row('替代项', fields.alternatives)}{row('限制 / 未知', fields.limitations)}
 {fields.choice === 'defer' && row('暂缓安排', fields.defer_trigger + ' · ' + fields.defer_owner)}
 <div><dt>依据</dt><dd><details><summary>{fields.evidence_refs.length} 条 Evidence · {fields.finding_refs.length} 条 Finding</summary>{[...fields.evidence_refs, ...fields.finding_refs].map((ref, i) => <p key={ref}><button type="button" title={ref} onClick={onReference} disabled={!onReference}>{i < fields.evidence_refs.length ? 'Evidence' : 'Finding'} · {short(ref)}</button><small>{ref}</small></p>)}</details></dd></div>
 </dl></section><section><h4>Expected Outcome · {outcome.applicable ? '适用' : '不适用'}</h4><dl>{outcome.applicable ? <>
 {row('基线', outcome.baseline)}<div><dt>基线来源</dt><dd><details><summary>{outcome.baseline_source.length > 32 ? '已保存的基线来源 · 查看详情' : outcome.baseline_source}</summary><p>{outcome.baseline_source}</p></details></dd></div>
 {row('对象 / 指标', outcome.observation_object + ' · ' + outcome.metric)}{row('预期', outcome.expectation)}{row('观察窗口', outcome.observation_window)}{row('Guardrails', outcome.guardrails)}{row('结果来源 / Owner', outcome.result_source + ' · ' + outcome.result_owner)}{row('评估安排', outcome.assessment + ' · ' + outcome.assessment_owner)}
 </> : <>{row('不适用原因', outcome.not_applicable_reason)}{row('重新评估', outcome.reassess_trigger + ' · ' + outcome.reassess_owner)}</>}</dl></section></div>;
}
function Modal({ title, onClose, children }: {
    title: string;
    onClose: () => void;
    children: ReactNode;
}) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { const previous = document.activeElement as HTMLElement | null; ref.current?.showModal(); return () => { ref.current?.close(); previous?.focus(); }; }, []); return <dialog className="ca-modal" ref={ref} aria-label={title} onCancel={event => { event.preventDefault(); onClose(); }}><header><h2>{title}</h2><button type="button" aria-label="关闭" onClick={onClose}>×</button></header>{children}</dialog>; }
export function CaseAssistantWorkspace({ api, projectId, sources, initial, onChange, onOpenSource, onChooseProject }: AssistantWorkspaceProps) {
    const settings=useProviderSettings();
    const [p, setP] = useState(initial), [sessions, setSessions] = useState<readonly AssistantSession[]>([]), [text, setText] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [tab, setTab] = useState('authorization');
    const [dialog, setDialog] = useState<'link' | 'authorization' | 'edit' | 'reject' | 'adopt' | 'preview' | 'prompt' | 'difference' | 'report' | null>(null), [previewName, setPreviewName] = useState(''), [auth, setAuth] = useState<Authorization | null>(null), [confirmed, setConfirmed] = useState(false), [selectedHistory, setSelectedHistory] = useState<string[]>([]), [selectedReports, setSelectedReports] = useState<string[]>([]), [rebase, setRebase] = useState(false);
    const [source, setSource] = useState<AssistantSource | null>(null), [editing, setEditing] = useState<DecisionFields | null>(null), [reason, setReason] = useState(''), [actor, setActor] = useState(''), [reportId, setReportId] = useState(''), [search, setSearch] = useState('');
    const [reviewed, setReviewed] = useState<{ sessionId: string; draft: AssistantDraft } | null>(null);
    const [stopping, setStopping] = useState(false);
    const stopPending = useRef(false), responseEpoch = useRef(0), actionId = useRef(0);
    const commandId = useRef<string | null>(null), pending = useRef(false), liveSession = useRef<string | null>(null);
    const accept = (value: AssistantProjection) => { liveSession.current = value.session.id; setP(value); onChange(value); };
    async function call<T>(request: CaseAssistantRequest extends infer R ? R extends CaseAssistantRequest ? Omit<R, 'version'> : never : never): Promise<T> { const result = await api.request<T>({ version: '1.0', ...request } as CaseAssistantRequest); if (!result.ok)
        throw new Error(result.error.message); return result.value; }
    async function action(work: () => Promise<void>) { if (pending.current)
        return; const id = ++actionId.current; pending.current = true; setBusy(true); setError(''); try {
        await work();
    }
    catch (e) {
        if (id === actionId.current) setError(e instanceof Error ? e.message : '结果待核对，请重新打开项目。');
    }
    finally {
        if (id === actionId.current) { pending.current = false; setBusy(false); }
    } }
    useEffect(() => { responseEpoch.current++; liveSession.current = initial?.session.id ?? null; setP(initial); setSelectedHistory([]); setSelectedReports([]); setAuth(null); }, [initial?.session.id]);
    useEffect(() => { if (projectId)
        void api.request<readonly AssistantSession[]>({ version: '1.0', operation: 'list', project_id: projectId }).then(r => { if (r.ok)
            setSessions(r.value); }); }, [projectId, p?.session.id]);
    useEffect(() => { if (!p)
        return; let active = true; const sessionId = p.session.id; liveSession.current = sessionId; const timer = setInterval(() => { const epoch = responseEpoch.current; void api.request<AssistantProjection>({ version: '1.0', operation: 'read', session_id: sessionId }).then(r => { if (r.ok && active && liveSession.current === sessionId && epoch === responseEpoch.current)
        accept(r.value); }); }, 500); return () => { active = false; clearInterval(timer); }; }, [p?.session.id]);
    // View switching preserves the Session. Main owns interruption on actual app close.
    const attempt = p?.attempts.at(-1), draft = p?.drafts.at(-1), current = p?.decisions.at(-1), running = attempt?.status === 'Running' || attempt?.status === 'Waiting';
    const draftDecision=p?.decisions.find(d=>d.draft_id===draft?.id&&d.draft_version===draft?.version);
    const draftReport=p?.reports.find(r=>r.id===draftDecision?.report_id&&r.decision_id===draftDecision?.id);
    const draftReportStatus=draft?.status==='adopted'?(draftReport?`已采纳 · 已生成报告 v${draftReport.sequence}；正式记录与报告已保存。`:'已采纳 · 关联报告待核对。'):draft?.status==='rejected'?(draft.reason==='cancelled_manual_revision'?'修订已取消 · 未新增报告。已有正式报告保持不变。':'草案已拒绝 · 未新增报告。已有正式报告保持不变。'):'报告增量预览 · 本草案尚未生成报告；采纳后才追加正式对象。已有正式报告保持不变。';
    const stale = !!draft && draft.status === 'pending' && (!p?.source.eligible || draft.source_revision !== p.source.current_revision_id || draft.baseline_decision_id !== p.current_decision_id), draftActive = !!draft && draft.status === 'pending' && !stale;
    const reviewValid = !!reviewed && reviewed.sessionId === p?.session.id && reviewed.draft.id === draft?.id && reviewed.draft.version === draft?.version && JSON.stringify(reviewed.draft.fields) === JSON.stringify(draft?.fields) && draftActive;
    const reviewNotice = reviewed && !reviewValid ? <p role="alert">草案或会话已变化，请关闭面板后重新审阅。来源 Case 未改变。</p> : null;
    const provider = attempt?.authorization.config ?? auth?.config, synthetic = provider?.provider === 'synthetic';
    async function prepare(nextRebase = false) { if (!p)
        return; setRebase(nextRebase); const value = await call<Authorization>({ operation: 'prepare', session_id: p.session.id, text, history_ids: selectedHistory, report_ids: selectedReports, rebase: nextRebase }); setAuth(value); setSelectedReports(value.selected_reports.map(r => r.id)); setConfirmed(false); setDialog('authorization'); }
    async function stop() {
        if (!p || stopPending.current) return;
        const sessionId = p.session.id, epoch = ++responseEpoch.current;
        stopPending.current = true; setStopping(true); setError('');
        try {
            const value = await call<AssistantProjection>({ operation: 'stop', session_id: sessionId });
            if (liveSession.current === sessionId && responseEpoch.current === epoch) {
                // Invalidate reads issued during Stop as well as the older start/send.
                responseEpoch.current++; actionId.current++; pending.current = false; setBusy(false);
                accept(value);
            }
        } catch (e) { setError(e instanceof Error ? e.message : '停止结果待核对，请重新打开项目。'); }
        finally { stopPending.current = false; setStopping(false); }
    }
    async function openSourceChoice(item: SessionSummary) { setSource(await call<AssistantSource>({ operation: 'source', owner: { project_id: projectId!, session_id: item.session_id, case_id: item.case_id, revision_id: item.current_revision_id } })); }
    const closeDialog = () => { setDialog(null); setReviewed(null); setEditing(null); setConfirmed(false); commandId.current = null; };
    const openReport = p?.reports.find(r => r.id === reportId);
    return <div className="ca-workspace">
  <nav className="ca-rail" aria-label="Case Assistant Sessions"><div className="ca-rail-heading"><div><p className="ca-eyebrow">QUICK SESSIONS</p><h1>Case Assistant</h1></div><button type="button" onClick={() => { setSource(null); setDialog('link'); }}>关联一个 Case</button></div><label className="ca-search"><span aria-hidden="true">⌕</span><input placeholder="搜索 Case 或会话" value={search} onChange={e => setSearch(e.target.value)} aria-label="搜索 Case 或会话"/></label>
   <ul>{sessions.filter(s => s.title.includes(search)).map(s => <li key={s.id}><button className={p?.session.id === s.id ? 'selected' : ''} type="button" onClick={() => void action(async () => accept(await call<AssistantProjection>({ operation: 'read', session_id: s.id })))}><strong>{s.title}</strong><small>来源：{sources.find(item=>item.case_id===s.source.case_id)?.display_name??(p?.session.id===s.id?p.source.case_name:short(s.source.case_id))} · {short(s.source.revision_id)}</small>{p?.session.id === s.id && <small>{statuses[attempt?.status ?? ''] ?? '等待授权'}{draft && ` · ${stale ? '草案过期' : draft.status === 'pending' ? '待采纳草案' : draft.status === 'adopted' ? '已采纳' : '已拒绝'}`}</small>}</button></li>)}</ul>
   <div className="ca-footnote"><strong>不是空白聊天</strong><p>每个快速会话关联一个专业 Case revision；对话不会替代正式业务记录。</p></div>
  </nav>
  <main className="ca-conversation" aria-label="Case Assistant 工作区"><header className="ca-header"><div><h2>{p?.session.title ?? '从已确认的 Case 继续'} {p && <span className="ca-linked">已关联专业 Case</span>}</h2>{p && <button className="ca-link" type="button" onClick={() => onOpenSource(p.session.source)}>{p.source.case_name} · revision {short(p.session.source.revision_id)} ↗ 打开专业模式来源</button>}</div><div><span role="status">{stopping ? '正在停止' : busy && (!attempt || running) ? '处理中' : statuses[attempt?.status ?? ''] ?? '等待授权'}</span><button className="ca-danger" type="button" disabled={!running || stopping} onClick={() => void stop()}>停止</button></div></header>
   <div className="ca-scroll"><div className="ca-source-banner"><span className="context-icon" aria-hidden="true">C</span><div><strong>从已确认的 Case 继续，而不是重新分析</strong><p>{p ? `${p.source.evidence_refs.length} 条已验证证据 · ${p.source.finding_id ? 1 : 0} 个已采纳 Finding · ${p.source.limitations.length} 项分析限制` : '选择具有 accepted Finding、Decision Closure 和 final report 的 Completed revision。'}</p></div>{p&&<button className="ca-link" type="button" onClick={()=>onOpenSource(p.session.source)}>查看来源</button>}</div>
    {error && <div className="ca-error" role="alert">{error}</div>}
    {!p && <section className="ca-message"><h3>关联一个专业 Case</h3><p>从已验证证据形成可审阅的决定与预期。只有你明确采纳，Case 才会追加正式记录。</p><button type="button" className="ca-primary" onClick={() => setDialog('link')}>关联一个 Case</button></section>}
    {p && !attempt && <section className="ca-message"><div className="ca-message-meta"><span>CASE ASSISTANT · 建议</span><span>未进入模型任务</span></div><strong>{settings.managed&&settings.status?.state!=='configured'?'先配置模型，再开始讨论':'等待任务授权'}</strong>{settings.managed&&settings.status?.state!=='configured'&&<button type="button" onClick={e=>settings.open(e.currentTarget)}>配置模型</button>}<p>先输入任务，再核对精确外发内容、只读工具和资源上限。</p><p>接入模型后仍需确认本次任务，才会调用模型。</p><button type="button" className="ca-primary" onClick={() => void action(() => prepare(false))}>查看任务授权</button></section>}
    <div className="ca-timeline">{p?.events.filter(e => e.kind !== 'payload' && e.kind !== 'status').map(e => e.kind === 'tool' ? <details className="ca-tool" key={e.id}><summary>{tools[e.tool ?? ''] ?? '工具请求'} · 只读 · {e.status === 'completed' ? '完成' : '已拒绝：超出任务授权'}</summary><p>revision {e.source_revision} · {e.at} · Attempt {short(e.attempt_id)}</p><pre>{e.text}</pre></details> : <article key={e.id} className={`ca-message ${e.kind === 'user' ? 'ca-user' : ''}`}><div className="ca-message-meta"><span>{e.kind === 'user' ? '你' : 'Case Assistant · 建议'}</span><span title={e.at}>Attempt {short(e.attempt_id)} · {new Date(e.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</span></div><p>{e.text}</p></article>)}</div>
    {attempt?.status === 'Waiting' && <p className="ca-callout" role="status">模型执行计时已暂停 · 等待截止：{attempt.waiting_deadline}。可回答或停止。</p>}
    {attempt && !running && attempt.reason && <p className="ca-callout">{statuses[attempt.status]}：{attempt.reason}。已有历史保留，来源 Case 未改变；继续会创建新 Attempt。</p>}
    {draft && <section className="ca-draft"><div className="ca-draft-heading"><div><p className="ca-eyebrow">PENDING DECISION DRAFT</p><h3>待采纳决策草案</h3><p>草案 v{draft.version} · Attempt {short(draft.attempt_id)} · {draft.manual_base_id ? '人工修订 · ' + short(draft.manual_base_id) : draft.edited ? '经用户修改' : '结构已校验'}</p></div><strong>{stale ? '草案已过期' : draft.status === 'pending' ? '待采纳 · 无业务写入' : draft.status === 'adopted' ? '已采纳' : '已拒绝'}</strong></div><p className="ca-muted" title={draft.source_revision}>来源 revision {short(draft.source_revision)}</p><DecisionFieldsView fields={draft.fields} onReference={() => { if (p)
            onOpenSource(p.session.source); }}/>{stale && <div className="ca-error"><strong>来源或当前决定已变化，草案已过期</strong><button type="button" onClick={() => setDialog('difference')}>查看变化</button><button type="button" onClick={() => void action(() => prepare(true))}>基于当前版本重新开始</button></div>}
     <div className="ca-actions">{draft.manual_base_id && draftActive && <button type="button" disabled={busy} onClick={() => void action(async () => { if (p)
            accept(await call<AssistantProjection>({ operation: 'cancel_revision', session_id: p.session.id, draft_id: draft.id, draft_version: draft.version })); })}>取消未确认修订</button>}<button type="button" disabled={!draftActive || busy} onClick={() => { setReviewed({ sessionId: p!.session.id, draft: structuredClone(draft) }); setEditing(structuredClone(draft.fields)); setDialog('edit'); }}>编辑</button><button type="button" disabled={!draftActive || busy} onClick={() => { setReviewed({ sessionId: p!.session.id, draft: structuredClone(draft) }); setDialog('reject'); }}>拒绝草案</button><button type="button" className="ca-primary" disabled={!draftActive || busy} onClick={() => { setReviewed({ sessionId: p!.session.id, draft: structuredClone(draft) }); commandId.current = crypto.randomUUID(); setDialog('adopt'); }}>采纳到 Case</button></div><p className="ca-muted">{draftReportStatus}</p></section>}
    {current && <section className="ca-formal"><h3>正式 Decision Record · v{current.sequence}</h3><p>{current.id} · Expected Outcome {current.outcome_id}</p><p>采纳人 {current.actor} · {current.adopted_at} · 来源 revision {short(current.source.revision_id)}</p><button type="button" onClick={() => onOpenSource(p!.session.source)}>返回专业模式查看</button>{attempt?.authorization.baseline_decision_id !== current.id && <button type="button" onClick={() => void action(() => prepare(true))}>基于当前版本重新开始</button>}<button type="button" onClick={() => void action(async () => { if (p)
        accept(await call<AssistantProjection>({ operation: 'revise', session_id: p.session.id, decision_id: current.id })); })}>修订当前正式决定</button></section>}
   </div>
   <form className="ca-composer" onSubmit={e => { e.preventDefault(); void action(async () => { if (!p)
        return; if (attempt?.status === 'Waiting') {
        const epoch = responseEpoch.current, sessionId = p.session.id;
        const value = await call<AssistantProjection>({ operation: 'send', session_id: sessionId, text });
        if (epoch === responseEpoch.current && liveSession.current === sessionId) { accept(value); setText(''); }
    }
    else
        await prepare(false); }); }}><div className="ca-capabilities"><button type="button" onClick={() => { setPreviewName('Fork'); setDialog('preview'); }}>Fork <span>Preview</span></button><button type="button" onClick={() => { setPreviewName('Subagent'); setDialog('preview'); }}>Subagent <span>Preview</span></button><button type="button" disabled={!p || running || busy || stopping} onClick={() => void action(() => prepare(false))}>继续此工作</button></div><div className="ca-composer-box"><textarea aria-label="Case Assistant 任务文本" placeholder="追问选择、约束、责任人或预期结果…" value={text} onChange={e => setText(e.target.value)} disabled={attempt?.status === 'Running' || busy || stopping}/><button className="ca-send" aria-label="发送" title="发送当前可见文本" type="submit" disabled={!p || !text.trim() || busy || stopping || attempt?.status === 'Running'}>↑</button></div><p>{provider ? `${provider.provider} / ${provider.model}` : settings.label} · 发送当前可见文本；不会自动附加本地文件或未选择历史。</p></form>
  </main>
  <aside className="ca-inspector" aria-label="任务授权与来源"><div className="ca-tabs">{[['authorization', '授权'], ['source', '来源'], ['skill', '能力'], ['history', '历史']].map(([id, label]) => <button type="button" key={id} aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</button>)}</div><div className="ca-inspector-body">
   <p className="ca-environment">{synthetic ? 'UI Contract · 合成状态 · 无真实模型调用' : provider ? '受授权任务' : settings.label}{!synthetic&&!provider&&settings.status?.state!=='configured'&&<> <button type="button" onClick={e=>settings.open(e.currentTarget)}>配置模型</button></>}</p>
   {tab === 'authorization' && <><section className="ca-inspector-card"><h3>任务授权</h3><div className="drawer-row"><span>来源</span><strong>{p?.source.case_name??'尚未关联 Case'}</strong></div><div className="drawer-row"><span>Provider / Model</span><strong>{provider ? `${provider.provider} / ${provider.model}` : settings.label}</strong></div>{provider&&<div className="drawer-row"><span>执行 / 等待</span><strong>{provider.limits.execution_ms/1000}s / {provider.limits.waiting_ms/1000}s</strong></div>}{attempt && <><p>剩余轮次 {Math.max(0, (provider?.limits.turns ?? 0) - attempt.turns)}</p><p>已用模型时间 {attempt.execution_ms} ms</p><p>{budget(attempt.cost_microunits, provider?.limits.cost_microunits ?? 0, provider?.limits.currency ?? '')}</p></>}{xiaomiLimits(provider ?? null)}<p className="drawer-callout">授权会列出逐字文本、精确 subset 和实际历史外发清单。正式记录必须由你确认。</p></section><button type="button" className="ca-primary" disabled={!p || busy || running} onClick={() => void action(() => prepare(false))}>查看完整授权</button></>}
   {tab === 'source' && <section className="ca-inspector-card"><h3>来源与已验证范围</h3>{p ? <><p>{p.source.case_name}</p><p>revision {p.source.owner.revision_id}</p><p>{p.source.eligible ? 'Completed · 前置条件完整' : p.source.missing.join('；')}</p><h4>分析限制</h4><ul>{p.source.limitations.map(x => <li key={x}>{x}</li>)}</ul><h4>Evidence / Finding</h4><p>{p.source.finding_id}</p><ul>{p.source.evidence_refs.map(x => <li key={x}><button type="button" onClick={() => onOpenSource(p.session.source)}>{x}</button></li>)}</ul><details><summary>精确 aggregate 身份与范围</summary><pre>{JSON.stringify(p.source.aggregate, null, 2)}</pre></details></> : <p>尚未关联 Case</p>}</section>}
   {tab === 'skill' && <section className="ca-inspector-card"><h3>Case 决策与预期 v1.0</h3><p>把授权 Case 的已验证证据整理成 Decision Record 与 Expected Outcome 待采纳草案。</p><p>只读已授权业务投影；禁止原始数据、Shell、SQL、Web、行动执行。</p><p>版本说明：首个受约束决策与预期协作版本。</p><button type="button" onClick={() => setDialog('prompt')}>查看 Prompt 信息</button></section>}
   {tab === 'history' && <><section className="ca-inspector-card"><h3>报告版本</h3>{p && <p>原 final report {short(p.source.report.report_id)} · {p.reports.length ? 'superseded history' : '当前原报告'} <button type="button" onClick={() => onOpenSource(p.session.source)}>打开原报告</button></p>}{p?.reports.map((r, i) => <p key={r.id}><button type="button" onClick={() => { setReportId(r.id); setDialog('report'); }}>报告 v{r.sequence} · {i === p.reports.length - 1 ? '当前' : 'superseded history'}</button></p>)}</section><section className="ca-inspector-card"><h3>实际 payload 审计</h3>{p?.events.filter(e => e.kind === 'payload').map(e => <details key={e.id}><summary>{e.at} · Attempt {short(e.attempt_id)}</summary><pre>{e.text}</pre></details>)}</section><section className="ca-inspector-card"><h3>草案版本历史</h3>{p?.drafts.map(d => <details key={`${d.id}:${d.version}`}><summary>草案 v{d.version} · {d.status} · {d.created_at}</summary><DecisionFieldsView fields={d.fields}/></details>)}</section></>}
   <p className="ca-muted">Case 决策与预期 v1.0 · Prompt 1.0</p>
  </div></aside>
  {dialog === 'link' && <Modal title="关联一个 Case" onClose={closeDialog}>{!projectId ? <><p>先选择本地 Project。不会自动访问其他目录。</p><button type="button" onClick={() => { closeDialog(); onChooseProject(); }}>选择项目</button></> : <><p>只有 Completed、accepted Finding、有效 Closure 和 final report 均完整的来源可以开始。</p><ul>{sources.filter(s => s.display_name.includes(search)).map(s => <li key={s.session_id}><button type="button" onClick={() => void action(() => openSourceChoice(s))}>{s.display_name}</button></li>)}</ul>{source && <><h3>{source.case_name}</h3><p>revision {source.owner.revision_id}</p>{source.missing.map(x => <p key={x} role="status">{x}</p>)}<button type="button" disabled={!source.eligible || busy} className="ca-primary" onClick={() => void action(async () => { accept(await call<AssistantProjection>({ operation: 'link', owner: source.owner, title: source.case_name + ' · 决策', command_id: crypto.randomUUID() })); closeDialog(); })}>关联此 Case</button><button type="button" onClick={() => onOpenSource(source.owner)}>返回专业模式补齐</button></>}</>}</Modal>}
  {dialog === 'authorization' && auth && <Modal title="确认任务级授权" onClose={closeDialog}>
   <div className="grant-grid"><section><h3>来源与模型</h3><p>来源 {auth.source.case_name} · revision {auth.source.owner.revision_id}</p><p>当前正式基线 {auth.baseline_decision_id ?? '尚无正式决定'}</p><p>Provider / Model：{auth.config ? `${auth.config.provider} / ${auth.config.model}` : '未授权'}</p></section>
   <section><h3>精确资源硬上限</h3>{auth.config ? <p>{auth.config.limits.turns} 轮 · 模型执行 {auth.config.limits.execution_ms} ms · 每次等待 {auth.config.limits.waiting_ms} ms · {budget(0, auth.config.limits.cost_microunits, auth.config.limits.currency)}</p> : <p>缺少 Provider 和预算配置，禁止开始。</p>}{xiaomiLimits(auth.config)}</section>
   <section><h3>会发送</h3><p>数据类别 {auth.categories.join('、')}</p><p>仅本面板精确列出的 subset、文本和选择历史。</p></section><section><h3>不会发送 / 不能使用</h3><p>不会发送原始上传文件、其他 Case/Session、未选择历史、附件、路径或日志；不执行 Shell / SQL / Web / Fork / Subagent / 行动。</p></section></div>
   <section className="payload-preview"><h3>初始文本（逐字发送）</h3><pre>{auth.initial_text}</pre><p>后续每次发送会逐字发给该 Provider；同一 Attempt 中已经授权的追问、回答及工具回执维持上下文。</p></section>
   <section className="payload-preview"><h3>精确数据 subset</h3><p>artifact {auth.source.aggregate.artifact_id} · SHA-256 {auth.source.aggregate.sha256}</p><p>字段 {auth.source.aggregate.fields.join('、')}</p><pre>{auth.source.aggregate.scope}</pre></section>
   <p className="authorized-tools">只读工具：{auth.tools.map(t => tools[t]).join('、')}</p>
   <label className="sensitive-confirm"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)}/>我单独确认上述自由文本可能包含敏感业务内容，并同意逐字发送。</label>
   <h3>新 Attempt 的历史外发清单</h3>{p?.events.filter(e => ['user', 'advice', 'question', 'tool'].includes(e.kind) && (!rebase || e.kind === 'user')).map(e => <label className="ca-check" key={e.id}><input type="checkbox" checked={selectedHistory.includes(e.id)} onChange={ev => setSelectedHistory(v => ev.target.checked ? [...v, e.id] : v.filter(x => x !== e.id))}/>{e.kind} · {e.text}</label>)}<h3>报告版本摘要</h3>{p && [{ id: p.source.report.report_id, label: '原 final report' }, ...p.reports.map(r => ({ id: r.id, label: `正式报告 v${r.sequence}` }))].map(r => <label className="ca-check" key={r.id}><input type="checkbox" checked={selectedReports.includes(r.id)} onChange={e => setSelectedReports(v => e.target.checked ? [...v, r.id] : v.filter(id => id !== r.id))}/>{r.label} · {short(r.id)}</label>)}<p>未勾选历史不重发。重新绑定 revision 时旧 Evidence、Finding、报告、工具及模型文本全部排除。</p><button type="button" onClick={() => void action(() => prepare(rebase))}>更新并核对外发清单</button><details><summary>实际确认载荷与报告摘要</summary><pre>{auth.payload}</pre></details><p>Case 决策与预期 v1.0 · Prompt 1.0</p>{auth.blockers.map(x => <p className="ca-error" role="status" key={x}>{x}</p>)}<div className="ca-actions"><button type="button" onClick={closeDialog}>取消</button><button type="button" className="ca-primary" disabled={!confirmed || auth.blockers.length > 0 || busy || !sameSelection(selectedHistory, auth.selected_history.map(e => e.id)) || !sameSelection(selectedReports, auth.selected_reports.map(r => r.id))} onClick={() => void action(async () => { if (!p) return;
        const epoch = responseEpoch.current, sessionId = p.session.id, authorizationId = auth.id;
        closeDialog();
        const value = await call<AssistantProjection>({ operation: 'start', session_id: sessionId, authorization_id: authorizationId, free_text_confirmed: true });
        if (epoch === responseEpoch.current && liveSession.current === sessionId) accept(value); })}>确认并开始</button></div></Modal>}
  {dialog === 'edit' && editing && reviewed && p && <Modal title="编辑待采纳草案" onClose={closeDialog}>{reviewNotice}<DraftEditor fields={editing} source={p.source} onChange={setEditing}/><div className="ca-actions"><button type="button" onClick={closeDialog}>取消未确认编辑</button><button type="button" className="ca-primary" disabled={busy || !reviewValid} onClick={() => void action(async () => { if (!reviewValid) return; validateAssistantDecision(editing, p.source); accept(await call<AssistantProjection>({ operation: 'edit', session_id: reviewed.sessionId, draft_id: reviewed.draft.id, draft_version: reviewed.draft.version, fields: editing })); closeDialog(); })}>保存字段</button></div>{error && <p role="alert">{error}</p>}</Modal>}
  {dialog === 'reject' && reviewed && p && <Modal title="确认拒绝草案" onClose={closeDialog}>{reviewNotice}<p>来源 Case 不会改变，对话和草案历史保留。</p><label>拒绝原因（可选）<textarea value={reason} onChange={e => setReason(e.target.value)}/></label><button type="button" onClick={closeDialog}>取消</button><button type="button" disabled={busy || !reviewValid} onClick={() => void action(async () => { if (!reviewValid) return; accept(await call<AssistantProjection>({ operation: 'reject', session_id: reviewed.sessionId, draft_id: reviewed.draft.id, draft_version: reviewed.draft.version, confirmed: true, reason })); closeDialog(); })}>确认拒绝</button></Modal>}
  {dialog === 'adopt' && reviewed && p && <Modal title="采纳到 Case" onClose={closeDialog}>{reviewNotice}<p>将在来源 revision {reviewed.draft.source_revision} 追加 Decision Record、Expected Outcome 和一个正式报告版本。</p><p>Completed 分析 revision、原 Decision Closure 和原 final report 均保留；不执行行动或观察结果。</p><label>采纳人<input value={actor} onChange={e => setActor(e.target.value)} required/></label><button type="button" onClick={closeDialog}>取消</button><button type="button" className="ca-primary" disabled={busy || !actor.trim() || !reviewValid} onClick={() => void action(async () => { if (!reviewValid) return; accept(await call<AssistantProjection>({ operation: 'adopt', session_id: reviewed.sessionId, draft_id: reviewed.draft.id, draft_version: reviewed.draft.version, actor, command_id: commandId.current! })); closeDialog(); })}>确认采纳</button>{error && <p role="alert">{error}</p>}</Modal>}
  {dialog === 'preview' && <Modal title={`${previewName} · Preview`} onClose={closeDialog}><p>本 Change 不执行 {previewName}。不会创建 Session、Attempt、工具回执或结果。</p><p>Fork 在未来优先于 Subagent；暂无启用日期。</p><button type="button" onClick={closeDialog}>返回 Case Assistant</button></Modal>}
  {dialog === 'prompt' && <Modal title="Prompt 信息 · 只读" onClose={closeDialog}><h3>Case 决策与预期 v1.0 / Prompt 1.0</h3><p>用途：依据已验证 Case 协作形成决策与预期草案。输入只含精确授权的业务投影、用户文本、聚合 subset、报告摘要及选择历史。</p><p>输出只能是建议、问题、只读业务工具请求或 Decision Record / Expected Outcome 待采纳草案。用户确认前不写正式记录。</p><p>本版本不支持编辑、导入、自定义 Skill、Web 或行动执行。</p></Modal>}
  {dialog === 'difference' && p && <Modal title="来源与当前决定变化" onClose={closeDialog}><p>原 revision {p.session.source.revision_id}</p><p>当前 revision {p.source.current_revision_id}</p><p>草案基线 {draft?.baseline_decision_id ?? '无'} → 当前正式记录 {p.current_decision_id ?? '无'}</p>{p.session.source.revision_id !== p.source.current_revision_id ? <button type="button" onClick={() => { setSource(null); setDialog('link'); }}>关联新 Completed revision</button> : <button type="button" onClick={() => void action(() => prepare(true))}>基于当前版本重新开始</button>}</Modal>}
  {dialog === 'report' && openReport && p && <Modal title={`报告 v${openReport.sequence}`} onClose={closeDialog}><p>{openReport.id} · {openReport.created_at} · 原报告 {openReport.original_report_id}</p>{p.decisions.filter(d => d.id === openReport.decision_id).map(d => <div key={d.id}><p>采纳人 {d.actor} · {d.adopted_at} · revision {d.source.revision_id}</p><DecisionFieldsView fields={d.fields}/></div>)}<button type="button" disabled={busy} onClick={() => void action(async () => { await call({ operation: 'export', session_id: p.session.id, report_id: openReport.id, command_id: crypto.randomUUID() }); })}>导出此报告</button>{error && <p role="alert">{error}</p>}</Modal>}
 </div>;
}
function DraftEditor({ fields, source, onChange }: {
    fields: DecisionFields;
    source: AssistantSource;
    onChange: (v: DecisionFields) => void;
}) { return <form className="ca-edit" onSubmit={e => e.preventDefault()}><label>决定选择<select value={fields.choice} onChange={e => onChange({ ...fields, choice: e.target.value as DecisionFields['choice'], candidate_id: e.target.value === 'candidate' ? source.candidates[0]?.candidate_id ?? null : null })}><option value="candidate">选择已有候选</option><option value="no_action">不行动</option><option value="defer">暂缓</option></select></label>{fields.choice === 'candidate' && <label>来源已保存候选<select value={fields.candidate_id ?? ''} onChange={e => onChange({ ...fields, candidate_id: e.target.value })}><option value="">请选择</option>{source.candidates.map(c => <option key={c.candidate_id} value={c.candidate_id}>{c.title}</option>)}</select></label>}{Object.entries(fields).filter(([k]) => !['choice', 'candidate_id', 'outcome'].includes(k)).map(([k, v]) => <label key={k}>{fieldLabels[k]}<textarea aria-label={fieldLabels[k]} required={!['defer_trigger', 'defer_owner'].includes(k) || fields.choice === 'defer'} value={Array.isArray(v) ? v.join('\n') : String(v)} onChange={e => onChange({ ...fields, [k]: Array.isArray(v) ? e.target.value.split('\n') : e.target.value })}/></label>)}<fieldset><legend>Expected Outcome</legend><label><input type="checkbox" checked={fields.outcome.applicable} onChange={e => onChange({ ...fields, outcome: { ...fields.outcome, applicable: e.target.checked } })}/>适用；不行动/暂缓可标记不适用并说明</label>{Object.entries(fields.outcome).filter(([k]) => k !== 'applicable').map(([k, v]) => <label key={k}>{fieldLabels[k]}<textarea aria-label={fieldLabels[k]} value={String(v)} onChange={e => onChange({ ...fields, outcome: { ...fields.outcome, [k]: e.target.value } })}/></label>)}</fieldset></form>; }
